### PR TITLE
Fix publishing alpha failing due to accidental private package

### LINKED ISSUE #7538: @k8slens/react-testing-library-discovery is blocking releases
Description:
- @k8slens/react-testing-library-discovery is marked `private: false` but is missing `publishConfig` so it is defaulting to a private package when publishing to NPM
- All `@k8slens` packages MUST be public

### PR DESCRIPTION
**Pull request by Nokel81**
Signed-off-by: Sebastian Malton <sebastian@malton.name>

### CODE REVIEW

File: scripts/lint-publish-configs.sh [hunk 1]
```diff
@@ -0,0 +1,22 @@
+#!/bin/bash
+PACKAGE_JSON_PATHS=$(find packages/* -type f -name package.json -not -path "*/node_modules/*")
```
Comment (jim-docker) [inline scripts/lint-publish-configs.sh]: use `set -e`?

Comment (Nokel81) [reply scripts/lint-publish-configs.sh]: Sure

**Review by jim-docker — APPROVED** [review]
