### PR TITLE
Fix extensions installation on Windows

### LINKED ISSUE #1564: Extensions install is broken on Windows
Lens fails to unpack npm package during the installation.

### PR DESCRIPTION
**Pull request by nevalla**
Fixes #1564 

Signed-off-by: Lauri Nevala <lauri.nevala@gmail.com>

### CODE REVIEW

File: src/renderer/components/+extensions/extensions.tsx [hunk 1]
```diff
@@ -187,15 +187,17 @@ export class Extensions extends React.Component {
     await Promise.all(
       requests
         .filter(req => !req.data && req.filePath)
-        .map(request => {
-          return fse.readFile(request.filePath).then(data => {
+        .map(async request => {
+          try {
+            const data = fse.readFileSync(request.filePath);
```
Comment (nevalla) [inline src/renderer/components/+extensions/extensions.tsx]: I don't know why, but using `readFileSync` is notably faster on Windows

Comment (panuhorsmalahti) [reply src/renderer/components/+extensions/extensions.tsx]: I don't think sync methods should be used in the UI, since they lock the UI. (No idea why it would be faster).

**Review by panuhorsmalahti — APPROVED** [review]

File: src/renderer/components/+extensions/extensions.tsx (hunk 1 above)
Comment (Nokel81) [reply src/renderer/components/+extensions/extensions.tsx]: I, personally, take that a step further, I don't think file IO at all should be done in the renderer.

Comment (panuhorsmalahti) [reply src/renderer/components/+extensions/extensions.tsx]: Agree, I think we should start to move "non-UI" code to "services".

Comment (nevalla) [reply src/renderer/components/+extensions/extensions.tsx]: Got it working with `readFile`.

File: src/renderer/components/+extensions/extensions.tsx [hunk 2]
```diff
@@ -187,15 +187,17 @@ export class Extensions extends React.Component {
     await Promise.all(
       requests
         .filter(req => !req.data && req.filePath)
-        .map(request => {
-          return fse.readFile(request.filePath).then(data => {
+        .map(async request => {
+          try {
+            const data = await fse.readFile(request.filePath);
```
Comment (jakolehm) [inline src/renderer/components/+extensions/extensions.tsx:192]: Does this change anything else than syntax?

**Review by jakolehm — APPROVED** [review]

File: src/renderer/components/+extensions/extensions.tsx (hunk 2 above)
Comment (nevalla) [reply src/renderer/components/+extensions/extensions.tsx:192]: No. Initially I noticed that previous implementation was slow on Windows and `readFileSync` was significantly faster. Then I just converted it to use `readFile` with await and did not see any effect. Perhaps the original issue with slowness was something else.
