### PR TITLE
Fix ERR_FAILED for splash screen on windows sometimes

### LINKED ISSUE #5511: Lens stays on blank screen after start
**Describe the bug**
When Lens loads after update to latest version, it remains on a blank screen with no menu items or anything (after a very brief loader that appears sometimes for less than a second)

**To Reproduce**
1. Start lens (either via Applications or CLI)

**Expected behavior**
Lens loads with existing clusters, etc

**Screenshots**

**Environment (please complete the following information):**
- Lens Version:
- OS: [e.g. OSX]
- Installation method (e.g. snap or AppImage in Linux):

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
info:    ▪ [MENU]: autoUpdateDisabled=false +47ms
error:   ┏ Loading main window failed +26ms
error:   ┃ [ 1] {
error:   ┃ [ 2]   error: Error: ERR_FAILED (-2) loading 'static://splash.html'
error:   ┃ [ 3]       at rejectAndCleanup (electron/js2c/browser_init.js:161:7486)
error:   ┃ [ 4]       at Object.stopLoadingListener (electron/js2c/browser_init.js:161:7861)
error:   ┃ [ 5]       at Object.emit (events.js:388:22)
error:   ┃ [ 6]       at Object.emit (domain.js:470:12)
error:   ┃ [ 7]       at Object.emitter.emit (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/@sentry/electron/main/integrations/electron-breadcrumbs.js:121:20) {
error:   ┃ [ 8]     errno: -2,
error:   ┃ [ 9]     code: 'ERR_FAILED',
error:   ┃ [10]     url: 'static://splash.html'
error:   ┃ [11]   }
error:   ┗ [12] }
```

**Additional context**
Appeared after upgrade from 5.5.1 to 5.5.2
OS: MacOS (Intel)

### PR DESCRIPTION
**Pull request by Nokel81**
Signed-off-by: Sebastian Malton <sebastian@malton.name>

fix issue reported on slack.

Also the main issue of https://github.com/lensapp/lens/issues/5511 is fixed

### CODE REVIEW

File: src/main/window-manager.ts [hunk 1]
```diff
@@ -257,7 +258,19 @@ export class WindowManager extends Singleton {
...
-      await this.splashWindow.loadURL("static://splash.html");
+
+      const splashWindowFilePath = path.join(staticFilesDirectory, "splash.html");
+
+      try {
+        await this.splashWindow.loadFile(splashWindowFilePath);
+      } catch (error) {
+        if (String(error).includes("ERR_FAILED")) {
+          // Try again, from reading some issues it seems that trying again immedeiately sometimes works
+          await this.splashWindow.loadFile(splashWindowFilePath);
```
Comment (jakolehm) [inline src/main/window-manager.ts:270]: Maybe add logging here so that we can see when this happens?

**Review by jakolehm — APPROVED** [review]

File: src/main/window-manager.ts (hunk 1 above)
Comment (Nokel81) [reply src/main/window-manager.ts:270]: That is a good idea, will do.
