### PR TITLE
fix: Remove erroneous prefixes when using loggerInjectable and prefixLoggerInjectable

### LINKED ISSUE #7744: Most log lines have been prefixed with `[LOGGER-FEATURE]:`
regression from https://github.com/lensapp/lens/pull/7731

### PR DESCRIPTION
**Pull request by Nokel81**
closes https://github.com/lensapp/lens/issues/7744

### CODE REVIEW

File: packages/logger/src/logger.injectable.ts [hunk 1]
```diff
@@ -56,24 +63,23 @@ export const logSillyInjectionToken = getInjectionToken<LogFunction>({
 
 const screamingKebabCase = (str: string) => pipeline(str, kebabCase, toUpper);
 
-const getLogFunctionFor =
-  (scenario: keyof Logger) =>
-  (di: DiContainerForInjection): LogFunction => {
+const getLogFunctionFor = (scenario: keyof Logger, namespace: string | undefined) => {
+  const prefix = namespace
+    ? `[${screamingKebabCase(namespace.replace(/-feature$/, ""))}]: `
```
Comment (jim-docker) [inline packages/logger/src/logger.injectable.ts:68]: we assume the id or namespace is lowercase?

**Review by jim-docker — APPROVED** [review]

File: packages/logger/src/logger.injectable.ts (hunk 1 above)
Comment (jim-docker) [reply packages/logger/src/logger.injectable.ts:68]: If somebody called their feature "my-feature"?

Comment (Nokel81) [reply packages/logger/src/logger.injectable.ts:68]: Yeah I did assume that given that all of them are. I can make a follow-up PR to fix this
