### PR TITLE
Fix IngressApi being registered with a wrong new apiBase

### LINKED ISSUE #4482: lens 5.3.2 ingress cant edit & cant open
environment

1. lens 5.3.2
2. Windows 21h2

i cant open a ingress rule and cant edit it
pls

### PR DESCRIPTION
**Pull request by Nokel81**
- Only during checkPreferredVersion()

- Add some unit tests

Signed-off-by: Sebastian Malton <sebastian@malton.name>

fixes #4482

### CODE REVIEW

File: src/common/k8s-api/kube-api.ts [hunk 1]
```diff
@@ -385,7 +402,15 @@ export class KubeApi<T extends KubeObject> {
...
-  getUrl({ name, namespace = "default" }: Partial<ResourceDescriptor> = {}, query?: Partial<IKubeApiQueryParams>) {
+  private computeApiBase(): string {
+    return createKubeApiURL({
+      apiPrefix: this.apiPrefix,
+      apiVersion: this.apiVersionWithGroup,
+      resource: this.apiResource,
+    });
+  }
+
+  getUrl({ name, namespace }: Partial<ResourceDescriptor> = {}, query?: Partial<IKubeApiQueryParams>) {
```
Comment (jim-docker) [inline src/common/k8s-api/kube-api.ts:413]: `getUrl()` could make use of `computeApiBase()`?

File: src/common/k8s-api/kube-api.ts [hunk 2]
```diff
@@ -262,25 +289,20 @@ export class KubeApi<T extends KubeObject> {
...
 
-  constructor(protected options: IKubeApiOptions<T>) {
-    const {
-      objectConstructor,
-      request = apiKube,
-      kind = options.objectConstructor?.kind,
-      isNamespaced = options.objectConstructor?.namespaced,
-    } = options || {};
-
+  constructor({ objectConstructor, request, kind, isNamespaced, ...options }: IKubeApiOptions<T>) {
```
Comment (jim-docker) [inline src/common/k8s-api/kube-api.ts]: `options` is the right type just by virtue of the other fields being destructured here?

**Review by jim-docker — COMMENTED** [review]
Looks good, testing...

File: src/common/k8s-api/kube-api.ts (hunk 2 above)
Comment (Nokel81) [reply src/common/k8s-api/kube-api.ts]: Do you mean the right name?

File: src/common/k8s-api/kube-api.ts (hunk 1 above)
Comment (Nokel81) [reply src/common/k8s-api/kube-api.ts:413]: Maybe, but I don't see the point since they both call the same helper function.

File: src/common/k8s-api/kube-api.ts (hunk 2 above)
Comment (jim-docker) [reply src/common/k8s-api/kube-api.ts]: I mean if you didn't destructure `kind`, say, then `options` is not the expected type. Just seems odd to rely on `...`

Comment (Nokel81) [reply src/common/k8s-api/kube-api.ts]: But I realized that all this is a breaking change, so I will revert this options change

**Review by jim-docker — APPROVED** [review]
