### PR TITLE
Handle errors from getLatestApiPrefixGroup.

### LINKED ISSUE #1570: Error: Can't find working API for the Kubernetes resource ingresses
**Describe the bug**

There is an error message "Error: Can't find working API for the Kubernetes resource ingresses
" when opening the developer console. The error is from https://github.com/lensapp/lens/blob/master/src/renderer/api/kube-api.ts#L168

Not sure it's a real bug or just my minikube doesn't support ingress API.

**To Reproduce**
1. Open Lens
2. Toggle Developer Tools
3. See error

**Expected behavior**

no uncaught error

**Environment (please complete the following information):**
- Lens Version: 4.0.0-rc.1
- OS: Big Sur
- Installation method (e.g. snap or AppImage in Linux): .dmg
 
**Logs:**

```
Uncaught (in promise) Error: Can't find working API for the Kubernetes resource ingresses
    at r.<anonymous> (Lens.js:2)
    at c (Lens.js:2)
    at Generator._invoke (Lens.js:2)
    at Generator.forEach.e.<computed> [as next] (Lens.js:2)
    at o (Lens.js:2)
```

**Additional context**

Maybe it's because my minikube doesn't support k8s `ingress` api?

`kubectl api-versions ` returns (no ingress api)
```
admissionregistration.k8s.io/v1
admissionregistration.k8s.io/v1beta1
apiextensions.k8s.io/v1
apiextensions.k8s.io/v1beta1
apiregistration.k8s.io/v1
apiregistration.k8s.io/v1beta1
apps/v1
authentication.k8s.io/v1
authentication.k8s.io/v1beta1
authorization.k8s.io/v1
authorization.k8s.io/v1beta1
autoscaling/v1
autoscaling/v2beta1
autoscaling/v2beta2
batch/v1
batch/v1beta1
certificates.k8s.io/v1
certificates.k8s.io/v1beta1
coordination.k8s.io/v1
coordination.k8s.io/v1beta1
discovery.k8s.io/v1beta1
events.k8s.io/v1
events.k8s.io/v1beta1
extensions/v1beta1
networking.k8s.io/v1
networking.k8s.io/v1beta1
node.k8s.io/v1beta1
policy/v1beta1
rbac.authorization.k8s.io/v1
rbac.authorization.k8s.io/v1beta1
scheduling.k8s.io/v1
scheduling.k8s.io/v1beta1
storage.k8s.io/v1
storage.k8s.io/v1beta1
v1
```

`kubectl version` returns
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-14T14:49:35Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

### PR DESCRIPTION
**Pull request by panuhorsmalahti**
Fixes #1570

### CODE REVIEW

File: src/renderer/api/kube-api.ts [hunk 1]
```diff
@@ -173,13 +173,18 @@ export class KubeApi<T extends KubeObject = any> {
...
-    } else {
-      return {
-        apiPrefix: this.apiPrefix,
-        apiGroup: this.apiGroup
-      };
+      try {
+        return await this.getLatestApiPrefixGroup();
+      } catch (error) {
+        // If valid API wasn't found, log the error and return defaults below
+        console.error(error);
```
Comment (jakolehm) [inline src/renderer/api/kube-api.ts]: Should we use `logger` here?

Comment (panuhorsmalahti) [reply src/renderer/api/kube-api.ts]: Changed.

I did notice that logger.error doesn't print the stack trace, console.error does, but that's probably good here.

**Review by jakolehm — APPROVED** [review]
