### PR TITLE
Wait for a file to be stable before computing diff

### LINKED ISSUE #3405: Lens disconnects from current cluster when kubeconfig is updated
**Describe the bug**
When the kubeconfig file used by Lens is updated, Lens disconnects from the currently connected cluster.

**To Reproduce**
1. Start Lens
2. Connect to a cluster
3. Perform a kubeconfig update (.e.g. with `aws eks update-kubeconfig`)
4. Observe that Lens disconnects from cluster and returns to catalog page

**Expected behavior**
Lens does not disconnect from the currently connected cluster

**Environment (please complete the following information):**
- Lens Version: 5.1.0 (also observed on 5.0.2)
- OS: Windows 10 21H1
- 
**Logs:**
These logs are displayed at the time of disconnect/kubeconfig update
```

error: [LENS-PROXY]: http proxy errored for cluster: Error: read ECONNRESET {"url":"/api/v1/namespaces?watch=1&resourceVersion=177244"}
error: [LENS-PROXY]: Failed to write headers: Cannot render headers after they are sent to the client {"code":"ERR_HTTP_HEADERS_SENT","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot render headers after they are sent to the client\n    at ServerResponse.writeHead (_http_server.js:273:13)\n    at ProxyServer.<anonymous> (C:\\Users\\ahempel\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:117433)\n    at ProxyServer.emit (C:\\Users\\ahempel\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\eventemitter3\\index.js:210:27)\n    at ClientRequest.proxyError (C:\\Users\\ahempel\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\http-proxy\\lib\\http-proxy\\passes\\web-incoming.js:165:18)\n    at ClientRequest.emit (events.js:228:7)\n    at ClientRequest.EventEmitter.emit (domain.js:475:20)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:223:5)\n    at Socket.EventEmitter.emit (domain.js:475:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)"}
error: [LENS-PROXY]: http proxy errored for cluster: Error: read ECONNRESET {"url":"/api/v1/namespaces?watch=1&resourceVersion=177244"}
error: [LENS-PROXY]: Failed to write headers: Cannot render headers after they are sent to the client {"code":"ERR_HTTP_HEADERS_SENT","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot render headers after they are sent to the client\n    at ServerResponse.writeHead (_http_server.js:273:13)\n    at ProxyServer.<anonymous> (C:\\Users\\ahempel\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:117433)\n    at ProxyServer.emit (C:\\Users\\ahempel\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\eventemitter3\\index.js:210:27)\n    at ClientRequest.proxyError (C:\\Users\\ahempel\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\http-proxy\\lib\\http-proxy\\passes\\web-incoming.js:165:18)\n    at ClientRequest.emit (events.js:228:7)\n    at ClientRequest.EventEmitter.emit (domain.js:475:20)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:223:5)\n    at Socket.EventEmitter.emit (domain.js:475:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)"}
error: [LENS-PROXY]: http proxy errored for cluster: Error: read ECONNRESET {"url":"/api/v1/events?watch=1&resourceVersion=177278"}
error: [LENS-PROXY]: Failed to write headers: Cannot render headers after they are sent to the client {"code":"ERR_HTTP_HEADERS_SENT","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot render headers after they are sent to the client\n    at ServerResponse.writeHead (_http_server.js:273:13)\n    at ProxyServer.<anonymous> (C:\\Users\\ahempel\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:117433)\n    at ProxyServer.emit (C:\\Users\\ahempel\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\eventemitter3\\index.js:210:27)\n    at ClientRequest.proxyError (C:\\Users\\ahempel\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\http-proxy\\lib\\http-proxy\\passes\\web-incoming.js:165:18)\n    at ClientRequest.emit (events.js:228:7)\n    at ClientRequest.EventEmitter.emit (domain.js:475:20)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:223:5)\n    at Socket.EventEmitter.emit (domain.js:475:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)"}
error: [LENS-PROXY]: http proxy errored for cluster: Error: read ECONNRESET {"url":"/api/v1/persistentvolumeclaims?watch=1&resourceVersion=177278"}
error: [LENS-PROXY]: Failed to write headers: Cannot render headers after they are sent to the client {"code":"ERR_HTTP_HEADERS_SENT","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot render headers after they are sent to the client\n    at ServerResponse.writeHead (_http_server.js:273:13)\n    at ProxyServer.<anonymous> (C:\\Users\\ahempel\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:117433)\n    at ProxyServer.emit (C:\\Users\\ahempel\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\eventemitter3\\index.js:210:27)\n    at ClientRequest.proxyError (C:\\Users\\ahempel\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\http-proxy\\lib\\http-proxy\\passes\\web-incoming.js:165:18)\n    at ClientRequest.emit (events.js:228:7)\n    at ClientRequest.EventEmitter.emit (domain.js:475:20)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:223:5)\n    at Socket.EventEmitter.emit (domain.js:475:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)"}
error: [LENS-PROXY]: http proxy errored for cluster: Error: read ECONNRESET {"url":"/api/v1/pods?watch=1&resourceVersion=177242"}
error: [LENS-PROXY]: Failed to write headers: Cannot render headers after they are sent to the client {"code":"ERR_HTTP_HEADERS_SENT","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot render headers after they are sent to the client\n    at ServerResponse.writeHead (_http_server.js:273:13)\n    at ProxyServer.<anonymous> (C:\\Users\\ahempel\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:117433)\n    at ProxyServer.emit (C:\\Users\\ahempel\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\eventemitter3\\index.js:210:27)\n    at ClientRequest.proxyError (C:\\Users\\ahempel\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\http-proxy\\lib\\http-proxy\\passes\\web-incoming.js:165:18)\n    at ClientRequest.emit (events.js:228:7)\n    at ClientRequest.EventEmitter.emit (domain.js:475:20)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:223:5)\n    at Socket.EventEmitter.emit (domain.js:475:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)"}
error: [LENS-PROXY]: http proxy errored for cluster: Error: read ECONNRESET {"url":"/api/v1/pods?watch=1&resourceVersion=177278"}
error: [LENS-PROXY]: Failed to write headers: Cannot render headers after they are sent to the client {"code":"ERR_HTTP_HEADERS_SENT","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot render headers after they are sent to the client\n    at ServerResponse.writeHead (_http_server.js:273:13)\n    at ProxyServer.<anonymous> (C:\\Users\\ahempel\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:117433)\n    at ProxyServer.emit (C:\\Users\\ahempel\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\eventemitter3\\index.js:210:27)\n    at ClientRequest.proxyError (C:\\Users\\ahempel\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\http-proxy\\lib\\http-proxy\\passes\\web-incoming.js:165:18)\n    at ClientRequest.emit (events.js:228:7)\n    at ClientRequest.EventEmitter.emit (domain.js:475:20)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:223:5)\n    at Socket.EventEmitter.emit (domain.js:475:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)"}
error: [LENS-PROXY]: http proxy errored for cluster: Error: read ECONNRESET {"url":"/api/v1/nodes?watch=1&resourceVersion=177244"}
error: [LENS-PROXY]: Failed to write headers: Cannot render headers after they are sent to the client {"code":"ERR_HTTP_HEADERS_SENT","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot render headers after they are sent to the client\n    at ServerResponse.writeHead (_http_server.js:273:13)\n    at ProxyServer.<anonymous> (C:\\Users\\ahempel\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:117433)\n    at ProxyServer.emit (C:\\Users\\ahempel\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\eventemitter3\\index.js:210:27)\n    at ClientRequest.proxyError (C:\\Users\\ahempel\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\http-proxy\\lib\\http-proxy\\passes\\web-incoming.js:165:18)\n    at ClientRequest.emit (events.js:228:7)\n    at ClientRequest.EventEmitter.emit (domain.js:475:20)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:223:5)\n    at Socket.EventEmitter.emit (domain.js:475:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)"}
error: [LENS-PROXY]: http proxy errored for cluster: Error: read ECONNRESET {"url":"/api/v1/events?watch=1&resourceVersion=177244"}
error: [LENS-PROXY]: Failed to write headers: Cannot render headers after they are sent to the client {"code":"ERR_HTTP_HEADERS_SENT","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot render headers after they are sent to the client\n    at ServerResponse.writeHead (_http_server.js:273:13)\n    at ProxyServer.<anonymous> (C:\\Users\\ahempel\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:117433)\n    at ProxyServer.emit (C:\\Users\\ahempel\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\eventemitter3\\index.js:210:27)\n    at ClientRequest.proxyError (C:\\Users\\ahempel\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\http-proxy\\lib\\http-proxy\\passes\\web-incoming.js:165:18)\n    at ClientRequest.emit (events.js:228:7)\n    at ClientRequest.EventEmitter.emit (domain.js:475:20)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:223:5)\n    at Socket.EventEmitter.emit (domain.js:475:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)"}
```

**Additional context**
This may be an edge case, but we work a lot with transient clusters, and have scripts that dynamically update our kubeconfigs. This issue does not happen with Lens 4.2.5 and older.

### PR DESCRIPTION
**Pull request by Nokel81**
Signed-off-by: Sebastian Malton <sebastian@malton.name>

fixes https://github.com/lensapp/lens/issues/3405

### CODE REVIEW

File: src/main/catalog-sources/kubeconfig-sync.ts [hunk 1]
```diff
@@ -36,9 +37,23 @@ import { UserStore } from "../../common/user-store";
...
 import { homedir } from "os";
+import globToRegExp from "glob-to-regexp";
+import { inspect } from "util";
 
 const logPrefix = "[KUBECONFIG-SYNC]:";
 
+/**
+ * This is the list of globs of which files are ignored when under a folder sync
+ */
+const ignoreGlobs = [
```
Comment (jakolehm) [inline src/main/catalog-sources/kubeconfig-sync.ts]: Could you split ignore stuff to a separate PR?

Comment (Nokel81) [reply src/main/catalog-sources/kubeconfig-sync.ts]: Sure

**Comment by Nokel81** [comment]
@jakolehm Done, this PR just has the stability check now.

**Review by jakolehm — APPROVED** [review]
