### PR TITLE
Fix spdy proxy

### LINKED ISSUE #913: Lens fails to open a pod shell with a proxied kubernetes api.
**Describe the bug**
I'm connecting through a Rancher instance that's behind a Nginx ingress controller.

I'm guessing that the Lens proxy is not passing the host headers when doing an "exec" to open a shell on a pod. Could be related to #873

```
➜ exec kubectl exec -i -t -n datadog datadog-workers-4pctl -c agent "--" sh -c "clear; (bash || ash || sh)"
error: unable to upgrade connection: <html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
Terminal will auto-close in 15 seconds ...
```

**To Reproduce**

- Connect to cluster managed by Rancher.
- Try to open a shell on a pod.

**Expected behavior**

Shell opens on pod. 
I have confirmed that this does work with using plain `kubectl`.

**Environment (please complete the following information):**
- Lens Version: 3.6.2
- OS: Linux Pop!_OS 20.04 LTS
- Installation method (e.g. snap or AppImage in Linux): Snap
 
**Logs:**

```
debug: Set kubectl version 1.17.11 for cluster version 1.17.11 using version map
info: [IPC]: setup channel "cluster:activate"
info: [IPC]: setup channel "cluster:disconnect"
info: [IPC]: setup channel "cluster:install-feature"
info: [IPC]: setup channel "cluster:uninstall-feature"
info: [IPC]: setup channel "cluster:upgrade-feature"
info: 🚀 Starting Lens from "/home/jgreat/snap/kontena-lens/118/.config/Lens"
info: SNAP env is defined, updater is disabled
debug: Lookup new free port..
debug: New port found: 41995
info: [STORE]: LOADED from /home/jgreat/snap/kontena-lens/118/.config/Lens/config.json
info: [STORE]: LOADED from /home/jgreat/snap/kontena-lens/118/.config/Lens/lens-cluster-store.json
info: [STORE]: LOADED from /home/jgreat/snap/kontena-lens/118/.config/Lens/lens-workspace-store.json
info: [CLUSTER-MANAGER]: init cluster {"id":"ef2984ad-e068-4f7f-a4ab-5f9901a0cd38","name":"rh-staging-u1-a","initialized":false}
debug: Lookup new free port..
info: [CLUSTER]: "rh-staging-u1-a" init success {"id":"ef2984ad-e068-4f7f-a4ab-5f9901a0cd38","context":"rh-staging-u1-a","apiUrl":"https://rancher.fakename.com/k8s/clusters/c-zwq6f"}
info: LensProxy server has started at http://localhost:41995
debug: New port found: 39097
debug: Dumping KubeConfig: {"apiVersion":"v1","kind":"Config","preferences":{},"current-context":"rh-staging-u1-a","clusters":[{"name":"rh-staging-u1-a","cluster":{"server":"http://127.0.0.1:41995/ef2984ad-e068-4f7f-a4ab-5f9901a0cd38"}}],"contexts":[{"name":"rh-staging-u1-a","context":{"cluster":"rh-staging-u1-a","user":"proxy"}}],"users":[{"name":"proxy","user":{}}]}
debug: Created temp kubeconfig "rh-staging-u1-a" at "/tmp/kubeconfig-ef2984ad-e068-4f7f-a4ab-5f9901a0cd38": 
apiVersion: v1
kind: Config
preferences: {}
current-context: rh-staging-u1-a
clusters:
  - name: rh-staging-u1-a
    cluster:
      server: 'http://127.0.0.1:41995/ef2984ad-e068-4f7f-a4ab-5f9901a0cd38'
contexts:
  - name: rh-staging-u1-a
    context:
      cluster: rh-staging-u1-a
      user: proxy
users:
  - name: proxy
    user: {}

debug: Acquired a lock for 1.17.11
debug: Releasing lock for 1.17.11
debug: spawning kubectl proxy with args: proxy,-p,39097,--kubeconfig,/home/jgreat/k8s/rh-staging-u1-a/kubeconfig.yaml,--context,rh-staging-u1-a,--accept-hosts,.*,--reject-paths,^[^/]
info: [KUBE-AUTH]: out-channel "kube-auth:ef2984ad-e068-4f7f-a4ab-5f9901a0cd38" {"data":"Authentication proxy started\n","meta":{"id":"ef2984ad-e068-4f7f-a4ab-5f9901a0cd38","name":"rh-staging-u1-a","initialized":true}}
info: [CLUSTER]: activate {"id":"ef2984ad-e068-4f7f-a4ab-5f9901a0cd38","name":"rh-staging-u1-a","initialized":true}
info: [CLUSTER]: bind events {"id":"ef2984ad-e068-4f7f-a4ab-5f9901a0cd38","name":"rh-staging-u1-a","initialized":true}
info: [CLUSTER]: refresh {"id":"ef2984ad-e068-4f7f-a4ab-5f9901a0cd38","name":"rh-staging-u1-a","initialized":true}
debug: Set kubectl version 1.18.8 for cluster version v1.18.8+k3s1 using version map
debug: features for rh-staging-u1-a
debug: feature metrics
debug: getting feature status...
debug: Acquired a lock for 1.18.8
debug: Local kubectl is version 1.18.8
debug: Releasing lock for 1.18.8
debug: feature user-mode
debug: getting feature status...
debug: getFeatures resolving with features: {"metrics":{"currentVersion":null,"installed":false,"latestVersion":"v2.17.2-lens1","canUpgrade":false},"user-mode":{"currentVersion":null,"installed":false,"latestVersion":"v2.0.0","canUpgrade":false}}
warn: PrometheusLens: failed to list services: services "prometheus" not found
warn: PrometheusLens: failed to list services: services "prometheus" not found
warn: PrometheusLens: failed to list services: services "prometheus" not found
warn: PrometheusLens: failed to list services: services "prometheus" not found
info: using lens as prometheus provider
info: using lens as prometheus provider
debug: watch using kubeconfig:{
  "contexts": [
    {
      "cluster": "rh-staging-u1-a",
      "name": "rh-staging-u1-a",
      "user": "proxy"
    }
  ],
  "clusters": [
    {
      "name": "rh-staging-u1-a",
      "server": "http://127.0.0.1:41995/ef2984ad-e068-4f7f-a4ab-5f9901a0cd38",
      "skipTLSVerify": false
    }
  ],
  "users": [
    {
      "name": "proxy"
    }
  ],
  "currentContext": "rh-staging-u1-a"
}
debug: watch using kubeconfig:{
  "contexts": [
    {
      "cluster": "rh-staging-u1-a",
      "name": "rh-staging-u1-a",
      "user": "proxy"
    }
  ],
  "clusters": [
    {
      "name": "rh-staging-u1-a",
      "server": "http://127.0.0.1:41995/ef2984ad-e068-4f7f-a4ab-5f9901a0cd38",
      "skipTLSVerify": false
    }
  ],
  "users": [
    {
      "name": "proxy"
    }
  ],
  "currentContext": "rh-staging-u1-a"
}
info: [CLUSTER]: refresh {"id":"ef2984ad-e068-4f7f-a4ab-5f9901a0cd38","name":"rh-staging-u1-a","initialized":true,"ready":true,"online":true,"accessible":true}
debug: Set kubectl version 1.18.8 for cluster version v1.18.8+k3s1 using version map
debug: features for rh-staging-u1-a
debug: feature metrics
debug: getting feature status...
debug: Acquired a lock for 1.18.8
debug: Local kubectl is version 1.18.8
debug: Releasing lock for 1.18.8
debug: feature user-mode
debug: getting feature status...
debug: getFeatures resolving with features: {"metrics":{"currentVersion":null,"installed":false,"latestVersion":"v2.17.2-lens1","canUpgrade":false},"user-mode":{"currentVersion":null,"installed":false,"latestVersion":"v2.0.0","canUpgrade":false}}
debug: Set kubectl version 1.18.8 for cluster version v1.18.8+k3s1 using version map
debug: Acquired a lock for 1.18.8
debug: Local kubectl is version 1.18.8
debug: Releasing lock for 1.18.8
debug: Acquired a lock for 1.18.8
debug: Local kubectl is version 1.18.8
debug: Releasing lock for 1.18.8
info: [KUBE-AUTH]: out-channel "kube-auth:ef2984ad-e068-4f7f-a4ab-5f9901a0cd38" {"data":"W0917 11:49:02.983069 1073704 dial.go:67] using custom dialer with no TLSClientConfig. Defaulting to InsecureSkipVerify\n","error":true,"meta":{"id":"ef2984ad-e068-4f7f-a4ab-5f9901a0cd38","name":"rh-staging-u1-a","initialized":true,"ready":true,"online":true,"accessible":true}}
(node:1073419) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
info: [CLUSTER]: refresh {"id":"ef2984ad-e068-4f7f-a4ab-5f9901a0cd38","name":"rh-staging-u1-a","initialized":true,"ready":true,"online":true,"accessible":true}
debug: Set kubectl version 1.18.8 for cluster version v1.18.8+k3s1 using version map
debug: features for rh-staging-u1-a
debug: feature metrics
debug: getting feature status...
debug: Acquired a lock for 1.18.8
debug: Local kubectl is version 1.18.8
debug: Releasing lock for 1.18.8
debug: feature user-mode
debug: getting feature status...
debug: getFeatures resolving with features: {"metrics":{"currentVersion":null,"installed":false,"latestVersion":"v2.17.2-lens1","canUpgrade":false},"user-mode":{"currentVersion":null,"installed":false,"latestVersion":"v2.0.0","canUpgrade":false}}
```

### PR DESCRIPTION
**Pull request by jakolehm**
Fixes cases where Host header is required for proxying to work (like Rancher).

Fixes #913

### CODE REVIEW

File: src/main/lens-proxy.ts [hunk 1]
```diff
@@ -73,12 +71,41 @@ export class LensProxy {
...
       const proxyUrl = await cluster.contextHandler.resolveAuthProxyUrl() + req.url.replace(apiKubePrefix, "")
       const apiUrl = url.parse(cluster.apiUrl)
-      const res = new http.ServerResponse(req)
-      res.assignSocket(socket)
-      res.setHeader("Location", proxyUrl)
-      res.setHeader("Host", apiUrl.hostname)
-      res.statusCode = 302
-      res.end()
+      const pUrl = url.parse(proxyUrl)
+      const connectOpts = {port: parseInt(pUrl.port), host: pUrl.hostname}
```
Comment (nevalla) [inline src/main/lens-proxy.ts]:
```suggestion
      const connectOpts = { port: parseInt(pUrl.port), host: pUrl.hostname }
```

File: src/main/lens-proxy.ts [hunk 2]
```diff
@@ -73,12 +71,41 @@ export class LensProxy {
...
+      const proxySocket = new net.Socket()
+      proxySocket.connect(connectOpts, () => {
+        proxySocket.write(`${req.method} ${pUrl.path} HTTP/1.1\r\n`)
+        proxySocket.write(`Host: ${apiUrl.host}\r\n`)
+        for(let i = 0; i < req.rawHeaders.length; i++) {
```
Comment (nevalla) [inline src/main/lens-proxy.ts]:
```suggestion
        for (let i = 0; i < req.rawHeaders.length; i++) {
```

File: src/main/lens-proxy.ts [hunk 3]
```diff
@@ -73,12 +71,41 @@ export class LensProxy {
...
+          const key = req.rawHeaders[i]
+          if (key !== "Host" && key !== "Authorization") {
+            proxySocket.write(`${req.rawHeaders[i]}: ${req.rawHeaders[i+1]}\r\n`)
+          }
+          i++
+        }
```
Comment (Nokel81) [inline src/main/lens-proxy.ts]: This is very error prone. I would recommend using `for (const [headerName, headerValue] of Object.entries(req.headers) { ... }`.

At the very least, having two places where you increment `i` seems like bad idea imo.

File: src/main/lens-proxy.ts [hunk 4]
```diff
@@ -73,12 +71,41 @@ export class LensProxy {
...
+        proxySocket.write(head)
+      })
+      proxySocket.on('data', function (chunk) {
+        socket.write(chunk)
+      })
+      proxySocket.on('end', function () {
+        socket.end()
+      })
+      proxySocket.on('error', function (err) {
+        socket.write("HTTP/" + req.httpVersion + " 500 Connection error\r\n\r\n");
```
Comment (Nokel81) [inline src/main/lens-proxy.ts:96]: Should we log the error some where, maybe to console?

**Review by Nokel81 — CHANGES_REQUESTED** [review]

File: src/main/lens-proxy.ts (hunk 3 above)
Comment (jakolehm) [reply src/main/lens-proxy.ts]: @Nokel81 how would you improve this? `rawHeaders` is an array with paired values.

Comment (jakolehm) [reply src/main/lens-proxy.ts]: Nevermind, you already posted an example how to improve 😄

**Review by nevalla — APPROVED** [review]
Added couple of coding style fixes, otherwise LGTM.

File: src/main/lens-proxy.ts (hunk 3 above)
Comment (Nokel81) [reply src/main/lens-proxy.ts]: If you want to keep the handling of headers the same (since `headers` does some de-duplication. I would mearly change the loop to be:

```js
for (let i = 0; i < req.rawHeaders.length; i += 2) {
    ...
}
```

Comment (jakolehm) [reply src/main/lens-proxy.ts]: Yes, we need rawHeaders. Thanks for the suggestion, much better now 👍

File: src/main/lens-proxy.ts (hunk 4 above)
Comment (jakolehm) [reply src/main/lens-proxy.ts:96]: Probably not here, proxy itself will log (and retry) if response has an error.

**Review by Nokel81 — APPROVED** [review]
