### PR TITLE
Show all pod addresses

### LINKED ISSUE #2745: Lens should show ALL pod addresses
**Describe the bug**
Currently Lens shows only the first (?) IP for a pod. Pod can actually have many (at least two) addresses e.g. when running the cluster in dual-stack mode (IPv4&6)

**To Reproduce**
Connect Lens into cluster running with dual stack mode, e.g. like k0s supports it: https://docs.k0sproject.io/v1.21.0+k0s.0/dual-stack/

The pod json data has the addresses like so:
```
        "podIP": "10.244.115.129",
        "podIPs": [
            {
                "ip": "10.244.115.129"
            },
            {
                "ip": "fd00::3:e501"
            }
        ],
```

**Expected behavior**
Lens should show all Pod addresses

**Screenshots**
Screenshot 2021-05-11 at 11 41 00

**Environment (please complete the following information):**
- Lens Version: 4.2.4
- OS: OSX
- Installation method (e.g. snap or AppImage in Linux):

### PR DESCRIPTION
**Pull request by vshakirova**
Screen Shot 2021-05-23 at 8 12 00 AM
Screen Shot 2021-05-23 at 8 12 16 AM

spec: 
https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/pkg/apis/core/types.go

fix: https://github.com/lensapp/lens/issues/2745

### CODE REVIEW

File: src/renderer/components/+network-services/service-details.tsx [hunk 1]
```diff
@@ -77,6 +77,24 @@ export class ServiceDetails extends React.Component<Props> {
           {spec.clusterIP}
         </DrawerItem>
 
+        {service.getClusterIps().length > 0 && (
+          <DrawerItem name="Cluster IPs">
+            {service.getClusterIps().join(", ")}
+          </DrawerItem>
+        )}
```
Comment (Nokel81) [inline src/renderer/components/+network-services/service-details.tsx]: Nit, `DrawerItem` has a `hidden` prop, which I think should be used instead of doing the `&&`.

Furthermore, I think it would be better to encapsulate all the IPs in `<Badge>` instead of just joining with `", "`. This would also apply to the above item too.

**Review by Nokel81 — COMMENTED** [review]
Thanks for doing this, just a visual recommendation.

File: src/renderer/components/+network-services/service-details.tsx (hunk 1 above)
Comment (nevalla) [reply src/renderer/components/+network-services/service-details.tsx]: How about just putting those in separate lines?

Comment (Nokel81) [reply src/renderer/components/+network-services/service-details.tsx]: That could work too, I just felt that badge's would look nicer.

Comment (vshakirova) [reply src/renderer/components/+network-services/service-details.tsx]: thank you, fixed it, but still have problems with test timeout.
```Timeout - Async callback was not invoked within the 60000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 60000 ms timeout specified by jest.setTimeout.Error:```

Comment (Nokel81) [reply src/renderer/components/+network-services/service-details.tsx]: @vshakirova If the tests pass locally on your machine, I would just rerun them. If you don't have permissions, just poke one of us.

File: src/renderer/api/endpoints/pods.api.ts [hunk 2]
```diff
@@ -485,6 +488,13 @@ export class Pod extends WorkloadKubeObject {
   getSelectedNodeOs(): string | undefined {
     return this.spec.nodeSelector?.["kubernetes.io/os"] || this.spec.nodeSelector?.["beta.kubernetes.io/os"];
   }
+
+  getIPs(): string[] {
+    if(!this.status.podIPs) return [];
+    const podIPs = this.status.podIPs;
+
+    return podIPs.map(value => value.ip);
+  }
```
Comment (Nokel81) [inline src/renderer/api/endpoints/pods.api.ts:497]: nit:
```suggestion
  getIPs(): string[] {
    return this.status.podIPs?.map(({ ip }) => ip) ?? [];
  }
```

**Review by Nokel81 — APPROVED** [review]

**Review by nevalla — APPROVED** [review]

File: src/renderer/api/endpoints/pods.api.ts [hunk 3]
```diff
@@ -275,6 +275,9 @@ export class Pod extends WorkloadKubeObject {
     }[];
     hostIP: string;
     podIP: string;
+    podIPs?: {
+      ip: string
+    }[];
```
Comment (BlackHole1) [inline src/renderer/api/endpoints/pods.api.ts:280]: there must be podIPs, we can remove the podIP

If there is only one ip, then it will have the following format:

```
podIPs: [{
  ip: "ip"
}]
```

Comment (vshakirova) [reply src/renderer/api/endpoints/pods.api.ts:280]: Hi @BlackHole1, yeah, we can. But the spec (https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go#L3638) still has this field. Maybe the spec still has this field for backward compatibility, PodIPs has been added in 1.16 kubernetes release (as I can see) https://github.com/kubernetes/kubernetes/blob/release-1.15/staging/src/k8s.io/api/core/v1/types.go

Comment (BlackHole1) [reply src/renderer/api/endpoints/pods.api.ts:280]: If we want to follow the spec definition, then our `hostIP`, `podIP`, etc. also need to be changed to optional

Comment (BlackHole1) [reply src/renderer/api/endpoints/pods.api.ts:280]: You're right.

Comment (Nokel81) [reply src/renderer/api/endpoints/pods.api.ts:280]: I would prefer if we didn't touch the fields at all. We can modify the methods so that `getPodIps()` returns the unique ip strings as an array if we want.
