### PR TITLE
Setting new workspace name restrictions

### LINKED ISSUE #826: User can create duplicately named workspaces (including default)
**Describe the bug**
When creating a workspace there is no check for a duplicately named workspace (including default). Lens does not get confused so this isn't strictly a bug but it can lead to a poor UX experience as the user can lose track of which workspace is which. Best to avoid this situation, or at least warn the user when a duplicate name is chosen

**To Reproduce**
1. Create duplicate workspaces
2. Click on workspace selector at bottom left corner (Lens 3.6)
3. Which is which?

**Expected behavior**
Don't allow duplicates, or at least warn the user when a duplicate name is chosen

**Screenshots**
Screen Shot 2020-09-08 at 12 39 11 PM

**Environment (please complete the following information):**
- Lens Version: 3.6.0-rc.1
- OS: tested on OSX 
- Installation method (e.g. snap or AppImage in Linux): dmg

### PR DESCRIPTION
**Pull request by aleksfront**
* Preventing workspaces to have empty or existent name
* Swapped 'save' and 'clear' buttons
* Save workspace on hitting `Enter`.

workspace errors

Resolves #826

### CODE REVIEW

File: src/common/workspace-store.ts [hunk 1]
```diff
@@ -67,14 +71,20 @@ export class WorkspaceStore extends BaseStore<WorkspaceStoreModel> {
   }
 
   @action
-  saveWorkspace(workspace: Workspace) {
-    const id = workspace.id;
+  saveWorkspace(workspace: Workspace): { workspace?: Workspace, error?: string} {
```
Comment (ixrock) [inline src/common/workspace-store.ts:74]: I think it's a wrong place to handle `error` like this.

Comment (Nokel81) [inline src/common/workspace-store.ts]: I know it is slightly more work but wouldn't it be better to have this return value be `{ workspace: Workspace } | { error: string }`?

File: src/renderer/components/+workspaces/workspaces.tsx [hunk 2]
```diff
@@ -41,10 +42,12 @@ export class Workspaces extends React.Component {
 
   saveWorkspace = (id: WorkspaceId) => {
     const draft = toJS(this.editingWorkspaces.get(id));
-    if (draft) {
+    const { error } = workspaceStore.saveWorkspace(draft);
+    if (!error) {
```
Comment (Nokel81) [inline src/renderer/components/+workspaces/workspaces.tsx]: Re: above; this would change to `const res = ...; if ("workspace" in res) { ...`

**Review by Nokel81 — APPROVED** [review]

File: src/common/workspace-store.ts (hunk 1 above)
Comment (ixrock) [reply src/common/workspace-store.ts]: @Nokel81 I guess in this case it would be a bit harder to consume results of this function in typescript. 
@aleksfront wdyt?

Comment (Nokel81) [reply src/common/workspace-store.ts]: A little (you have to do `"workspace" in res` but I think that it better communicates what the intent is.

**Review by jakolehm — CHANGES_REQUESTED** [review]
Error should show as in cluster settings / preferences (error message comes directly under a field).

File: src/common/workspace-store.ts (hunk 1 above)
Comment (aleksfront) [reply src/common/workspace-store.ts]: What if this function will return a value **only** if it has error? So return type would be as simple as `string`. If saving goes okay, it won't return anything.

File: src/common/workspace-store.ts [hunk 3]
```diff
@@ -67,14 +71,20 @@ export class WorkspaceStore extends BaseStore<WorkspaceStoreModel> {
...
+    const { id, name } = workspace;
     const existingWorkspace = this.getById(id);
+    if (!name) {
+      return { error: "Workspace should has a name." };
+    }
+    if (this.getByName(name)) {
+      return { error: `Workspace '${name}' already exist.` };
```
Comment (jim-docker) [inline src/common/workspace-store.ts]: typo: should be `already exists`

File: src/common/workspace-store.ts (hunk 1 above)
Comment (Nokel81) [reply src/common/workspace-store.ts]: Makes sense, `string | null` since I see the only case where this function's return value is being used is to check the error.

File: src/common/workspace-store.ts [hunk 4]
```diff
@@ -67,14 +71,20 @@ export class WorkspaceStore extends BaseStore<WorkspaceStoreModel> {
   }
 
   @action
-  saveWorkspace(workspace: Workspace) {
-    const id = workspace.id;
+  saveWorkspace(workspace: Workspace): { workspace?: Workspace, error?: string} {
+    const { id, name } = workspace;
     const existingWorkspace = this.getById(id);
+    if (!name) {
+      return { error: "Workspace should has a name." };
```
Comment (jim-docker) [inline src/common/workspace-store.ts]: typo: should be `should have a name`. Or `"Workspace requires a name."`

File: src/common/workspace-store.ts [hunk 5]
```diff
@@ -67,14 +71,20 @@ export class WorkspaceStore extends BaseStore<WorkspaceStoreModel> {
   }
 
   @action
-  saveWorkspace(workspace: Workspace) {
-    const id = workspace.id;
+  saveWorkspace(workspace: Workspace): { workspace?: Workspace, error?: string} {
+    const { id, name } = workspace;
```
Comment (jim-docker) [inline src/common/workspace-store.ts:75]: name should be trimmed for leading/trailing spaces (and probably add a unit test for `" "`)

**Comment by aleksfront** [comment]
Sep-10-2020 11-03-59
Sep-10-2020 11-02-33

Made described changes with more elegant way using build-in validators.

@ixrock Please re-review.

File: src/common/workspace-store.ts (hunk 5 above)
Comment (aleksfront) [reply src/common/workspace-store.ts:75]: Great catch! Thanks for pointing out. Added more test cases.

File: src/common/workspace-store.ts (hunk 3 above)
Comment (aleksfront) [reply src/common/workspace-store.ts]: Fixed in custom validator.

**Review by jakolehm — APPROVED** [review]
