### PR TITLE
Fix Resource Quota Rendering

### LINKED ISSUE #465: ResourceQuota with 0 produces invalid Used value.
**Describe the bug**
If in ResourceQuota some quota is set to `0`, Used has invalid result `NaN` in the tooltip.

**To Reproduce**
Set some resource quota to `0`

**Expected behavior**
Value of the Used in the tooltip should be 100%

**Screenshots**
image

### LINKED ISSUE #519: ResourceQuota used percentage is wrong if total expressed with "k" suffix
**Describe the bug**
The used percentage of resourcequota is wrong in case the total is in terms of thousands, and the used is actual value. 
eg: if the total is 5k and the used is 5, it reports 100% used.

**To Reproduce**

**Expected behavior**
The usage percent computation should take the suffix into account. 5/5k is 0.1%

**Screenshots**
Screenshot 2020-06-24 at 10 20 35 PM

**Environment :**
- Lens Version: 3.5.0
- OS: OSX
- Installation method: homebrew

### PR DESCRIPTION
**Pull request by Nokel81**
- add parsing of quota values which are non-numeric in the general case

fixes #519 
fixes #465

~~I decided to put the PR against this branch as other code has been similarly brought in.~~

### CODE REVIEW

**Comment by nevalla** [comment]
> I decided to put the PR against this branch as other code has been similarly brought in.

I feel more natural to change this against `master` since `vue_react_migration` branch is already bloat enough

**Comment by Nokel81** [comment]
Okay, will do then.

**Comment by nevalla** [comment]
> Okay, will do then.

Are you able to change branch off the target branch for the PR? If not, I can do it.

**Comment by Nokel81** [comment]
I have and I have rebased the branch against master

File: src/renderer/utils/convertCpu.ts [hunk 1]
```diff
@@ -1,10 +1,13 @@
 // Helper to convert CPU K8S units to numbers
 
+const thousand = 1000;
+const million = thousand * thousand;
+const shortBillion = thousand * million;
```
Comment (aleksfront) [inline src/renderer/utils/convertCpu.ts:5]: Keywords are easier to understand, thanks for the idea! But why we need here `shortBillion` since it's just a `billion`. Suggesting to remove `short` part.

File: src/renderer/utils/convertMemory.ts [hunk 2]
```diff
@@ -7,6 +7,7 @@ export function unitsToBytes(value: string) {
   if (!suffixes.some(suffix => value.includes(suffix))) {
     return parseFloat(value)
   }
+
```
Comment (aleksfront) [inline src/renderer/utils/convertMemory.ts:10]: Linter is highlighting empty space. But maybe remove whole empty line since this style not used anywhere in this file.

**Comment by aleksfront** [comment]
👀

File: src/renderer/components/+config-resource-quotas/resource-quota-details.tsx [hunk 3]
```diff
@@ -15,24 +15,34 @@ import { KubeObjectMeta } from "../kube-object/kube-object-meta";
...
-      if (name.includes("cpu")) {
-        return cpuUnitsToNumber(value)
-      }
-      return parseInt(value)
-    }
-    return Object.entries(hard).map(([name, value]) => {
-      if (!used[name]) return null
+const onlyNumbers = /$[0-9]*^/g;
+
+function transformUnit(name: string, value: string): number {
```
Comment (aleksfront) [inline src/renderer/components/+config-resource-quotas/resource-quota-details.tsx:20]: Is there a reason moving `transformUnit` & `renderQuotas` out of `ResourceQuotaDetails` component?

File: src/renderer/components/+config-resource-quotas/resource-quota-details.tsx [hunk 4]
```diff
@@ -15,24 +15,34 @@ import { KubeObjectMeta } from "../kube-object/kube-object-meta";
...
+  if (name.includes("memory") || name.includes("storage")) {
+    return unitsToBytes(value)
+  }
+
```
Comment (aleksfront) [inline src/renderer/components/+config-resource-quotas/resource-quota-details.tsx]: Linter is claiming 1 unnecessary space.

File: src/renderer/components/+config-resource-quotas/resource-quota-details.tsx [hunk 5]
```diff
@@ -15,24 +15,34 @@ import { KubeObjectMeta } from "../kube-object/kube-object-meta";
...
+  }
+ 
+  if (name.includes("cpu")) {
+    return cpuUnitsToNumber(value)
+  }
+
+  if (onlyNumbers.test(value)) {
+    return parseInt(value);
+  }
+
```
Comment (aleksfront) [inline src/renderer/components/+config-resource-quotas/resource-quota-details.tsx]: Same here for linter.

File: src/renderer/components/+config-resource-quotas/resource-quota-details.tsx [hunk 6]
```diff
@@ -15,24 +15,34 @@ import { KubeObjectMeta } from "../kube-object/kube-object-meta";
...
+  if (onlyNumbers.test(value)) {
+    return parseInt(value);
+  }
+  
+  return compactedUnitsToNumber(value);
+}
+
+function renderQuotas(quota: ResourceQuota): JSX.Element[] {
+  const { hard = {}, used = {} } = quota.status
+
```
Comment (aleksfront) [inline src/renderer/components/+config-resource-quotas/resource-quota-details.tsx]: Same here for linter.

File: src/renderer/utils/compactedUnitsToNumber.ts [hunk 7]
```diff
@@ -0,0 +1,10 @@
+const base = 1000;
+const suffixes = ["k", "m", "g", "t", "q"];
+
+export function compactedUnitsToNumber(value: string): number {
```
Comment (aleksfront) [inline src/renderer/utils/compactedUnitsToNumber.ts]: Can you please add some comment about what this function actually doing with examples, like 1k -> 1000k. At first glance it's hard to understand what actually `compacted` part mean here. Maybe better to use some other naming, lime `metricUnitsToNumber`, wdyt?

File: src/renderer/utils/compactedUnitsToNumber.ts [hunk 8]
```diff
@@ -0,0 +1,10 @@
...
+  const justLetters = value.toLowerCase().replace(/[0-9]\./g, '')[0];
```
Comment (aleksfront) [inline src/renderer/utils/compactedUnitsToNumber.ts]: Please check this line. It seems that it doesn't work properly at the moment, making whole function work line `parseInt()`. It getting wrong results with values like `125k` - it always return number part. Maybe we can get suffix from value by popping last character? Like `value.toLowerCase().slice(-1)`?

File: src/renderer/components/+config-resource-quotas/resource-quota-details.tsx [hunk 9]
```diff
@@ -15,24 +15,34 @@ import { KubeObjectMeta } from "../kube-object/kube-object-meta";
...
+function transformUnit(name: string, value: string): number {
+  if (name.includes("memory") || name.includes("storage")) {
+    return unitsToBytes(value)
+  }
+ 
+  if (name.includes("cpu")) {
+    return cpuUnitsToNumber(value)
+  }
+
+  if (onlyNumbers.test(value)) {
```
Comment (aleksfront) [inline src/renderer/components/+config-resource-quotas/resource-quota-details.tsx]: Probably there's no need for this condition (and `onlyNumbers` constant) since following `compactedUnitsToNumber()` (or different func if we replace it's name like I suggested in comments) can handle this case. Just be aware of int to string transformation.

File: src/renderer/utils/index.ts [hunk 10]
```diff
@@ -20,3 +20,4 @@ export * from './formatDuration'
 export * from './isReactNode'
 export * from './convertMemory'
 export * from './convertCpu'
+export * from  './compactedUnitsToNumber'
```
Comment (aleksfront) [inline src/renderer/utils/index.ts]: Please remove second space after `from`.

File: src/renderer/utils/convertCpu.ts (hunk 1 above)
Comment (Nokel81) [reply src/renderer/utils/convertCpu.ts:5]: I wanted to make it clear to anyone (mostly from Europe) that it wasn't a `longBillion` (million * million). But if most everyone finds it clear enough then sure.

File: src/renderer/components/+config-resource-quotas/resource-quota-details.tsx (hunk 3 above)
Comment (Nokel81) [reply src/renderer/components/+config-resource-quotas/resource-quota-details.tsx:20]: They are essentially free functions that don't need access to `this`. So for better understanding I find that we shouldn't clutter up `ResourceQuotaDetails`.

File: src/renderer/utils/convertMemory.ts (hunk 2 above)
Comment (Nokel81) [reply src/renderer/utils/convertMemory.ts:10]: Which linter, I cannot find it locally or in the CI

Comment (aleksfront) [reply src/renderer/utils/convertMemory.ts:10]: Not sure what exact liner does that, but I have similar view in VSCode. All of the unecessary spaces goes highlighted.
empty spaces

**Review by aleksfront — APPROVED** [review]
Thanks for adding unit tests, they're really helping here.
