### PR TITLE
Fix detail views not watching child components

### LINKED ISSUE #4314: Pods list on Deployment details page doesn't update
This is happening on master:

https://user-images.githubusercontent.com/40840436/141183468-e72f1d40-f3ea-4554-80c9-2e9cf101eed5.mov

Even if you close the details page or show a different deployment's details page and then reopen the details page, the pods list is stale. If you click to a different dashboard page and then back to deployments and reopen, then the pods list is up-to-date. Missing watch on pods for deployments?

### PR DESCRIPTION
**Pull request by Nokel81**
- Add subscribeStores calls to all relavent details

- Add support for tracking overlapping subscribes as an optimization

Signed-off-by: Sebastian Malton <sebastian@malton.name>

fixes #4314

### CODE REVIEW

File: src/common/k8s-api/kube-watch-api.ts [hunk 1]
```diff
@@ -25,156 +25,185 @@
...
+  watchChanges: boolean;
+  namespaces: string[];
+  onLoadFailure?: (err: any) => void;
+}
 
-  constructor() {
-    makeObservable(this);
-    autoBind(this);
-  }
+class WatchCount {
```
Comment (jim-docker) [inline src/common/k8s-api/kube-watch-api.ts:79]: I'm surprised you didn't pull in a package, like refcount, for handling this

File: src/common/k8s-api/kube-object.store.ts [hunk 2]
```diff
@@ -167,21 +171,21 @@ export abstract class KubeObjectStore<T extends KubeObject> extends ItemStore<T>
     }
   }
 
-  protected async loadItems({ namespaces, api, reqInit, onLoadFailure }: KubeObjectStoreLoadingParams<T>): Promise<T[]> {
-    if (!this.context?.cluster.isAllowedResource(api.kind)) {
+  protected async loadItems({ namespaces, reqInit, onLoadFailure }: KubeObjectStoreLoadingParams): Promise<T[]> {
```
Comment (jim-docker) [inline src/common/k8s-api/kube-object.store.ts:174]: Why was `api` passed in as an argument? Could it be different than `this.api`?

File: src/common/k8s-api/kube-watch-api.ts [hunk 3]
```diff
@@ -25,156 +25,185 @@
...
+        cancelReloading();
+        childController.abort();
+        unsubscribe();
+      }
     };
   }
 
-  protected log({ message, cssStyle = "", meta = {}}: IKubeWatchLog) {
-    if (isProduction && !isDebugging) {
+  subscribeStores(stores: KubeObjectStore<KubeObject>[], { namespaces, onLoadFailure }: KubeWatchSubscribeStoreOptions = {}): Disposer {
```
Comment (jim-docker) [inline src/common/k8s-api/kube-watch-api.ts:179]: no more need for `preload`/`waitUntilLoaded`/`loadOnce` options? Certainly looks cleaner

**Review by jim-docker — COMMENTED** [review]
LVGTM, going to test a bit more tomorrow. Might be good if someone else looked this over too...

File: src/common/k8s-api/kube-watch-api.ts (hunk 1 above)
Comment (Nokel81) [reply src/common/k8s-api/kube-watch-api.ts:79]: Refcount seems to have 14 weekly downloads. For something like this I don't think a package is worth it.

File: src/common/k8s-api/kube-object.store.ts (hunk 2 above)
Comment (Nokel81) [reply src/common/k8s-api/kube-object.store.ts:174]: It used to be possible for it to be different. When a store supported several apis. But that was removed. This makes it clearer and should remove a possible future bug.

File: src/common/k8s-api/kube-watch-api.ts (hunk 3 above)
Comment (Nokel81) [reply src/common/k8s-api/kube-watch-api.ts:179]: No they are not needed as `preload` was default `true` and never set to `false`. Neither was `waitUntilLoaded` ever used. Finally `loadOnce`, IMO, was code smell because it meant that the watch was not high enough up. It was only used for the `NamespaceSelect` component but was not necessary because `NamespaceStore` was being watched at the cluster level anyway.

File: src/common/k8s-api/kube-watch-api.ts [hunk 4]
```diff
@@ -25,156 +25,185 @@
...
-      cancelReloading = reaction(() => this.context?.contextNamespaces, namespaces => {
-        preloading?.cancelLoading();
-        unsubscribeStores();
-        preloading = load(namespaces);
-        preloading.loading.then(subscribe);
-      }, {
-        equals: comparer.shallow,
-      });
-    }
+    loadThenSubscribe(namespaces);
```
Comment (nevalla) [inline src/common/k8s-api/kube-watch-api.ts]: `loadThenSubscribe` is async funtion, does this have any side effect that we don't await here?

File: src/common/k8s-api/kube-watch-api.ts [hunk 5]
```diff
@@ -25,156 +25,185 @@
...
+
+    // unsubscribe
+    return once(() => {
+      parent.abort();
+      unsubscribe();
+    });
+  }
+
+  protected log(message: any, meta: any) {
+    if (isProduction) {
```
Comment (nevalla) [inline src/common/k8s-api/kube-watch-api.ts]: why don't we log if `isProduction===true`? was it like this previously too?

File: src/common/k8s-api/kube-watch-api.ts (hunk 4 above)
Comment (Nokel81) [reply src/common/k8s-api/kube-watch-api.ts]: No, and in fact we don't want to await this (maybe I should make the obvious) because if the set of selected namespaces changes, we want to immediately abort and restart, which is what the reaction below is for.

File: src/common/k8s-api/kube-watch-api.ts (hunk 5 above)
Comment (Nokel81) [reply src/common/k8s-api/kube-watch-api.ts]: Good catch, I did subtly (and accidentally) change this. I think we probably should just remove this, and I will.

**Review by nevalla — COMMENTED** [review]
In general, looking good. This is fundamentally touching the store subscription, so we should look carefully that those are working properly. Could not spot any issues while reading, but did not test out.

**Comment by jim-docker** [comment]
Doing a stress test, the dashboard UI eventually freezes (the cluster renderer process?) sorry for the long video.

Using kubectl, 200 namespaces are created, then they are removed in Lens. During removal the UI eventually freezes.

https://user-images.githubusercontent.com/40840436/143138138-47aca86d-af1d-40ce-82ed-6bb244db6f93.mov

This is relevant here because the dashboard UI doesn't freeze on master (the watch looks to be broken though) for the same test.

Another interesting fact is that the UI freeze happens on local clusters (tried minikube on mac, microk8s on linux) but everything is fine for applying the same test on spaces clusters.

Not sure how important this is for this PR...

some output (tail) from the main process:

```
[0] info:    ▪ [KUBE-API] watch (devcluster-1) retried /apis/entities.k8slens.dev/v1beta1/namespaces/default/devclusters?watch=1&resourceVersion=1522857 +167ms
[0] info:    ▪ [KUBE-API] watch (weblink-1) retried /apis/entities.k8slens.dev/v1/namespaces/default/weblinks?watch=1&resourceVersion=1522857 +3ms
[0] info:    ┏ [CLUSTER]: refresh +30s
[0] info:    ┃ [1] {
[0] info:    ┃ [2]   id: '87bac5783b9b6bb49d42137caf351757',
[0] info:    ┃ [3]   name: 'minikube',
[0] info:    ┃ [4]   ready: true,
[0] info:    ┃ [5]   online: true,
[0] info:    ┃ [6]   accessible: true,
[0] info:    ┃ [7]   disconnected: false
[0] info:    ┗ [8] }
[0] 
[0] <--- Last few GCs --->
[0] 
[0] [60096:0x3600000000]   880762 ms: Scavenge 3806.0 (3966.8) -> 3800.8 (3968.1) MB, 6.7 / 0.0 ms  (average mu = 0.910, current mu = 0.921) allocation failure 
[0] [60096:0x3600000000]   880909 ms: Scavenge 3807.4 (3968.1) -> 3802.2 (3968.6) MB, 10.6 / 0.0 ms  (average mu = 0.910, current mu = 0.921) allocation failure 
[0] [60096:0x3600000000]   881255 ms: Scavenge 3808.5 (3968.6) -> 3803.4 (3968.6) MB, 209.2 / 0.0 ms  (average mu = 0.910, current mu = 0.921) allocation failure 
[0] 
[0] 
[0] <--- JS stacktrace --->
[0] 
[0] info:    ┏ [SHELL-SESSION]: websocket for 87bac5783b9b6bb49d42137caf351757:7cc19f97-d4da-4adb-a096-f7cb2a76414a closed with code=GoingAway(1001) +13s
[0] info:    ┃ [ 1] {
[0] info:    ┃ [ 2]   cluster: {
[0] info:    ┃ [ 3]     id: '87bac5783b9b6bb49d42137caf351757',
[0] info:    ┃ [ 4]     name: 'minikube',
[0] info:    ┃ [ 5]     ready: true,
[0] info:    ┃ [ 6]     online: true,
[0] info:    ┃ [ 7]     accessible: true,
[0] info:    ┃ [ 8]     disconnected: false
[0] info:    ┃ [ 9]   }
[0] info:    ┗ [10] }
[0] error:   ┏ [IPC]: failed to send IPC message "extensions@f3691b58df3ee1ce8cfc5e7d2dc88221b297786eed2f772bf44d140b16f25de4:spaces" to view "remote=5"'s subframe "frameInfo.processId"=10 "frameInfo.frameId"=5 +9s
[0] error:   ┗ [1] { error: 'Error: Render frame was disposed before WebFrameMain could be accessed' }
[0] error:   ┏ [IPC]: failed to send IPC message "extensions@f3691b58df3ee1ce8cfc5e7d2dc88221b297786eed2f772bf44d140b16f25de4:spaces" to view "window=1"'s subframe "frameInfo.processId"=10 "frameInfo.frameId"=5 +1ms
[0] error:   ┗ [1] { error: 'Error: Render frame was disposed before WebFrameMain could be accessed' }
[0] error:   ┏ [IPC]: failed to send IPC message "catalog:items" to view "remote=5"'s subframe "frameInfo.processId"=10 "frameInfo.frameId"=5 +1s
[0] error:   ┗ [1] { error: 'Error: Render frame was disposed before WebFrameMain could be accessed' }
[0] error:   ┏ [IPC]: failed to send IPC message "catalog:items" to view "window=1"'s subframe "frameInfo.processId"=10 "frameInfo.frameId"=5 +3ms
[0] error:   ┗ [1] { error: 'Error: Render frame was disposed before WebFrameMain could be accessed' }
[0] error:   ┏ [IPC]: failed to send IPC message "catalog:items" to view "remote=5"'s subframe "frameInfo.processId"=10 "frameInfo.frameId"=5 +1s
[0] error:   ┗ [1] { error: 'Error: Render frame was disposed before WebFrameMain could be accessed' }
[0] error:   ┏ [IPC]: failed to send IPC message "catalog:items" to view "window=1"'s subframe "frameInfo.processId"=10 "frameInfo.frameId"=5 +1ms
[0] error:   ┗ [1] { error: 'Error: Render frame was disposed before WebFrameMain could be accessed' }
[0] info:    ┏ [CLUSTER]: refresh +6s
[0] info:    ┃ [1] {
[0] info:    ┃ [2]   id: '87bac5783b9b6bb49d42137caf351757',
[0] info:    ┃ [3]   name: 'minikube',
[0] info:    ┃ [4]   ready: true,
[0] info:    ┃ [5]   online: true,
[0] info:    ┃ [6]   accessible: true,
[0] info:    ┃ [7]   disconnected: false
[0] info:    ┗ [8] }
[0] error:   ┏ [IPC]: failed to send IPC message "cluster:state" to view "remote=5"'s subframe "frameInfo.processId"=10 "frameInfo.frameId"=5 +78ms
[0] error:   ┗ [1] { error: 'Error: Render frame was disposed before WebFrameMain could be accessed' }
[0] error:   ┏ [IPC]: failed to send IPC message "cluster:state" to view "window=1"'s subframe "frameInfo.processId"=10 "frameInfo.frameId"=5 +1ms
[0] error:   ┗ [1] { error: 'Error: Render frame was disposed before WebFrameMain could be accessed' }
[0] error:   ┏ [IPC]: failed to send IPC message "catalog:items" to view "remote=5"'s subframe "frameInfo.processId"=10 "frameInfo.frameId"=5 +7ms
[0] error:   ┗ [1] { error: 'Error: Render frame was disposed before WebFrameMain could be accessed' }
[0] error:   ┏ [IPC]: failed to send IPC message "catalog:items" to view "window=1"'s subframe "frameInfo.processId"=10 "frameInfo.frameId"=5 +1ms
[0] error:   ┗ [1] { error: 'Error: Render frame was disposed before WebFrameMain could be accessed' }
[0] error:   ┏ [IPC]: failed to send IPC message "cluster:state" to view "remote=5"'s subframe "frameInfo.processId"=10 "frameInfo.frameId"=5 +14ms
[0] error:   ┗ [1] { error: 'Error: Render frame was disposed before WebFrameMain could be accessed' }
[0] error:   ┏ [IPC]: failed to send IPC message "cluster:state" to view "window=1"'s subframe "frameInfo.processId"=10 "frameInfo.frameId"=5 +1ms
[0] error:   ┗ [1] { error: 'Error: Render frame was disposed before WebFrameMain could be accessed' }
[0] error:   ┏ [IPC]: failed to send IPC message "cluster:state" to view "remote=5"'s subframe "frameInfo.processId"=10 "frameInfo.frameId"=5 +1ms
[0] error:   ┗ [1] { error: 'Error: Render frame was disposed before WebFrameMain could be accessed' }
[0] error:   ┏ [IPC]: failed to send IPC message "cluster:state" to view "window=1"'s subframe "frameInfo.processId"=10 "frameInfo.frameId"=5 +0ms
[0] error:   ┗ [1] { error: 'Error: Render frame was disposed before WebFrameMain could be accessed' }
[0] error:   ┏ [IPC]: failed to send IPC message "catalog:items" to view "remote=5"'s subframe "frameInfo.processId"=10 "frameInfo.frameId"=5 +1s
[0] error:   ┗ [1] { error: 'Error: Render frame was disposed before WebFrameMain could be accessed' }
[0] error:   ┏ [IPC]: failed to send IPC message "catalog:items" to view "window=1"'s subframe "frameInfo.processId"=10 "frameInfo.frameId"=5 +0ms
[0] error:   ┗ [1] { error: 'Error: Render frame was disposed before WebFrameMain could be accessed' }
[0] info:    ┏ [CLUSTER]: refresh +29s
[0] info:    ┃ [1] {
[0] info:    ┃ [2]   id: '87bac5783b9b6bb49d42137caf351757',
[0] info:    ┃ [3]   name: 'minikube',
[0] info:    ┃ [4]   ready: true,
[0] info:    ┃ [5]   online: true,
[0] info:    ┃ [6]   accessible: true,
[0] info:    ┃ [7]   disconnected: false
[0] info:    ┗ [8] }
```

**Comment by Nokel81** [comment]
Thanks for the stress test. I think I missed checking if the stores' API resource is cluster scoped. Therefore abort less often.

Also I think that I should hoist the cluster scope check higher up so that we don't abort and restart in this case.

File: src/common/k8s-api/kube-watch-api.ts [hunk 6]
```diff
@@ -151,9 +146,15 @@ export class KubeWatchApi {
     const cancelReloading = watchChanges
       ? reaction(
         // Note: must slice because reaction won't fire if it isn't there
-        () => this.context.contextNamespaces.slice(),
-        namespaces => {
-          console.log(`changing watch ${store.api.apiBase}`, namespaces);
+        () => [KubeWatchApi.context.contextNamespaces.slice(), KubeWatchApi.context.hasSelectedAll] as const,
+        ([namespaces, curSelectedAll], [, prevSelectedAll]) => {
+          if (curSelectedAll && prevSelectedAll) {
+            console.log(`[KUBE-WATCH-API]: Not changing watch for ${store.api.apiBase} because a new namespace was created but all namespaces are selected`);
```
Comment (jim-docker) [inline src/common/k8s-api/kube-watch-api.ts]: created or deleted, right?

File: src/renderer/cluster-frame.tsx [hunk 7]
```diff
@@ -120,9 +124,14 @@ export class ClusterFrame extends React.Component {
...
 
+    const clusterContext = new FrameContext(cluster);
+
     // Setup hosted cluster context
     KubeObjectStore.defaultContext.set(clusterContext);
-    kubeWatchApi.context = clusterContext;
+    WorkloadsOverview.clusterContext
+      = KubeObjectListLayout.clusterContext
+      = KubeWatchApi.context
+      = clusterContext;
```
Comment (jim-docker) [inline src/renderer/cluster-frame.tsx:134]: Why have clusterContext now stored in 3 places instead of one?

File: src/common/k8s-api/kube-watch-api.ts (hunk 6 above)
Comment (Nokel81) [reply src/common/k8s-api/kube-watch-api.ts]: Yes, will update (and change to `debug`)

File: src/renderer/cluster-frame.tsx (hunk 7 above)
Comment (Nokel81) [reply src/renderer/cluster-frame.tsx:134]: Because each they all individually need to know about the selected namespaces.

Comment (jim-docker) [reply src/renderer/cluster-frame.tsx:134]: But they could already do that via import, right?

Comment (Nokel81) [reply src/renderer/cluster-frame.tsx:134]: I guess so, I guess this is a form of dependency injection.

File: src/common/k8s-api/kube-watch-api.ts [hunk 8]
```diff
@@ -147,11 +147,11 @@ export class KubeWatchApi {
       ? reaction(
         // Note: must slice because reaction won't fire if it isn't there
         () => [KubeWatchApi.context.contextNamespaces.slice(), KubeWatchApi.context.hasSelectedAll] as const,
-        ([namespaces, curSelectedAll], [, prevSelectedAll]) => {
+        ([namespaces, curSelectedAll], [prevNamespaces, prevSelectedAll]) => {
           if (curSelectedAll && prevSelectedAll) {
-            console.log(`[KUBE-WATCH-API]: Not changing watch for ${store.api.apiBase} because a new namespace was created but all namespaces are selected`);
+            const action = namespaces.length > prevNamespaces.length ? "created" : "deleted";
```
Comment (jim-docker) [inline src/common/k8s-api/kube-watch-api.ts:152]: getting fancy. Is it possible that one namespace is created and another deleted at the same time (wrt this reaction)?

**Review by jim-docker — APPROVED** [review]
verified that the bug related to namespace create/delete is fixed, smooth UI now.

File: src/common/k8s-api/kube-watch-api.ts (hunk 8 above)
Comment (Nokel81) [reply src/common/k8s-api/kube-watch-api.ts:152]: Well the message will still be correct on that case 😅.

I don't think begin so fancy is worth it.
