### PR TITLE
Fix custom resources not having a fallback details component

### LINKED ISSUE #3541: Generic CRD details are empty
Regression from #2981

### PR DESCRIPTION
**Pull request by Nokel81**
Signed-off-by: Sebastian Malton <sebastian@malton.name>

fixes #3541

### CODE REVIEW

File: src/renderer/api/kube-object.ts [hunk 1]
```diff
@@ -86,6 +86,16 @@ export class KubeStatus {
...
 
+export interface KubeObjectStatus {
+  conditions: {
+    lastTransitionTime: string;
+    message: string;
+    reason: string;
+    status: string;
+    type?: string;
+  }[];
+}
```
Comment (Nokel81) [inline src/renderer/api/kube-object.ts]: This is the starting of a similar type to `KubeObjectMetadata`. In the future we should be able to use it everywhere because kube uses this type for object (even custom objects) it seems.

File: src/renderer/components/+custom-resources/crd-resource-details.tsx [hunk 2]
```diff
@@ -24,18 +24,18 @@ import "./crd-resource-details.scss";
...
-import { crdStore } from "./crd.store";
 import { KubeObjectMeta } from "../kube-object/kube-object-meta";
 import { Input } from "../input";
 import type { AdditionalPrinterColumnsV1, CustomResourceDefinition } from "../../api/endpoints/crd.api";
 import { parseJsonPath } from "../../utils/jsonPath";
+import type { KubeObject, KubeObjectMetadata, KubeObjectStatus } from "../../api/kube-object";
 
-interface Props extends KubeObjectDetailsProps<CustomResourceDefinition> {
+interface Props extends KubeObjectDetailsProps<KubeObject> {
+  crd: CustomResourceDefinition;
```
Comment (Nokel81) [inline src/renderer/components/+custom-resources/crd-resource-details.tsx:38]: I changed to passing in the crd (which should be the parent crd of `object`) because the single use of this component already needs to have it.

File: src/renderer/components/+custom-resources/crd-resource-details.tsx [hunk 3]
```diff
@@ -60,24 +60,15 @@ function convertSpecValue(value: any): any {
...
-    super(props);
-    makeObservable(this);
-  }
-
-  @computed get crd() {
-    return crdStore.getByObject(this.props.object);
-  }
-
-  renderAdditionalColumns(crd: CustomResourceDefinition, columns: AdditionalPrinterColumnsV1[]) {
+  renderAdditionalColumns(resource: KubeObject, columns: AdditionalPrinterColumnsV1[]) {
```
Comment (Nokel81) [inline src/renderer/components/+custom-resources/crd-resource-details.tsx:63]: This component was incorrect because it said it was dealing with `CustomResourceDefenition`'s as its main type. It is not, it is dealing with custom resources (which are from Lens' perspective, just `KubeObject`'s).

File: src/renderer/components/+custom-resources/crd-resource-details.tsx [hunk 4]
```diff
@@ -60,24 +60,15 @@ function convertSpecValue(value: any): any {
...
     return columns.map(({ name, jsonPath: jp }) => (
       <DrawerItem key={name} name={name} renderBoolean>
-        {convertSpecValue(jsonPath.value(crd, parseJsonPath(jp.slice(1))))}
+        {convertSpecValue(jsonPath.value(resource, parseJsonPath(jp.slice(1))))}
       </DrawerItem>
     ));
   }
 
-  renderStatus(crd: CustomResourceDefinition, columns: AdditionalPrinterColumnsV1[]) {
+  renderStatus(crd: KubeObject<KubeObjectMetadata, KubeObjectStatus, any>, columns: AdditionalPrinterColumnsV1[]) {
```
Comment (Nokel81) [inline src/renderer/components/+custom-resources/crd-resource-details.tsx]: Hopefully in the future, we won't need to specify `KubeObjectStatus` and we can just specify `KubeObject` but we are not there yet.

File: src/renderer/components/kube-object/kube-object-details.tsx [hunk 5]
```diff
@@ -169,6 +166,18 @@ export class KubeObjectDetails extends React.Component {
...
+    if (details.length === 0) {
+      const crd = crdStore.getByObject(object);
+
+      /**
+       * This is a fallback so that if a custom resource object doesn't have
+       * any defined details we should try and display at least some details
+       */
+      if (crd) {
+        details.push(<CrdResourceDetails key={object.getId()} object={object} crd={crd} />);
+      }
```
Comment (Nokel81) [inline src/renderer/components/kube-object/kube-object-details.tsx:179]: By fixing the typing on `CrdResourceDetails` (to not saying we want a `CustomResourceDefenition` as `object`, because we don't) it is no longer necessary to use a type cast.

File: src/renderer/components/kube-object/kube-object-details.tsx [hunk 6]
```diff
@@ -169,6 +166,18 @@ export class KubeObjectDetails extends React.Component {
...
       ));
 
+    if (details.length === 0) {
+      const crd = crdStore.getByObject(object);
+
+      /**
+       * This is a fallback so that if a custom resource object doesn't have
+       * any defined details we should try and display at least some details
+       */
+      if (crd) {
```
Comment (jakolehm) [inline src/renderer/components/kube-object/kube-object-details.tsx:177]: Why do we need to get & check `crd`? `object` already is the crd, right?

Comment (Nokel81) [reply src/renderer/components/kube-object/kube-object-details.tsx:177]: No object is a resource that is described by a CRD (I would call it a CR).

I guess we should fall back to just `KubeObjectDetails` if `crd` is false.

File: src/renderer/api/kube-object.ts (hunk 1 above)
Comment (jakolehm) [reply src/renderer/api/kube-object.ts]: Are we sure all kubernetes objects have these?

Comment (jakolehm) [reply src/renderer/api/kube-object.ts]: ~~Also I think this interface does not match actual implementation, conditions seems to be an array of objects.~~

File: src/renderer/api/kube-object.ts [hunk 7]
```diff
@@ -86,6 +86,16 @@ export class KubeStatus {
   }
 }
 
+export interface KubeObjectStatus {
+  conditions: {
```
Comment (jakolehm) [inline src/renderer/api/kube-object.ts]:
```suggestion
  conditions?: {
```

File: src/renderer/api/kube-object.ts (hunk 1 above)
Comment (Nokel81) [reply src/renderer/api/kube-object.ts]: So I am not sure if all kube controllers do use this (or something like this...)

After reading:
 - https://github.com/kubernetes/kubernetes/issues/50798
 - https://github.com/kubernetes/kubernetes/issues/7856
 - https://github.com/kubernetes/community/pull/4521

and https://maelvls.dev/kubernetes-conditions/

It seems clear that not everything does use this type (or at least MUST use something like this). But that it is still the recommended way of displaying the history of data.

**Review by jakolehm — APPROVED** [review]
LGTM
