### PR TITLE
Fix jobs sorting if condition is empty

### LINKED ISSUE #224: app crashes when sorting jobs by "Conditions"
**Describe the bug**
I open Jobs tab and filter jobs by "Conditions column" and i got the following error

image

- Lens 3.1.0 on Fedora installed via snap
- K8s 1.11

### PR DESCRIPTION
**Pull request by nevalla**
Fixes #224

### CODE REVIEW

File: dashboard/client/components/+workloads-jobs/jobs.tsx [hunk 1]
```diff
@@ -35,7 +35,7 @@ export class Jobs extends React.Component<Props> {
         sortingCallbacks={{
           [sortBy.name]: (job: Job) => job.getName(),
           [sortBy.namespace]: (job: Job) => job.getNs(),
-          [sortBy.conditions]: (job: Job) => job.getCondition().type,
+          [sortBy.conditions]: (job: Job) => job.getCondition() != null ? job.getCondition().type : "",
```
Comment (jakolehm) [inline dashboard/client/components/+workloads-jobs/jobs.tsx:38]: Shorter version:

```suggestion
          [sortBy.conditions]: (job: Job) => job.getCondition()?.type,
```

**Review by jakolehm — APPROVED** [review]
LGTM
