### PR TITLE
Fix resolveSystemProxyFromElectron causing a crash on quit

### LINKED ISSUE #7378: Crash on quit
**Describe the bug**
App crashes on quit. It might be a regression from #7375.

**To Reproduce**
1. Start application
2. Quit application

**Expected behavior**
No crash on quit.

**Environment (please complete the following information):**
- Lens Version: `master`
- OS: MacOS
- Installation method (e.g. snap or AppImage in Linux): dev & manual build

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Electron [1148]
Path:                  /Users/USER/*/Electron.app/Contents/MacOS/Electron
Identifier:            com.github.Electron
Version:               19.1.9 (19.1.9)
Code Type:             ARM-64 (Native)
Parent Process:        Exited process [1147]
Responsible:           Terminal [3033]
User ID:               501

Date/Time:             2023-03-20 07:43:50.2087 +0200
OS Version:            macOS 12.6.3 (21G419)
Report Version:        12
Anonymous UUID:        6271649C-8F00-7C4B-D3FF-EB6F388B0D1A

Sleep/Wake UUID:       CEE4059F-3993-43E7-9416-99F3F0403682

Time Awake Since Boot: 590000 seconds
Time Since Wake:       1868 seconds

System Integrity Protection: enabled

Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called


Thread 0 Crashed:: CrBrowserMain Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x1ac7a6d98 __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x1ac7dbee0 pthread_kill + 288
2   libsystem_c.dylib             	       0x1ac716340 abort + 168
3   Electron Framework            	       0x108a25938 uv_mutex_lock + 28
4   Electron Framework            	       0x10e5e31d4 napi_release_threadsafe_function + 40
5   fsevents.node                 	       0x10108cbcc fse_instance_destroy + 120
6   Electron Framework            	       0x10e5e35b0 node_api_get_module_file_name + 740
7   Electron Framework            	       0x10e5d8ce0 node::Stop(node::Environment*) + 1016
8   Electron Framework            	       0x10e5e33f8 node_api_get_module_file_name + 300

```

### PR DESCRIPTION
**Pull request by jakolehm**
Fixes #7378

### CODE REVIEW

File: packages/core/src/main/utils/resolve-system-proxy/resolve-system-proxy-window.injectable.ts [hunk 1]
```diff
@@ -3,17 +3,14 @@
  * Licensed under MIT License. See LICENSE in root directory for more information.
  */
 import { getInjectable } from "@ogre-tools/injectable";
-import type { BrowserWindowConstructorOptions } from "electron";
 import { BrowserWindow } from "electron";
 
-const electronBrowserWindowInjectable = getInjectable({
-  id: "electron-browser-window",
+const resolveSystemProxyWindowInjectable = getInjectable({
```
Comment (jakolehm) [inline packages/core/src/main/utils/resolve-system-proxy/resolve-system-proxy-window.injectable.ts:8]: Changed because we really need a very specific instance (this is not a generic electron BrowserWindow).

File: packages/core/src/main/utils/resolve-system-proxy/resolve-system-proxy-window.injectable.ts [hunk 2]
```diff
@@ -3,17 +3,14 @@
...
+  id: "resolve-system-proxy-window",
   instantiate: () => {
-    return (opts: BrowserWindowConstructorOptions) => {
-      return new BrowserWindow(opts);
-    };
+    return new BrowserWindow({ show: false, paintWhenInitiallyHidden: false });
```
Comment (jakolehm) [inline packages/core/src/main/utils/resolve-system-proxy/resolve-system-proxy-window.injectable.ts:11]: `paintWhenInitiallyHidden: false` is the actual fix.

**Review by Nokel81 — APPROVED** [review]
