### PR TITLE
Fixing Dialog Escape keypress behavior

### LINKED ISSUE #757: Esc closes too many windows at once
**Describe the bug**
Esc key seems to be always returning Lens UI to the "list of stuff" state, even if I have opened sidebar with details for some object and then some modal window on top of it.

**To Reproduce**
1. Open a list of pods
2. Click on one of the pods in the list, opening the sidebar with pod details
3. Click on the "Logs" button to open dialog with pod logs
4. Press Esc

**Expected behaviour**
I expect pod logs dialog to be closed and sidebar with pod details to remain in place.

**Actual behaviour**
Both logs dialog and sidebar are closed.

**Environment (please complete the following information):**
- Lens Version: 3.5.0
- OS: macOS

### PR DESCRIPTION
**Pull request by aleksfront**
Allowing to close Dialog only (not along with opened Drawer) after hitting Esc key. Made by changed `keypress` target - `document.body` is located 'lower' in event bubbling stairs so it will fire event earlier than Drawer.

esc closes dialog

Fixes #757 

Signed-off-by: Alex Andreev <alex.andreev.email@gmail.com>

### CODE REVIEW

**Review by Nokel81 — APPROVED** [review]

File: src/renderer/components/dialog/dialog.tsx [hunk 1]
```diff
@@ -92,15 +92,15 @@ export class Dialog extends React.PureComponent<DialogProps, DialogState> {
     this.props.onOpen();
     if (!this.props.pinned) {
       if (this.elem) this.elem.addEventListener('click', this.onClickOutside);
-      window.addEventListener('keydown', this.onEscapeKey);
+      document.body.addEventListener('keydown', this.onEscapeKey);
```
Comment (ixrock) [inline src/renderer/components/dialog/dialog.tsx:96]: Please add comment (to the code) why `document.body` is used and how it's related to `Drawer`'s event(s).

**Review by ixrock — APPROVED** [review]
