### PR TITLE
Fix: charts stripes alignment

### LINKED ISSUE #2008: Chart stripes are misaligned from bars
For some reason, "zebra stripes" are not aligned strictly on bar corners. They should cover some amount of bars positioned strictly on their edges.

image

image

### PR DESCRIPTION
**Pull request by aleksfront**
* Updating chart stripes width and position on every dataset update
* Hide stripes if less than 10 minutes presented (one stripe covers 10 min period normally)

fixed stripes
fixed stripes 15 minutes

Fixes #2008 

Signed-off-by: Alex Andreev <alex.andreev.email@gmail.com>

### CODE REVIEW

File: src/renderer/components/chart/bar-chart.tsx [hunk 1]
```diff
@@ -136,7 +136,8 @@ export class BarChart extends React.Component<Props> {
       },
       plugins: {
         ZebraStripes: {
-          stripeColor: chartStripesColor
+          stripeColor: chartStripesColor,
+          interval: chartData.datasets.length ? chartData.datasets[0].data.length : 61
```
Comment (Nokel81) [inline src/renderer/components/chart/bar-chart.tsx]: I see that `61` is used in other places too. However it seems like a strange number. Maybe add a comment about why it was chosen?

Comment (aleksfront) [reply src/renderer/components/chart/bar-chart.tsx]: Yes, you're right. Actually, we don't need any predefined numbers in here since `datasets[0].data.length` always contains needed value. Fixed.

**Review by jakolehm — APPROVED** [review]

**Review by Nachasic — APPROVED** [review]
Aside from the issue with magic number "61" pointed out above, LGTM
