### PR TITLE
Fix terminal fit errors

### LINKED ISSUE #5637: Terminal is broken in latest master
terminal errors

https://user-images.githubusercontent.com/9607060/173784007-b63c1a88-bd1b-4aaa-8320-d464c629b7fb.mov

### PR DESCRIPTION
**Pull request by Nokel81**
Signed-off-by: Sebastian Malton <sebastian@malton.name>

fixes https://github.com/lensapp/lens/issues/5637

### CODE REVIEW

File: src/common/utils/disposer.ts [hunk 1]
```diff
@@ -3,23 +3,35 @@
  * Licensed under MIT License. See LICENSE in root directory for more information.
  */
 
-export type Disposer = () => void;
 
-interface Extendable<T> {
-  push(...vals: T[]): void;
+
```
Comment (jim-docker) [inline src/common/utils/disposer.ts:7]: Are changes in this file part of the fix?

**Review by jim-docker — APPROVED** [review]

**Review by jansav — CHANGES_REQUESTED** [review]
I don't think that the disposer changes are relevant here, so let's get those out. Otherwise looks good.

File: src/common/utils/disposer.ts (hunk 1 above)
Comment (Nokel81) [reply src/common/utils/disposer.ts:7]: Yes, because the `this.xterm.onResize` returns a `Disposable`

**Review by jansav — APPROVED** [review]
