### PR TITLE
Convert the cluster settings view to React

### LINKED ISSUE #494: Can't upload cluster icons with special characters in filename
**Describe the bug**
When trying to upload cluster icon containing for example japanese letters, the icon file is not generated correctly and user see corrupted image as cluster icon.

**Expected behavior**
Cluster icon should be uploaded correctly and user can see it properly.

### PR DESCRIPTION
**Pull request by Nokel81**
- Add a basic file picker component

### CODE REVIEW

**Comment by Nokel81** [comment]
I have put up this PR now since a vast majority of the work is done. There are a few more bugs to iron out and I will start working on them now.

File: src/common/cluster-ipc.ts [hunk 1]
```diff
@@ -17,4 +17,37 @@ export const clusterIpc = {
...
+  installFeature: createIpcChannel({
+    channel: "cluster:install-feature",
+    handle: async (clusterId: ClusterId, feature: string, config?: any) => {
+      tracker.event("cluster", "install", feature);
+      const cluster = clusterStore.getById(clusterId);
+
+      if (cluster) {
+        const success = await cluster.installFeature(feature, config);
+        if (!success) {
+          throw "Installation failed";
```
Comment (ixrock) [inline src/common/cluster-ipc.ts]: Maybe `installFeature()` should throw error in case of fail? Otherwise it's not clear why "installation failed"

File: src/common/cluster-store.ts [hunk 2]
```diff
@@ -93,8 +94,8 @@ export class ClusterStore extends BaseStore<ClusterStoreModel> {
     return this.clustersList.some(cluster => cluster.contextName === name);
   }
 
-  getById(id: ClusterId): Cluster {
-    return this.clusters.get(id);
+  getById(id: ClusterId): Cluster | null {
+    return this.clusters.get(id) || null;
```
Comment (ixrock) [inline src/common/cluster-store.ts]: Why do you need exactly `null` if cluster not found? It will return `undefined` without `|| null`

File: src/renderer/components/+cluster-settings/cluster-settings.scss [hunk 3]
```diff
@@ -1,3 +1,79 @@
 .ClusterSettings {
-  
+    overflow-y: scroll;
+    width: -webkit-fill-available;
+    padding: 1cm 20%;
```
Comment (ixrock) [inline src/renderer/components/+cluster-settings/cluster-settings.scss]: Weird values for `padding` (both). 
Btw have a look at `wizard-layout.tsx`. It's used already in `add-cluster`, `workspaces` and `preferences` and maybe you can apply it for `cluster-settings` as well.

File: src/renderer/components/+cluster-settings/cluster-settings.scss [hunk 4]
```diff
@@ -1,3 +1,79 @@
 .ClusterSettings {
-  
+    overflow-y: scroll;
+    width: -webkit-fill-available;
```
Comment (ixrock) [inline src/renderer/components/+cluster-settings/cluster-settings.scss]: Let's not use such chrome-specific values, especially when it's not necessary.. 
You can get what you want with `display: grid` or `display: flex`

File: src/renderer/components/+cluster-settings/cluster-settings.scss [hunk 5]
```diff
@@ -1,3 +1,79 @@
...
+    padding: 1cm 20%;
+
+    .ClusterSettingsGrouping {
+        margin-top: 40px;
+    }
+
+    .ClusterSettingsGrouping:first-child {
+        margin-top: 0px;
+    }
```
Comment (ixrock) [inline src/renderer/components/+cluster-settings/cluster-settings.scss]:
```
  .ClusterSettingsGrouping {
    margin-top: 40px;
    
    &:first-child {
      margin-top: 0px;
    }
  }
```

File: src/renderer/components/+cluster-settings/cluster-settings.tsx [hunk 6]
```diff
@@ -1,14 +1,22 @@
...
-      </div>
-    );
+    const cluster = getHostedCluster();
+    
+    return <div className="ClusterSettings">
+      <Status cluster={cluster}></Status>
+      <General cluster={cluster}></General>
+      <Features cluster={cluster}></Features>
+      <Removal cluster={cluster}></Removal>
+    </div>;
```
Comment (ixrock) [inline src/renderer/components/+cluster-settings/cluster-settings.tsx]: Let's wrap return value in `()` and put div to next line for better readability.

File: src/renderer/components/+cluster-settings/components/cluster-home-dir-setting.tsx [hunk 7]
```diff
@@ -0,0 +1,108 @@
...
+        onSubmit={this.updateClusterInitialWorkingDirectory}
+        onChange={this.changeWorkingDirectoryState}
+        iconRight={this.getIconRight()}
+        placeholder="$HOME"
+      />
+    </>;
+  }
+
+  @autobind()
+  changeWorkingDirectoryState(directory: string, _e: React.ChangeEvent) {
```
Comment (ixrock) [inline src/renderer/components/+cluster-settings/components/cluster-home-dir-setting.tsx]: If it's callback/handler let's start naming with `on`, so should be `onChangeWorkingDirectory` ("state" is probably redundant here)

File: src/renderer/components/+cluster-settings/components/cluster-home-dir-setting.tsx [hunk 8]
```diff
@@ -0,0 +1,108 @@
...
+    if (this.dirDiffers(directory) !== ValueStatus.DIRTY) {
+      return;
+    }
+
+    this.setState({ status: ValueStatus.UPDATING });
+    const newCluster = this.props.cluster;
+    newCluster.preferences.terminalCWD = directory;
+    
+    try {
+      const cs = ClusterStore.getInstance<ClusterStore>();
```
Comment (ixrock) [inline src/renderer/components/+cluster-settings/components/cluster-home-dir-setting.tsx]: Import `clusterStore` directly instead as it's done in all other places.
+ avoid variable names like `cs` (code readability first!)

File: src/renderer/components/+cluster-settings/components/cluster-icon-setting.tsx [hunk 9]
```diff
@@ -0,0 +1,82 @@
+import React from "react";
+import { Cluster } from "../../../../main/cluster";
+import { ClusterStore, clusterStore } from "../../../../common/cluster-store"
+import { Icon } from "../../icon";
+import { FilePicker } from "../../../components/file";
```
Comment (ixrock) [inline src/renderer/components/+cluster-settings/components/cluster-icon-setting.tsx]: Inconsistent filename and imported class-name.

File: src/renderer/components/+cluster-settings/components/cluster-icon-setting.tsx [hunk 10]
```diff
@@ -0,0 +1,82 @@
...
+    const { cluster } = this.props;
+    
+    try {
+      cluster.preferences.icon = "";
+      if (file) {
+        console.log(`using ${file.name}`);
+
+      }
+      const buf = Buffer.from(await file.arrayBuffer());
+      cluster.preferences.icon = `data:image/jpeg;base64, ${buf.toString('base64')}`;
```
Comment (ixrock) [inline src/renderer/components/+cluster-settings/components/cluster-icon-setting.tsx]: I thought we're saving icon to external folder which defined in static path `ClusterStore.iconsDir`?

File: src/renderer/components/+cluster-settings/components/cluster-name-setting.tsx [hunk 11]
```diff
@@ -0,0 +1,104 @@
...
+  render() {
+    return <>
+      <h4>Cluster Name</h4>
+      <p>Change cluster name:</p>
+      <Input
+        theme="round-black"
+        className="box grow"
+        value={this.state.name}
+        onSubmit={this.updateClusterName.bind(this)}
+        onChange={this.changeNameState.bind(this)}
```
Comment (ixrock) [inline src/renderer/components/+cluster-settings/components/cluster-name-setting.tsx]: Let's not use `.bind(this)` since it loose type-safety.
Please use `@autobind` decorator or arrow-function to define callback.

File: src/renderer/components/+cluster-settings/components/cluster-name-setting.tsx [hunk 12]
```diff
@@ -0,0 +1,104 @@
...
+      return;
+    }
+
+    this.setState({ status: ValueStatus.UPDATING });
+    const newCluster = this.props.cluster;
+    newCluster.preferences.clusterName = name;
+    
+    try {
+      const cs = ClusterStore.getInstance<ClusterStore>();
+      await cs.addCluster(newCluster)
```
Comment (ixrock) [inline src/renderer/components/+cluster-settings/components/cluster-name-setting.tsx]: Same thing as above, `cs`, `clusterStore`

File: src/renderer/components/+cluster-settings/components/cluster-prometheus-setting.tsx [hunk 13]
```diff
@@ -0,0 +1,42 @@
...
+        value={prom}
+        options={options}
+        onChange={this.changePrometheusProvider}
+      />
+    </>;
+  }
+
+  @autobind()
+  async changePrometheusProvider({ value }: SelectProps<string>) {
+    const cs: ClusterStore = ClusterStore.getInstance();
```
Comment (ixrock) [inline src/renderer/components/+cluster-settings/components/cluster-prometheus-setting.tsx]: import `clusterStore`

File: src/renderer/components/+cluster-settings/components/cluster-prometheus-setting.tsx [hunk 14]
```diff
@@ -0,0 +1,42 @@
...
+
+    const newCluster = this.props.cluster;
+    newCluster.preferences.prometheusProvider = { type: value || null };
+    await cs.addCluster(newCluster);
+    console.log(`change to: ${options.find((op) => op.value === value).label}`);
```
Comment (ixrock) [inline src/renderer/components/+cluster-settings/components/cluster-prometheus-setting.tsx]: Don't forget to remove all `console.log`s

File: src/renderer/components/+cluster-settings/components/cluster-proxy-setting.tsx [hunk 15]
```diff
@@ -0,0 +1,120 @@
...
+import { Tooltip, TooltipContent } from "../../tooltip";
+import { autobind } from "../../../utils";
+
+enum ValueStatus {
+  CLEAN = "clean",
+  DIRTY = "dirty",
+  UPDATING = "updating",
+  ERROR = "error",
+  UPDATED = "updated",
+}
```
Comment (ixrock) [inline src/renderer/components/+cluster-settings/components/cluster-proxy-setting.tsx]: Why it's repeated over and over again in other files?
Maybe it's better to handler directly in `input.tsx`?

File: src/renderer/components/+cluster-settings/components/cluster-workspace-setting.tsx [hunk 16]
```diff
@@ -0,0 +1,113 @@
...
+import { Select } from "../../../components/select";
+import { Tooltip, TooltipContent } from "../../tooltip";
+
+enum ValueStatus {
+  CLEAN = "clean",
+  DIRTY = "dirty",
+  UPDATING = "updating",
+  ERROR = "error",
+  UPDATED = "updated",
+}
```
Comment (ixrock) [inline src/renderer/components/+cluster-settings/components/cluster-workspace-setting.tsx]: DRY

File: src/renderer/components/+cluster-settings/components/install-metrics.tsx [hunk 17]
```diff
@@ -0,0 +1,144 @@
...
+
+  getDisabledToolTip(id: string, action: string): React.ReactNode {
+    const { cluster } = this.props;
+    if (cluster.isAdmin) {
+      return null;
+    }
+
+    return <Tooltip htmlFor={id} position={{ top: true }}>
+      <TooltipContent warning nowrap>{action} only allowed by admins</TooltipContent>
+    </Tooltip>;
```
Comment (ixrock) [inline src/renderer/components/+cluster-settings/components/install-metrics.tsx]: Wrap return value in `()`

File: src/renderer/components/+cluster-settings/settings-group-features.tsx [hunk 18]
```diff
@@ -0,0 +1,20 @@
+import React from "react";
+import { Cluster } from "../../../main/cluster";
+import { InstallMetrics } from "./components/install-metrics";
+import { InstallUserMode } from "./components/install-user-mode";
+
+interface Props {
+  cluster: Cluster;
+}
+
+export class Features extends React.Component<Props> {
```
Comment (ixrock) [inline src/renderer/components/+cluster-settings/settings-group-features.tsx]: Inconsistent classname and filename (suggest to rename file to `features.tsx`)

File: src/renderer/components/+cluster-settings/settings-group-general.tsx [hunk 19]
```diff
@@ -0,0 +1,28 @@
...
+import { ClusterIconSetting } from "./components/cluster-icon-setting";
+import { ClusterProxySetting } from "./components/cluster-proxy-setting";
+import { ClusterPrometheusSetting } from "./components/cluster-prometheus-setting";
+import { ClusterHomeDirSetting } from "./components/cluster-home-dir-setting";
+
+interface Props {
+  cluster: Cluster;
+}
+
+export class General extends React.Component<Props> {
```
Comment (ixrock) [inline src/renderer/components/+cluster-settings/settings-group-general.tsx]: If this is root component then names should be `ClusterSettings` and `cluster-settings.tsx`

File: src/renderer/components/+cluster-settings/settings-group-removal.tsx [hunk 20]
```diff
@@ -0,0 +1,75 @@
...
+interface Props {
+    cluster: Cluster;
+}
+
+interface State {
+  status: RemovalStatus;
+  errorText?: string;
+}
+
+export class Removal extends React.Component<Props, State> {
```
Comment (ixrock) [inline src/renderer/components/+cluster-settings/settings-group-removal.tsx]: Maybe `ClusterRemoveButton` + update filename.

File: src/renderer/components/+cluster-settings/settings-group-status.tsx [hunk 21]
```diff
@@ -0,0 +1,55 @@
...
+    
+    const rows = [
+      <h5 key="online-header">Online Status</h5>,
+      <span key="online-value">{cluster.online ? "online" : `offline (${cluster.failureReason || "unknown reason"})`}</span>,
+      <h5 key="distribution-header">Distribution</h5>,
+      <span key="distribution-value">{cluster.distribution}</span>,
+      <h5 key="version-header">Kernel Version</h5>,
+      <span key="version-value">{cluster.version}</span>,
+      <h5 key="api-header">API Address</h5>,
+      <span key="api-value">{cluster.apiUrl}</span>,
```
Comment (ixrock) [inline src/renderer/components/+cluster-settings/settings-group-status.tsx]: If you want to iterate over values it's better to split data and layout, so:

```
const rows: [string, React.ReactNode][] = [
 ["Online Status", cluster.online ? "online" : `offline (${cluster.failureReason || "unknown reason"})`],
]
```

File: src/renderer/components/+cluster-settings/settings-group-status.tsx [hunk 22]
```diff
@@ -0,0 +1,55 @@
...
+
+    return <div className="ClusterSettingsGrouping">
+      <h2>Status</h2>
+      <hr/>
+      <h4>Cluster status</h4>
+      <p>
+        Cluster status information including: detected distribution, kernel version, and online status.
+      </p>
+      {
+        cluster.initialized
```
Comment (ixrock) [inline src/renderer/components/+cluster-settings/settings-group-status.tsx]: Most probably you will never see `cluster.initialized == false` at this stage, so the spinner will never show.

File: src/renderer/components/cluster-manager/cluster-status.tsx [hunk 23]
```diff
@@ -11,6 +11,11 @@ import { Icon } from "../icon";
 import { Button } from "../button";
 import { cssNames } from "../../utils";
 
+interface State {
+  loadingDots: string;
+  cancel?: NodeJS.Timeout;
+}
+
```
Comment (ixrock) [inline src/renderer/components/cluster-manager/cluster-status.tsx]: Forgot to remove?

File: src/renderer/components/input/input.tsx [hunk 24]
```diff
@@ -13,7 +13,7 @@ type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>
 type InputElement = HTMLInputElement | HTMLTextAreaElement;
 type InputElementProps = InputHTMLAttributes<InputElement> & TextareaHTMLAttributes<InputElement> & DOMAttributes<InputElement>;
 
-export type InputProps<T = string> = Omit<InputElementProps, "onChange"> & {
+export type InputProps<T = string> = Omit<Omit<InputElementProps, "onChange">, "onSubmit"> & {
```
Comment (ixrock) [inline src/renderer/components/input/input.tsx]: Maybe `Omit<InputElementProps, "onChange" | "onSubmit">`?

File: src/renderer/components/file/file.tsx [hunk 25]
```diff
@@ -0,0 +1,188 @@
...
+
+export interface State {
+    errorText?: string;
+    status: "CLEAR" | "PROCESSING" | "ERROR";
+}
+
+export type Props = BaseProps & (MemoryUseProps | FileUploadProps) ;
+
+export class FilePicker extends React.Component<Props, State> {
+  static defaultProps = {
```
Comment (ixrock) [inline src/renderer/components/file/file.tsx]: No types?

File: src/renderer/components/file/file.tsx [hunk 26]
```diff
@@ -0,0 +1,188 @@
...
+    onOverLimit: "Reject",
+    onOverTotalSizeLimit: "Reject",
+  }
+
+  constructor(props: Props) {
+    super(props);
+    this.state = {
+      status: "CLEAR",
+    };
+  }
```
Comment (ixrock) [inline src/renderer/components/file/file.tsx]: Do you know that you can define `state` directly on class without using constructor?
Anyway highly recommend to stop using vanilla `setState` and switch to `mobx`

File: src/renderer/components/file/file.scss [hunk 27]
```diff
@@ -0,0 +1,14 @@
+.FilePicker {
```
Comment (ixrock) [inline src/renderer/components/file/file.scss]: filename should be `file-picker.scss`

File: src/renderer/components/file/file.tsx [hunk 28]
```diff
@@ -0,0 +1,188 @@
+import "./file.scss"
```
Comment (ixrock) [inline src/renderer/components/file/file.tsx]: filenames

File: src/renderer/components/file/file.tsx [hunk 29]
```diff
@@ -0,0 +1,188 @@
...
+
+  async handlePickFiles(selectedFiles: FileList) {
+    const files: File[] = Array.from(selectedFiles);
+
+    try {
+      const numberLimitedFiles = this.handleFileCount(files);
+      const sizeLimitedFiles = this.handleIndiviualFileSizes(numberLimitedFiles);
+      const totalSizeLimitedFiles = this.handleTotalFileSizes(sizeLimitedFiles);
+      
+      if ("uploadDir" in this.props) {
```
Comment (ixrock) [inline src/renderer/components/file/file.tsx]: Why not `if(this.props.uploadDir)`?

File: src/renderer/components/file/file.tsx [hunk 30]
```diff
@@ -0,0 +1,188 @@
...
+      } else {
+        this.props.handler(totalSizeLimitedFiles);
+      }
+    } catch (errorText) {
+      this.setState({ errorText, status: "ERROR" });
+      return;
+    }
+  }
+
+  render(): React.ReactElement {
```
Comment (ixrock) [inline src/renderer/components/file/file.tsx]: Redundant return type definition.

**Review by ixrock — CHANGES_REQUESTED** [review]

File: src/renderer/components/+cluster-settings/components/cluster-icon-setting.tsx (hunk 10 above)
Comment (Nokel81) [reply src/renderer/components/+cluster-settings/components/cluster-icon-setting.tsx]: I tried that, but it doesn't work on development due to security concerns. I found that this works even better since we don't have to do file cleanup and we don't have to disable webSecurity during development.

File: src/renderer/components/+cluster-settings/settings-group-status.tsx (hunk 22 above)
Comment (Nokel81) [reply src/renderer/components/+cluster-settings/settings-group-status.tsx]: Fair, when I first starting this work I was seeing `cluster.initialized` every time I did a `⌘+R` (reload). Will remove.

File: src/renderer/components/input/input.tsx (hunk 24 above)
Comment (Nokel81) [reply src/renderer/components/input/input.tsx]: Ah TIL

File: src/renderer/components/file/file.tsx (hunk 29 above)
Comment (Nokel81) [reply src/renderer/components/file/file.tsx]: But you get the error `"uploadDir" does not exist on (Readonly<BaseProps & FileUploadProps> & Readonly<{ children?: ReactNode; }>) | (Readonly<BaseProps & MemoryUseProps> & Readonly<...>)`

File: src/renderer/components/file/file.tsx (hunk 30 above)
Comment (Nokel81) [reply src/renderer/components/file/file.tsx]: Do you mean that render always returns `React.ReactNode`? I think that explicit typing in as many places as possible is better overall since it is very up front with what we think the contract is and so that the implicit type doesn't get changed under our feet.

Comment (ixrock) [reply src/renderer/components/file/file.tsx]: I mean only for `render()` method in  react-components, otherwise explicit types is good.

File: src/renderer/components/file/file.tsx (hunk 29 above)
Comment (ixrock) [reply src/renderer/components/file/file.tsx]: Well, question is why it's not exists there? you define shape of the props for this component?
Anyway accessing props like this discouraged..

Comment (Nokel81) [reply src/renderer/components/file/file.tsx]: Why is it discouraged?

File: src/renderer/components/file/file.tsx (hunk 30 above)
Comment (Nokel81) [reply src/renderer/components/file/file.tsx]: okay

File: src/renderer/components/file-picker/file-picker.tsx [hunk 31]
```diff
@@ -76,12 +72,11 @@ const defaultProps: Partial<Props> = {
   onOverTotalSizeLimit: OverTotalSizeLimitStyle.REJECT,
 };
 
-export class FilePicker extends React.Component<Props, State> {
+export class FilePicker extends React.Component<Props> {
```
Comment (ixrock) [inline src/renderer/components/file-picker/file-picker.tsx:78]: Forgot `@observer`?

File: src/renderer/components/+cluster-settings/components/install-user-mode.tsx [hunk 32]
```diff
@@ -101,48 +85,51 @@ export class InstallUserMode extends React.Component<Props, State> {
...
-      }
+  @autobind()
+  async uninstallMetrics() {
+    const { cluster } = this.props;
+    console.log(`uninstalling metrics from ${cluster.preferences.clusterName}`);
+
+    try {
+      this.status = ActionStatus.PROCESSING
+      const res = await clusterIpc.uninstallFeature.invokeFromRenderer(cluster.id, UserModeFeature.id);
+      console.log("installer response:", res);
```
Comment (ixrock) [inline src/renderer/components/+cluster-settings/components/install-user-mode.tsx]: Console.log's are planning to stay here?

Comment (Nokel81) [reply src/renderer/components/+cluster-settings/components/install-user-mode.tsx]: No, but I am currently getting errors from these two buttons which I am trying to track down

**Comment by Nokel81** [comment]
So the only part of the PR that I don't think is finished is the refreshing of the features on the cluster. For some reason `refresh` or for that matter `getFeatures` fails because `kubeconfigManager` is not set

**Comment by Nokel81** [comment]
Because it is a better mental model for what was trying to be expressed which is an ordered list of items where each position is only present once. `Set`'s iteration is defined to be insert order (of the first insert).

File: src/renderer/components/file/file.tsx (hunk 29 above)
Comment (ixrock) [reply src/renderer/components/file/file.tsx]: > The `in` operator returns true if the specified property is in the specified object or its prototype chain.

because you might know/define exact shape of `props` and you don't need to "guess"

Comment (Nokel81) [reply src/renderer/components/file/file.tsx]: I guess then I should use `this.props.hasOwnProperty("uploadDir")`. The reason that it is not always defined is deliberate. The type of `handler` is dependent on whether `uploadDir` is present. Namely see `FileUploadProps` vs `MemoryUseProps`.

File: src/main/kube-auth-proxy.ts [hunk 33]
```diff
@@ -82,6 +88,7 @@ export class KubeAuthProxy {
 
   protected async sendIpcLogMessage(res: KubeAuthProxyLog) {
     const channel = `kube-auth:${this.cluster.id}`
+    console.trace();
```
Comment (ixrock) [inline src/main/kube-auth-proxy.ts]: Forgot to remove?

File: src/renderer/components/+cluster-settings/removal.tsx [hunk 34]
```diff
@@ -0,0 +1,18 @@
...
+
+interface Props {
+    cluster: Cluster;
+}
+
+export class Removal extends React.Component<Props> {
+  render() {
+    const { cluster } = this.props;
+
+    return <div className="ClusterSettingsGrouping">
```
Comment (ixrock) [inline src/renderer/components/+cluster-settings/removal.tsx]: Inconsistent css-name and component-class/filename

File: src/renderer/components/+cluster-settings/status.tsx [hunk 35]
```diff
@@ -0,0 +1,51 @@
...
+      ["API Address", cluster.apiUrl],
+    ];
+
+    if (cluster.nodes > 0) {
+      rows.push(["Nodes Count", cluster.nodes]);
+    }
+
+    return rows
+      .map(([header, value]) => [
+        <h5 key={headerToKey(header, "header")}>{header}</h5>,
```
Comment (ixrock) [inline src/renderer/components/+cluster-settings/status.tsx]: Using `headerToKey` looks redundant, value of `key` might be any uniq `string | number`.
Therefore `key={header + "some-fish"}` or even `key={index}` should be enough for this case.

File: src/renderer/components/tooltip/tooltip.tsx [hunk 36]
```diff
@@ -108,8 +104,9 @@ export class Tooltip extends React.Component<TooltipProps> {
       }
     }
     if (!this.activePosition) {
-      const { left, top } = this.getPosition(allPositions[0], selfBounds, targetBounds)
-      this.activePosition = allPositions[0];
+      const preferedPosition = positionPreference.values().next().value
```
Comment (ixrock) [inline src/renderer/components/tooltip/tooltip.tsx]: Maybe better `Array.from(positionPreference)[0]`?

File: src/renderer/components/+cluster-settings/components/cluster-icon-setting.tsx [hunk 37]
```diff
@@ -0,0 +1,74 @@
...
+      if (file) {
+        const buf = Buffer.from(await file.arrayBuffer());
+        cluster.preferences.icon = `data:image/jpeg;base64, ${buf.toString('base64')}`;
+      } else {
+        // this has to be done as a seperate branch (and not always) because `cluster`
+        // is observable and triggers an update loop.
+        cluster.preferences.icon = undefined;
+      }
+
+      await clusterStore.addCluster(cluster);
```
Comment (ixrock) [inline src/renderer/components/+cluster-settings/components/cluster-icon-setting.tsx]: Why this is here? You should only update `cluster.preferences.icon` to "hosted-cluster"

File: src/renderer/components/+cluster-settings/components/cluster-workspace-setting.tsx [hunk 38]
```diff
@@ -0,0 +1,39 @@
...
+    </>;
+  }
+
+  @autobind()
+  async changeWorkspace({ value: workspace }: SelectOption<string>) {
+    this.workspace = workspace;
+    
+    const newCluster = this.props.cluster;
+    newCluster.workspace = workspace;
+    await clusterStore.addCluster(newCluster);
```
Comment (ixrock) [inline src/renderer/components/+cluster-settings/components/cluster-workspace-setting.tsx]: `clusterStore.addCluster` should be used only in `add-cluster-page`

Comment (Nokel81) [reply src/renderer/components/+cluster-settings/components/cluster-workspace-setting.tsx]: Is it not an create or update function? That seems to be what it is doing on the implementation side...

File: src/renderer/components/+cluster-settings/components/install-metrics.tsx [hunk 39]
```diff
@@ -0,0 +1,148 @@
...
+          Install {this.getStatusIcon()} {this.getDisabledToolTip("cluster-feature-metrics-install", "Installing")}
+        </Button>
+      );
+    }
+
+    return buttons;
+  }
+
+  @autobind()
+  async installMetrics() {
```
Comment (ixrock) [inline src/renderer/components/+cluster-settings/components/install-metrics.tsx]: Lot's of common logic in `installMetrics(), uninstallMetrics() and upgradeMetrics()`..
Could be extracted in common method and re-used with provided "action" only:

```ts
  async applyAction(action: () => Promise<any>){
    // setup
    try {
      await action();
    } catch (err){
      // handle error
    }
    // teardown
  }
```
Please check all other places for such pattern reuse.

File: src/renderer/components/file/file.tsx (hunk 29 above)
Comment (ixrock) [reply src/renderer/components/file/file.tsx]: So why not define as `optional` prop and check normally?

File: src/renderer/components/+cluster-settings/components/cluster-workspace-setting.tsx (hunk 38 above)
Comment (ixrock) [reply src/renderer/components/+cluster-settings/components/cluster-workspace-setting.tsx]: It's only create function. Update cluster data directly on `Cluster` object.

File: src/renderer/components/file-picker/file-picker.tsx [hunk 40]
```diff
@@ -0,0 +1,202 @@
...
+    const { maxTotalSize, onOverTotalSizeLimit } = this.props;
+
+    const totalSize = files.map(f => f.size).reduce((a, b) => a + b, 0);
+    if (totalSize <= maxTotalSize) {
+      return files;
+    }
+
+    switch (onOverTotalSizeLimit) {
+    case OverTotalSizeLimitStyle.FILTER_LARGEST:
+      files = files.sort((a, b) => a.size - b.size);
```
Comment (ixrock) [inline src/renderer/components/file-picker/file-picker.tsx]: Let's use `orderBy` from `lodash`?
