### PR TITLE
Fix ERR_UNSAFE_PORT from LensProxy

### LINKED ISSUE #4524: ERR_UNSAFE_PORT (-312) loading 'http://localhost:4045/'
**Describe the bug**
Today opening Lens I got this error:  
`ERR_UNSAFE_PORT (-312) loading 'http://localhost:4045/'`  
Seems like it is not a firewall problem, but just Lens seems scared to contact that port (like some browsers, where you should add something like `--explicitly-allowed-ports=4045`)

**To Reproduce**
1. Open Lens

**Expected behavior**
Lens should connect on its server

**Screenshots**
image
image

**Environment (please complete the following information):**
- Lens Version: 5.3.2
- OS: Windows
- Installation method (e.g. snap or AppImage in Linux):

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
info: [WINDOW-MANAGER]: Loading Main window from url: http://localhost:4045 ...
error: [WINDOW-MANAGER]: Failed to load Main window {"code":-312,"desc":"ERR_UNSAFE_PORT"}
error: Loading main window failed {"error":{"errno":-312,"code":"ERR_UNSAFE_PORT","url":"http://localhost:4045/"}}
info: [WINDOW-MANAGER]: Main window loaded
```

**Additional context**
Actually I didn't try to reboot my system, later I will try it but I still want report it because I think it could be useful for someone else or other reasons

### PR DESCRIPTION
**Pull request by Nokel81**
- Use the current list of ports from chromium as it is much easier to
  just reject using one of those instead of trying to handle the
  ERR_UNSAFE_PORT laod error from a BrowserWindow.on("did-fail-load")

Signed-off-by: Sebastian Malton <sebastian@malton.name>

### CODE REVIEW

**Comment by Nokel81** [comment]
This can be tested by using the following generator to attempt to use the bad ports:

```
const portNumbers = (function*() {
  yield 1719;
  yield 1720;
  yield 1723;
  yield 2049;
  yield 3659;
  yield 4045;
  yield 5060;
  yield 5061;
  yield 6000;
  yield 6566;
  yield 6665;
  yield 6666;
  yield 6667;
  yield 6668;
  yield 6669;
  yield 6697;
  yield 10080;

  for (;;) {
    yield 0;
  }
})();
```

File: src/main/index.ts [hunk 1]
```diff
@@ -184,13 +184,39 @@ app.on("ready", async () => {
...
   initializers.initClusterMetadataDetectors();
 
-  try {
-    logger.info("🔌 Starting LensProxy");
-    await lensProxy.listen();
-  } catch (error) {
-    dialog.showErrorBox("Lens Error", `Could not start proxy: ${error?.message || "unknown error"}`);
+  logger.info("🔌 Starting LensProxy");
+
+  for (let attempt = 0;; attempt += 1) {
```
Comment (jakolehm) [inline src/main/index.ts]: I think retries should be hidden within `lensProxy.listen()` .. if it cannot find proper port then throw.

Comment (Nokel81) [reply src/main/index.ts]: Sounds good. 

I had initially tried catching the error from the load itself but felt that that was too complicated.

**Review by jakolehm — APPROVED** [review]
LGTM

**Review by jweak — APPROVED** [review]
LGTM
