### PR TITLE
lens:// routing shouldn't ignore intree extensions

### LINKED ISSUE #3090: `lens://` routing ignores in-tree extensions
**Describe the bug**
If an intree extension registers a `lens://` protocol route. And a user tries to go to that route, a notification will be displayed that implies that no extension was found.

### PR DESCRIPTION
**Pull request by Nokel81**
Signed-off-by: Sebastian Malton <sebastian@malton.name>

fixes #3090

### CODE REVIEW

File: src/common/protocol-handler/router.ts [hunk 1]
```diff
@@ -179,7 +179,7 @@ export abstract class LensProtocolRouter extends Singleton {
     const { [EXTENSION_PUBLISHER_MATCH]: publisher, [EXTENSION_NAME_MATCH]: partialName } = match.params;
     const name = [publisher, partialName].filter(Boolean).join("/");
 
-    const extension = ExtensionLoader.getInstance().userExtensionsByName.get(name);
+    const extension = ExtensionLoader.getInstance().getInstanceByName(name);
```
Comment (jim-docker) [inline src/common/protocol-handler/router.ts:182]: Couldn't you have just used the existing `getExtensionByName()`?

Comment (Nokel81) [reply src/common/protocol-handler/router.ts:182]: Do you mean instead of changing its name to `getInstanceByName`?

Comment (Nokel81) [reply src/common/protocol-handler/router.ts:182]: I changed the name because we have a difference between `InstalledExtension`'s (which use the name `extension` in the loader's method names and `LensExtension`'s (or instances) which tend to use the work `instance` in the loader's method names.

I updated this function name to be inline with that.

File: src/extensions/extension-loader.ts [hunk 2]
```diff
@@ -81,28 +101,8 @@ export class ExtensionLoader extends Singleton {
...
-        continue;
-      }
-
-      extensions.set(val.manifest.name, val);
-    }
-
-    return extensions;
-  }
-
-  getExtensionByName(name: string): LensExtension | null {
```
Comment (jim-docker) [inline src/extensions/extension-loader.ts:98]: This function as is doesn't do what you need? Did you have to add the `instancesByName` observable.map?

Comment (Nokel81) [reply src/extensions/extension-loader.ts:98]: No, it was an optimization. Similar to those done in `CatalogEntityRegistry` in `renderer`. To avoid rebuilding the whole map every time a dependent is changed.

**Review by jim-docker — APPROVED** [review]
