### PR TITLE
Fix rendering of boolean values in CRDs

### LINKED ISSUE #1071: Boolean not rendering on additional printer columns.
**Describe the bug**
When a CRD has a boolean additional printer column, it doesn't show the value in the table.

**To Reproduce**
Apply this CRD, and then the example resource.
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: boolexamples.bool.example.com
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.randomBool
    name: Bool
    type: boolean
  group: bool.example.com
  names:
    kind: BoolExample
    listKind: BoolExampleList
    plural: boolexamples
    singular: boolexample
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            randomBool:
              type: boolean
          required:
          - randomBool
          type: object
        status:
          type: object
      type: object
```
```yaml
apiVersion: bool.example.com/v1
kind: BoolExample
metadata:
  name: randombool-sample
spec:
  randomBool: true
```

**Expected behavior**
When viewing the `BoolExample` CRD tab, the resource should have a boolean `true` in its row.

**Environment (please complete the following information):**
- Lens Version: 3.6.6
- OS: Windows
- Installation method (e.g. snap or AppImage in Linux): Installer
 
**Logs:**
No relevant logs in the console or debug tools.

**Additional context**
Executing `kubectl` shows the value correctly:
```bash
$ kubectl get boolexamples
NAME                BOOL
randombool-sample   true
```

### PR DESCRIPTION
**Pull request by Nokel81**
- add optional special casing for boolean values in DrawerItems and
  TableRows since React (imo annoying fashion) does not render boolean
  values by default.
- add a spinner on the sidebar for when the CRD menu is expeanded but
  the entries have not been loaded yet.
- Add ability to double click a Badge to expand, also make it so that
  Badges highligh all text on first click.

Signed-off-by: Sebastian Malton <sebastian@malton.name>

fixes #1071

### CODE REVIEW

File: src/renderer/components/badge/badge.tsx [hunk 1]
```diff
@@ -3,21 +3,35 @@ import "./badge.scss"
...
   label?: React.ReactNode;
 }
 
 @withTooltip
+@observer
 export class Badge extends React.Component<Props> {
+  @observable isExpanded = false
+
+  @autobind()
+  onDoubleClick() {
```
Comment (aleksfront) [inline src/renderer/components/badge/badge.tsx]: In overall, I guess it's a great idea to make badges expandable. I'm thinking maybe it's worth to help user understand how he can toggle badges. We can do this by changing cursor to `pointer` and maybe highlight badge background a bit on hover. And how about using just a `onClick` instead of `onDoubleClick`?

File: src/renderer/components/badge/badge.tsx [hunk 2]
```diff
@@ -3,21 +3,35 @@ import "./badge.scss"
...
+    this.isExpanded = !this.isExpanded
+    window.getSelection()?.empty()
```
Comment (aleksfront) [inline src/renderer/components/badge/badge.tsx]: Not really get why we need this. All selection stuff should be done with css if possible. And maybe keep native behavior untouched?
Btw maybe this line relate to current wonky selection behavior?
selecting a badge

File: src/renderer/components/badge/badge.tsx [hunk 3]
```diff
@@ -3,21 +3,35 @@ import "./badge.scss"
...
+  }
+
   render() {
     const { className, label, small, children, ...elemProps } = this.props;
-    return <>
-      <span className={cssNames("Badge", { small }, className)} {...elemProps}>
+    const classNames = cssNames("Badge", { small }, className, { expanded: this.isExpanded })
+
+    return (
+      <span className={classNames} {...elemProps} onDoubleClick={this.onDoubleClick}>
```
Comment (aleksfront) [inline src/renderer/components/badge/badge.tsx]: Maybe use `onClick`?

File: src/renderer/components/drawer/drawer-item.tsx [hunk 4]
```diff
@@ -1,25 +1,29 @@
...
   render() {
-    const { name, title, labelsOnly, children, hidden, ...elemProps } = this.props
-    let { className } = this.props;
+    const { name, title, labelsOnly, children, hidden, className, renderBoolean, ...elemProps } = this.props
     if (hidden) return null
-    className = cssNames("DrawerItem", className, { labelsOnly });
+
+    const classNames = cssNames("DrawerItem", className, { labelsOnly });
+    const content = displayBooleans(renderBoolean, children)
+    console.log(renderBoolean, content)
```
Comment (aleksfront) [inline src/renderer/components/drawer/drawer-item.tsx]: Forgotten `console.log` 👀

File: src/renderer/components/drawer/drawer-item.tsx [hunk 5]
```diff
@@ -1,25 +1,29 @@
...
 export class DrawerItem extends React.Component<DrawerItemProps> {
   render() {
-    const { name, title, labelsOnly, children, hidden, ...elemProps } = this.props
-    let { className } = this.props;
+    const { name, title, labelsOnly, children, hidden, className, renderBoolean, ...elemProps } = this.props
     if (hidden) return null
-    className = cssNames("DrawerItem", className, { labelsOnly });
+
+    const classNames = cssNames("DrawerItem", className, { labelsOnly });
+    const content = displayBooleans(renderBoolean, children)
```
Comment (aleksfront) [inline src/renderer/components/drawer/drawer-item.tsx:20]: Do we really need to increase complexity for such a case? It *feels* like we shouldn't wrap all component content with highly specialized `displayBooleans` wrapper. My guess for current case using the statement you provided in utility would be enough:
```
if (typeof children === "boolean") {
      return from.toString()
}
```

File: src/renderer/components/drawer/drawer-item.tsx [hunk 6]
```diff
@@ -1,25 +1,29 @@
...
-import { cssNames } from "../../utils";
+import { cssNames, displayBooleans } from "../../utils";
 
 export interface DrawerItemProps extends React.HTMLAttributes<any> {
   name: React.ReactNode;
   className?: string;
   title?: string;
   labelsOnly?: boolean;
   hidden?: boolean;
+  renderBoolean?: boolean; // show "true" or "false" for all of the children elements are "typeof boolean"
```
Comment (aleksfront) [inline src/renderer/components/drawer/drawer-item.tsx:11]: We probably need to show boolean values as strings always, so no necessity for a new prop.

File: src/renderer/components/badge/badge.scss [hunk 7]
```diff
@@ -8,8 +8,15 @@
   max-width: 100%;
   overflow: hidden;
   text-overflow: ellipsis;
+  -webkit-user-select: all;
```
Comment (aleksfront) [inline src/renderer/components/badge/badge.scss]: We can use property without `-webkit` part, just `user-select: all`. But, actually I found that selection flackiness (presented with gif in one of my comments) are gone if I comment/remove this line. Please check this part.

File: src/renderer/api/api-manager.ts [hunk 8]
```diff
@@ -23,6 +23,7 @@ export class ApiManager {
       return this.apis.get(pathOrCallback) || this.apis.get(KubeApi.parseApi(pathOrCallback).apiBase);
     }
 
+    pathOrCallback ??= (api: KubeApi) => true; // pick first if none given
```
Comment (aleksfront) [inline src/renderer/api/api-manager.ts]: Can you explain a bit the purpose of this line?

File: src/renderer/components/spinner/spinner.tsx [hunk 9]
```diff
@@ -17,12 +18,9 @@ export class Spinner extends React.Component<Props, {}> {
...
-    let { className } = this.props;
-    className = cssNames('Spinner', className, {
-      singleColor: singleColor,
-      center: center,
-    });
-    return <div {...props} className={className} ref={e => this.elem = e}/>;
+    const { center, singleColor, centerHorizontal, className, ...props } = this.props;
+    const classNames = cssNames('Spinner', className, { singleColor, center, centerHorizontal });
+
+    return <div {...props} className={classNames} ref={e => this.elem = e} />;
```
Comment (aleksfront) [inline src/renderer/components/spinner/spinner.tsx]: `ref={e => this.elem = e}` can be removed.

File: src/renderer/components/table/table-cell.tsx [hunk 10]
```diff
@@ -52,20 +53,20 @@ export class TableCell extends React.Component<TableCellProps> {
...
   render() {
-    const { className, checkbox, isChecked, sortBy, _sort, _sorting, _nowrap, children, title, ...cellProps } = this.props;
+    const { className, checkbox, isChecked, sortBy, _sort, _sorting, _nowrap, children, title, renderBoolean: displayBoolean, ...cellProps } = this.props;
     const classNames = cssNames("TableCell", className, {
       checkbox: checkbox,
       nowrap: _nowrap,
       sorting: this.isSortable,
     });
-    const content = title || children;
+    const content = displayBooleans(displayBoolean, title || children)
```
Comment (aleksfront) [inline src/renderer/components/table/table-cell.tsx:67]: I would suggest to explicitly check for a boolean here without using an external wrapper and utility

File: src/renderer/components/table/table-cell.tsx [hunk 11]
```diff
@@ -13,6 +13,7 @@ export interface TableCellProps extends React.DOMAttributes<HTMLDivElement> {
   title?: ReactNode;
   checkbox?: boolean; // render cell with a checkbox
   isChecked?: boolean; // mark checkbox as checked or not
+  renderBoolean?: boolean; // show "true" or "false" for all of the children elements are "typeof boolean"
```
Comment (aleksfront) [inline src/renderer/components/table/table-cell.tsx:16]: Probably no need to hide boolean values, suggesting to remove this prop.

File: src/renderer/api/api-manager.ts (hunk 8 above)
Comment (ixrock) [reply src/renderer/api/api-manager.ts]: Btw I would not overuse such operator(s) `??=` since it's **not** adds readability to code IMHO.

File: src/renderer/components/drawer/drawer-item.tsx (hunk 5 above)
Comment (Nokel81) [reply src/renderer/components/drawer/drawer-item.tsx:20]: That is not good enough because if for some reason anyone uses the (imo unfortunately) ubiquitous pattern of `cond && expr` inside a drawer item, then instead of rendering nothing it would render a bunch of `false`'s.

File: src/renderer/api/api-manager.ts (hunk 8 above)
Comment (Nokel81) [reply src/renderer/api/api-manager.ts]: I encountered a runtime error where this variable was not set to anything. Namely I got "pathOrCallback is not a function" (it was undefined) so I added this to return a better result.

@ixrock I don't think this is an overuse. This is exactly what that operator was designed for, plus I think it is much clearer than using `||=` for instance.

File: src/renderer/components/badge/badge.tsx (hunk 1 above)
Comment (Nokel81) [reply src/renderer/components/badge/badge.tsx]: I like the idea of changing the cursor, I am going to look into only having it when `text-overflow` would trigger. I am okay with using `onClick` instead.

File: src/renderer/components/spinner/spinner.tsx (hunk 9 above)
Comment (Nokel81) [reply src/renderer/components/spinner/spinner.tsx]: why?

Comment (Nokel81) [reply src/renderer/components/spinner/spinner.tsx]: NVM, I see that it is not longer used. Will remove

File: src/renderer/api/api-manager.ts (hunk 8 above)
Comment (aleksfront) [reply src/renderer/api/api-manager.ts]: Maybe better to change `first` to `true` inside a comment since first meaning is confusing (it can relate to first part of these operators, left-hand side)

File: src/renderer/components/drawer/drawer-item.tsx (hunk 5 above)
Comment (aleksfront) [reply src/renderer/components/drawer/drawer-item.tsx:20]: @Nokel81 I've checked example with PodDetails component in line https://github.com/lensapp/lens/blob/master/src/renderer/components/+workloads-pods/pod-details.tsx#L82 and there's no problem if keeping 
`const content = typeof children === "boolean" ? children.toString() : children`
inside `DrawerItem`. So double check if can we remove `displayBooleans` wrapper

**Comment by aleksfront** [comment]
Related to extra icons
extra icons

Also, it's better to stick with Bagde only for expanding it. IMHO I feel that Click event and pointer cursor is enough for such a feature.

**Comment by Nokel81** [comment]
The user experience is terrible with click because it fires even when you are highlighting.

File: src/renderer/components/drawer/drawer-item.tsx (hunk 5 above)
Comment (Nokel81) [reply src/renderer/components/drawer/drawer-item.tsx:20]: Line 82 is irreverent because it is not `typeof === "boolean"` but `typeof === "string"`. If that line happened to be `nodeName.length > 0 && ( ... )` then it wouldn't work.

File: src/renderer/components/badge/badge.tsx (hunk 2 above)
Comment (Nokel81) [reply src/renderer/components/badge/badge.tsx]: Agreed, fixed

File: src/renderer/components/drawer/drawer-item.tsx (hunk 5 above)
Comment (aleksfront) [reply src/renderer/components/drawer/drawer-item.tsx:20]: It actually works okay with `nodeName.length > 0 && ( ... )`:
node name

**Comment by aleksfront** [comment]
@Nokel81 To move things forward I suggest to relocate Badge expanding mechanism to another issue and PR. Please also check this comment https://github.com/lensapp/lens/pull/1087#discussion_r517830639. I guess we can merge this PR with those `typeof` conditoins. Wdyt?

File: src/renderer/components/drawer/drawer-item.tsx (hunk 5 above)
Comment (Nokel81) [reply src/renderer/components/drawer/drawer-item.tsx:20]: It "works" in so far as if the LHS is truthy then the RHS is the result. However, if it is falsy then it would display:

```
Node              false
```

**Comment by Nokel81** [comment]
@aleksfront Made #1236 With the badge changes

**Comment by aleksfront** [comment]
@Nokel81 Can you add please unit tests to `displayBooleans` utility?

File: src/renderer/components/drawer/drawer-item.tsx [hunk 12]
```diff
@@ -1,25 +1,28 @@
...
+
+    const classNames = cssNames("DrawerItem", className, { labelsOnly });
+    const content = displayBooleans(renderBoolean, children)
+
     return (
-      <div {...elemProps} className={className} title={title}>
+      <div {...elemProps} className={classNames} title={title}>
         <span className="name">{name}</span>
-        <span className="value">{children}</span>
+        <div className="value">{content}</div>
```
Comment (aleksfront) [inline src/renderer/components/drawer/drawer-item.tsx]: It's a bit unclear why replacing `span` to `div` here?

File: src/renderer/components/+custom-resources/crd-resource-details.tsx [hunk 13]
```diff
@@ -12,67 +12,83 @@ import { KubeObjectDetailsProps } from "../kube-object";
...
+
 @observer
 export class CrdResourceDetails extends React.Component<Props> {
   @computed get crd() {
     return crdStore.getByObject(this.props.object);
   }
 
+  renderAdditionalColumns(crd: CustomResourceDefinition, columns: AdditionalPrinterColumnsV1[]) {
+    return columns.map(({ name, jsonPath: jp }) => (
+      <DrawerItem key={name} name={name} renderBoolean>
```
Comment (aleksfront) [inline src/renderer/components/+custom-resources/crd-resource-details.tsx:48]: Maybe set `renderBoolean` `true` by default so no need to explicitly set this prop? Wdyt?

**Review by aleksfront — APPROVED** [review]

File: src/renderer/components/+custom-resources/crd-resource-details.tsx (hunk 13 above)
Comment (Nokel81) [reply src/renderer/components/+custom-resources/crd-resource-details.tsx:48]: We could definitely do that. However I am a bit on the fence about it. If we make rendering boolean's default it makes the coding easier but we might then get random booleans being rendered. If keep it false then we have to add `renderBoolean` to a bunch of places but we are much less likely to get unwanted booleans being rendered.
