### PR TITLE
add a zero width space to Badges to fix double click highlighting issue

### LINKED ISSUE #869: End of Label text should be word boundary
**Describe the bug**
When using double-click to being selecting words from the UI, in some fields, such as Labels, the end of an entry is not treated as a word boundary and the selection extends to the beginning of the next entry.

This happens, for example, when selecting Labels or Annotations. 

A more severe case is with Conditions, where double-clicking selects all conditions at once. 

**To Reproduce**
1. Go to pod details
2. Double-Click on part of a label, keep the mouse button down
3. Move the cursor to extend the selection
4. See that it is impossible to end the selection at the end of the label if there is another label following the current one

**Expected behavior**

The selection would end at the end of the label, unless the cursor moved down to the next labe.

**Screenshots**

Lens double-click select

**Environment (please complete the following information):**
- Lens Version: 3.5.3
- OS: OS X 10.15.6
- Installation method (e.g. snap or AppImage in Linux): Lens.dmg
 
**Additional context**

This happens in a lot of areas of the UI but works correctly in a lot of other areas. Environment and Mounts work properly, Liveness and Readiness do not.

### PR DESCRIPTION
**Pull request by Nokel81**
Signed-off-by: Sebastian Malton <sebastian@malton.name>

fixes #869

### CODE REVIEW

File: src/renderer/components/badge/badge.tsx [hunk 1]
```diff
@@ -13,11 +13,12 @@ interface Props extends React.HTMLAttributes<any>, TooltipDecoratorProps {
...
   render() {
     const { className, label, small, children, ...elemProps } = this.props;
-    return (
+    return <>
       <span className={cssNames("Badge", { small }, className)} {...elemProps}>
         {label}
         {children}
       </span>
-    );
+      &#8203;
```
Comment (jim-docker) [inline src/renderer/components/badge/badge.tsx:27]: add some comments why it's needed?

**Review by jim-docker — APPROVED** [review]

**Review by nevalla — APPROVED** [review]
LGTM
