### PR TITLE
Fix shouldShowResource when not a cluster admin

### LINKED ISSUE #6858: OpenLens 6.3.0 on macOS does not show pods and config/network/storage sections are empty, all work fine in 6.2.6.
**Describe the bug**
OpenLens 6.3.0 on macOS does not show pods and config/network/storage sections are empty, all work fine in 6.2.6.

**To Reproduce**
1. git checkout v6.3.0 # or master d6531f2
2. make clean && make dev
3. When window appears, connect to a namespace (there's already configured single namespace in Namespace/Accessible Namespaces)
4. Expand 'Workloads'
5. Do not see Pods, but can see Deployments, DaemonSets, StatefulSets, ReplicaSets, Jobs, CronJobs
6. Scroll down to 'Config' and expand
7. Do not see ConfigMaps, Secrets, Resource Quotas, Limit Ranges, HPA, Pod Disruption Budgets
8. Scroll down to 'Network' and expand
9. Do not see Services, Endpoints, Ingresses, Network Policies but can only see Port Forwarding
10. Scroll down to 'Storage'
11. Can't expand as it's empty (can't see Persistent Volume Claims')

**Expected behavior**
5. I see Pods in 'Workloads' section
7. I see ConfigMaps, Secrets, Resource Quotas, Limit Ranges, HPA, Pod Disruption Budgets in 'Config' section
9. I see Services, Endpoints, Ingresses, Network Policies in 'Network' section
11. I see Persistent Volume Claims in 'Storage' section

**Screenshots**
Wrong one from OpenLens 6.3.0:
Screenshot 2023-01-02 at 16 21 36

Correct one from OpenLens 6.2.6:
Screenshot 2023-01-02 at 16 14 32

**Environment (please complete the following information):**
- Lens Version: 6.3.0
- OS: macOS
- Installation method (e.g. snap or AppImage in Linux): make clean && make dev # from github tag

**Kubeconfig:**
```
apiVersion: v1
clusters:
- cluster:
    server: https://api-kube.***
  name: cluster1
...
contexts:
- context:
    cluster: cluster1
    namespace: ns1
    user: some-user
  name: cluster1-ns1
...
current-context: cluster1-ns1
kind: Config
preferences: {}
users:
- name: some-user
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=https://***
      - --oidc-client-id=api-kube
      - --oidc-client-secret=***
      - --oidc-extra-scope=groups
      command: kubectl
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
```

### LINKED ISSUE #6879: Allow Resource with group set to v1 in rbac.ts are not showing, if your are not cluster admin
**Describe the bug**
Allow Resource with group set to v1 in rbac.ts are not showing, if your are not cluster admin

https://github.com/lensapp/lens/pull/6657/files?show-deleted-files=true&show-viewed-files=true&file-filters%5B%5D=#r1062429006

**To Reproduce**
1. Create a user than can only view a single namespace.
2. Open lens with this context
3. No ConfigMap is showing

**Expected behavior**
I can see the configmap....

**Environment (please complete the following information):**
- Lens Version: 6.3
- Installation method (e.g. snap or AppImage in Linux): OpenLens

### PR DESCRIPTION
**Pull request by Nokel81**
Signed-off-by: Sebastian Malton <sebastian@malton.name>

fixes https://github.com/lensapp/lens/issues/6858
fixes https://github.com/lensapp/lens/issues/6879
closes https://github.com/lensapp/lens/pull/6880

### CODE REVIEW

File: src/main/cluster/request-core-api-versions.injectable.ts [hunk 1]
```diff
@@ -16,7 +16,7 @@ const requestCoreApiVersionsInjectable = getInjectable({
       const { versions } = await k8sRequest(cluster, "/api") as V1APIVersions;
 
       return versions.map(version => ({
-        group: version,
```
Comment (Nokel81) [inline src/main/cluster/request-core-api-versions.injectable.ts:19]: This is the majority of the bug fix

**Review by ixrock — APPROVED** [review]
LGTM

**Review by jansav — APPROVED** [review]
