### PR TITLE
fixed non-virtual list row rendering

### LINKED ISSUE #4960: Empty Events table in Workloads overview
Events table header shows that there must be visible items, but the list itself is empty
empty events list

### PR DESCRIPTION
**Pull request by jim-docker**
fixes #4960

### CODE REVIEW

File: src/renderer/components/item-object-list/content.tsx [hunk 1]
```diff
@@ -68,67 +68,76 @@ export class ItemListLayoutContent<I extends ItemObject> extends React.Component
     return this.props.store.failedLoading;
   }
 
+  @boundMethod
+  renderRow(item: I) {
+    return this.getTableRow(item);
+  }
+
+  getTableRow(item: I) {
```
Comment (jim-docker) [inline src/renderer/components/item-object-list/content.tsx:76]: this function implementation is cut and paste from getRow() below, no functional change

**Review by Nokel81 — APPROVED** [review]

**Review by aleksfront — APPROVED** [review]
