### PR TITLE
Fix getExtensionPageUrl on Windows

### LINKED ISSUE #1607: Extension cluster pages does not open on Windows
Link to cluster pages coming from extensions is not right on Windows and pages do not open.

image

image

### PR DESCRIPTION
**Pull request by nevalla**
Fixes #1607 

Signed-off-by: Lauri Nevala <lauri.nevala@gmail.com>

### CODE REVIEW

File: src/extensions/registries/page-registry.ts [hunk 1]
```diff
@@ -44,7 +44,7 @@ export function getExtensionPageUrl<P extends object>({ extensionId, pageId = ""
   const extensionBaseUrl = compile(`/extension/:name`)({
     name: sanitizeExtensionName(extensionId), // compile only with extension-id first and define base path
   });
-  const extPageRoutePath = path.join(extensionBaseUrl, pageId); // page-id might contain route :param-s, so don't compile yet
+  const extPageRoutePath = path.join(extensionBaseUrl, pageId).replace(/\\/g, "/"); // path.join returns \ as separator on Windows and needs to be replaced with /
```
Comment (jakolehm) [inline src/extensions/registries/page-registry.ts]: A test for this would be nice.

Comment (nevalla) [reply src/extensions/registries/page-registry.ts]: test is already there and actually it was failing. We would have seen that if tests were running on windows too. Will be fixed in #1610

Comment (panuhorsmalahti) [inline src/extensions/registries/page-registry.ts]: It doesn't seem correct to use path.join (intended for file paths) for joining the url. See https://stackoverflow.com/a/16301947

Comment (nevalla) [reply src/extensions/registries/page-registry.ts]: it seems that we cannot achieve the same with `new URL()` since we are combining the path part of the url. However `path.posix.join` might be something that we want to use.

**Review by jakolehm — APPROVED** [review]

File: src/extensions/registries/page-registry.ts (hunk 1 above)
Comment (panuhorsmalahti) [reply src/extensions/registries/page-registry.ts]: path.posix.join also doesn't sound like optimal here, even if `new URL()` is insufficient. Surely there's some npm dependency to join url parts properly.
