### PR TITLE
Wait app to be ready before creating a BrowserWindow for system proxy resolver

### LINKED ISSUE #7436: quitting causes a failure
**Describe the bug**
Whenever i quit openlens 6.4.11 i get a popup saying it quit unexpectedly. even tho i clicked on quit!

**To Reproduce**
1. Go to '...' the file menu and click on "quit"

**Expected behavior**
lens quits nices

**Screenshots**
Screenshot 2023-03-30 at 8 00 37 AM

**Environment (please complete the following information):**
- Lens Version: 6.4.11
- OS: [e.g. OSX] osx 13.2
- Installation method (e.g. snap or AppImage in Linux): brew

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

### PR DESCRIPTION
**Pull request by jakolehm**
Should fix #7436 .

### CODE REVIEW

File: packages/core/src/main/utils/resolve-system-proxy/resolve-system-proxy-window.injectable.ts [hunk 1]
```diff
@@ -4,13 +4,21 @@
...
 
-    window.hide();
+    await app.whenReady();
+    
+    const window = new BrowserWindow({
+      show: false,
+      paintWhenInitiallyHidden: false,
+    });
+
+    window.hide();
```
Comment (Iku-turso) [inline packages/core/src/main/utils/resolve-system-proxy/resolve-system-proxy-window.injectable.ts:21]: Does the window need deliberate `.hide()` if it's already `show: false`?

File: packages/core/src/main/utils/resolve-system-proxy/resolve-system-proxy-window.injectable.ts [hunk 2]
```diff
@@ -4,13 +4,21 @@
...
 
 const resolveSystemProxyWindowInjectable = getInjectable({
   id: "resolve-system-proxy-window",
-  instantiate: () => {
-    const window = new BrowserWindow({ show: false });
+  instantiate: async (di) => {
+    const app = di.inject(electronAppInjectable);
 
-    window.hide();
+    await app.whenReady();
```
Comment (Iku-turso) [inline packages/core/src/main/utils/resolve-system-proxy/resolve-system-proxy-window.injectable.ts:14]: Cleaner way to do this:
`const app = await di.inject(readyElectronAppInjectable);`

File: packages/core/src/main/utils/resolve-system-proxy/resolve-system-proxy-window.injectable.ts [hunk 3]
```diff
@@ -4,13 +4,21 @@
  */
 import { getInjectable } from "@ogre-tools/injectable";
 import { BrowserWindow } from "electron";
+import electronAppInjectable from "../../electron-app/electron-app.injectable";
 
 const resolveSystemProxyWindowInjectable = getInjectable({
```
Comment (Iku-turso) [inline packages/core/src/main/utils/resolve-system-proxy/resolve-system-proxy-window.injectable.ts:9]: Name indicates `function`, but it's actually a `window`. Proposed name: `systemProxyWindowInjectable`.

File: packages/core/src/main/utils/resolve-system-proxy/resolve-system-proxy-window.injectable.ts (hunk 1 above)
Comment (jakolehm) [reply packages/core/src/main/utils/resolve-system-proxy/resolve-system-proxy-window.injectable.ts:21]: I'm trying to play safe here, Electron docs say that `show: false` does not mean it is marked as hidden.

> If a BrowserWindow is created with show: false, the initial visibility state will be visible despite the window actually being hidden.

File: packages/core/src/main/utils/resolve-system-proxy/resolve-system-proxy-window.injectable.ts [hunk 4]
```diff
@@ -4,13 +4,21 @@
...
   id: "resolve-system-proxy-window",
-  instantiate: () => {
-    const window = new BrowserWindow({ show: false });
+  instantiate: async (di) => {
+    const app = di.inject(electronAppInjectable);
 
-    window.hide();
+    await app.whenReady();
+    
+    const window = new BrowserWindow({
```
Comment (Iku-turso) [inline packages/core/src/main/utils/resolve-system-proxy/resolve-system-proxy-window.injectable.ts:16]: This is a competing way to create new "lensWindows". That means it isn't recognised in eg.
`closeAllWindowsInjectable`, and doesn't therefore get closed. Maybe that's one source of this bug?

**Comment by Iku-turso** [comment]
This is a kludgy hot-fix PR, and requires concrete plan to be done properly with eg. unit tests.

File: packages/core/src/main/utils/resolve-system-proxy/resolve-system-proxy-window.injectable.ts (hunk 1 above)
Comment (Iku-turso) [reply packages/core/src/main/utils/resolve-system-proxy/resolve-system-proxy-window.injectable.ts:21]: Roger, resolved.

File: packages/core/src/main/utils/resolve-system-proxy/resolve-system-proxy-window.injectable.ts (hunk 4 above)
Comment (jakolehm) [reply packages/core/src/main/utils/resolve-system-proxy/resolve-system-proxy-window.injectable.ts:16]: I agree that we probably should close the window by ourselves but this particular window is not really like “normal” LensWindow .. and I even had a runnable for doing this but it did not help.

Comment (Iku-turso) [reply packages/core/src/main/utils/resolve-system-proxy/resolve-system-proxy-window.injectable.ts:16]: This will mean that behaviour or name of `closeAllWindowsInjectable` needs to change, as now it's not accurate.

Resolved.

**Review by Iku-turso — APPROVED** [review]
