### PR TITLE
Fix completely overriding PATH in shellSync

### LINKED ISSUE #4931: Shell sync overrides modified PATH
During shell sync we override the PATH variable on non-snap environments. However, if the user has modified the PATH, for instance by setting up a virtual environment for certain dependencies, this gets overridden.

We should instead do some sort of concat or maybe merge.

### PR DESCRIPTION
**Pull request by Nokel81**
- This allows local changes to PATH in the shell that is used to open
  lens to persist after shellSync.

- This helps with using python virtual environments

Signed-off-by: Sebastian Malton <sebastian@malton.name>

fixes #4931

### CODE REVIEW

File: src/common/utils/iter.ts [hunk 1]
```diff
@@ -233,3 +233,18 @@ export function every<T>(src: Iterable<T>, fn: (val: T) => any): boolean {
 
   return true;
 }
+
+/**
+ * Takes two iterators and creates a new iterator over both in sequence.
+ * @param first The first iterable to iterate over
+ * @param second The second iterable to iterate over
+ */
+export function* chain<T>(first: Iterable<T>, second: Iterable<T>): Iterable<T> {
```
Comment (ixrock) [inline src/common/utils/iter.ts]: It's unused in PR?

Comment (Nokel81) [reply src/common/utils/iter.ts]: Good catch, I added this in a previous iteration of `unionPATHs`, will remove.

File: src/main/shell-sync.ts [hunk 2]
```diff
@@ -25,7 +26,8 @@ export async function shellSync() {
   }
 
   if (!isSnap) {
-    process.env.PATH = env.PATH;
+    // Prefer the synced PATH over the initial one
+    process.env.PATH = unionPATHs(env.PATH ?? "",  process.env.PATH ?? "");
```
Comment (ixrock) [inline src/main/shell-sync.ts:30]: What happens if both `env.PATH` and `process.env.PATH` are defined?  Or it's expected to be merged if so?

**Review by ixrock — APPROVED** [review]

File: src/main/shell-sync.ts (hunk 2 above)
Comment (Nokel81) [reply src/main/shell-sync.ts:30]: That is expected, and yes it is expected that they will be merged.

Furthermore, the entries within each will be de-duplicated as well.

File: src/common/utils/__tests__/union-env-path.test.ts [hunk 3]
```diff
@@ -0,0 +1,32 @@
...
+
+import path from "path";
+import { unionPATHs } from "../union-env-path";
+
+describe("unionPATHs", () => {
+  it("return the same path if given only one with no double delimiters", () => {
+    expect(unionPATHs(`/bin/bar${path.delimiter}/usr/bin`)).toBe(`/bin/bar${path.delimiter}/usr/bin`);
+  });
+
+  it("return equivalent path if given only one with no double delimiters", () => {
```
Comment (jim-docker) [inline src/common/utils/__tests__/union-env-path.test.ts:14]: should this read:
```suggestion
  it("return equivalent path if given only one with double delimiters", () => {
```

**Comment by Nokel81** [comment]
Closing for the time being as neither @jim-docker nor I can reproduce the linked issue.

**Review by jim-docker — APPROVED** [review]
Couldn't actually reproduce the bug to confirm this fixes it. Regardless this shouldn't hurt anything(?)

File: src/common/utils/__tests__/union-env-path.test.ts (hunk 3 above)
Comment (Nokel81) [reply src/common/utils/__tests__/union-env-path.test.ts:14]: Will fix in follow up PR
