### PR TITLE
Fix installation of helm charts

### LINKED ISSUE #5827: Installing Helm Chart doesn't work properly
**Describe the bug**

Issues:

1. Clicking "Install" button results to "Bad Request" notification.
2. Dock tab for doesn't load properly when you have already tried to install some chart (leave dock tab open for it) and try installing second chart.
3. Clicking "View Helm Release" after installing opens the Details for Release but then quickly closes it again. After that any details for releases cannot be opened.
4. In confirmation dialog for deleting release there is missing space between "Remove" and name of release. 
5. Changing version in dock tab for installing chart doesn't work.

**Environment (please complete the following information):**
- Lens Version: 5.6.0-alpha.6.20220706.1
- OS: OSX
- Installation method: Website + auto update

https://user-images.githubusercontent.com/3083083/178434974-6dead347-9277-4511-8fa0-f1a99cd7c9ad.mov

image

### PR DESCRIPTION
**Pull request by jansav**
Fixes #5827 

Notice the added behaviours, they describe completely how it should work. There's still lot to improve in the implementation, but that's enough for now.

### CODE REVIEW

File: src/renderer/components/+helm-charts/details/versions/helm-chart-details-version-selection.injectable.ts [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+    const versionsOfSelectedHelmChart = di.inject(
+      versionsOfSelectedHelmChartInjectable,
+      chart,
+    );
+
+    const state = observable.box<HelmChart>();
+
+    return {
+      value: computed(
+        () => state.get() || versionsOfSelectedHelmChart.value.get()[0],
```
Comment (Nokel81) [inline src/renderer/components/+helm-charts/details/versions/helm-chart-details-version-selection.injectable.ts:36]: nit, using `??` is more semantically correct.

File: src/renderer/components/dock/editor-panel.tsx [hunk 2]
```diff
@@ -59,7 +61,7 @@ const NonInjectedEditorPanel = observer(({
       autoFocus={autoFocus}
       id={tabId}
       value={value}
-      className={cssNames(styles.EditorPanel, className)}
+      className={cssNames(styles.EditorPanel, className, { hidden })}
```
Comment (Nokel81) [inline src/renderer/components/dock/editor-panel.tsx:64]: This seems strange, why is this needed?

File: src/renderer/components/dock/install-chart/chart-data/call-for-helm-chart-values.injectable.ts [hunk 3]
```diff
@@ -0,0 +1,19 @@
...
+
+export type CallForHelmChartValues = (
+  repo: string,
+  name: string,
+  version: string
+) => Promise<string>;
+
+const callForHelmChartValuesInjectable = getInjectable({
+  id: "call-for-helm-chart-values",
+  instantiate: (): CallForHelmChartValues => getChartValues,
```
Comment (Nokel81) [inline src/renderer/components/dock/install-chart/chart-data/call-for-helm-chart-values.injectable.ts:16]: Shouldn't this also be `causesSideEffects`?

File: src/renderer/components/dock/install-chart/get-random-install-chart-tab-id.injectable.ts [hunk 4]
```diff
@@ -0,0 +1,13 @@
...
+ * Licensed under MIT License. See LICENSE in root directory for more information.
+ */
+import { getInjectable } from "@ogre-tools/injectable";
+import getRandomIdInjectable from "../../../../common/utils/get-random-id.injectable";
+
+const getRandomInstallChartTabIdInjectable = getInjectable({
+  id: "get-random-install-chart-tab-id",
+  instantiate: (di) => di.inject(getRandomIdInjectable),
+});
+
```
Comment (Nokel81) [inline src/renderer/components/dock/install-chart/get-random-install-chart-tab-id.injectable.ts:12]: This is weird, why have this additional level of abstraction?

File: src/renderer/components/dock/install-chart/install-chart-model.injectable.tsx [hunk 5]
```diff
@@ -0,0 +1,281 @@
...
+
+  instantiate: async (di, tabId: string) => {
+    const store = di.inject(installChartTabStoreInjectable);
+    const callForHelmChartValues = di.inject(callForHelmChartValuesInjectable);
+    const callForHelmChartVersions = di.inject(callForHelmChartVersionsInjectable);
+    const callForCreateHelmRelease = di.inject(callForCreateHelmReleaseInjectable);
+    const dockStore = di.inject(dockStoreInjectable);
+    const navigateToHelmReleases = di.inject(navigateToHelmReleasesInjectable);
+    const closeTab = () => dockStore.closeTab(tabId);
+    const callChartByTab = async () => await waitUntilDefined(() => store.getData(tabId));
```
Comment (Nokel81) [inline src/renderer/components/dock/install-chart/install-chart-model.injectable.tsx]: nit: this is a strange variable name for something that doesn't do an API call.

File: src/renderer/components/dock/install-chart/install-chart-model.injectable.tsx [hunk 6]
```diff
@@ -0,0 +1,281 @@
...
+import type { SingleValue } from "react-select";
+import type { CallForHelmChartVersions } from "../../+helm-charts/details/versions/call-for-helm-chart-versions.injectable";
+import callForHelmChartVersionsInjectable from "../../+helm-charts/details/versions/call-for-helm-chart-versions.injectable";
+
+const installChartModelInjectable = getInjectable({
+  id: "install-chart-model",
+
+  instantiate: async (di, tabId: string) => {
+    const store = di.inject(installChartTabStoreInjectable);
+    const callForHelmChartValues = di.inject(callForHelmChartValuesInjectable);
```
Comment (Nokel81) [inline src/renderer/components/dock/install-chart/install-chart-model.injectable.tsx:35]: comment: what is the benefit of naming these sort of injectables with the `callFor` prefix? Wouldn't `getHelmChartValues` be descriptive enough?

File: src/renderer/getDiForUnitTesting.tsx [hunk 7]
```diff
@@ -111,6 +112,9 @@ export const getDiForUnitTesting = (opts: { doGeneralOverrides?: boolean } = {})
 
     di.override(historyInjectable, () => createMemoryHistory());
     di.override(legacyOnChannelListenInjectable, () => () => noop);
+
+    di.override(storageSaveDelayInjectable, () => 0);
```
Comment (Nokel81) [inline src/renderer/getDiForUnitTesting.tsx:116]: Why is this override different than that of `main`'s `getDiForUnitTesting`?

Comment (jansav) [reply src/renderer/getDiForUnitTesting.tsx:116]: This is used only by `createStorage` which is `renderer` thing.

File: src/renderer/components/dock/install-chart/get-random-install-chart-tab-id.injectable.ts (hunk 4 above)
Comment (jansav) [reply src/renderer/components/dock/install-chart/get-random-install-chart-tab-id.injectable.ts:12]: Overriding in test. If I would have overridden `getRandomIdInjectable` then all of use places (even the ones not relevant here) would be overridden.

File: src/renderer/components/dock/editor-panel.tsx (hunk 2 above)
Comment (jansav) [reply src/renderer/components/dock/editor-panel.tsx:64]: Because `MonacoEditor` works incorrectly

```typescript
const SomeComponent = observer(({ someProp, value }: Props) => (
  <div>
    {someProp.get() ? <MonacoEditor value={value.get()} /> : <div>Something else</div>}
  </div>
));

```

1. `someProp.get()` returns truthy value, `MonacoEditor` is rendered
2. `someProp.get()` changes to falsy value, `MonacoEditor` is not rendered
3. `value.get()` changes
4. `someProp.get()`  changes back to truthy value, `MonacoEditor` renders with old value

File: src/renderer/components/dock/install-chart/chart-data/call-for-helm-chart-values.injectable.ts (hunk 3 above)
Comment (jansav) [reply src/renderer/components/dock/install-chart/chart-data/call-for-helm-chart-values.injectable.ts:16]: Sure, good catch.

Comment (jansav) [reply src/renderer/components/dock/install-chart/chart-data/call-for-helm-chart-values.injectable.ts:16]: Fixed

File: src/renderer/components/dock/install-chart/install-chart-model.injectable.tsx (hunk 5 above)
Comment (jansav) [reply src/renderer/components/dock/install-chart/install-chart-model.injectable.tsx]: Actually it was leftover. It's used only for waiting till chart is present in store so I named it `waitForChart` and made it `() => Promise<void>`

File: src/renderer/components/dock/install-chart/install-chart-model.injectable.tsx (hunk 6 above)
Comment (jansav) [reply src/renderer/components/dock/install-chart/install-chart-model.injectable.tsx:35]: It's just matter of preference and what we're used to. 

We've been using `callForX` for stuff that needs to be get from somewhere outside of the system. E.g. API call, file system, local storage. `getX` doesn't really communicate enough because it could also mean that we are getting some static value from somewhere or e.g. some deeply nested value from the input.

File: src/renderer/getDiForUnitTesting.tsx (hunk 7 above)
Comment (Nokel81) [reply src/renderer/getDiForUnitTesting.tsx:116]: Then why should `main` even know about it?

File: src/renderer/components/dock/editor-panel.tsx (hunk 2 above)
Comment (Nokel81) [reply src/renderer/components/dock/editor-panel.tsx:64]: Then shouldn't we fix `MonacoEditor`? That sounds like it isn't checking for an updated `value` prop (in `componentDidUpdate` or something).

Comment (jansav) [reply src/renderer/components/dock/editor-panel.tsx:64]: Yes, we should. Draw the line here, because there is lot to improve in `MonacoEditor`. Issue is that it's calling `this.restoreViewState(this.model);` when it creates the editor. Didn't go any deeper than that.

File: src/renderer/getDiForUnitTesting.tsx (hunk 7 above)
Comment (jansav) [reply src/renderer/getDiForUnitTesting.tsx:116]: It doesn't?

**Review by Nokel81 — APPROVED** [review]

**Comment by jim-docker** [comment]
https://user-images.githubusercontent.com/40840436/179756154-eb74dcb4-2325-4a7c-a7d3-3428355de3e7.mov

Or maybe this is related to the Upgrade bug

**Comment by jansav** [comment]
> 
> 
> https://user-images.githubusercontent.com/40840436/179756154-eb74dcb4-2325-4a7c-a7d3-3428355de3e7.mov
> 
> 
> 
> Or maybe this is related to the Upgrade bug

Yes, this is related to the other issue I created today. #5852

**Comment by jim-docker** [comment]
The release details page slides in a few extra times (sometimes it doesn't happen till ~30 seconds later)
Also, after removing a release, the release list gets redrawn a few extra times.

https://user-images.githubusercontent.com/40840436/179889331-fb8a374a-84f4-4494-9bb0-32fdb433de70.mov

**Comment by jim-docker** [comment]
crash after removing a release with an upgrade tab open

https://user-images.githubusercontent.com/40840436/179889451-ec409597-387a-42b4-a254-2ba254b5955a.mov

**Review by jim-docker — APPROVED** [review]
approving in case found issues should be fixed in another PR
