### PR TITLE
Keep shell processes alive between network offline periods

### LINKED ISSUE #4250: Terminal process dies if network goes offline
**Describe the bug**

Lens kills terminal process whenever network goes offline (for example when laptop sleeps). This is really annoying because Lens resets whole terminal tab (process is killed, working directory is different etc).

**Expected behavior**

Lens should keep terminal process running and reconnect to that specific process when computer resumes from sleep (or from offline).

### PR DESCRIPTION
**Pull request by Nokel81**
- Allows long running processes in the lens terminal to servive the
  computer going to sleep

Signed-off-by: Sebastian Malton <sebastian@malton.name>

fixes #4250

### CODE REVIEW

File: src/main/shell-session/shell-session.ts [hunk 1]
```diff
@@ -40,41 +41,140 @@ export class ShellOpenError extends Error {
   }
 }
 
+export enum WebSocketCloseEvent {
```
Comment (jakolehm) [inline src/main/shell-session/shell-session.ts:44]: Not sure if we need all events defined (documented) here because we are just using few of them?

Comment (Nokel81) [reply src/main/shell-session/shell-session.ts:44]: I decided to include all of them so that were could use the name and have some docs for them in our code.

I don't see the point of only including a few of them in an enumeration but if you think it would be better to just document the uses I can revert.

I prefer enums over commented (and especially uncommented) special values.

File: src/main/shell-session/shell-session.ts [hunk 2]
```diff
@@ -40,41 +41,140 @@ export class ShellOpenError extends Error {
...
+
+  constructor(protected websocket: WebSocket, protected cluster: Cluster, terminalId: string) {
     this.kubectl = new Kubectl(cluster.version);
     this.kubeconfigPathP = this.cluster.getProxyKubeconfigPath();
     this.kubectlBinDirP = this.kubectl.binDir();
+    this.terminalId = `${cluster.id}:${terminalId}`;
   }
 
-  protected async open(shell: string, args: string[], env: Record<string, any>) {
+  protected async _open(shell: string, args: string[], env: Record<string, any>) {
```
Comment (jakolehm) [inline src/main/shell-session/shell-session.ts]: Why this is called `_open`?

Comment (Nokel81) [reply src/main/shell-session/shell-session.ts]: I renamed it because it is more of a helper function to the child classes `open()` methods. Since they both don't take any args but this one does. I felt that it made it clearer instead of overloading. 

Maybe I should add some docs to this method.

Comment (jakolehm) [reply src/main/shell-session/shell-session.ts]: Ok, perhaps we could consider other name (like `openShellProcess`) for this helper.

**Review by jakolehm — DISMISSED** [review]

**Review by jakolehm — APPROVED** [review]
