### PR TITLE
TLS cert per cluster for lens-k8s-proxy

### LINKED ISSUE #5042: Connecting to docker-desktop fails authentication
Important: connecting to eg. minikube works just fine.
Edit: Important2: 5.4.3 does not have this problem. Missing hot fix?

**To Reproduce**
1. Go to Catalog -> Clusters -> docker-desktop.
2. Witness crash.

**Expected behavior**
No crash.

**Screenshots**
image

**Environment (please complete the following information):**
- Lens Version: master branch
- OS: MacOs
- Installation method (e.g. snap or AppImage in Linux): make dev

**Logs:**
```[LENS-PROXY]: http proxy errored for cluster: Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: kubernetes.docker.internal. is not in the cert's altnames: DNS:localhost, IP Address:127.0.0.1```

### PR DESCRIPTION
**Pull request by jakolehm**
Fixes #5042

### CODE REVIEW

**Review by Nokel81 — DISMISSED** [review]

File: src/main/kube-auth-proxy/get-kube-auth-proxy-certificate.ts [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+ * Licensed under MIT License. See LICENSE in root directory for more information.
+ */
+
+import type * as selfsigned from "selfsigned";
+
+type SelfSignedGenerate = typeof selfsigned.generate;
+
+const certCache: Map<string, selfsigned.SelfSignedCert> = new Map();
+
+export function getKubeAuthProxyCertificate(hostname: string, generate: SelfSignedGenerate, useCache = true): selfsigned.SelfSignedCert {
```
Comment (jim-docker) [inline src/main/kube-auth-proxy/get-kube-auth-proxy-certificate.ts:12]: `fromCache` might be better name since the cache is always used, in the sense that it is always updated (line 36) when generated (regardless of the value of `useCache`)

**Review by jim-docker — COMMENTED** [review]
@Nokel81 I think you missed updating `src/main/catalog-sources/kubeconfig-sync-manager/kubeconfig-sync-manager.injectable.ts`?

```
ERROR in /Users/jimehrismann/git/lensapp/lens/src/main/catalog-sources/kubeconfig-sync-manager/kubeconfig-sync-manager.injectable.ts
13:49-16:3
[tsl] ERROR in /Users/jimehrismann/git/lensapp/lens/src/main/catalog-sources/kubeconfig-sync-manager/kubeconfig-sync-manager.injectable.ts(13,50)
      TS2345: Argument of type '{ directoryForKubeConfigs: string; createCluster: (model: ClusterModel) => Cluster; }' is not assignable to parameter of type 'Dependencies'.
  Property 'logger' is missing in type '{ directoryForKubeConfigs: string; createCluster: (model: ClusterModel) => Cluster; }' but required in type 'Dependencies'.
```

**Comment by jim-docker** [comment]
I'm seeing "All checks have passed" but there are only 2 checks??

**Review by Nokel81 — APPROVED** [review]

**Review by jim-docker — APPROVED** [review]
