### PR TITLE
Fix: Support metrics for Pods with multiple containers

### LINKED ISSUE #7854: Metrics doesn't work for every container in POD with few containers
**Describe the bug**
After upgrading to new version the metrics are not displayed for each individual container within a pod when there are multiple containers. For PODs with one container there are not issues.

**To Reproduce**
1. Go to Workloads ->PODs-> choose any POD with 2 or more containers
2. Click on it 
3. Scroll down to information about each container `Containers`
4. See error ` Metrics not available at the moment`
5. (Optional) Click on the `memory` and back to `CPU`

**Expected behavior**
CPU/Memory/Filesystem metrics 

**Screenshots**
image

**Environment:**
- Lens Version: lens 2023.5310801-latest
- OS: Latest MacOS + Windows 11
- Installation method (e.g. snap or AppImage in Linux): Download from https://k8slens.dev/

### PR DESCRIPTION
**Pull request by JohnDaly**
Passing the `container` prop from `PodDetailsContainerMetrics` to `podContainerMetricsInjectable` so that we can query for metrics at the `container` level.

Fixes: https://github.com/lensapp/lens/issues/7854

### CODE REVIEW

**Review by Nokel81 — DISMISSED** [review]

File: packages/core/src/renderer/components/workloads-pods/container-metrics.injectable.ts [hunk 1]
```diff
@@ -5,9 +5,14 @@
...
 import requestPodMetricsInjectable from "../../../common/k8s-api/endpoints/metrics.api/request-pod-metrics.injectable";
 
+interface PodContainerParams {
+  pod: Pod;
+  container: Container;
+}
+
 const podContainerMetricsInjectable = getInjectable({
   id: "pod-container-metrics",
   instantiate: (di, pod) => {
```
Comment (JohnDaly) [inline packages/core/src/renderer/components/workloads-pods/container-metrics.injectable.ts]:
```suggestion
  instantiate: (di, { pod, container }) => {
```

**Review by Nokel81 — APPROVED** [review]

**Comment by JohnDaly** [comment]
@Nokel81 I think the failing test might be flaky. Can we try re-running the test?

**Comment by manuasir** [comment]
Can we get this merged, please? Thanks!

**Comment by JohnDaly** [comment]
@Nokel81 Is there anything else we need to do in order to get this merged?
