### PR TITLE
Fix AppImage windows not showing the application icon

### LINKED ISSUE #6443: Task bar icon missing on U22.04 / XFCE
**To Reproduce**
Launch lens on Ubuntu 22.04 under XFCE

**Expected behavior**
I'd expect to see lens' icon :)

~A PR is on it's way.~ PR available #6444

**Screenshots**
Current
image

Expected
image

**Environment (please complete the following information):**
- Lens Version: 6.1.12
- OS: Ubuntu 22.04 amd64 / XFCE
- Installation method (e.g. snap or AppImage in Linux): AppImage

### PR DESCRIPTION
**Pull request by babs**
Fixes #6443, missing task bar icon on some environments (e.g. U22.04 / XFCE)

Might be interesting to use a better quality icon than the tray's one but it's beyond my knowledge

image => image

### CODE REVIEW

**Comment by Nokel81** [comment]
Thanks for this PR. However, it is subtly incorrect because `trayIcon` could be one of several icons (checking for updates, etc...).

Furthermore, I think we would only want to set this on linux (and not on macOS or Windows). I will do some investigation to see how easy this is to accommodate.

**Comment by babs** [comment]
I'm still looking around, i'm following the track of `getAbsolutePath(lensResourcesDir, "../open-lens.png")`
I'll take a look to add the is-linux / is-windows / is-mac.

**Comment by babs** [comment]
Got something, give me a moment :)

**Comment by babs** [comment]
Promising...
image

**Comment by babs** [comment]
ok, @Nokel81, I think it's good:
 * uses the bundled open-lens.png
 * only set on linux version
 * check that the file actually exists (in case of icon name change without notice)

File: src/main/start-main-application/lens-window/application-window/create-electron-window.injectable.ts [hunk 1]
```diff
@@ -79,6 +87,14 @@ const createElectronWindowInjectable = getInjectable({
         },
       });
 
+      if (isLinux) {
+        const iconFileName = getAbsolutePath(lensResourcesDir, "../open-lens.png");
+
+        if (existsSync(iconFileName)) {
+          browserWindow.setIcon(iconFileName);
+        }
```
Comment (Nokel81) [inline src/main/start-main-application/lens-window/application-window/create-electron-window.injectable.ts]: Don't know if this with pass CI...

In any case I think using `pathExistsInjectable` and then having this be

```ts
pathExists(iconFileName)
  .then(iconExists => {
    if (iconExists) {
      browserWindow.setIcon(iconFileName);
    }
  });
```

File: src/main/start-main-application/lens-window/application-window/create-electron-window.injectable.ts [hunk 2]
```diff
@@ -79,6 +87,14 @@ const createElectronWindowInjectable = getInjectable({
         },
       });
 
+      if (isLinux) {
+        const iconFileName = getAbsolutePath(lensResourcesDir, "../open-lens.png");
```
Comment (Nokel81) [inline src/main/start-main-application/lens-window/application-window/create-electron-window.injectable.ts]: This files doesn't exist in the repo, where does it get generated?

File: src/main/start-main-application/lens-window/application-window/create-electron-window.injectable.ts (hunk 1 above)
Comment (babs) [reply src/main/start-main-application/lens-window/application-window/create-electron-window.injectable.ts]: I tried async/promise but in the (unlikely) eventuality of nag screen going away before promise resolution, it might generate an error message but I can encolse it in a try / catch

File: src/main/start-main-application/lens-window/application-window/create-electron-window.injectable.ts (hunk 2 above)
Comment (babs) [reply src/main/start-main-application/lens-window/application-window/create-electron-window.injectable.ts]: good question, I thinks it's generated at build time from a svg ?

image

Comment (Nokel81) [reply src/main/start-main-application/lens-window/application-window/create-electron-window.injectable.ts]: Do you just run `make build`?

Comment (babs) [reply src/main/start-main-application/lens-window/application-window/create-electron-window.injectable.ts]: I did a `make build`, then run the generated dist AppImage

Comment (Nokel81) [reply src/main/start-main-application/lens-window/application-window/create-electron-window.injectable.ts]: Ah I think I understand. You are inside the mount that the AppImage produces.

Comment (babs) [reply src/main/start-main-application/lens-window/application-window/create-electron-window.injectable.ts]: yes, I'm unable to find a "icon asset" injectable :/

File: src/main/start-main-application/lens-window/application-window/create-electron-window.injectable.ts (hunk 1 above)
Comment (babs) [reply src/main/start-main-application/lens-window/application-window/create-electron-window.injectable.ts]: Code is going to be

```node
      if (isLinux) {
        const iconFileName = getAbsolutePath(lensResourcesDir, "../open-lens.png");

        pathExists(iconFileName)
          .then(iconExists => {
            if (iconExists) {
              try {
                browserWindow.setIcon(iconFileName);
              } catch (err) {
                logger.warn(`Error while setting window icon ${err}`);
              }
            }
          });
      }
```

File: src/main/start-main-application/lens-window/application-window/create-electron-window.injectable.ts (hunk 2 above)
Comment (babs) [reply src/main/start-main-application/lens-window/application-window/create-electron-window.injectable.ts]: I can also test `/usr/share/icons/hicolor/512x512/apps/open-lens.png` should be ok on packages versions but not if the file name itself changes (I'm thinking of the commercial edition)

File: src/main/start-main-application/lens-window/application-window/create-electron-window.injectable.ts (hunk 1 above)
Comment (babs) [reply src/main/start-main-application/lens-window/application-window/create-electron-window.injectable.ts]: This part is working. Remains the icon location mystery :)

File: src/main/start-main-application/lens-window/application-window/create-electron-window.injectable.ts (hunk 2 above)
Comment (babs) [reply src/main/start-main-application/lens-window/application-window/create-electron-window.injectable.ts]: `${packager.executableName}` in `./node_modules/app-builder-lib/out/targets/fpm.js`, still digging

Comment (Nokel81) [reply src/main/start-main-application/lens-window/application-window/create-electron-window.injectable.ts]: `const iconFileName = getAbsolutePath(lensResourcesDir, "../open-lens.png");` should be fine.

The only thing that needs to be changed is the file name itself. To get that please do the following:

1. In `src/common/vars/application-information.injectable.ts` change the `ApplicationInformation` type to include the `"name"` field.
2. Add a `name` destructure to fix the type error within that file.
3. Use `applicationInformationInjectable` in `src/main/start-main-application/lens-window/application-window/create-electron-window.injectable.ts` to produce the file name, which should be `../${applicationInformation.name}.png`

Comment (babs) [reply src/main/start-main-application/lens-window/application-window/create-electron-window.injectable.ts]: I have two paths to test and several options:
 - first is to set one icon location based on `process.env["APPIMAGE"] == null`
 - second is to test two paths but I end up with nested promise which is quite inelegant

Any suggestions ?

Comment (babs) [reply src/main/start-main-application/lens-window/application-window/create-electron-window.injectable.ts]: Or I go with `di.inject(fsInjectable).existsSync` ?

Comment (babs) [reply src/main/start-main-application/lens-window/application-window/create-electron-window.injectable.ts]:
```node
        const iconFileName = [
          getAbsolutePath(lensResourcesDir, `../${applicationInformation.name}.png`),
          `/usr/share/icons/hicolor/512x512/apps/${applicationInformation.name}.png`,
        ].find(di.inject(fsInjectable).existsSync);

        if (iconFileName != null) {
          try {
            browserWindow.setIcon(iconFileName);
          } catch (err) {
            logger.warn(`Error while setting window icon ${err}`);
          }
        } else {
          logger.warn(`No suitable icon found for task bar.`);
        }
```
 @Nokel81 what about this one ?

**Comment by babs** [comment]
[80bd3ee](https://github.com/lensapp/lens/pull/6444/commits/80bd3eec7d25af116a57d63664ca7451faa862f4) has been tested with AppImage and deb install

**Comment by babs** [comment]
removed review request is the result of a misclick

File: src/main/start-main-application/lens-window/application-window/create-electron-window.injectable.ts (hunk 2 above)
Comment (Nokel81) [reply src/main/start-main-application/lens-window/application-window/create-electron-window.injectable.ts]: That looks file, I would just add some prefix to the log calls, something like `[ELECTRON-WINDOW]:`

Comment (babs) [reply src/main/start-main-application/lens-window/application-window/create-electron-window.injectable.ts]: Done :)

**Review by Nokel81 — APPROVED** [review]
Let's try CI
