### PR TITLE
Only allow extensions to use non-lens specific cluster phases

### LINKED ISSUE #4035: Entity status phase does not get reset after disconnecting
**Describe the bug**
A connected cluster, when disconnected, does not have its status updated. This is a regression from https://github.com/lensapp/lens/pull/4009

### PR DESCRIPTION
**Pull request by Nokel81**
Signed-off-by: Sebastian Malton <sebastian@malton.name>

fixes #4035

### CODE REVIEW

File: src/common/catalog-entities/kubernetes-cluster.ts [hunk 1]
```diff
@@ -59,13 +59,7 @@ export interface KubernetesClusterMetadata extends CatalogEntityMetadata {
   kubeVersion?: string;
 }
 
-export type KubernetesClusterStatusPhase = "connected" | "connecting" | "disconnected" | "deleting";
-
-export interface KubernetesClusterStatus extends CatalogEntityStatus {
-  phase: KubernetesClusterStatusPhase;
-}
-
-export class KubernetesCluster extends CatalogEntity<KubernetesClusterMetadata, KubernetesClusterStatus, KubernetesClusterSpec> {
```
Comment (Nokel81) [inline src/common/catalog-entities/kubernetes-cluster.ts]: This was done because it is just not true anymore

File: src/main/cluster-manager.ts [hunk 2]
```diff
@@ -27,14 +27,23 @@ import logger from "./logger";
...
 import type { ClusterId } from "../common/cluster-types";
 
 const logPrefix = "[CLUSTER-MANAGER]:";
 
+enum LensClusterStatus {
+  DELETING = "deleting",
+  CONNECTING = "connecting",
+  CONNECTED = "connected",
+  DISCONNECTED = "disconnected"
+}
```
Comment (Nokel81) [inline src/main/cluster-manager.ts]: This should remove at least some instances of special string values, which should be avoided

File: src/main/cluster.ts [hunk 3]
```diff
@@ -405,6 +404,7 @@ export class Cluster implements ClusterModel, ClusterState {
     this.allowedNamespaces = [];
     this.resourceAccessStatuses.clear();
     this.pushState();
+    logger.info(`[CLUSTER]: disconnect`, this.getMeta());
```
Comment (Nokel81) [inline src/main/cluster.ts:407]: This was changed because otherwise the meta values were wrong slightly, they were too old to be useful.

File: src/main/cluster-manager.ts (hunk 2 above)
Comment (ixrock) [reply src/main/cluster-manager.ts]: Why moving status types definition here from `kubernetes-cluster.ts`? 
Isn't it comes purely from k8s/cluster apis? What if we need to re-use this in another module?

**Review by ixrock — DISMISSED** [review]

File: src/main/cluster-manager.ts (hunk 2 above)
Comment (Nokel81) [reply src/main/cluster-manager.ts]: You are right, I should move them back. Not use them as the type but use them all over as a means to reduce spelling errors.

**Review by chenhunghan — DISMISSED** [review]
This looks better, tested in space extension.

**Review by jim-docker — APPROVED** [review]
