### PR TITLE
Fix service account's imagePullSecrets rendering if secret is not found

### LINKED ISSUE #823: TypeError: Cannot read property 'getId' of undefined
**Describe the bug**
Clicking on a service account produces the following error:

```js
TypeError: Cannot read property 'getId' of undefined
    at http://22aa7143-a6de-46c2-bfa3-eded4d2f01f4.localhost:61115/build/Lens.js:2:8165431
    at Array.map (<anonymous>)
    at r.value (http://22aa7143-a6de-46c2-bfa3-eded4d2f01f4.localhost:61115/build/Lens.js:2:8165369)
    at r.value (http://22aa7143-a6de-46c2-bfa3-eded4d2f01f4.localhost:61115/build/Lens.js:2:8166269)
    at ve (http://22aa7143-a6de-46c2-bfa3-eded4d2f01f4.localhost:61115/build/Lens.js:2:33319)
    at http://22aa7143-a6de-46c2-bfa3-eded4d2f01f4.localhost:61115/build/Lens.js:2:13199
    at ce (http://22aa7143-a6de-46c2-bfa3-eded4d2f01f4.localhost:61115/build/Lens.js:2:31425)
    at e.track (http://22aa7143-a6de-46c2-bfa3-eded4d2f01f4.localhost:61115/build/Lens.js:2:42789)
    at r.l [as render] (http://22aa7143-a6de-46c2-bfa3-eded4d2f01f4.localhost:61115/build/Lens.js:2:13147)
    at r.X (http://22aa7143-a6de-46c2-bfa3-eded4d2f01f4.localhost:61115/build/Lens.js:2:13294)
```

This is what gets printed to the console:

```
react-dom.production.min.js:209 TypeError: Cannot read property 'getId' of undefined
    at service-accounts-details.tsx:55
    at Array.map (<anonymous>)
    at r.value (service-accounts-details.tsx:53)
    at r.value (service-accounts-details.tsx:86)
    at ve (mobx.module.js:992)
    at mobxreact.esm.js:299
    at ce (mobx.module.js:775)
    at e.track (mobx.module.js:1809)
    at r.l [as render] (mobxreact.esm.js:297)
    at r.X (mobxreact.esm.js:312)
```

**To Reproduce**
1. Go to Service Accounts
2. Click on any service account
3. See error

**Expected behavior**
Error not to appear

**Environment (please complete the following information):**
- Lens Version: 3.6.0-rc.1
- OS: [e.g. OSX] Windows
- Installation method (e.g. snap or AppImage in Linux): Windows Installer
 
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
info: [IPC]: setup channel "cluster:init"
info: [IPC]: setup channel "cluster:activate"
info: [IPC]: setup channel "cluster:disconnect"
info: [IPC]: setup channel "cluster:install-feature"
info: [IPC]: setup channel "cluster:uninstall-feature"
info: [IPC]: setup channel "cluster:upgrade-feature"
info: ≡ƒÜÇ Starting Lens from "C:\Users\Vilsol\AppData\Roaming\Lens"
info: Checking for update
info: [STORE]: LOADED from C:\Users\Vilsol\AppData\Roaming\Lens\config.json
info: [STORE]: LOADED from C:\Users\Vilsol\AppData\Roaming\Lens\lens-cluster-store.json
info: [STORE]: LOADED from C:\Users\Vilsol\AppData\Roaming\Lens\lens-workspace-store.json
info: [CLUSTER-MANAGER]: init cluster {"id":"*","name":"*","initialized":false}
info: [CLUSTER]: "*" init success {"id":"*","context":"*","apiUrl":"*"}
info: [CLUSTER-MANAGER]: init cluster {"id":"*","name":"minikube","initialized":false}
info: [CLUSTER]: "minikube" init success {"id":"*","context":"minikube","apiUrl":"https://127.0.0.1:32768"}
info: [CLUSTER-MANAGER]: init cluster {"id":"*","name":"*","initialized":false}
info: [CLUSTER]: "*" init success {"id":"*","context":"*","apiUrl":"*"}
info: LensProxy server has started at http://localhost:61115
info: [CLUSTER]: activate {"id":"*","name":"*","initialized":true}
info: [CLUSTER]: bind events {"id":"*","name":"*","initialized":true}
info: [CLUSTER]: reconnect {"id":"*","name":"*","initialized":true}
info: [KUBE-AUTH]: out-channel "kube-auth:*" {"data":"Authentication proxy started\n","meta":{"id":"*","name":"*","initialized":true}}
info: [CLUSTER]: refresh {"id":"*","name":"*","initialized":true,"disconnected":false}
info: Update for version 3.6.0-rc.1 is not available (latest version: 3.6.0-rc.1, downgrade is disallowed).
info: using lens as prometheus provider
info: using lens as prometheus provider
info: [CLUSTER]: refresh {"id":"*","name":"*","initialized":true,"online":true,"accessible":true,"disconnected":false}
info: [CLUSTER]: refresh {"id":"*","name":"*","initialized":true,"online":true,"accessible":true,"disconnected":false}
info: [CLUSTER]: refresh {"id":"*","name":"*","initialized":true,"online":true,"accessible":true,"disconnected":false}
info: [CLUSTER]: refresh {"id":"*","name":"*","initialized":true,"online":true,"accessible":true,"disconnected":false}
```

**Additional context**

Here is the relevant excerpt from the response on `/api-kube/api/v1/serviceaccounts` query:

```json
{
  "kind": "ServiceAccountList",
  "apiVersion": "v1",
  "metadata": {
    "selfLink": "/api/v1/serviceaccounts",
    "resourceVersion": "4282980"
  },
  "items": [
    {
      "metadata": {
        "name": "rbd-csi-nodeplugin",
        "namespace": "default",
        "selfLink": "/api/v1/namespaces/default/serviceaccounts/rbd-csi-nodeplugin",
        "uid": "*",
        "resourceVersion": "965256",
        "creationTimestamp": "2020-08-29T07:24:09Z",
        "annotations": {
          "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"v1\",\"kind\":\"ServiceAccount\",\"metadata\":{\"annotations\":{},\"name\":\"rbd-csi-nodeplugin\",\"namespace\":\"default\"}}\n"
        },
        "managedFields": [
          {
            "manager": "kube-controller-manager",
            "operation": "Update",
            "apiVersion": "v1",
            "time": "2020-08-29T07:24:09Z",
            "fieldsType": "FieldsV1",
            "fieldsV1": {"f:secrets":{".":{},"k:{\"name\":\"rbd-csi-nodeplugin-token-lckkg\"}":{".":{},"f:name":{}}}}
          },
          {
            "manager": "kubectl",
            "operation": "Update",
            "apiVersion": "v1",
            "time": "2020-08-29T07:24:09Z",
            "fieldsType": "FieldsV1",
            "fieldsV1": {"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}}}}
          },
          {
            "manager": "imagepullsecret-patcher",
            "operation": "Update",
            "apiVersion": "v1",
            "time": "2020-08-31T05:31:52Z",
            "fieldsType": "FieldsV1",
            "fieldsV1": {"f:imagePullSecrets":{}}
          }
        ]
      },
      "secrets": [
        {
          "name": "rbd-csi-nodeplugin-token-lckkg"
        }
      ],
      "imagePullSecrets": [
        {
          "name": "image-pull-secret"
        }
      ]
    }
  ]
}
```

Here is the response from `/api-kube/api/v1/namespaces/default/secrets/rbd-csi-nodeplugin-token-lckkg`:

```json
{
  "apiVersion": "v1",
  "data": {
    "ca.crt": "*",
    "namespace": "*",
    "token": "*"
  },
  "kind": "Secret",
  "metadata": {
    "annotations": {
      "kubernetes.io/service-account.name": "rbd-csi-nodeplugin",
      "kubernetes.io/service-account.uid": "446bc750-20b6-4319-beb8-d23257aa48b6"
    },
    "creationTimestamp": "2020-08-29T07:24:09Z",
    "managedFields": [
      {
        "apiVersion": "v1",
        "fieldsType": "FieldsV1",
        "fieldsV1": {
          "f:data": {
            ".": {},
            "f:ca.crt": {},
            "f:namespace": {},
            "f:token": {}
          },
          "f:metadata": {
            "f:annotations": {
              ".": {},
              "f:kubernetes.io/service-account.name": {},
              "f:kubernetes.io/service-account.uid": {}
            }
          },
          "f:type": {}
        },
        "manager": "kube-controller-manager",
        "operation": "Update",
        "time": "2020-08-29T07:24:09Z"
      }
    ],
    "name": "rbd-csi-nodeplugin-token-lckkg",
    "namespace": "default",
    "resourceVersion": "191433",
    "selfLink": "/api/v1/namespaces/default/secrets/rbd-csi-nodeplugin-token-lckkg",
    "uid": "8209cb3d-b8e1-4b37-a8cd-4097e4396914"
  },
  "type": "kubernetes.io/service-account-token"
}
```

### PR DESCRIPTION
**Pull request by nevalla**
This PR fixes service account's imagePullSecrets rendering if the secret does not exist. Now if the imagePullSecret is not found, app will display warning icon with `Secret is not found` as tooltip text beside the value of imagePullSecret.

If the secret is found, app will render link to the secret like before.

Fixes #823
Signed-off-by: Lauri Nevala <lauri.nevala@gmail.com>

### CODE REVIEW

File: src/renderer/components/+user-management-service-accounts/service-accounts-details.tsx [hunk 1]
```diff
@@ -15,28 +15,33 @@ import { getDetailsUrl } from "../../navigation";
...
     const { object: serviceAccount } = this.props;
     if (!serviceAccount) {
       return;
     }
     const namespace = serviceAccount.getNs();
     const secrets = serviceAccount.getSecrets().map(({ name }) => {
-      const secret = secretsStore.getByName(name, namespace);
-      if (!secret) return secretsStore.load({ name, namespace });
-      return secret;
+      return secretsStore.load({ name, namespace });
```
Comment (nevalla) [inline src/renderer/components/+user-management-service-accounts/service-accounts-details.tsx:38]: `secretStore.load` calls `this.getByName(..)` so doing that multiple times is redundant

**Review by Nokel81 — APPROVED** [review]
