### PR TITLE
Automatically sync all kubeConfigPaths

### LINKED ISSUE #3221: Connection to clusters with external kubeconfig files lost after upgrade to 5.0.0
**Describe the bug**
Ability to connect to clusters through external kubeconfig files broken in 5.0.0

**To Reproduce**
1. Dialog displayed offering to upgrade to latest version 5.0.0.  No warning that accepting will lose all connectivity to clusters if using external kubeconfig files.
2. Click to upgrade.
3. After restart with 5.0.0 previous clusters are shown in "hotbar" but saying "unknown".  Clusters can be added but only with copy-paste content (and with warning that clusters will not be merged into .kubeconfig) and not by accessing existing files.
4. %AppData%/Roaming/Lens/lens-cluster-store.json still contains cluster setups with correct "kubeConfigPath", and the kubeconfig file still exists and with correct content.

**Expected behavior**
1. Support for multiple external kubeconfigs should be supported (I don't want or need cloud sync of single kubeconfig file).
2. Failing that at the very least a strong warning that connectivity will be lost should be displayed before upgrade when external kubeconfig files are configured.

**Environment (please complete the following information):**
- Lens Version: now 5.0.0
- OS: Windows
- Installation method (e.g. snap or AppImage in Linux): in-app upgrade from previous version.

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
info: ≡ƒôƒ Setting Lens as protocol client for lens://
info: ≡ƒôƒ Protocol client register succeeded Γ£à
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
n/a - previous configs worked fine in v4.x, current kubeconfigs are not even processed
```

**Additional context**
none, but need access to clusters via lens asap.

### PR DESCRIPTION
**Pull request by Nokel81**
Signed-off-by: Sebastian Malton <sebastian@malton.name>

fixes #3221

### CODE REVIEW

File: src/common/hotbar-store.ts [hunk 1]
```diff
@@ -94,7 +94,7 @@ export class HotbarStore extends BaseStore<HotbarStoreModel> {
   }
 
   @action
-  protected async fromStore(data: Partial<HotbarStoreModel> = {}) {
+  protected fromStore(data: Partial<HotbarStoreModel> = {}) {
```
Comment (Nokel81) [inline src/common/hotbar-store.ts]: These cannot be `async`. See https://github.com/lensapp/lens/pull/3178

File: src/migrations/user-store/5.0.1.ts [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+
+      if (syncPaths.has(cluster.kubeConfigPath) || syncPaths.has(dirOfKubeconfig)) {
+        migrationLog(`Skipping ${cluster.id} because kubeConfigPath is already being synced`);
+        continue;
+      }
+
+      if (!existsSync(cluster.kubeConfigPath)) {
+        migrationLog(`Skipping ${cluster.id} because kubeConfigPath no longer exists`);
+        continue;
+      }
```
Comment (Nokel81) [inline src/migrations/user-store/5.0.1.ts]: I know this is technically a race condition but I think it is better not to confuse users by adding files that don't exist at this point.

File: src/common/hotbar-store.ts (hunk 1 above)
Comment (nevalla) [reply src/common/hotbar-store.ts]: Are we sure this change does not have any side effects?

File: src/common/user-store.ts [hunk 3]
```diff
@@ -206,6 +204,7 @@ export class UserStore extends BaseStore<UserStoreModel> {
     }
 
     if (preferences.syncKubeconfigEntries) {
+      console.log(preferences.syncKubeconfigEntries);
```
Comment (nevalla) [inline src/common/user-store.ts]: debug leftover here?

Comment (aleksfront) [inline src/common/user-store.ts:207]: Forgotten `console.log`

**Comment by aleksfront** [comment]
It works for different kubeconfig paths 🎉 , but migration is started only if app version number is moved to `5.0.1`. Probably tests are failing for the same reason.

**Comment by msa0311** [comment]
@aleksfront mentioned that this branch is causing app crash on startup: https://github.com/lensapp/lens/issues/3242
Please lets make sure this is fixed before merging the PR. @Nokel81

File: src/common/hotbar-store.ts (hunk 1 above)
Comment (Nokel81) [reply src/common/hotbar-store.ts]: This actually fixed the fromStore not working

File: src/migrations/user-store/5.0.1.ts [hunk 4]
```diff
@@ -0,0 +1,66 @@
...
+
+      migrationLog(`Adding ${cluster.kubeConfigPath} from ${cluster.id} to sync paths`);
+      syncPaths.add(cluster.kubeConfigPath);
+    }
+
+    const updatedSyncEntries: KubeconfigSyncEntry[] = [...syncPaths].map(filePath => ({ filePath }));
+
+    migrationLog("Final list of syned paths", updatedSyncEntries);
```
Comment (jim-docker) [inline src/migrations/user-store/5.0.1.ts]:
```suggestion
    migrationLog("Final list of synced paths", updatedSyncEntries);
```

File: src/migrations/user-store/5.0.1.ts [hunk 5]
```diff
@@ -0,0 +1,66 @@
...
+import { MigrationDeclaration, migrationLog } from "../helpers";
+
+export default {
+  version: "5.0.1",
+  run(store) {
+    const { syncKubeconfigEntries = [], ...preferences }: UserPreferencesModel = store.get("preferences") ?? {};
+    const { clusters = [] }: ClusterStoreModel = readJsonSync(path.resolve(app.getPath("userData"), "lens-cluster-store.json"));
+    const syncPaths = new Set(syncKubeconfigEntries.map(s => s.filePath));
+
+    syncPaths.add(path.join(os.homedir(), ".kube"));
```
Comment (jim-docker) [inline src/migrations/user-store/5.0.1.ts]: Does this get executed even for a new install of Lens?

Comment (Nokel81) [reply src/migrations/user-store/5.0.1.ts]: Yes because the file doesn't exist yet

Comment (jim-docker) [reply src/migrations/user-store/5.0.1.ts]: So migrations get run even for a new install? Adding ".kube" to the list of sync'ed paths is "setup" and it seems odd to have it done in a migration (and not easy to find)

Comment (jim-docker) [reply src/migrations/user-store/5.0.1.ts]: In light of #3254 should we just add ".kube/config"? User can manually add ".kube" in that case. But as it is the user cannot remove ".kube" (because it will keep getting added back, right?) Using ".kube" folder to save backups is probably not a typical use case but certainly possible. Could be done in another PR.

Comment (Nokel81) [reply src/migrations/user-store/5.0.1.ts]: That was the intentional design. I would actually choose to close that issue as "working as intended"

File: src/migrations/user-store/5.0.2-beta.1.ts [hunk 6]
```diff
@@ -0,0 +1,66 @@
...
+import { app } from "electron";
+import { existsSync, readJsonSync } from "fs-extra";
+import path from "path";
+import os from "os";
+import { ClusterStore, ClusterStoreModel } from "../../common/cluster-store";
+import type { KubeconfigSyncEntry, UserPreferencesModel } from "../../common/user-store";
+import { MigrationDeclaration, migrationLog } from "../helpers";
+
+export default {
+  version: "5.0.2-beta.1",
```
Comment (jakolehm) [inline src/migrations/user-store/5.0.2-beta.1.ts]:
```suggestion
  version: "5.0.3-beta.1",
```

File: package.json [hunk 7]
```diff
@@ -3,7 +3,7 @@
   "productName": "OpenLens",
   "description": "OpenLens - Open Source IDE for Kubernetes",
   "homepage": "https://github.com/lensapp/lens",
-  "version": "5.0.2",
+  "version": "5.0.2-beta.1",
```
Comment (jakolehm) [inline package.json]:
```suggestion
  "version": "5.0.3-beta.1",
```

File: src/migrations/user-store/5.0.3-beta.1.ts [hunk 8]
```diff
@@ -0,0 +1,66 @@
...
+
+    for (const cluster of clusters) {
+      const dirOfKubeconfig = path.dirname(cluster.kubeConfigPath);
+
+      if (dirOfKubeconfig === ClusterStore.storedKubeConfigFolder) {
+        migrationLog(`Skipping ${cluster.id} because kubeConfigPath is under ClusterStore.storedKubeConfigFolder`);
+        continue;
+      }
+
+      if (syncPaths.has(cluster.kubeConfigPath) || syncPaths.has(dirOfKubeconfig)) {
```
Comment (jakolehm) [inline src/migrations/user-store/5.0.3-beta.1.ts]: Should this check include if any parent dir is already in `syncPaths`?

Comment (Nokel81) [reply src/migrations/user-store/5.0.3-beta.1.ts]: No because we only sync shallowly. See https://github.com/lensapp/lens/blob/master/src/main/catalog-sources/kubeconfig-sync.ts#L265

File: src/migrations/user-store/5.0.1.ts (hunk 5 above)
Comment (Nokel81) [reply src/migrations/user-store/5.0.1.ts]: FYI this migration will only happen once. So once this migration happens a user will be able to remove `~/.kube` to their hearts desire.

File: src/migrations/hotbar-store/5.0.0-beta.10.ts [hunk 9]
```diff
@@ -148,8 +148,8 @@ export default {
 
       store.set("hotbars", hotbars);
     } catch (error) {
-      if (!(error.code === "ENOENT" && error.path.endsWith("lens-workspace-store.json"))) {
-        // ignore lens-workspace-store.json being missing
+      if (error.code !== "ENOENT") {
+        // ignore files being missing
```
Comment (jim-docker) [inline src/migrations/hotbar-store/5.0.0-beta.10.ts:152]: (old) nit: this comment is about not entering the if statement

File: src/migrations/user-store/5.0.3-beta.1.ts [hunk 10]
```diff
@@ -0,0 +1,75 @@
...
+          continue;
+        }
+
+        if (!existsSync(cluster.kubeConfigPath)) {
+          migrationLog(`Skipping ${cluster.id} because kubeConfigPath no longer exists`);
+          continue;
+        }
+
+        migrationLog(`Adding ${cluster.kubeConfigPath} from ${cluster.id} to sync paths`);
+        syncPaths.add(cluster.kubeConfigPath);
```
Comment (jim-docker) [inline src/migrations/user-store/5.0.3-beta.1.ts:59]: can a file get added here and then subsequently the file's dir is added, and then the file should be removed (since it is covered by the dir)?

**Review by jim-docker — APPROVED** [review]

File: src/migrations/user-store/5.0.3-beta.1.ts (hunk 10 above)
Comment (Nokel81) [reply src/migrations/user-store/5.0.3-beta.1.ts:59]: No because we never add `dirOfKubeconfig`

File: src/migrations/hotbar-store/5.0.0-beta.10.ts (hunk 9 above)
Comment (Nokel81) [reply src/migrations/hotbar-store/5.0.0-beta.10.ts:152]: I fix that in a follow up PR.

File: src/migrations/user-store/5.0.3-beta.1.ts [hunk 11]
```diff
@@ -0,0 +1,75 @@
...
+  version: "5.0.3-beta.1",
+  run(store) {
+    try {
+      const { syncKubeconfigEntries = [], ...preferences }: UserPreferencesModel = store.get("preferences") ?? {};
+      const { clusters = [] }: ClusterStoreModel = readJsonSync(path.resolve(app.getPath("userData"), "lens-cluster-store.json")) ?? {};
+      const syncPaths = new Set(syncKubeconfigEntries.map(s => s.filePath));
+
+      syncPaths.add(path.join(os.homedir(), ".kube"));
+
+      for (const cluster of clusters) {
```
Comment (jakolehm) [inline src/migrations/user-store/5.0.3-beta.1.ts:40]: We should only loop through local clusters. Looping through all clusters will have nasty side-effect -> it adds extension generated kubeconfigs as kubeconfig watch paths.
