### PR TITLE
Fix jsonPath functions

### LINKED ISSUE #6527: Custom resource with a / in the field name
I have a custom resource that often uses a / in the field name. Lens throws an error when I try to view this resource. The troublesome YAML in the custom resource is:

```
status:
  summary/status:
    exposedAPISummary: Complete
```

The Error stack in Lens shows:

```
Error stack:

Error: Lexical error on line 1. Unrecognized text.
$.status.summary/status.exposedAPIsu
----------------^
    at Parser.parseError (http://1fc53dcf36c51058a081ab94a3f11f9a.localhost:62981/build/Lens.js?a14a85334ce4a9e9c4a8:3567:21)
    at Parser.parser.yy.parseError (http://1fc53dcf36c51058a081ab94a3f11f9a.localhost:62981/build/Lens.js?a14a85334ce4a9e9c4a8:3186:21)
    at Object.parseError (http://1fc53dcf36c51058a081ab94a3f11f9a.localhost:62981/build/Lens.js?a14a85334ce4a9e9c4a8:3751:28)
    at Object.next (http://1fc53dcf36c51058a081ab94a3f11f9a.localhost:62981/build/Lens.js?a14a85334ce4a9e9c4a8:4006:25)
    at Object.lex (http://1fc53dcf36c51058a081ab94a3f11f9a.localhost:62981/build/Lens.js?a14a85334ce4a9e9c4a8:4016:22)
    at lex (http://1fc53dcf36c51058a081ab94a3f11f9a.localhost:62981/build/Lens.js?a14a85334ce4a9e9c4a8:3604:27)
    at Parser.parse (http://1fc53dcf36c51058a081ab94a3f11f9a.localhost:62981/build/Lens.js?a14a85334ce4a9e9c4a8:3617:26)
    at JSONPath.nodes (http://1fc53dcf36c51058a081ab94a3f11f9a.localhost:62981/build/Lens.js?a14a85334ce4a9e9c4a8:3292:33)
    at JSONPath.query (http://1fc53dcf36c51058a081ab94a3f11f9a.localhost:62981/build/Lens.js?a14a85334ce4a9e9c4a8:3276:28)
    at http://1fc53dcf36c51058a081ab94a3f11f9a.localhost:62981/build/Lens.js?a14a85334ce4a9e9c4a8:559569:175
```

### PR DESCRIPTION
**Pull request by Nokel81**
- Add handling of / shorthand
- Update tests to show new behaviour of safeJSONPathValue so that it is more usable

Signed-off-by: Sebastian Malton <sebastian@malton.name>

### CODE REVIEW

File: src/renderer/components/+custom-resources/crd-resource-details.tsx [hunk 1]
```diff
@@ -15,11 +15,10 @@ import { KubeObjectMeta } from "../kube-object-meta";
 import { Input } from "../input";
 import type { AdditionalPrinterColumnsV1 } from "../../../common/k8s-api/endpoints/custom-resource-definition.api";
 import { CustomResourceDefinition } from "../../../common/k8s-api/endpoints/custom-resource-definition.api";
-import { convertKubectlJsonPathToNodeJsonPath } from "../../utils/jsonPath";
+import { safeJSONPathValue } from "../../utils/jsonPath";
 import type { KubeObjectMetadata, KubeObjectStatus } from "../../../common/k8s-api/kube-object";
 import { KubeObject } from "../../../common/k8s-api/kube-object";
 import logger from "../../../common/logger";
-import { JSONPath } from "@astronautlabs/jsonpath";
```
Comment (Iku-turso) [inline src/renderer/components/+custom-resources/crd-resource-details.tsx:22]: Can this dependency be removed from package.json as well?

**Review by Iku-turso — APPROVED** [review]

File: src/renderer/components/+custom-resources/crd-resource-details.tsx (hunk 1 above)
Comment (Nokel81) [reply src/renderer/components/+custom-resources/crd-resource-details.tsx:22]: No, because it is still being used https://github.com/lensapp/lens/pull/6530/files#diff-165d77f8a773439c161bd8259ce449213d2890c41cea52516c68b00f0a1a82f1L6-L7
