### PR TITLE
Fix shell-env timeout

### LINKED ISSUE #2764: Stuck in Syncing shell environment
**Describe the bug**
No window appears

**To Reproduce**
for view where the app stuck i have used the following command `gnome-terminal -- /bin/bash -c '/snap/bin/kontena-lens'`

**Screenshots**
```
info: 📟 Setting Lens as protocol client for lens://
info: 📟 failed ❗
info: 🚀 Starting Lens from "/home/lop/snap/kontena-lens/179/.config/Lens"
info: 🐚 Syncing shell environment
```

**Environment (please complete the following information):**
- Lens Version: 4.2.2
- OS: Ubuntu 20.04
- Installation method: snap

**Additional context**
if you run CTRL+c the following error appears:
```
^Cerror: shellEnv: TypeError: Cannot read property 'split' of undefined
```
the application proceed and the window appears

### PR DESCRIPTION
**Pull request by jim-docker**
fixes #2764

### CODE REVIEW

File: src/main/utils/shell-env.ts [hunk 1]
```diff
@@ -0,0 +1,67 @@
+import execa from "execa";
```
Comment (jim-docker) [inline src/main/utils/shell-env.ts]: This file is a copy of https://www.npmjs.com/package/shell-env, converted to typescript and added a timeout parameter

**Comment by jakolehm** [comment]
@jim-docker what if we just mark "shell env" as "invalid" during boot and skip shell-env within terminal if we see an invalid shell?

File: src/main/utils/shell-env.ts [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+          reject(new Error("Resolving shell environment is taking very long. Please review your shell configuration."));
+        }, timeout))
+      ]);
+    } catch (error) {
+      logger.error(`shellEnv: ${error}`);
+      shellSyncFailed = true;
+    }
+  } else {
+    logger.error("shellSync(): Resolving shell environment took too long. Please review your shell configuration.");
+  }
```
Comment (Nokel81) [inline src/main/utils/shell-env.ts:63]: @jakolehm is this line skipping on subsequent calls?

File: src/main/utils/shell-env.ts [hunk 3]
```diff
@@ -31,14 +31,20 @@ let shellSyncFailed = false;
...
-      ]);
+      if (timeout > 0 ) {
+        envVars = await Promise.race([
+          shellEnvironment(shell),
+          new Promise((_resolve, reject) => setTimeout(() => {
+            reject(new Error("Resolving shell environment is taking very long. Please review your shell configuration."));
+          }, timeout))
+        ]);
+      } else {
+        envVars = await shellEnvironment(shell);
```
Comment (Nokel81) [inline src/main/utils/shell-env.ts]: Why would we want to not timeout?

Comment (jim-docker) [reply src/main/utils/shell-env.ts]: To provide generic behaviour? (it is how we were using it before--the `shell-env` package does not support a timeout). Otherwise we need to force a minimum timeout. Or we could make `shellEnv()` less generic, just hard-code it with a 5s timeout.

Comment (Nokel81) [reply src/main/utils/shell-env.ts]: Why do we need to force a minimum timeout? The above code handles the 0s timeout excellently (it will always fail).

Comment (jim-docker) [reply src/main/utils/shell-env.ts]: How is that useful?

Comment (Nokel81) [reply src/main/utils/shell-env.ts]: Safer I would argue. Since you would have to explicitly pass in `Number.PositiveInfinity`

File: src/main/utils/shell-env.ts (hunk 2 above)
Comment (jakolehm) [reply src/main/utils/shell-env.ts:63]: I don't understand this question 🤔

File: src/main/utils/shell-env.ts (hunk 3 above)
Comment (jakolehm) [reply src/main/utils/shell-env.ts]: I think we want always timeout... but if first call does timeout we should have a way to try again.

Comment (jim-docker) [reply src/main/utils/shell-env.ts]: I thought the user would have to restart lens to try the shell sync again. This is what I do with vs code when the shell sync time out, though maybe I missed a way to do it without restarting.

Comment (jim-docker) [reply src/main/utils/shell-env.ts]: > Safer I would argue. Since you would have to explicitly pass in `Number.PositiveInfinity`

But it is unnecessary to create a timer in this case. The timer would never get cleared, if the `shellEnv` function blocked

Comment (jim-docker) [reply src/main/utils/shell-env.ts]: nvm, we always want to timeout

File: src/main/utils/shell-env.ts (hunk 2 above)
Comment (Nokel81) [reply src/main/utils/shell-env.ts:63]: It was in response to this comment made by you:

> @jim-docker what if we just mark "shell env" as "invalid" during boot and skip shell-env within terminal if we see an invalid shell?

**Review by Nokel81 — APPROVED** [review]
