### PR TITLE
Fix open-lens package missing fonts

### LINKED ISSUE #7008: Editor and terminal fonts not loaded properly in 6.4.0
broken monaco fonts

To reproduce open terminal or any of the monaco editor instances.

### PR DESCRIPTION
**Pull request by jakolehm**
Fixes #7008

### CODE REVIEW

**Review by ixrock — APPROVED** [review]

File: packages/open-lens/webpack/renderer.ts [hunk 1]
```diff
@@ -113,6 +114,15 @@
       filename: "[name].css",
     }),
 
+    new CopyPlugin({
+      patterns: [
+        {
+          from: "node_modules/@k8slens/core/static/build/library/*.ttf",
+          to: "[name][ext]",
```
Comment (ixrock) [inline packages/open-lens/webpack/renderer.ts:121]: _nit:_
```suggestion
          to: "fonts/[name][ext]",
```

Comment (jakolehm) [reply packages/open-lens/webpack/renderer.ts:121]: I would love to put them under `fonts/` but it means that `core` package also should have fonts under `fonts/`. I will leave this to follow up PRs.
