### PR TITLE
Parse jsonPath expressions

### LINKED ISSUE #503: Crash on CRD "revision" of Knative
**Describe the bug**
Can't display Knative "revision" resources

**To Reproduce**
1. [Install](https://knative.dev/docs/install/any-kubernetes-cluster/) knative
2. Click on "Custom Resources" => "serving.knative.dev" => "Revision"

**Expected behavior**
It should display all revisions

**Screenshots**

image

**Environment (please complete the following information):**
- Lens Version: 3.5.0
 
**Logs:**
```
Error stack:

 
Error: Lexical error on line 1. Unrecognized text.
metadata.labels['serving\.knative\.d
----------------^
    at Parser.parseError (webpack-internal:///105:3928:15)
    at Parser.parser.yy.parseError (webpack-internal:///105:5128:17)
    at Object.parseError (webpack-internal:///105:4103:28)
    at Object.next (webpack-internal:///105:4357:25)
    at Object.lex (webpack-internal:///105:4367:22)
    at lex (webpack-internal:///105:3956:28)
    at Parser.parse (webpack-internal:///105:3969:26)
    at JSONPath.nodes (webpack-internal:///105:4982:26)
    at JSONPath.query (webpack-internal:///105:4958:22)
    at eval (webpack-internal:///993:15901:39)
```

### LINKED ISSUE #1773: An error occurs when loading list of specific custom resources
**Describe the bug**
An error occurs when loading list of specific custom resources. The issue appears to be caused by the improper parsing of namespaced labels.  This issue was reported in issue #369, but it doesn't appear to have ever been resolved.

**Screenshots**
81794044-c1c96880-953c-11ea-945f-b1e6f7996e0b

**Environment (please complete the following information):**
- Lens Version: 4.0.2
- OS: MacOS 11

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Error: Lexical error on line 1. Unrecognized text.
...ta.labels.kubesphere\.io/workspace
-----------------------^
    at Parser.parseError (webpack-internal:///105:3928:15)
    at Parser.parser.yy.parseError (webpack-internal:///105:5128:17)
    at Object.parseError (webpack-internal:///105:4103:28)
    at Object.next (webpack-internal:///105:4357:25)
    at Object.lex (webpack-internal:///105:4367:22)
    at lex (webpack-internal:///105:3956:28)
    at Parser.parse (webpack-internal:///105:3969:26)
    at JSONPath.nodes (webpack-internal:///105:4982:26)
    at JSONPath.query (webpack-internal:///105:4958:22)
    at eval (webpack-internal:///990:13303:39)```

![81794044-c1c96880-953c-11ea-945f-b1e6f7996e0b](https://user-images.githubusercontent.com/7546084/102090357-3cf44500-3dd2-11eb-8666-dd3459cd3d8d.png)

### PR DESCRIPTION
**Pull request by nevalla**
`jsonPath.value()` method does not work well with invalid-indentifier names, so changed these to use indexed notation as suggested [here](https://github.com/dchester/jsonpath/issues/102#issuecomment-422987669). Also required to get rid of `\` characters.

Fixes #503, fixes #1773

Signed-off-by: Lauri Nevala <lauri.nevala@gmail.com>

### CODE REVIEW

File: src/renderer/components/+custom-resources/crd-resources.tsx [hunk 1]
```diff
@@ -91,10 +92,15 @@ export class CrdResources extends React.Component<Props> {
...
-          })),
+          ...extraColumns.map((column) => {
+            const pathExpression = parseJsonPath(column.jsonPath.slice(1));
+
+            return {
+              renderBoolean: true,
+              children: jsonPath.value(crdInstance, pathExpression),
+            };
+          }
+          ),
```
Comment (Nokel81) [inline src/renderer/components/+custom-resources/crd-resources.tsx]:
```suggestion
          ...extraColumns.map(column => ({
            renderBoolean: true,
            children: parseJsonPath(
              jsonPath.value(crdInstance, column.jsonPath.slice(1))
            ),
          })),
```

File: src/renderer/utils/__tests__/jsonPath.test.tsx [hunk 2]
```diff
@@ -0,0 +1,22 @@
+import { parseJsonPath } from "../jsonPath";
+
+describe("parseJsonPath", () => {
+  test("should convert \. to use indexed notation", () => {
+    const res = parseJsonPath(".metadata.labels.kubesphere\\.io/alias-name");
+
+    expect(res).toBe(".metadata['labels']['kubesphere.io/alias-name']");
```
Comment (Nokel81) [inline src/renderer/utils/__tests__/jsonPath.test.tsx]: It seems weird that `labels` would be also converted to indexed notation, I guess it doesn't matter much but the test name implies something else.

File: src/renderer/utils/jsonPath.ts [hunk 3]
```diff
@@ -0,0 +1,21 @@
...
+    // for example: .metadata.labels.kubesphere\.io/alias-name -> .metadata['labels']['kubesphere\.io/alias-name']
+    const columnArr = jsonPath.split(/(?<=\w)\./);
+
+    columnArr.forEach((value, index) => {
+      if (index == 0) {
+        pathExpression = `${value}`;
+      } else {
+        pathExpression += `['${value}']`;
+      }
+    });
```
Comment (Nokel81) [inline src/renderer/utils/jsonPath.ts]:
```suggestion
    const [first, ...rest] = jsonPath.split(/(?<=\w)\./);
    if (rest.length === 0) {
        pathExpression = first;
    }
    
    pathExpression = `${first}${rest.map(value => `[${value}]`)}`;
```

File: src/renderer/utils/__tests__/jsonPath.test.tsx [hunk 4]
```diff
@@ -0,0 +1,22 @@
...
+
+  });
+
+  test("strips '\' away from the result", () => {
+    const res = parseJsonPath(".metadata.labels['serving\\.knative\\.dev/configuration']");
+
+    expect(res).toBe(".metadata.labels['serving.knative.dev/configuration']");
+  });
+
```
Comment (Nokel81) [inline src/renderer/utils/__tests__/jsonPath.test.tsx]: there should be a test for the following case: `".metadata.labels\.serving['some.other.item']"`

**Review by Nokel81 — CHANGES_REQUESTED** [review]

File: src/renderer/utils/__tests__/jsonPath.test.tsx (hunk 2 above)
Comment (nevalla) [reply src/renderer/utils/__tests__/jsonPath.test.tsx]: Fixed it now, so that only those keys which have illegal characters are converted

File: src/renderer/utils/__tests__/jsonPath.test.tsx (hunk 4 above)
Comment (nevalla) [reply src/renderer/utils/__tests__/jsonPath.test.tsx]: Added test case for this

File: src/renderer/components/+custom-resources/crd-resources.tsx (hunk 1 above)
Comment (nevalla) [reply src/renderer/components/+custom-resources/crd-resources.tsx]: parseJsonPath must be done before calling `jsonPath.value` because that is the call that is throwing error. Changed my implementation to one-liner.

File: src/renderer/utils/jsonPath.ts [hunk 5]
```diff
@@ -0,0 +1,35 @@
+// Helper to convert strings used for jsonPath where \. or - is present to use indexed notation,
+// for example: .metadata.labels.kubesphere\.io/alias-name -> .metadata.labels['kubesphere\.io/alias-name']
```
Comment (Nokel81) [inline src/renderer/utils/jsonPath.ts:2]:
```suggestion
// for example: .metadata.labels.kubesphere\.io/alias-name -> .metadata.labels['kubesphere.io/alias-name']
```

File: src/renderer/utils/__tests__/jsonPath.test.tsx [hunk 6]
```diff
@@ -0,0 +1,35 @@
+import { parseJsonPath } from "../jsonPath";
+
+describe("parseJsonPath", () => {
```
Comment (Nokel81) [inline src/renderer/utils/__tests__/jsonPath.test.tsx:3]: some more test cases that I have thought of:

1. Include one with `\\\` signifying an escaped '\' or something similar.
2. perhaps escaping other characters too, like `\'` (which might break your index conversion)

**Review by Nokel81 — COMMENTED** [review]
Looks good, I thought about the requirement to convert other "escaped" characters

**Review by Nokel81 — APPROVED** [review]

**Review by jakolehm — APPROVED** [review]
