### PR TITLE
Fix ResourceQuotaDetails quotas display bugs

### LINKED ISSUE #5892: Resource quota details odities
The quotas are displayed as progress bars of sorts (but display full if 0 is used)
Screen Shot 2022-07-25 at 3 11 46 PM

### PR DESCRIPTION
**Pull request by Nokel81**
Signed-off-by: Sebastian Malton <sebastian@malton.name>

fixes https://github.com/lensapp/lens/issues/5892

### CODE REVIEW

**Comment by jim-docker** [comment]
Nice, it actually works now. But, perhaps unrelated, is this right?

Screen Shot 2022-07-28 at 5 29 51 PM

cpu is `500m / 1k`? Isn't that 0.05% not 50%? Used the Resource Quotas example from https://kubernetes.io/docs/concepts/policy/resource-quotas/#:~:text=apiVersion%3A%20v1,%22low%22%5D (the above png shows the pods-high resource quota, which has `hard.cpu = "1000"`

**Comment by Nokel81** [comment]
I have now also fixed what @jim-docker found, 

here is a screenshot:

Screen Shot 2022-07-29 at 3 38 08 PM

File: src/common/utils/convertCpu.ts [hunk 1]
```diff
@@ -3,18 +3,36 @@
...
+  }
 
-export function cpuUnitsToNumber(cpu: string) {
-  const cpuNum = parseInt(cpu);
+  const { digits, unit } = match;
+  const convertion = unitConverters.get(unit);
 
-  if (cpu.includes("m")) return cpuNum / thousand;
-  if (cpu.includes("u")) return cpuNum / million;
-  if (cpu.includes("n")) return cpuNum / shortBillion;
```
Comment (jim-docker) [inline src/common/utils/convertCpu.ts:17]: Could `u` and `n` be from an older kube version? Could keep them around just to be safe?

File: src/common/utils/convertCpu.ts [hunk 2]
```diff
@@ -3,18 +3,36 @@
...
+  const match = cpuUnitsRegex.captures(value);
+
+  if (!match) {
+    return undefined;
+  }
 
-export function cpuUnitsToNumber(cpu: string) {
-  const cpuNum = parseInt(cpu);
+  const { digits, unit } = match;
+  const convertion = unitConverters.get(unit);
```
Comment (jim-docker) [inline src/common/utils/convertCpu.ts]: nit
```suggestion
  const conversion = unitConverters.get(unit);
```

File: src/renderer/components/+config-resource-quotas/resource-quota-details.tsx [hunk 3]
```diff
@@ -53,7 +67,7 @@ function renderQuotas(quota: ResourceQuota): JSX.Element[] {
             value={current}
             tooltip={(
               <p>
-                {`Set: ${rawMax}. Usage: ${usage}%`}
+                {`Set: ${rawMax}. Usage: ${+usage.toFixed(2)}%`}
```
Comment (jim-docker) [inline src/renderer/components/+config-resource-quotas/resource-quota-details.tsx:70]: Is this better? It will show 100 as 100.00? I guess otherwise anything under 1 will show as 1?

Comment (Nokel81) [reply src/renderer/components/+config-resource-quotas/resource-quota-details.tsx:70]: So this will show `100` as `100` but will correctly show `0.05` as `0.05` instead of what it currently does which is `1`

File: src/common/utils/convertCpu.ts (hunk 1 above)
Comment (Nokel81) [reply src/common/utils/convertCpu.ts:17]: Sure

File: src/common/utils/convertCpu.ts [hunk 4]
```diff
@@ -3,18 +3,38 @@
...
 
-  if (cpu.includes("m")) return cpuNum / thousand;
-  if (cpu.includes("u")) return cpuNum / million;
-  if (cpu.includes("n")) return cpuNum / shortBillion;
+  if (conversion === undefined) {
+    return undefined;
+  }
 
-  return parseFloat(cpu);
+  return parseInt(digits) * conversion;
```
Comment (jim-docker) [inline src/common/utils/convertCpu.ts]: Oh, couldn't the number be a float? You can have 0.5 for cpu, no? https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#meaning-of-cpu:~:text=Fractional%20requests%20are%20allowed

Comment (Nokel81) [reply src/common/utils/convertCpu.ts]: Maybe, but having tried it kubernetes seems to convert a YML file with `0.5` for the CPU into `500m`

**Review by ixrock — DISMISSED** [review]

File: src/common/utils/convertCpu.ts (hunk 4 above)
Comment (Nokel81) [reply src/common/utils/convertCpu.ts]: Yes parsing float would probably be better. Will change.

**Review by jim-docker — APPROVED** [review]
