### PR TITLE
Wait for shell to bring up prompt before sending commands

### LINKED ISSUE #3279: Draining a node opens a terminal but no command is sent
**Describe the bug**
In the Nodes tab of a cluster, when I click the breadcrumbs/3dots next to a node and select "Drain" a new terminal opens, but no command gets sent to that terminal from lens, which means that effectively nothing happens.

**To Reproduce**
1. Go to Nodes tab in a cluster
2. (Optional, works as expected) On a node select the breadcrumbs/3 dots to the far right, and click cordon
3. On a node select the breadcrumbs/3 dots to the far right, and click drain
4. New but empty terminal opens in lens, without a command being sent to that terminal by lens

**Expected behavior**
New terminal opens and a command gets sent, eg `kubectl drain <node>` similar to how Cordon sends `kubectl cordon <node>`.

**Environment (please complete the following information):**
- Lens Version: doesnt work in 5.0.0-latest.20210629.3, 5.0.2-latest.20210705.2
- OS: OSX
- Installation method (e.g. snap or AppImage in Linux): downloaded .dmg from website

### PR DESCRIPTION
**Pull request by Nokel81**
Signed-off-by: Sebastian Malton <sebastian@malton.name>

fixes https://github.com/lensapp/lens/issues/3279

### CODE REVIEW

File: src/renderer/api/terminal-api.ts [hunk 1]
```diff
@@ -55,42 +57,43 @@ export class TerminalApi extends WebSocketApi {
...
 
-    return `${wss}${hostname}${port}/api?${stringify(query)}`;
+    this.url = url.format({
+      protocol: protocol.includes("https") ? "wss" : "ws",
+      hostname,
+      port,
+      pathname: "/api",
+      query,
+      slashes: true,
+    });
```
Comment (Nokel81) [inline src/renderer/api/terminal-api.ts:89]: This was done because `getUrl()` both doesn't need to be `async` and because it should never change, so we might as well only do the work once.

File: src/renderer/api/terminal-api.ts [hunk 2]
```diff
@@ -106,6 +109,17 @@ export class TerminalApi extends WebSocketApi {
     this.onReady.removeAllListeners();
   }
 
+  _onRcReady = (data: string) => {
+    if (!data) {
+      return;
+    }
+
+    if (data.match(/\r?\n/) === null && data.endsWith(" ")) {
```
Comment (Nokel81) [inline src/renderer/api/terminal-api.ts]: This is the most finicky part, basically I assume that all prompts will have a space and be only a single line.

File: src/renderer/api/terminal-api.ts [hunk 3]
```diff
@@ -55,42 +57,43 @@ export class TerminalApi extends WebSocketApi {
...
 
-  async connect() {
-    const apiUrl = await this.getUrl();
-
+  connect() {
     this.emitStatus("Connecting ...");
     this.onData.addListener(this._onReady, { prepend: true });
-
-    return super.connect(apiUrl);
+    this.onData.addListener(this._onRcReady);
```
Comment (aleksfront) [inline src/renderer/api/terminal-api.ts]: Can you make names like `_onRcReady`, `rcIsFinished` more self-explanatory? What is RC here and why we're firing it after on `onData`?

File: src/renderer/api/terminal-api.ts (hunk 2 above)
Comment (aleksfront) [reply src/renderer/api/terminal-api.ts]: Need an explanation what are we doing here. Probably by moving to separate function with explanatory name or just by writing a comment.

File: src/renderer/components/dock/terminal.store.ts [hunk 4]
```diff
@@ -104,18 +105,42 @@ export class TerminalStore extends Singleton {
...
+        Notifications.info("Terminal shell is taking a long time to complete startup. Please check your .rc file.", {
+          timeout: 4_000,
+        });
+      }, 2_500);
+      const notifyVeryLong = setTimeout(() => {
+        rcIsFinished.cancel();
+        Notifications.info("Bypassing shell completion check.", {
+          timeout: 4_000,
+        });
+      }, 7_500);
```
Comment (aleksfront) [inline src/renderer/components/dock/terminal.store.ts]: Seems like between 2 timeouts just 5 seconds of difference. Maybe worth combine those 2 notifications into 1?

File: src/renderer/api/terminal-api.ts (hunk 2 above)
Comment (Nokel81) [reply src/renderer/api/terminal-api.ts]: Sounds good, will do both.

File: src/renderer/components/dock/terminal.store.ts (hunk 4 above)
Comment (Nokel81) [reply src/renderer/components/dock/terminal.store.ts]: Sounds good.

File: src/renderer/api/terminal-api.ts (hunk 3 above)
Comment (Nokel81) [reply src/renderer/api/terminal-api.ts]: How about with the name `_onShellRunCommandsFinished` and `shellRunCommandsFinished`?

**Review by aleksfront — APPROVED** [review]
