### PR TITLE
use the Kubernetes regex for matching system names

### LINKED ISSUE #584: Error during creation of Kubernetes secret
**Describe the bug**
When creating a secret in a kubernetes cluster, if you have a period in the secret name, the following error appears beneath the Name field:
```This field must contain only lowercase latin characters, numbers and dash.```

When I create the secret using the  kubectl command, it successfully creates the secret with the period in the secret name.  Here is the regex used by kubectl to determine a valid secret name 
```a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')```

**To Reproduce**
1. Go to your cluster
2. Expand Configuration in the left menu
3. Click on 'Secrets'
4. Click on the Plus icon in the lower right corner of the window
5. Enter the text `test.dat` in the **SECRET NAME** field
6. See error below the **SECRET NAME** field

**Expected behavior**
Secret naming validation should use Kubernetes validation regex.

**Environment (please complete the following information):**
- Lens Version: 3.5.1s
- OS: OSX 10.15.5 (19F101)
- Installation method (e.g. snap or AppImage in Linux): downloaded dmg file from github
 
**Additional context**
Kubernetes version:
```Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-26T06:16:15Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

### PR DESCRIPTION
**Pull request by Nokel81**
Signed-off-by: Sebastian Malton <smalton@mirantis.com>

This PR also adds some tests for input validators.

Fixes #584

### CODE REVIEW

File: src/renderer/components/input/input.validators.ts [hunk 1]
```diff
@@ -53,9 +53,10 @@ export const maxLength: Validator = {
   validate: (value, { maxLength }) => value.length <= maxLength,
 };
 
+const systemNameMatcher = /^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$/;
 export const systemName: Validator = {
-  message: () => _i18n._(t`This field must contain only lowercase latin characters, numbers and dash.`),
-  validate: value => !!value.match(/^[a-z0-9-]+$/),
+  message: () => _i18n._(t`A System Name must be lowercase DNS labels seperated by dots. DNS labels are alphanumerics and dashes enclosed by alphanumerics.`),
```
Comment (jim-docker) [inline src/renderer/components/input/input.validators.ts]: separated

**Review by jim-docker — APPROVED** [review]
