### PR TITLE
Fix resource links on Release details

### LINKED ISSUE #3120: Selecting resource from Helm released details fails with 404
**Describe the bug**
When selecting resource from Helm release details pane fails

**To Reproduce**
1. Go to Release details
2. Click on some resource
3. See error

**Expected behavior**
Selected resource details should open

**Screenshots**
image

**Environment (please complete the following information):**
- Lens Version: 5.0.0-beta.9

### PR DESCRIPTION
**Pull request by nevalla**
It turned out that `item.metadata.selfLink` is not present so we need to resolve api different way.

Fixes #3120

### CODE REVIEW

File: src/renderer/components/+apps-releases/release-details.tsx [hunk 1]
```diff
@@ -208,7 +208,7 @@ export class ReleaseDetails extends Component<Props> {
             {items.map(item => {
               const name = item.getName();
               const namespace = item.getNs();
-              const api = apiManager.getApi(item.metadata.selfLink);
```
Comment (Nokel81) [inline src/renderer/components/+apps-releases/release-details.tsx:211]: Wouldn't it be better to call `ensureObjectSelflink` on `items`?

Comment (nevalla) [reply src/renderer/components/+apps-releases/release-details.tsx:211]: that requires resolved `api`

Comment (Nokel81) [reply src/renderer/components/+apps-releases/release-details.tsx:211]: Okay

**Review by Nokel81 — APPROVED** [review]
