### PR TITLE
Fix cluster's apiUrl

### LINKED ISSUE #845: Cluster is showing wrong api url
**Describe the bug**
Api url for a cluster is read from the current context of the Kubeconfig file. Instead it should read that from the cluster object of the context that is assigned to Lens cluster.

### PR DESCRIPTION
**Pull request by nevalla**
Fixes #845 

Signed-off-by: Lauri Nevala <lauri.nevala@gmail.com>

### CODE REVIEW

File: src/main/cluster.ts [hunk 1]
```diff
@@ -82,8 +82,7 @@ export class Cluster implements ClusterModel {
   @action
   updateModel(model: ClusterModel) {
     Object.assign(this, model);
-    this.apiUrl = this.getKubeconfig().getCurrentCluster()?.server;
-    this.contextName = this.contextName || this.preferences.clusterName;
+    this.apiUrl = this.getKubeconfig().getCluster(this.getKubeconfig().getContextObject(this.contextName).cluster).server
```
Comment (aleksfront) [inline src/main/cluster.ts]: Maybe it's better to move `this.getKubeconfig()` into some `const` before this line to avoid parsing kubeconfig twice.

Comment (nevalla) [reply src/main/cluster.ts]: Done. Also moved this assign into constructor, since it's not going to change.

**Review by aleksfront — APPROVED** [review]
LGTM!
