### PR TITLE
Check cluster connected status from cluster.status.phase property

### LINKED ISSUE #3077: Cannot install/toggle Lens Metrics
**Describe the bug**
Lens Metrics settings (Lens 5) does not detect connected cluster properly. Despite the cluster is connected, there's error message `Lens Metrics settings requires established connection to the cluster.`

**Screenshots**
image

### PR DESCRIPTION
**Pull request by nevalla**
Fixes #3077

### CODE REVIEW

File: extensions/metrics-cluster-feature/src/metrics-settings.tsx [hunk 1]
```diff
@@ -81,7 +81,7 @@ export class MetricsSettings extends React.Component<Props> {
 
   @computed get isTogglable() {
     if (this.inProgress) return false;
```
Comment (Nokel81) [inline extensions/metrics-cluster-feature/src/metrics-settings.tsx:83]: Nit: maybe do one chain?

```suggestion
    return (
      !this.inProgress
      && !this.canUpgrade
      && this.isActiveMetricsProvider
      && this.props.cluster.status.phase === "connected"
    );
```

**Review by Nokel81 — APPROVED** [review]

**Review by jakolehm — APPROVED** [review]
