### PR TITLE
Fix being able to view clusters outside the current workspace

### LINKED ISSUE #1759: An extension cannot reliably ask Lens to activate a cluster
After some hacking, this seems to work, although it doesn't _always_ work (not sure why):
```javascript
  Store.clusterStore.activeClusterId = clusterId;
  extension.navigate(`/cluster/${clusterId}`);
```

I noticed that `clusterStore` does not provide a `setActive(clusterId)` similar to `workspaceStore.setActive(wsId)` where the latter, when called, activates the workspace AND switches to it.

On the surface, it would be seem logical to have `clusterStore.setActive(clusterId)`, and when called, Lens activates the cluster AND switches the view to it.

Note that today, just doing `Store.clusterStore.activeClusterId = clusterId` will only _activate_ (or at least, seem to) the cluster (by putting a white square behind its icon in the left sidebar, like what happens when you click the icon), however it does NOT also navigate to that cluster.

### LINKED ISSUE #2348: Possible to view clusters not in current workspace
**Describe the bug**
The `ClusterStore.activeCluster` is not always kept up to date with the current workspace. Leading to opening a cluster in one workspace and then switching workspaces and the cluster is still active.

**To Reproduce**
1. Go to the `default` workspace
2. Click on an added cluster
3. Go to another workspace that doesn't have that cluster and doesn't have a last selected cluster
4. See that the same cluster is still visible.

**Expected behavior**
The cluster view frame should be empty

**Extra Information:**
It probably should just be deprecated and delegated to `WorkspaceStore`

### PR DESCRIPTION
**Pull request by Nokel81**
- Completely removes ClusterStore.activeCluster
- Every workspace now tracks it current activeCluster
- If an active cluster is removed then the workspace's activeClusterId is set to undefined
- Only show welcome notification on the first time a non-managed workspace is viewed in the workspace overview
- Add unit tests for the WorkspaceStore
- Add validation that only valid clusters can be set to the activeClusterId field
- Marks the current workspace as disabled in the switch workspace's command

Signed-off-by: Sebastian Malton <sebastian@malton.name>

fixes #2348 

### future work:
- I could make it so that if you disconnect from a cluster it pick another one to go to instead of popping you back to the overview screen (see end of video).

### New look:

https://user-images.githubusercontent.com/8225332/111534350-44631b80-873e-11eb-8580-c42cd898a24d.mov

### CODE REVIEW

File: src/common/workspace-store.ts [hunk 1]
```diff
@@ -152,16 +241,24 @@ export class WorkspaceStore extends BaseStore<WorkspaceStoreModel> {
   private static stateRequestChannel = "workspace:states";
 
   @observable currentWorkspaceId = WorkspaceStore.defaultId;
+
+  #seenWorkspaces = observable.set<WorkspaceId>();
```
Comment (ixrock) [inline src/common/workspace-store.ts]: Why do we use private fields here btw?

File: src/renderer/components/cluster-manager/clusters-menu.tsx [hunk 2]
```diff
@@ -32,6 +32,9 @@ interface Props {
 @observer
 export class ClustersMenu extends React.Component<Props> {
   @observable workspaceMenuVisible = false;
+  @computed get workspace() {
```
Comment (ixrock) [inline src/renderer/components/cluster-manager/clusters-menu.tsx]: There is no need in `@computed` when nothing to calculate/derive inside the getter.

**Review by ixrock — DISMISSED** [review]
LGTM

File: src/common/workspace-store.ts (hunk 1 above)
Comment (Nokel81) [reply src/common/workspace-store.ts]: Do you mean instead of typescript's `private` modifier? I felt that this was a better way to prevent outside consumers from using the raw values

File: src/renderer/components/cluster-manager/clusters-menu.tsx (hunk 2 above)
Comment (Nokel81) [reply src/renderer/components/cluster-manager/clusters-menu.tsx]: Fair, will remove

**Comment by Nokel81** [comment]
Hopefully this can be in rc.2

**Review by ixrock — DISMISSED** [review]

File: src/renderer/components/+landing-page/landing-page.tsx [hunk 3]
```diff
@@ -11,28 +11,28 @@ import { Icon } from "../icon";
...
       });
     }
+
+    workspaceStore.markSeen(this.workspace);
   }
 
   render() {
-    const showBackButton = this.clusters.length > 0;
-    const header = <><Icon svg="logo-lens" big /> <h2>{workspaceStore.currentWorkspace.name}</h2></>;
+    const showBackButton = this.workspaceClusters.length > 0;
```
Comment (jim-docker) [inline src/renderer/components/+landing-page/landing-page.tsx]: I think the back button should only be shown if there is an active cluster in this workspace because this is the landing page, there is no place to go back to from the landing page if there is no active cluster. (unless we go to the previous workspace, if there is one. But I think that would be a weird UX)

File: src/common/workspace-store.ts [hunk 4]
```diff
@@ -6,20 +6,25 @@ import { appEventBus } from "./event-bus";
 import { broadcastMessage, handleRequest, requestMain } from "../common/ipc";
 import logger from "../main/logger";
 import type { ClusterId } from "./cluster-store";
+import { Cluster } from "../main/cluster";
+import migrations from "../migrations/workspace-store";
 
 export type WorkspaceId = string;
 
+export class InvarientError extends Error {}
```
Comment (jim-docker) [inline src/common/workspace-store.ts]:
```suggestion
export class InvariantError extends Error {}
```

**Review by jim-docker — COMMENTED** [review]
This is a lot of refactoring to introduce between 4.2.0-rc.1 and rc.2. Did you consider doing just a surgical fix for the issue now, and saving this for 4.2.1 (or even 4.3)?

File: src/common/workspace-store.ts [hunk 5]
```diff
@@ -98,9 +104,88 @@ export class Workspace implements WorkspaceModel, WorkspaceState {
...
+      return false;
+    }
+
+    if (this.activeClusterId === clusterOrId.id) {
+      this.clearActiveCluster();
+
+      return true;
+    }
+
+    return false;
```
Comment (jim-docker) [inline src/common/workspace-store.ts]: You could avoid duplicating logic similar to what you did in `isActive()`, `hasBeenSeen()`,`markSeen()`

File: src/common/workspace-store.ts [hunk 6]
```diff
@@ -233,6 +330,44 @@ export class WorkspaceStore extends BaseStore<WorkspaceStoreModel> {
...
+  isActive(workspaceOrId: Workspace | WorkspaceId): boolean {
+    const workspaceId = typeof workspaceOrId === "string"
+      ? workspaceOrId
+      : workspaceOrId.id;
+
+    return this.currentWorkspaceId === workspaceId;
+  }
+
+  /**
+   * Checks to see if the workspace has been to the overview page before
```
Comment (jim-docker) [inline src/common/workspace-store.ts]: workspace-store doesn't really know anything about overview page, does it? Is there another way you could describe this? Or is there a more appropriate place for these methods?

File: src/common/workspace-store.ts [hunk 7]
```diff
@@ -98,9 +104,88 @@ export class Workspace implements WorkspaceModel, WorkspaceState {
...
+      logger.error("[WORKSPACE]: activeClusterId was attempted to be set to an invalid value", { clusterOrId, workspaceName: this.name });
+    }
+  }
+
+  /**
+   * Tries to clear the cluster as this workspace's activeCluster.
+   * @param clusterOrId the cluster instance or its ID
+   * @returns true if it matches the `activeClusterId` (and is thus cleared) else false
+   */
+  @action tryClearAsCurrentActiveCluster(clusterOrId: ClusterId | Cluster): boolean {
```
Comment (jim-docker) [inline src/common/workspace-store.ts]:
```suggestion
  @action tryClearAsActiveCluster(clusterOrId: ClusterId | Cluster): boolean {
```

File: src/common/workspace-store.ts [hunk 8]
```diff
@@ -293,18 +428,23 @@ export class WorkspaceStore extends BaseStore<WorkspaceStoreModel> {
...
   }
 
   @action
-  setLastActiveClusterId(clusterId?: ClusterId, workspaceId = this.currentWorkspaceId) {
-    this.getById(workspaceId).lastActiveClusterId = clusterId;
+  /**
+   * Attempts to clear `cluster` as the `activeCluster` from its own workspace
+   * @returns true if the cluster was previously the active one for its workspace
+   */
+  tryClearAsWorkspaceActiveCluster(cluster: Cluster): boolean {
```
Comment (jim-docker) [inline src/common/workspace-store.ts]: This could have the same name as its `workspace` counterpart?

File: src/extensions/stores/cluster-store.ts [hunk 9]
```diff
@@ -16,16 +17,21 @@ export class ClusterStore extends Singleton {
...
+    return internalWorkspaceStore.currentWorkspace.activeClusterId;
   }
 
   /**
    * Set active cluster id
+   * @deprecated use navigate
    */
   set activeClusterId(id : ClusterId) {
-    internalClusterStore.activeCluster = id;
+    console.warn("Store.ClusterStore.activeClusterId is deprecated. Use LensExtension.navigate()");
```
Comment (jim-docker) [inline src/extensions/stores/cluster-store.ts:34]: Shouldn't this still do something?
`internalWorkspaceStore.currentWorkspace.activeClusterId = id;`?

File: src/main/index.ts [hunk 10]
```diff
@@ -106,11 +106,13 @@ app.on("ready", async () => {
   await Promise.all([
     userStore.load(),
     clusterStore.load(),
-    workspaceStore.load(),
     extensionsStore.load(),
     filesystemProvisionerStore.load(),
   ]);
 
+  // load this after clusterStore, because it does validation on its entries
+  await workspaceStore.load();
```
Comment (jim-docker) [inline src/main/index.ts]: Can you keep it in the `promise.all()` as `clusterStore.load().then(workspaceStore.load)`?

File: src/extensions/stores/cluster-store.ts (hunk 9 above)
Comment (Nokel81) [reply src/extensions/stores/cluster-store.ts:34]: So the previous code was basically completely broken so I doubt that anyone was really using it and I don't think we need to keep the behaviour. This wrapper class is marked as `@beta` anyway. I kept this setter (marking it as `@deprecated`) so that things will still build but I don't really think we need to maintain the broken code. 

I can be persuaded to the contrary, that is just my current position.

File: src/main/index.ts (hunk 10 above)
Comment (Nokel81) [reply src/main/index.ts]: Yes I think so

File: src/common/workspace-store.ts (hunk 8 above)
Comment (Nokel81) [reply src/common/workspace-store.ts]: Probably

File: src/common/workspace-store.ts (hunk 6 above)
Comment (Nokel81) [reply src/common/workspace-store.ts]: Maybe as a store like what is in #2279 ?

File: src/extensions/stores/cluster-store.ts (hunk 9 above)
Comment (jim-docker) [reply src/extensions/stores/cluster-store.ts:34]: You're right, it's no big deal.  I leave it up to you. 

But if it's easy to keep supporting that broken behaviour as deprecated then why not? Otherwise someone will say "I know it was broken, but now it's brokener". :)

Comment (Nokel81) [reply src/extensions/stores/cluster-store.ts:34]: Okay sounds good. I am also now working on #1759 so in that PR I'll change what the deprecation message is.

**Comment by Nokel81** [comment]
I did consider a more patchwork fix, we could push this to 4.2.1 depending on how other people feel about this.

I think that if we test it enough it should be fine to put it into rc.2 though.

File: src/extensions/stores/cluster-store.ts [hunk 11]
```diff
@@ -18,7 +18,7 @@ export class ClusterStore extends Singleton {
   /**
    * Active cluster id
    *
-   * @deprecated use `workspaceStore.activeCluster`
+   * @deprecated use `workspaceStore.currentWorkspace.activeClusterId`
    */
   get activeClusterId(): string {
     console.warn("get Store.ClusterStore.activeClusterId is deprecated. Use workspace.activeCluster");
```
Comment (jim-docker) [inline src/extensions/stores/cluster-store.ts]: use workspaceStore.currentWorkspace.activeClusterId

File: src/renderer/components/+landing-page/landing-page.tsx [hunk 12]
```diff
@@ -3,14 +3,17 @@ import React from "react";
...
+import { WorkspaceId, workspaceStore } from "../../../common/workspace-store";
 import { WorkspaceOverview } from "./workspace-overview";
 import { PageLayout } from "../layout/page-layout";
 import { Notifications } from "../notifications";
 import { Icon } from "../icon";
+import { createStorage } from "../../utils";
 
 @observer
 export class LandingPage extends React.Component {
+  private static storage = createStorage<WorkspaceId[]>("landing_page", []);
```
Comment (jim-docker) [inline src/renderer/components/+landing-page/landing-page.tsx]: so it will persist, nice, great idea.

File: src/renderer/components/+landing-page/landing-page.tsx [hunk 13]
```diff
@@ -20,14 +23,17 @@ export class LandingPage extends React.Component {
...
+    if (!workspacesSeen.has(this.workspace.id) && this.workspaceClusters.length === 0) {
       Notifications.info(<><b>Welcome!</b><p>Get started by associating one or more clusters to Lens</p></>, {
         timeout: 30_000,
         id: "landing-welcome"
       });
     }
 
-    workspaceStore.markSeen(this.workspace);
+    workspacesSeen.add(this.workspace.id);
+    LandingPage.storage.set(Array.from(workspacesSeen));
```
Comment (jim-docker) [inline src/renderer/components/+landing-page/landing-page.tsx]: I think the storage will also need to be updated wherever workspaces are deleted, so they can be removed from this storage.

**Comment by Nokel81** [comment]
I have moved this to target 4.2.1

**Comment by jim-docker** [comment]
> I have moved this to target 4.2.1

this will be a known issue for 4.2.0 then?

**Comment by Nokel81** [comment]
Yes in the final release notes I'll add that.

File: src/extensions/stores/cluster-store.ts [hunk 14]
```diff
@@ -21,7 +21,7 @@ export class ClusterStore extends Singleton {
    * @deprecated use `workspaceStore.currentWorkspace.activeClusterId`
    */
   get activeClusterId(): string {
-    console.warn("get Store.ClusterStore.activeClusterId is deprecated. Use workspace.activeCluster");
+    console.warn("get Store.ClusterStore.activeClusterId is deprecated. Use workspace..currentWorkspace.activeClusterId");
```
Comment (jim-docker) [inline src/extensions/stores/cluster-store.ts]: two dots? :)

File: src/renderer/components/+landing-page/landing-page.tsx [hunk 15]
```diff
@@ -23,17 +23,23 @@ export class LandingPage extends React.Component {
   }
 
   componentDidMount() {
-    const workspacesSeen = new Set(LandingPage.storage.get());
+    // ignore workspaces that don't exist
+    const seenWorkspaces = new Set(
+      LandingPage
+        .storage
+        .get()
+        .filter(id => workspaceStore.getById(id))
```
Comment (jim-docker) [inline src/renderer/components/+landing-page/landing-page.tsx:27]: slick!

File: src/renderer/components/+landing-page/landing-page.tsx [hunk 16]
```diff
@@ -23,17 +23,23 @@ export class LandingPage extends React.Component {
...
+    );
 
-    if (!workspacesSeen.has(this.workspace.id) && this.workspaceClusters.length === 0) {
+    if (!seenWorkspaces.has(this.workspace.id) && this.workspaceClusters.length === 0 && !this.workspace.isManaged) {
```
Comment (jim-docker) [inline src/renderer/components/+landing-page/landing-page.tsx]: just noticed this might need to be done in a `reaction()`, because this page may already be visible when user creates a new one, or switches to an empty one.

**Review by jim-docker — DISMISSED** [review]
I can't tell what's changed since I last reviewed. I am assuming it's just merge conflicts? I tested again, LGTM

File: src/renderer/ipc/index.tsx [hunk 17]
```diff
@@ -76,7 +76,7 @@ function ListNamespacesForbiddenHandler(event: IpcRendererEvent, ...[clusterId]:
     (
       <div className="flex column gaps">
         <b>Add Accessible Namespaces</b>
-        <p>Cluster <b>{clusterStore.active.name}</b> does not have permissions to list namespaces. Please add the namespaces you have access to.</p>
+        <p>Cluster <b>{clusterStore.getById(clusterId).name}</b> does not have permissions to list namespaces. Please add the namespaces you have access to.</p>
```
Comment (ixrock) [inline src/renderer/ipc/index.tsx]: Could be `clusterStore.getById(clusterId)` undefined?

File: src/renderer/components/+landing-page/landing-page.tsx [hunk 18]
```diff
@@ -1,38 +1,58 @@
...
 import { WorkspaceOverview } from "./workspace-overview";
 import { PageLayout } from "../layout/page-layout";
 import { Notifications } from "../notifications";
 import { Icon } from "../icon";
+import { createStorage } from "../../utils";
 
 @observer
 export class LandingPage extends React.Component {
-  @observable showHint = true;
+  private static storage = createStorage<WorkspaceId[]>("landing_page", []);
```
Comment (ixrock) [inline src/renderer/components/+landing-page/landing-page.tsx]: Storage key name doesn't reflect what it stores. 
Why it's tighted to landing-page only? Maybe just `seen_workspaces`?

**Review by ixrock — DISMISSED** [review]

File: src/renderer/ipc/index.tsx (hunk 17 above)
Comment (Nokel81) [reply src/renderer/ipc/index.tsx]: I guess in theory though this event is currently only sent by the main process while loading a cluster so I doubt that the cluster won't exist for the renderer.

File: src/renderer/components/+landing-page/landing-page.tsx (hunk 18 above)
Comment (Nokel81) [reply src/renderer/components/+landing-page/landing-page.tsx]: Sure I can rename it to `seen_workspaces`. What do you mean by "tighted"? That isn't a word that I know.

Comment (ixrock) [reply src/renderer/components/+landing-page/landing-page.tsx]: Ok, I mean `tied` :)

**Review by ixrock — DISMISSED** [review]

File: src/renderer/components/+landing-page/landing-page.tsx (hunk 18 above)
Comment (Nokel81) [reply src/renderer/components/+landing-page/landing-page.tsx]: Ah now I understand the question. This is the only place that `"seen_workspaces"` is used and Jim pointed out (reasonably imo) that storing it in `WorkspaceStore` doesn't make much sense.

**Review by jim-docker — DISMISSED** [review]

**Comment by stefcameron** [comment]
@Nokel81 Can you give me an overview of what the new API to activate a cluster in a workspace looks like now, with changes in this PR, since it sounds like it'll fix #1759 ?

**Comment by Nokel81** [comment]
@stefcameron I think it will be as simple as `<LensExtensionInstance>.navigate("/cluster/<cluster-id>");` but I will verify this in the morning.

**Comment by Nokel81** [comment]
@stefcameron Done, I have added it. I don't know why the `LensExtension.navigate` method is only limited to a specific extension but whatever.

You need to do the following:
```ts
import { Store } from "@k8slens/extensions";

...
const cluster = ...;

await Store.workspaceStore.setActiveCluster(cluster); // or cluster ID
```

**Comment by stefcameron** [comment]
> @stefcameron Done, I have added it. I don't know why the `LensExtension.navigate` method is only limited to a specific extension but whatever.
> 
> You need to do the following:
> 
> ```ts
> import { Store } from "@k8slens/extensions";
> 
> ...
> const cluster = ...;
> 
> await Store.workspaceStore.setActiveCluster(cluster); // or cluster ID
> ```

Thanks for following-up on this, @Nokel81 ! I will watch for this in 4.2.1 (unless I get to it off `master` before then) and will update my code accordingly.

Based on the call, the cluster doesn't have to be in the active workspace. Could be in some other workspace, and Lens will also activate the workspace as a result? Of course, this means Lens now ensures (maybe it always has; I haven't specifically tested) that all clusters have unique IDs...

**Comment by Nokel81** [comment]
No that call will update the active workspace too. Though now that I think about it. I think we should instead have it be `Navigation.navigate("/cluster/<cluster-id");` and instead change the active workspace on the fly. So I might back out this change.

**Comment by Nokel81** [comment]
But I need to think about it. I only mention this because workspace are going away and I would prefer if what I told you will also work in 5.0

**Comment by stefcameron** [comment]
> But I need to think about it. I only mention this because workspace are going away and I would prefer if what I told you will also work in 5.0

Whaaaaat? 😉 OK, I'd like to know a way that will survive, though if workspaces disappear, that will definitely impact my extension.

BTW, `extension.navigate("/cluster/<cluster-id>");` is what I'm already doing, but it's not reliable, which is the reason for #1759

**Comment by Nokel81** [comment]
@stefcameron So as we discussed, I am going to leave this API as is since putting more work into this is misplaced effort.

**Comment by stefcameron** [comment]
> @stefcameron So as we discussed, I am going to leave this API as is since putting more work into this is misplaced effort.

You mean it will be `await Store.workspaceStore.setActiveCluster(cluster); // or cluster ID` for now until Lens 5.0 when workspaces disappear? I assume there will be some equivalent method off the Catalogue API to activate an object at that point.

**Comment by Nokel81** [comment]
Yeah that.

File: src/renderer/components/select/select.scss [hunk 19]
```diff
@@ -104,9 +104,7 @@ html {
 
       &--is-disabled {
         cursor: not-allowed;
-        background: none !important;
```
Comment (jakolehm) [inline src/renderer/components/select/select.scss]: Are these changes by accident here?

Comment (Nokel81) [reply src/renderer/components/select/select.scss]: I honestly don't remember. I think I changed this because there are some places where the disabled text looks weird without it (since it changes the text colour).

Comment (jakolehm) [reply src/renderer/components/select/select.scss]: Should we revert this.. feels a bit dangerous change.

Comment (Nokel81) [reply src/renderer/components/select/select.scss]: Sure I can, I don't think it is as dangerous as it feels. I'll make a new PR with this change if I come across the need again.

**Review by jakolehm — APPROVED** [review]

**Review by nevalla — APPROVED** [review]
LGTM
