### PR TITLE
Fix listing charts failing due to bad versions

### LINKED ISSUE #3250: Apps/Charts endless loading
**Describe the bug**
After few latest updates (including version 5) of Lens - Apps/Charts are in endless loading.
Where the Apps/Releases works fine.

**To Reproduce**
1. Go to 'Apps/Charts'

**Expected behavior**
Full list of Helm charts (based on installed repositories) in the UI

**Screenshots**
Screenshot 2021-07-02 at 11 52 20 AM

**Environment (please complete the following information):**
- Lens Version: 5.0.0-latest.20210629.3
- OS: macOS Big Sur 11.4
- Installation method (e.g. snap or AppImage in Linux): brew

**Logs:**
Nothing interesting, except 
```
[CLUSTER]: refresh {"id":"*","name":"dev","ready":true,"online":true,"accessible":true,"disconnected":false}
```

**Kubeconfig:**
N/A

**Additional context**
Is there any option to enable debug mode, see more precise logs?

### PR DESCRIPTION
**Pull request by Nokel81**
- Add generic sorting function that uses the comparitors directory

- Because repos are 3rd party managed resources we cannot enforce strict
  semver compatibility. Therefore we should loosely coerce versions to
  semver versions.

- If a version is not even loosely coercable then we should just sort
  alphanumerically.

- Sort semver before non-semver

- Filter out a chart if any of the versions are marked as deprecated

Signed-off-by: Sebastian Malton <sebastian@malton.name>

fixes https://github.com/lensapp/lens/issues/3250

---
NOTE: please review each commit separately and do not squash this PR.

### CODE REVIEW

File: src/main/helm/helm-service.ts [hunk 1]
```diff
@@ -132,28 +133,55 @@ class HelmService {
...
+    return Object.fromEntries(
+      iter.filterMap(
+        Object.entries(chartGroups),
+        ([name, charts]) => {
+          for (const chart of charts) {
+            if (chart.deprecated) {
+              // ignore chart group if any chart is deprecated
+              return undefined;
+            }
+          }
```
Comment (jim-docker) [inline src/main/helm/helm-service.ts:145]: Can you add this change of behaviour to the PR description?

**Review by jim-docker — APPROVED** [review]
