### PR TITLE
Pre-Validate kubeconfig before making available in Lens

### LINKED ISSUE #599: Kube config is not found on Windows
**Describe the bug**

When I try to add a new cluster to Lens I don't see any of the clusters defined in my kube config. 
My kube config is in the default location.

image

**To Reproduce**
1. Go to 'File'
2. Click on 'Add Cluster'
3. Select to 'Select kubeconfig'
4. No existing clusters are shown

**Expected behavior**

Existing clusters are shown

**Screenshots**

image

**Environment (please complete the following information):**
- Lens Version: 3.5.1
- OS: Win 10 2004
- Installation method (e.g. snap or AppImage in Linux):  Exe
- Kubectl 1.14.2
 
Can I manually point Lens at my kube config?

### LINKED ISSUE #843: Can't setup kubeconfig as system kubeconfig has invalid config
**Describe the bug**
When I go to the "Add New Cluster" page I consistently get a notification saying:
Screen Shot 2020-09-09 at 11 02 58 AM

And the dropdown for adding new clusters is empty.

**To Reproduce**
1. Have the following entry in your kubeconfig under `contexts:`
```yml
- context:
    cluster: ""
    user: ""
  name: default/foo.kuberbetes.com/kubeuser
```
2. Click on the "Add Cluster" button on the left menu
3. Observe error notification

**Expected behavior**
The invalid contexts are filtered out and ignored.

**Screenshots**
See above

**Environment (please complete the following information):**
- Lens Version: 3.6.0-rc2
- OS: [e.g. OSX] macos
- Installation method (e.g. snap or AppImage in Linux): download
 
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
error: contexts[0].context.cluster is missing
```

### PR DESCRIPTION
**Pull request by stevejr**
Fixes: #843

Signed-off-by: Steve Richards <srichards@mirantis.com>

### CODE REVIEW

File: src/common/kube-helpers.ts [hunk 1]
```diff
@@ -16,16 +16,50 @@ function resolveTilde(filePath: string) {
   return filePath;
 }
 
+function loadFromFile(file: string) {
+  return loadFromString(fse.readFileSync(file, 'utf8'));
+}
+
+function loadFromString(config: string) {
```
Comment (Nokel81) [inline src/common/kube-helpers.ts]: I would like to see a unit test covering this change

File: src/common/kube-helpers.ts [hunk 2]
```diff
@@ -16,16 +16,50 @@ function resolveTilde(filePath: string) {
...
+      for (const [i, value] of obj["contexts"].entries()) {
+        if (!value.name || !value.context.cluster || !value.context.user) {
+          logger.error(`loadFromString: context ${JSON.stringify(value)} in kubeconfig has an error so will not be made available to Lens`);
+          obj["contexts"].splice(i, 1);
+        }
+      }
+    }
+    return yaml.dump(obj);
+  } catch (err) {
+    const error = String(err);
```
Comment (jim-docker) [inline src/common/kube-helpers.ts]: this isn't used?

File: src/common/kube-helpers.ts [hunk 3]
```diff
@@ -16,16 +16,50 @@ function resolveTilde(filePath: string) {
...
+    // Validate the context structure for invalid context objects
+    if ('contexts' in obj) {
+      for (const [i, value] of obj["contexts"].entries()) {
+        if (!value.name || !value.context.cluster || !value.context.user) {
+          logger.error(`loadFromString: context ${JSON.stringify(value)} in kubeconfig has an error so will not be made available to Lens`);
+          obj["contexts"].splice(i, 1);
+        }
+      }
+    }
+    return yaml.dump(obj);
```
Comment (jim-docker) [inline src/common/kube-helpers.ts]: what if `obj["contexts"]` is empty at this point? Should we throw here instead? What does the user see?

File: src/common/kube-helpers.ts [hunk 4]
```diff
@@ -16,16 +16,50 @@ function resolveTilde(filePath: string) {
...
+  } catch (err) {
+    const error = String(err);
+    logger.error(`Could not pre-validate contexts key in supplied config string - ${config}`)
+    return config;
```
Comment (jim-docker) [inline src/common/kube-helpers.ts]: This just punts to `kc.loadFromString()` in `loadConfig()`, which is ok because it is the same behaviour as before adding pre-validation but just wondering if we should throw here instead?

File: src/common/kube-helpers.ts (hunk 2 above)
Comment (stevejr) [reply src/common/kube-helpers.ts]: Have added usage of error string into message

File: src/common/kube-helpers.ts (hunk 3 above)
Comment (stevejr) [reply src/common/kube-helpers.ts]: So, if we do not have any contexts in the config then we will see an error in the console which will have the config supplied and the message `Error - TypeError: Cannot read property 'entries' of null`

Lens will still start up and when the user navigates to the Add Cluster screen then will see the error thrown from this block in the validateConfig function:

```
if (!config.contexts || config.contexts.length == 0) {
    throw new Error("No contexts provided in config")
}
```

Screen Shot 2020-10-14 at 11 16 58

Is this ok @jim-docker ?

File: src/common/kube-helpers.ts (hunk 4 above)
Comment (stevejr) [reply src/common/kube-helpers.ts]: @jim-docker - I have now wrapped the original loadConfig logic in a try/catch so we can actually catch errors from the Kubernetes Client functions (this wasn't happening before). So, my thought process was I only want to pre-validate the context object and if I can't do that because of some error we should just return the original config and let the Kubernetes Client create a kubeconfig object and catch the errors from that. 

If I catch and re-throw an error then we won't generate a kubeconfig object and right now Lens won't even load up!

File: src/common/kube-helpers.ts (hunk 1 above)
Comment (stevejr) [reply src/common/kube-helpers.ts]: Adding unit tests today and tomorrow.

Comment (stevejr) [reply src/common/kube-helpers.ts]: @Nokel81 - Can you please check the unit tests I have just added?

File: src/common/__tests__/kube-helpers.test.ts [hunk 5]
```diff
@@ -0,0 +1,179 @@
...
+  }],
+  kind: string,
+  'current-context': string,
+  preferences: {}
+}
+
+import { loadConfig } from "../kube-helpers"
+import { KubeConfig } from "@kubernetes/client-node";
+
+console.log("") // fix bug
```
Comment (Nokel81) [inline src/common/__tests__/kube-helpers.test.ts]:
```suggestion
console = new Console(process.stdout, process.stderr) // fix bug
```

File: src/common/__tests__/kube-helpers.test.ts [hunk 6]
```diff
@@ -0,0 +1,179 @@
...
+let mockKubeConfig: kubeconfig;
+
+describe("pre-validate context object in kubeconfig tests", () => {
+  beforeEach(() => {
+    jest.clearAllMocks()
+  });
+
+  describe('Check logger.error() output', () => {
+    it("invalid yaml string", () => {
+      //expect(loadConfig("fancy foo config")).toEqual({"clusters": [], "contexts": [], "currentContext": undefined, "users": []});
```
Comment (Nokel81) [inline src/common/__tests__/kube-helpers.test.ts]: please remove

File: src/common/__tests__/kube-helpers.test.ts [hunk 7]
```diff
@@ -0,0 +1,179 @@
...
+      loadConfig("fancy foo config")
+      expect(logger.error).toHaveBeenCalledWith("Could not pre-validate contexts key in supplied config string - \"fancy foo config\". Error - TypeError: Cannot use 'in' operator to search for 'contexts' in fancy foo config");
```
Comment (Nokel81) [inline src/common/__tests__/kube-helpers.test.ts]: I this this is a bit too strong since detecting the whole error means any change to the error message means changing this test. I would recommend changing something else. To be far, we also don't want to propagate the typeerror up to the user. So both this check should be changed to `toInclude` and we should intercept the error and strip out any type errors.

File: src/common/kube-helpers.ts (hunk 3 above)
Comment (jim-docker) [reply src/common/kube-helpers.ts]: Sounds ok, since this PR doesn't really specify the UX, which can be addressed in another PR, if necessary.
It might be more accurate to say `"No valid contexts provided in config"`

File: src/common/__tests__/kube-helpers.test.ts (hunk 5 above)
Comment (stevejr) [reply src/common/__tests__/kube-helpers.test.ts]: Actually I don't think I need it as this test set is not using mockFS so have removed it.

File: src/common/__tests__/kube-helpers.test.ts (hunk 6 above)
Comment (stevejr) [reply src/common/__tests__/kube-helpers.test.ts]: Done

File: src/common/__tests__/kube-helpers.test.ts (hunk 7 above)
Comment (stevejr) [reply src/common/__tests__/kube-helpers.test.ts]: @Nokel81 - Updated and pushed. Could you have one quick last look to make sure all is good. Thanks.

**Review by Nokel81 — DISMISSED** [review]
I think that this PR is in a good state now, @jim-docker ?

File: src/common/kube-helpers.ts (hunk 3 above)
Comment (jim-docker) [reply src/common/kube-helpers.ts]: I tried this out with some bad configs and I think there needs to be more feedback to the user. If I have a config that I know has 3 contexts but only two are offered up in the "Selected contexts" drop-down, it is very puzzling. Something like
```
  if (obj["contexts"].length < config["contexts"].length) {
    notify user that "one or more contexts could not be added"
  }
```

File: src/common/__tests__/kube-helpers.test.ts [hunk 8]
```diff
@@ -0,0 +1,180 @@
...
+    });
+
+    it("empty user in context causes it to be removed", async () => {
+      mockKubeConfig.contexts.push({context: {cluster: "cluster-2", user: ""}, name: "cluster-2"});
+      expect(mockKubeConfig.contexts.length).toBe(2);
+      const kc:KubeConfig = loadConfig(JSON.stringify(mockKubeConfig));
+      expect(logger.error).toBeCalledWith("loadFromString: context {\"context\":{\"cluster\":\"cluster-2\",\"user\":\"\"},\"name\":\"cluster-2\"} in kubeconfig has an error so will not be made available to Lens");
+      expect(kc.getCurrentContext()).toBe('minikube');
+      expect(kc.contexts.length).toBe(1);
+    });
```
Comment (jim-docker) [inline src/common/__tests__/kube-helpers.test.ts]: should also test missing name/cluster/user? I tried a config file with typos:
```
contexts:
- context:
    scluster: docker-desktop
    user: docker-desktop
  name: docker-desktop
- context:
    cluster: kind-jim
    suser: kind-jim
  name: kind-jim
- context:
    cluster: minikube
    user: minikube
  sname: minikube
```
I was surprised to find that the `kind-jim` cluster was accepted as valid. There must be a default user(?)

**Review by Nokel81 — APPROVED** [review]

**Comment by jim-docker** [comment]
This now just silently excludes bad contexts from the "Select contexts" list. No more notifications?

File: src/renderer/components/+add-cluster/add-cluster.tsx [hunk 9]
```diff
@@ -63,9 +63,11 @@ export class AddCluster extends React.Component {
       this.kubeConfigPath = filePath;
       userStore.kubeConfigPath = filePath; // save to store
     } catch (err) {
-      Notifications.error(
-        <div>Can&apos;t setup <code>{filePath}</code> as kubeconfig: {String(err)}</div>
-      );
+      if (!userStore.isDefaultKubeConfigPath) {
+        Notifications.error(
+          <div>Can&apos;t setup <code>{filePath}</code> as kubeconfig: {String(err)}</div>
```
Comment (jim-docker) [inline src/renderer/components/+add-cluster/add-cluster.tsx:68]:
```suggestion
          <div>Can&apos;t set up <code>{filePath}</code> as kubeconfig: {String(err)}</div>
```

File: src/common/kube-helpers.ts [hunk 10]
```diff
@@ -23,14 +24,36 @@ function resolveTilde(filePath: string) {
...
+  const obj = yaml.safeLoad(rawYaml);
+
+  if (typeof obj !== "object" || !obj) {
+    throw new TypeError("KubeConfig root entry must be an object");
+  }
+
+  const { clusters: rawClusters, users: rawUsers, contexts: rawContexts, "current-context": currentContext } = obj;
+  const clusters = newClusters(rawClusters);
+  const users = newUsers(rawUsers);
+  const contexts = newContexts(rawContexts?.filter(checkRawContext));
```
Comment (jim-docker) [inline src/common/kube-helpers.ts:45]: Seems a bit weird to just apply `checkRawContent`. This PR originally used `validateKubeConfig()` at this stage (before loading the kubeconfig), right?

So if `name`, `cluster` or `user` is missing the context is silently not included. If cluster is set to an unknown value then the context is included and the user is only informed that it is bad when they try to add it by clicking the Add Cluster button. It would be nice to catch all static problems with the config before the context is added to the "Select contexts" list.

Comment (Nokel81) [reply src/common/kube-helpers.ts:45]: I think that the filtering is best (though what might be better is having the contexts in the list but disabled with the errors displayed on hover). Though we can do that in a follow up PR.

**Comment by Nokel81** [comment]
@jim-docker I know a lot more people were annoyed by the notifications.

**Comment by jim-docker** [comment]
> @jim-docker I know a lot more people were annoyed by the notifications.

They don't like being told that there are errors in their kubeconfig? This is only when adding clusters, which isn't done that often(?) Anyway, none of my last comments here are blockers, this PR is an improvement.

**Review by jim-docker — APPROVED** [review]

**Comment by Nokel81** [comment]
See the two linked issues.
