### PR TITLE
ensure namespace placeholder reflects what will be saved to local storage

### LINKED ISSUE #4171: "All namespaces" is not the same as manually selecting all the namespaces
One small issue with https://github.com/lensapp/lens/pull/3983. If I manually select all the namespaces in the dropdown, the dropdown wrongly switches to showing "All namespaces". It should just show the list of the ones I selected. This looks to be only a UI issue because it correctly saves the list, not `[]` to local storage.

### PR DESCRIPTION
**Pull request by jim-docker**
If all of the namespaces have been manually selected by the user then those
namespaces are explicitly saved to the namespace store (not `[]`, representing
all namespaces). Thus, in this case, the placeholder in the selector should show this list,
not "All namespaces".

Signed-off-by: Jim Ehrismann <jehrismann@mirantis.com>

fixes #4171

### CODE REVIEW

File: src/renderer/components/+namespaces/namespace-select-filter.tsx [hunk 1]
```diff
@@ -36,10 +36,10 @@ import { isMac } from "../../../common/vars";
 const Placeholder = observer((props: PlaceholderProps<any, boolean>) => {
   const getPlaceholder = (): React.ReactNode => {
     const namespaces = namespaceStore.contextNamespaces;
+    const length = namespaceStore.selectedNamespaces.length ? namespaces.length : 0;
```
Comment (Nokel81) [inline src/renderer/components/+namespaces/namespace-select-filter.tsx]: why not just `namspaceStore.selectedNamespaces.length`?

Comment (jim-docker) [reply src/renderer/components/+namespaces/namespace-select-filter.tsx]: you are right, thanks.

**Review by Nokel81 — DISMISSED** [review]

**Review by jakolehm — APPROVED** [review]
