### PR TITLE
Flush response headers always when proxy gets a response

### LINKED ISSUE #1988: Terminal is hanging after the result of a kubectl rollout status command is returned
**Describe the bug**
When issuing a `kubectl rollout status` command the result is returned to the terminal but it doesn't complete, the terminal just hangs for approx 5mins. This means tools like Flux who rely on the result of these commands as part of their bootstrap process fail.

**To Reproduce**
1. Open lens and connect to a cluster
2. Find a deployment object
3. Open a new terminal in Lens and perform the command `kubectl rollout status -n <namespace> deployment <deployment>`
4. The result should be returned but the terminal hangs

**Expected behavior**
The terminal should return the result from the kubectl command and then return to a prompt.

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 4.0.6
- OS: OSX
- Installation method (e.g. snap or AppImage in Linux): DMG

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

### PR DESCRIPTION
**Pull request by jakolehm**
Headers were automatically flushed when response got data. That might not happen with watch requests and that's why we need to force flush.

Fixes #1988

### CODE REVIEW

**Review by nevalla — DISMISSED** [review]
LGTM

**Review by Nokel81 — DISMISSED** [review]

**Comment by jakolehm** [comment]
One integration test seems to fail (even after retry). Maybe this has side-effects 🤔

File: src/main/lens-proxy.ts [hunk 1]
```diff
@@ -127,8 +127,10 @@ export class LensProxy {
         this.retryCounters.delete(retryCounterId);
       }
 
-      if (!res.headersSent) {
-        res.flushHeaders();
+      if (!res.headersSent && req.url) {
+        const url = new URL(req.url, "http://localhost");
+
+        if (url.searchParams.has("watch")) res.flushHeaders();
       }
```
Comment (Nokel81) [inline src/main/lens-proxy.ts]:
```suggestion
      if (!res.headersSent && (new URL(req.url, "http://localhost")).searchParams.has("watch")) {
        res.flushHeaders();
      }
```

**Review by Nokel81 — APPROVED** [review]
I think that this is slightly clearer since the url will convert to a valid URL (without `watch` as a `searchParam`).

**Review by nevalla — APPROVED** [review]

File: src/main/lens-proxy.ts (hunk 1 above)
Comment (jakolehm) [reply src/main/lens-proxy.ts]: I prefer my version of this, it's longer but easier to read 🙂
