### PR TITLE
Fix check for user exec command

### LINKED ISSUE #2079: User Exec command "/usr/local/bin/aws" not found on host.
**Describe the bug**
I am using Lens on Windows, all my interactions with a kubenetes cluster i perform via kubectl installed on Windows Subsystem for Linux (WSL). I have also installed aws cli on WSL. My kubeconfig file is in WSL, i am able to reference the file in Lens using the path `\\wsl$\Ubuntu-18.04\home\user\.kube`
When i try to use one of my aws eks clusters, i get the above error message. I am assuming it's because it's trying to use aws cli from windows.

Is there any way to get it working without having to install aws cli in two places (WSL and Windows)?

**To Reproduce**
Use a kubeconfig file that contains a reference an aws eks cluster, see below.

The problem arises where the `command: /usr/local/bin/aws` has been defined, i added the fully qualified path but that hasn't helped.

**Expected behavior**
It should be able to load the cluster

**Environment (please complete the following information):**
- Lens Version: 4.0.8
- OS: Windows 10 Pro
- Installation method (e.g. snap or AppImage in Linux): From websiteusing installer
- WsL: Ubuntu 18.04

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
User Exec command "/usr/local/bin/aws" not found on host.
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: 
    server: https://asdfasdfasdfasdfasd.gr7.us-east-2.eks.amazonaws.com
  name: arn:aws:eks:us-east-2:999999999999:cluster/xxxxxxx-1
contexts:
- context:
    cluster: arn:aws:eks:us-east-2:999999999999:cluster/xxxxxxx-1
    namespace: xxxxxxx-rc5
    user: arn:aws:eks:us-east-2:999999999999:cluster/xxxxxxx-1
  name: arn:aws:eks:us-east-2:999999999999:cluster/xxxxxxx-1
current-context: arn:aws:eks:us-east-2:999999999999:cluster/xxxxxxx-1
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-east-2:999999999999:cluster/xxxxxxx-1
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - us-east-2
      - eks
      - get-token
      - --cluster-name
      - xxxxxxx-1
      - --role
      - arn:aws:iam::999999999999:role/xxxxxxx-1-cluster-admin
      command: /usr/local/bin/aws
      env:
      - name: AWS_PROFILE
        value: xxxxxxx-eks
```

### PR DESCRIPTION
**Pull request by Nokel81**
Signed-off-by: Sebastian Malton <sebastian@malton.name>

fixes #2079

### CODE REVIEW

File: src/common/kube-helpers.ts [hunk 1]
```diff
@@ -295,13 +295,22 @@ export function validateKubeConfig(config: KubeConfig, contextName: string, vali
...
     if (validateExec && user?.exec) {
-      const execCommand = user.exec["command"];
-      // check if the command is absolute or not
-      const isAbsolute = path.isAbsolute(execCommand);
-
-      // validate the exec struct in the user object, start with the command field
-      if (!commandExists.sync(execCommand)) {
-        return new ExecValidationNotFoundError(execCommand, isAbsolute);
+      try {
+        execFileSync(user.exec.command, { timeout: 1 });
```
Comment (jakolehm) [inline src/common/kube-helpers.ts]: Could you explain how does this fix the issue? Any tests that verify correct behavior?

Comment (Nokel81) [reply src/common/kube-helpers.ts]: Yes tests are good.

As for how this works. The basic idea is for the OS to try and find the file or command to execute if it succeed then either node will kill the program and we get the timeout error or the program exits immediately in which no error should occur.

Comment (jakolehm) [reply src/common/kube-helpers.ts]: I get how this change works but not sure why the previous logic didn't work? Also it feels a bit risky to execute binary, why not just check if it can be executed?

**Comment by Nokel81** [comment]
I have improved the error handling of the add-clusters page as well so that YAML errors are caught and displayed. Here is a short video:


https://user-images.githubusercontent.com/8225332/133313889-b56315fd-65c8-44b4-9b71-aae7ca599a0a.mov

**Comment by jim-docker** [comment]
> I have improved the error handling of the add-clusters page as well so that YAML errors are caught and displayed. Here is a short video:
> 

Is that the right video?

**Comment by Nokel81** [comment]
Nope, thanks. I thought I checked to make sure it was.

**Comment by Nokel81** [comment]
@jim-docker fixed

**Review by jim-docker — APPROVED** [review]
LGTM but did not verify it fixes #2079
