### PR TITLE
Fix auto finding logic of preferred versions

### LINKED ISSUE #6565: No longer able to see CronJobs
**Describe the bug**
After 6.1.19 I am no longer able to see CronJobs on Kubernetes 1.20

**To Reproduce**
1. Run Kubernetes 1.20
2. Go to Workloads->CronJobs

**Expected behavior**
List of CronJob objects

**Screenshots**
image

**Environment (please complete the following information):**
- Lens Version: 6.1.19
- OS: Manjaro
- Installation method (e.g. snap or AppImage in Linux): AUR

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**
presumably works perfectly on cronjobs with `apiVersion: batch/v1`

### PR DESCRIPTION
**Pull request by Nokel81**
- The kube preferred version might not contain the resource requested in some kube versions. Whereas the resource does exist on some previous api version

Signed-off-by: Sebastian Malton <sebastian@malton.name>

fixes https://github.com/lensapp/lens/issues/6565

### CODE REVIEW

File: src/common/k8s-api/kube-api.ts [hunk 1]
```diff
@@ -142,6 +143,38 @@ export interface KubeApiResourceList {
...
+      version.groupVersion === list.preferredVersion.groupVersion
+      && version.version === list.preferredVersion.version
+    ) {
+      continue;
+    }
+
+    result.push(version);
+  }
+
+  return result;
```
Comment (Iku-turso) [inline src/common/k8s-api/kube-api.ts]: Simplify with `filter()`?

File: src/common/k8s-api/__tests__/kube-api.test.ts [hunk 2]
```diff
@@ -212,9 +212,9 @@ describe("KubeApi", () => {
       await flushPromises();
     });
 
-    it("requests resources from the versioned api group from the initial apiBase", () => {
+    it("requests version list from the api group from the initial apiBase", () => {
```
Comment (Iku-turso) [inline src/common/k8s-api/__tests__/kube-api.test.ts]: This test file is like 2000 lines long, and covers different technicalities. Split to more files?

File: src/common/k8s-api/__tests__/kube-api.test.ts [hunk 3]
```diff
@@ -409,21 +423,220 @@ describe("KubeApi", () => {
...
+                headers: {
+                  "content-type": "application/json",
+                },
+                method: "get",
+              },
+            ]);
+          });
+
+          it("sets fields in the api instance", () => {
+            expect(ingressApi).toEqual(expect.objectContaining({
```
Comment (Iku-turso) [inline src/common/k8s-api/__tests__/kube-api.test.ts]: Mutating fields of an "API" is a pretty shady practice, if you can agree without my effort to justify :) Let's try thinking of alternate patterns elsewhere in the future.

File: src/common/k8s-api/__tests__/kube-api.test.ts [hunk 4]
```diff
@@ -409,21 +423,220 @@ describe("KubeApi", () => {
...
+              let getCall: Promise<Ingress | null>;
+
+              beforeEach(async () => {
+                getCall = ingressApi.get({
+                  name: "foo1",
+                  namespace: "default",
+                });
+
+                // This is needed because of how JS promises work
+                await flushPromises();
```
Comment (Iku-turso) [inline src/common/k8s-api/__tests__/kube-api.test.ts]: `flushPromises` is generally needed when the actual promise just about to resolve isn't accessible in our scope. Most of the time this translates to a design error from an avoidable orphan promise. Not sure if this is the case here.

File: src/common/k8s-api/kube-api.ts [hunk 5]
```diff
@@ -310,15 +353,20 @@ export class KubeApi<
...
+          const { resources } = await this.request.get(`${apiPrefix}/${resourceVersion.groupVersion}`) as KubeApiResourceList;
+
+          if (resources.some(({ name }) => name === resource)) {
+            return {
+              apiPrefix,
+              apiGroup,
+              apiVersionPreferred: resourceVersion.version,
+            };
+          }
         }
```
Comment (Iku-turso) [inline src/common/k8s-api/kube-api.ts:359]: Could we use `Promise.race` here, or is the intended behaviour to sequentially probe for requests until bingo?

File: src/common/k8s-api/kube-api.ts [hunk 6]
```diff
@@ -736,8 +755,9 @@ export class KubeApi<
         });
       })
       .catch(error => {
-        logger.error(`[KUBE-API] watch (${watchId}) throwed ${watchUrl}`, error);
-
+        if (!abortController.signal.aborted) {
+          this.dependencies.logger.error(`[KUBE-API] watch (${watchId}) throwed ${watchUrl}`, error);
```
Comment (Iku-turso) [inline src/common/k8s-api/kube-api.ts]: Ahem. Throwed -> threw :) The error message could be more informative.

**Review by Iku-turso — DISMISSED** [review]
No deal breakers, just conversation starters :)

File: src/common/k8s-api/__tests__/kube-api.test.ts (hunk 3 above)
Comment (Nokel81) [reply src/common/k8s-api/__tests__/kube-api.test.ts]: oh sure, this is just part of the existing API

File: src/common/k8s-api/kube-api.ts (hunk 5 above)
Comment (Nokel81) [reply src/common/k8s-api/kube-api.ts:359]: The intended behaviour is to sequentially probe. Furthermore this only happens the very first time any call occurs.

File: src/common/k8s-api/__tests__/kube-api.test.ts (hunk 2 above)
Comment (Nokel81) [reply src/common/k8s-api/__tests__/kube-api.test.ts]: sure

File: src/common/k8s-api/kube-api.ts (hunk 1 above)
Comment (Nokel81) [reply src/common/k8s-api/kube-api.ts]: sure

File: src/common/k8s-api/__tests__/kube-api.test.ts (hunk 4 above)
Comment (Nokel81) [reply src/common/k8s-api/__tests__/kube-api.test.ts]: I think this is still required, will check.

Comment (Nokel81) [reply src/common/k8s-api/__tests__/kube-api.test.ts]: No this is required because without it none of the calls will actually happen between the `beforeEach` and the `it`.

**Review by Iku-turso — APPROVED** [review]
