### PR TITLE
Fix not being able to remove role bindings via the UI

### LINKED ISSUE #4359: Can't remove user from ClusterRoleBinding details page
https://user-images.githubusercontent.com/40840436/142031858-1edb1ef0-be70-4c72-9a8b-26805ab8b775.mov

happens on master

### PR DESCRIPTION
**Pull request by Nokel81**
Signed-off-by: Sebastian Malton <sebastian@malton.name>

fixes #4359

### CODE REVIEW

File: src/common/k8s-api/kube-api.ts [hunk 1]
```diff
@@ -436,10 +458,10 @@ export class KubeApi<T extends KubeObject> {
     throw new Error(`GET multiple request to ${url} returned not an array: ${JSON.stringify(parsed)}`);
   }
 
-  async get({ name = "", namespace = "default" } = {}, query?: IKubeApiQueryParams): Promise<T | null> {
+  async get(desc: ResourceDescriptor, query?: IKubeApiQueryParams): Promise<T | null> {
```
Comment (Nokel81) [inline src/common/k8s-api/kube-api.ts:461]: While this is technically a breaking change I think it is acceptable because a call to `get()` without this first argument would return the "list" result which would then trigger the `Array.isArray()` check on line 468 bellow.

File: src/common/k8s-api/kube-api.ts [hunk 2]
```diff
@@ -450,19 +472,18 @@ export class KubeApi<T extends KubeObject> {
...
 
-  async create({ name = "", namespace = "default" } = {}, data?: Partial<T>): Promise<T | null> {
+  async create({ name, namespace }: Partial<ResourceDescriptor>, data?: Partial<T>): Promise<T | null> {
     await this.checkPreferredVersion();
 
     const apiUrl = this.getUrl({ namespace });
     const res = await this.request.post(apiUrl, {
-      data: merge({
-        kind: this.kind,
-        apiVersion: this.apiVersionWithGroup,
```
Comment (Nokel81) [inline src/common/k8s-api/kube-api.ts:460]: These two pieces of data are unnecessary due to them being in the URL

**Review by jweak — APPROVED** [review]
LGTM
