### PR TITLE
Catch errors when responding from proxy error

### LINKED ISSUE #1356: 4.0.0-beta.1 - Crash on exit
**Describe the bug**
Close the application

**To Reproduce**
1. Open app..
2. Close app..

**Expected behavior**
Exists cleanly

**Screenshots**
image

**Environment (please complete the following information):**
- Lens Version: 4.0.0-beta.1
- OS: OSX
- Installation method (e.g. snap or AppImage in Linux): DMG

### PR DESCRIPTION
**Pull request by nevalla**
This PR will catch errors when responding from proxy error. Most of the proxy errors are happening when closing the app and it's not possible to respond anymore from proxy server.

Fixes #1356 . Also before this fix saw this error #191, but not anymore after the fix.

Signed-off-by: Lauri Nevala <lauri.nevala@gmail.com>

### CODE REVIEW

File: src/main/lens-proxy.ts [hunk 1]
```diff
@@ -131,7 +131,11 @@ export class LensProxy {
           }
         }
       }
-      res.writeHead(500).end("Oops, something went wrong.")
+      try {
+        res.writeHead(500).end("Oops, something went wrong.")
+      } catch (e) {
+        // Can't send headers. Probably app is closing.
```
Comment (jakolehm) [inline src/main/lens-proxy.ts]: Should we log an error?

Comment (nevalla) [reply src/main/lens-proxy.ts]: I have a feeling that logger is going south also at this point, but does not hurt if that does not cause any further issues

Comment (ixrock) [reply src/main/lens-proxy.ts]: Are we writing logs to `~/Library/Logs/Electron/lens.log`, right?

Comment (nevalla) [reply src/main/lens-proxy.ts]: yes. Tested logging the error and at least on Windows it did not cause any further issues.

**Review by ixrock — APPROVED** [review]
