### PR TITLE
Fix buggy node metrics/chart

### LINKED ISSUE #1699: Wrong data about CPU, DISK, PODS usage per node
**Describe the bug**
Wrong data about CPU, DISK, PODs usage per node

**To Reproduce**
1. Go to a cluster
2. Click on the node
3. Click on graf selector Cpu, Disk, Pods
4. See the wrong data

**Screenshots**
image
image

**Environment (please complete the following information):**
- Lens Version: kontena-lens                     4.0.0                       144
- OS: Ubuntu 20.4
- Installation method (e.g. snap or AppImage in Linux): snap

### PR DESCRIPTION
**Pull request by jakolehm**
Fixes #1699

### CODE REVIEW

File: src/renderer/components/+nodes/node-charts.tsx [hunk 1]
```diff
@@ -26,9 +26,11 @@ export const NodeCharts = observer(() => {
   const [
     memoryUsage,
     memoryRequests,
+    _memoryLimits, // DO NOT REMOVE!!!
```
Comment (panuhorsmalahti) [inline src/renderer/components/+nodes/node-charts.tsx]: I think warning can be removed by setting `varsIgnorePattern` in `no-unused-vars` configuration to something like "^_"

**Review by panuhorsmalahti — APPROVED** [review]

**Review by aleksfront — APPROVED** [review]

File: src/renderer/components/+nodes/node-charts.tsx [hunk 2]
```diff
@@ -26,9 +26,11 @@ export const NodeCharts = observer(() => {
   const [
     memoryUsage,
     memoryRequests,
+    _memoryLimits, // eslint-disable-line unused-imports/no-unused-vars-ts
     memoryCapacity,
     cpuUsage,
     cpuRequests,
+    _cpuLimits, // eslint-disable-line unused-imports/no-unused-vars-ts
```
Comment (shadonna-bossy) [inline src/renderer/components/+nodes/node-charts.tsx:33]: - [@sha256
```suggestion
    _cpuLimits, // eslint-disable-line unused-imports/no-unused-vars-ts
```
]()
