### PR TITLE
Open external links in web browser

### LINKED ISSUE #502: Links in chart descriptions don't work
**Describe the bug**
Links don't work in chart descriptions.

**To Reproduce**
1. Go to Apps -> Charts
2. Click on a chart
3. Panel appears
4. Click on a link

**Expected behavior**
Opens the link in browser.

**Environment (please complete the following information):**
- Lens Version: 3.5.0
- OS: MacOs 10.15
- dmg
 
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
How can I run it from terminal on Mac?

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
Not related

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by nevalla**
This PR will open external links (links that have `target="_blank"`) in a web browser. 

Fixes #502

### CODE REVIEW

**Review by jakolehm — APPROVED** [review]
LGTM

File: src/renderer/components/ClusterPage.vue [hunk 1]
```diff
@@ -92,6 +92,10 @@ export default {
     lensLoaded: function() {
       console.log("lens loaded")
       this.lens.loaded = true;
+      this.lens.webview.getWebContents().on('new-window', (e, url) => {
```
Comment (Nokel81) [inline src/renderer/components/ClusterPage.vue]: I know that we are only using a one or two month old version of electron. But https://www.electronjs.org/docs/breaking-changes#removed-webviewgetwebcontents seems to say that this will not be possible if we ever choose to upgrade. Would seeing if it is possible to use the recommended newer version be a good idea?

Comment (jakolehm) [reply src/renderer/components/ClusterPage.vue]: @Nokel81 good catch!

Comment (nevalla) [reply src/renderer/components/ClusterPage.vue]: Yes, definitely 🍻 . Changed to implementation.

**Review by Nokel81 — APPROVED** [review]
