### PR TITLE
Fix bundled extension install on Linux/AppImage

### LINKED ISSUE #1162: Lens fails to install bundled extensions on Linux/AppImage
Because "npm install" does not support read-only filesystems.

```
npm ERR! code EROFS
npm ERR! syscall access
npm ERR! path /tmp/.mount_Lens-4n78npS/resources/extensions/metrics-cluster-feature
npm ERR! errno -30
npm ERR! rofs EROFS: read-only file system, access '/tmp/.mount_Lens-4n78npS/resources/extensions/metrics-cluster-feature'
npm ERR! rofs Often virtualized file systems, or other file systems
npm ERR! rofs that don't support symlinks, give this error.
```

### PR DESCRIPTION
**Pull request by jakolehm**
Fixes #1162

### CODE REVIEW

**Review by nevalla — APPROVED** [review]
LGTM

File: src/extensions/extension-manager.ts [hunk 1]
```diff
@@ -39,7 +47,13 @@ export class ExtensionManager {
 
   async load() {
     logger.info("[EXTENSION-MANAGER] loading extensions from " + this.extensionPackagesRoot)
-    await fs.ensureDir(path.join(this.extensionPackagesRoot, "node_modules"))
+    if (this.inTreeFolderPath !== this.inTreeTargetPath) {
```
Comment (nevalla) [inline src/extensions/extension-manager.ts:50]: when this condition is false? (ie `this.inTreeFolderPath === this.inTreeTargetPath`)

Comment (jakolehm) [reply src/extensions/extension-manager.ts:50]: I'm not actually sure (I think it depends on an environment). This is just to safeguard our in-tree extensions (if these match we would remove sources).

Comment (jakolehm) [reply src/extensions/extension-manager.ts:50]: Other option is to check if `this.inTreeFolderPath` is read-only.
