### PR TITLE
fix node shell failure to open

### LINKED ISSUE #2433: Node-shell  Stopped working in v4.2.0
**Describe the bug**
Node-shell Stopped working, 

**To Reproduce**
1. Go to Nodes in any cluster
2. Click on Shell Icon at the top
3. See error

```
W0401 22:41:27.588552   56494 loader.go:223] Config not found: undefined
The connection to the server localhost:8080 was refused - did you specify the right host or port?
Terminal will auto-close in 15 seconds ...
```
FYI, I'm using a remote Cluster
Version: 4.2.0

### PR DESCRIPTION
**Pull request by jim-docker**
fixes #2433

This is a minimal fix, `node-shell-session.ts` needs some rework

### CODE REVIEW

**Review by Nokel81 — APPROVED** [review]

File: src/main/node-shell-session.ts [hunk 1]
```diff
@@ -20,6 +20,10 @@ export class NodeShellSession extends ShellSession {
   }
 
   public async open() {
+    // these are needed by the ShellSession getCachedShellEnv() method
```
Comment (jakolehm) [inline src/main/node-shell-session.ts:23]: Did this break in #2372 ?

**Review by jakolehm — APPROVED** [review]

File: src/main/node-shell-session.ts (hunk 1 above)
Comment (jim-docker) [reply src/main/node-shell-session.ts:23]: yes
