### PR TITLE
Lens should point to the release docs

### LINKED ISSUE #2254: Lens always links to latest documentation
**Describe the bug**
When selecting "Help" -> "Documentation" Lens navigates to `https://docs.k8slens.dev/` but should navigate to the documentation corresponding to the running version (e.g. `https://docs.k8slens.dev/v4.1.0/`).

### PR DESCRIPTION
**Pull request by Nokel81**
Signed-off-by: Sebastian Malton <sebastian@malton.name>

- On production builds Lens should point to its version of the docs.
- On dev builds it should point to latest (as the next version hasn't been released yet)

### CODE REVIEW

File: src/common/vars.ts [hunk 1]
```diff
@@ -42,5 +42,8 @@ export const apiKubePrefix = "/api-kube"; // k8s cluster apis
 // Links
 export const issuesTrackerUrl = "https://github.com/lensapp/lens/issues";
 export const slackUrl = "https://join.slack.com/t/k8slens/shared_invite/enQtOTc5NjAyNjYyOTk4LWU1NDQ0ZGFkOWJkNTRhYTc2YjVmZDdkM2FkNGM5MjhiYTRhMDU2NDQ1MzIyMDA4ZGZlNmExOTc0N2JmY2M3ZGI";
-export const docsUrl = "https://docs.k8slens.dev/";
 export const supportUrl = "https://docs.k8slens.dev/latest/support/";
+
+const docsVersion = isProduction ? `v${packageInfo.version}` : "latest";
```
Comment (jim-docker) [inline src/common/vars.ts]: Doesn't work for releases like 4.1.0-beta.2 but probably no big deal?

**Review by jim-docker — DISMISSED** [review]

File: src/common/vars.ts (hunk 1 above)
Comment (Nokel81) [reply src/common/vars.ts]: A good catch, probably a good idea to strip the suffix

File: src/common/vars.ts [hunk 2]
```diff
@@ -44,6 +45,9 @@ export const issuesTrackerUrl = "https://github.com/lensapp/lens/issues";
 export const slackUrl = "https://join.slack.com/t/k8slens/shared_invite/enQtOTc5NjAyNjYyOTk4LWU1NDQ0ZGFkOWJkNTRhYTc2YjVmZDdkM2FkNGM5MjhiYTRhMDU2NDQ1MzIyMDA4ZGZlNmExOTc0N2JmY2M3ZGI";
 export const supportUrl = "https://docs.k8slens.dev/latest/support/";
 
-const docsVersion = isProduction ? `v${packageInfo.version}` : "latest";
+// This explicitly ignores the prerelease info on the package version
+const { major, minor, patch } = new SemVer(packageInfo.version);
+const mmpVersion = [major, minor, patch].join(".");
```
Comment (jim-docker) [inline src/common/vars.ts:50]: The `v4.2.0` docs might not exist until `4.2.0` is actually released(?) This would mean 404 for `4.2.0-rc.1`. Just show latest? I guess either way it's wrong. But what you have here will work if someone installs an rc version after the final release was made.

**Review by jim-docker — APPROVED** [review]

File: src/common/vars.ts (hunk 2 above)
Comment (jakolehm) [reply src/common/vars.ts:50]: I agree with @jim-docker, pre-releases should point to `latest`.

**Review by jakolehm — APPROVED** [review]
I still think pre-release should point to "latest" but we can fix that later.

**Comment by Nokel81** [comment]
Shall I fix that in a follow up PR before we release, or it do it now? I completely forgot to implement that @jakolehm .

**Comment by jakolehm** [comment]
> Shall I fix that in a follow up PR before we release, or it do it now? I completely forgot to implement that @jakolehm .

IMHO this PR is already an improvement so follow up PR is fine.
