### PR TITLE
Fix Pod Container sorting not correlating to visuals

### LINKED ISSUE #5165: Pod list Containers sort doesn't work
https://user-images.githubusercontent.com/9607060/161237511-f8088df4-1152-46a5-b18b-c12287bf3ba0.mov

### PR DESCRIPTION
**Pull request by Nokel81**
- Add some specific tuple.zip types

- Remove the `string` part of `TableOrderBy` to simplify implementation
  and because it removes any sort of intellisense

Signed-off-by: Sebastian Malton <sebastian@malton.name>

fixes #5165

### CODE REVIEW

File: src/renderer/components/+workloads-pods/pods.tsx [hunk 1]
```diff
@@ -82,7 +82,7 @@ export class Pods extends React.Component {
           sortingCallbacks={{
             [columnId.name]: pod => getConvertedParts(pod.getName()),
             [columnId.namespace]: pod => pod.getNs(),
-            [columnId.containers]: pod => pod.getContainers().length,
+            [columnId.containers]: pod => pod.getContainerStatuses().length,
```
Comment (aleksfront) [inline src/renderer/components/+workloads-pods/pods.tsx:116]: I find it more intuitive to keep container amount as the sorting criteria. Sorting by the statuses is not clear enough.

**Review by aleksfront — CHANGES_REQUESTED** [review]

File: src/renderer/components/+workloads-pods/pods.tsx (hunk 1 above)
Comment (Nokel81) [reply src/renderer/components/+workloads-pods/pods.tsx:116]: Well the bug was that you found the previous sorting mechanism unintuitive. With this the sorting matches the visuals.

**Review by aleksfront — APPROVED** [review]

**Review by ixrock — APPROVED** [review]
