### PR TITLE
Fix PodDetailsList being empty over 100 pods

### LINKED ISSUE #4067: Node details pod list is empty if more than 100 pods
Probably because it switches to virtual mode if node has > 100 pods.

### PR DESCRIPTION
**Pull request by Nokel81**
- Add fixedHeight prop to VirtualList which bypasses AutoSizer behaviour
  when used as a child to "overflow: scroll" DOM nodes

- Minor cleanup on Table

Signed-off-by: Sebastian Malton <sebastian@malton.name>

fixes #4067

### CODE REVIEW

File: src/renderer/components/virtual-list/virtual-list.tsx [hunk 1]
```diff
@@ -98,34 +104,45 @@ export class VirtualList extends Component<Props, State> {
     this.listRef.current?.scrollToItem(index, align);
   };
 
-  render() {
-    const { width, className, items, getRow, onScroll, outerRef } = this.props;
+  renderVSL(height: number | undefined) {
```
Comment (aleksfront) [inline src/renderer/components/virtual-list/virtual-list.tsx]: `renderVSL` not a best name for the method, since `VSL` is impossible to understand at first sight. Maybe `renderList()`?

File: src/renderer/components/+workloads-pods/pod-details-list.tsx [hunk 2]
```diff
@@ -144,24 +132,36 @@ export class PodDetailsList extends React.Component<Props> {
   }
 
   render() {
-    const { pods, showTitle } = this.props;
-    const virtual = pods.length > 100;
```
Comment (aleksfront) [inline src/renderer/components/+workloads-pods/pod-details-list.tsx:148]: We should keep this trigger. We don't need to show empty long space if there's small amount of pods presented. Here is how it looks without `const virtual = pods.length > 100;`
long empty space

**Review by aleksfront — CHANGES_REQUESTED** [review]

File: src/renderer/components/+workloads-pods/pod-details-list.tsx (hunk 2 above)
Comment (Nokel81) [reply src/renderer/components/+workloads-pods/pod-details-list.tsx:148]: Okay sounds good, will make it shorter (probably around 20 or so) but good point.

**Review by aleksfront — APPROVED** [review]
