### PR TITLE
fix side bar scrolls after clicking on lower item

### LINKED ISSUE #828: Side bar scrolls after clicking on lower item
**Describe the bug**
If you expand some of the side bar items it becomes necessary to scroll down to see some items (such as Service Accounts). When you click on such an item the side bar immediately scrolls up, potentially hiding the currently selected item.

**To Reproduce**
1. Expand some items in the side bar until the scroll bar appears
2. Scroll the side bar down till you see Sevice Accounts (expand Access Control)
3. Select Service Accounts
4. See error (side bar scrolls back to top)

**Expected behavior**
Side bar should not scroll when selecting a visible item

**Screenshots**
navbarjump

**Environment (please complete the following information):**
- Lens Version: 3.6.0-rc.1
- OS: OSX
- Installation method (e.g. snap or AppImage in Linux): dmg

### PR DESCRIPTION
**Pull request by junior-5058**
fixes #828
`MainLayout` was used inside pages like `Network`, `Storage`, etc. When top level react-route is changed, `MainLayout` will be mount again. The `Sidebar` will be mount again as well. As a result, the side bar scrolls to the top. The pull request moves `MainLayout` inside `App` component to fix the issue.

### CODE REVIEW

File: src/renderer/components/layout/tab-layout.tsx [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+}
+
+interface Props {
+  children: ReactNode;
+  className?: any;
+  tabs?: TabRoute[];
+  contentClass?: string;
+}
+
+export const TabLayout = ({ className, contentClass, tabs, children }: Props) => {
```
Comment (ixrock) [inline src/renderer/components/layout/tab-layout.tsx]: This component should be wrapped into `observer` decorator from `mobx-react` in order to react to observables like `getHostedCluster()` and `navigation.location.pathname` used inside render().

**Review by ixrock — APPROVED** [review]
Thanks for PR! LGTM.

One thing I noticed though, at cluster home page (screenshot 1) there is no scrollbar in the sidebar when it should be (screenshot 2, clicked to nodes). This doesn't happen in current `master`. Please check.

**Screenshot 1**
Screenshot 2020-09-19 at 18 12 14

**Screenshot 2**
Screenshot 2020-09-19 at 18 12 22

**Review by ixrock — CHANGES_REQUESTED** [review]
Noticed also critical issue, there is no main/content area when sidebar is collapsed/minimized:
image

File: src/renderer/components/layout/tab-layout.tsx (hunk 1 above)
Comment (junior-5058) [reply src/renderer/components/layout/tab-layout.tsx]: @ixrock Thanks for your review. Wrapped `TabLayout` with `observer` in the latest commit.

**Comment by junior-5058** [comment]
@ixrock Thanks for your review. The main area missing issue is fixed in the latest commit. About no scrollbar in the sidebar, I couldn't reproduce on my machine. 
Screenshot 2020-09-19 at 22 00 19

**Comment by ixrock** [comment]
@wangyangjun please try to reduce window size to about **1099px** to reproduce scrollbar issue at main page, the layout should switch a bit at this breakpoint.

**Comment by junior-5058** [comment]
@ixrock reproduced the issue, will fix it later

**Comment by junior-5058** [comment]
@ixrock fixed with an update. Please review it again.

**Review by ixrock — APPROVED** [review]
