### PR TITLE
Fix filtering deprecated charts

### LINKED ISSUE #3515: Lens doesn't find/list all expected charts
**Describe the bug**
Hi. I have added some repositories like grafana

**To Reproduce**
1. Go to 'Preferences >  Kubernetes > Helm Charts > Select 'grafana' from the list'
2. Click on cluster on the sidebar
3. Scroll down to Apps > Charts
4. Search for Grafana
5. some charts are shown from the grafana repo but not all. The chart for grafana itself doesn't show up. I have tried `helm repo update` and closing/reopening the app but no difference.

**Expected behavior**
I would expect Lens to list all the charts in the enabled repos.

**Environment (please complete the following information):**
- Lens Version: 5.1.3-latest.20210722.1
- OS: [e.g. OSX] macOS Big Sur 11.5
- Installation method (e.g. snap or AppImage in Linux): Just downloaded the app from the website

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
````
https://pastebin.ubuntu.com/p/zwFQKy3hTk/
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ...
    server: https://x.x.x.x:6443
  name: alpha
contexts:
- context:
    cluster: alpha
    user: alpha
  name: alpha
current-context: alpha
kind: Config
preferences: {}
users:
- name: alpha
  user:
    client-certificate-data: ...
    client-key-data: ...e
```

**Additional context**
Not sure of what other info to provide. Thanks in advance!

### PR DESCRIPTION
**Pull request by Nokel81**
- Always show charts, just disable the option to select them in the
  details view

- Optimize the loading of repo charts to sort and normalize once

- Using the structured clone algorithm instead of JSON and fix the cache
  placement

Signed-off-by: Sebastian Malton <sebastian@malton.name>

fixes #3515

### CODE REVIEW

File: src/main/helm/helm-chart-manager.ts [hunk 1]
```diff
@@ -20,86 +20,100 @@
...
+              })),
+              logger.warn,
+            ),
+          ] as const)
+          .filter(([, charts]) => !charts.every(chart => chart.deprecated))
+      );
+
+      if (this.repo.name === "grafana") {
+        console.log(JSON.stringify(normalized));
       }
```
Comment (aleksfront) [inline src/main/helm/helm-chart-manager.ts]: Probably left from debugging?

File: src/main/helm/helm-chart-manager.ts [hunk 2]
```diff
@@ -20,86 +20,100 @@
...
-
-type CachedYaml = {
-  entries: RepoHelmChartList
-};
+import { sortCharts } from "../../common/utils";
 
 export class HelmChartManager {
-  protected cache: any = {};
-  protected repo: HelmRepo;
+  static #cache = new Map<string, Buffer>();
```
Comment (aleksfront) [inline src/main/helm/helm-chart-manager.ts:33]: We're not using such style anywhere else. Probably better to omit the hash sign?

File: src/main/helm/helm-chart-manager.ts [hunk 3]
```diff
@@ -20,86 +20,100 @@
...
+        Object.entries(entries)
+          .map(([name, charts]) => [
+            name,
+            sortCharts(
+              charts.map(chart => ({
+                ...chart,
+                created: Date.parse(chart.created).toString(),
+                repo: this.repo.name,
+              })),
+              logger.warn,
```
Comment (aleksfront) [inline src/main/helm/helm-chart-manager.ts]: Just to make sure. Will `logger.warm` be okay for both prod and dev environment?

**Review by aleksfront — COMMENTED** [review]
Left few minor comments. While testing works okay, fixes the issues listed in #3515. However, unable to find any deprecated chart versions to test this one (versions with `line-through` visibility) https://github.com/lensapp/lens/pull/3635/files#diff-4ada9d82cde72ab9fa11079e8dd1c571c9d3de88a5a5ff0494ac8c04eea92a25

File: src/main/helm/helm-chart-manager.ts (hunk 2 above)
Comment (Nokel81) [reply src/main/helm/helm-chart-manager.ts:33]: This is a better version of `private` as it is actually enforced at runtime

File: src/main/helm/helm-chart-manager.ts (hunk 3 above)
Comment (Nokel81) [reply src/main/helm/helm-chart-manager.ts]: Yes of course, though this was mostly don't so that we don't have warnings in the tests, I think I will change this.

**Comment by Nokel81** [comment]
> However, unable to find any deprecated chart versions to test this one (versions with line-through visibility)

Sure, you can add the `grafana             	https://grafana.github.io/helm-charts` repo, then the `grafana` chart has versions 5.5.7 and 5.5.6 which are deprecated.

File: src/main/helm/helm-chart-manager.ts (hunk 2 above)
Comment (aleksfront) [reply src/main/helm/helm-chart-manager.ts:33]: Why is this better? And why mark `static` property as private? Asking because static property can not be called on instance of a class.

File: src/common/utils/sort-compare.ts [hunk 4]
```diff
@@ -53,3 +56,32 @@ export function sortCompareChartVersions(left: ChartVersion, right: ChartVersion
...
+export function sortCharts(charts: RawHelmChart[]) {
+  interface ExtendedHelmChart extends RawHelmChart {
+    __version: SemVer;
+  }
+
+  const chartsWithVersion = Array.from(
+    iter.map(
+      charts,
+      (chart => {
+        const __version = coerce(chart.version, { includePrerelease: true, loose: true });
```
Comment (aleksfront) [inline src/common/utils/sort-compare.ts:71]: What is the meaning to use underscores before variable name here? `__version`?

File: src/main/helm/helm-chart-manager.ts [hunk 5]
```diff
@@ -20,86 +20,95 @@
...
+      return await this.cachedYaml();
     } catch(error) {
       logger.error("HELM-CHART-MANAGER]: failed to list charts", { error });
 
       return {};
     }
   }
 
-  public async getReadme(name: string, version = "") {
+  private async command(action: string, name: string, version?: string) {
```
Comment (aleksfront) [inline src/main/helm/helm-chart-manager.ts]:
```suggestion
  private async executeCommand(action: string, name: string, version?: string) {
```

File: src/main/helm/helm-chart-manager.ts (hunk 2 above)
Comment (Nokel81) [reply src/main/helm/helm-chart-manager.ts:33]: Same reason to mark an instance property as `private`, so to better model the encapsulation.

A `static` property that is `#` (JS private) cannot be accessed by code that is not a static member or an instance member.

File: src/common/utils/sort-compare.ts (hunk 4 above)
Comment (Nokel81) [reply src/common/utils/sort-compare.ts:71]: I meant it as both "temporary" and less likely to conflict with other fields. I chose `__version` because it is related to the `version` field but I don't want to override that field.

File: src/main/helm/helm-chart-manager.ts (hunk 5 above)
Comment (Nokel81) [reply src/main/helm/helm-chart-manager.ts]: sure

**Review by aleksfront — APPROVED** [review]
LGTM
