### PR TITLE
Refactor / fix cluster view visibility

### LINKED ISSUE #2653: Hotbar click does not always open a cluster dashboard
**Describe the bug**
Sometimes hotbar cluster icon click opens a catalog instead of a cluster dashboard.

**To Reproduce**
1. Add cluster A & B to hotbar
2. Click cluster A in hotbar
3. Click cluster B in hotbar
4. In some cases Lens shows Catalog instead of cluster B dashboard

**Expected behavior**
Lens should show clicked cluster dashboard always.

### PR DESCRIPTION
**Pull request by jakolehm**
Fixes #2653

### CODE REVIEW

File: src/renderer/components/hotbar/hotbar-menu.tsx [hunk 1]
```diff
@@ -26,7 +25,7 @@ export class HotbarMenu extends React.Component<Props> {
   }
 
   isActive(item: CatalogEntity) {
-    return ClusterStore.getInstance().activeClusterId == item.getId();
+    return catalogEntityRegistry.activeEntity?.metadata?.uid == item.getId();
```
Comment (jakolehm) [inline src/renderer/components/hotbar/hotbar-menu.tsx:28]: Changed because hotbar should only know about CatalogEntities.

File: src/renderer/api/catalog-entity-registry.ts [hunk 2]
```diff
@@ -39,6 +40,14 @@ export class CatalogEntityRegistry {
     });
   }
 
+  set activeEntity(entity: CatalogEntity) {
```
Comment (jakolehm) [inline src/renderer/api/catalog-entity-registry.ts:43]: Set/get because we might need to do some additional operations on `set` soon.

**Review by aleksfront — APPROVED** [review]

File: src/renderer/components/cluster-manager/cluster-view.tsx [hunk 3]
```diff
@@ -26,15 +27,37 @@ export class ClusterView extends React.Component<Props> {
...
+
+  showCluster(clusterId: string) {
+    initView(clusterId);
+    requestMain(clusterActivateHandler, this.clusterId, false);
+
+    const entity = catalogEntityRegistry.getById(this.clusterId);
+
+    if (entity) {
+      catalogEntityRegistry.activeEntity = entity;
+    }
```
Comment (Nokel81) [inline src/renderer/components/cluster-manager/cluster-view.tsx:50]: Why would we not revert to the catalog in the invalid ID state?

**Review by Nokel81 — APPROVED** [review]

File: src/renderer/components/cluster-manager/cluster-view.tsx (hunk 3 above)
Comment (jakolehm) [reply src/renderer/components/cluster-manager/cluster-view.tsx:50]: Good question, we probably should. I'll this (and few other things) in a follow-up PR.
