### PR TITLE
Fix auto update not working for AppImage

### LINKED ISSUE #3767: Linux AppImage: old version restarts after update
**Describe the bug**
On linux using the app, after clicking "Yes" on the update notification, the app automatically quits and is restarted but it it is the previous version that restarts.

**To Reproduce**
1. `./Lens-5.1.3-latest.20210722.1.x86_64.AppImage`
2. wait for update notification
3. click "Yes"
4. observe old version restarts
5. note that the new AppImage file has been downloaded (and the previous version file is gone) as expected

**Environment (please complete the following information):**
- Lens Version: 5.2.0 (perhaps any 5.x)
- OS: Linux
- Installation method: AppImage

### PR DESCRIPTION
**Pull request by Nokel81**
- Emulate electron.autoUpdater's 'before-quit-for-update' event flow

Signed-off-by: Sebastian Malton <sebastian@malton.name>

fixes #3767

### CODE REVIEW

File: src/main/app-updater.ts [hunk 1]
```diff
@@ -48,6 +48,8 @@ function handleAutoUpdateBackChannel(event: Electron.IpcMainEvent, ...[arg]: Upd
            * download it from itself via electron.
            */
           electronAutoUpdater.checkForUpdates();
+        } else if (isLinux) {
+          electronAutoUpdater.emit("before-quit-for-update");
```
Comment (jim-docker) [inline src/main/app-updater.ts]: nit: I guess the above comment should apply to this too

**Review by jim-docker — DISMISSED** [review]

File: src/main/app-updater.ts (hunk 1 above)
Comment (Nokel81) [reply src/main/app-updater.ts]: Sort of, the first line yes but the reason is different.

**Review by jim-docker — APPROVED** [review]
