### PR TITLE
Fix Extensions browse icon onClick event

### LINKED ISSUE #2851: Extensions browse button doesn't work
`onClick` event doesn't trigger showing Browse dialog.
broken browse

### PR DESCRIPTION
**Pull request by aleksfront**
browse button click

Fixes #2851 

Signed-off-by: Alex Andreev <alex.andreev.email@gmail.com>

### CODE REVIEW

File: src/renderer/components/+extensions/install.tsx [hunk 1]
```diff
@@ -29,6 +29,7 @@ import { SubTitle } from "../layout/sub-title";
 import { TooltipPosition } from "../tooltip";
 import { ExtensionInstallationStateStore } from "./extension-install.store";
 import { observer } from "mobx-react";
+import { MaterialTooltip } from "../+catalog/material-tooltip/material-tooltip";
```
Comment (jakolehm) [inline src/renderer/components/+extensions/install.tsx]: Already mentioned about this before but why `MaterialTooltip` is under `+catalog` if it's general purpose component?

Comment (aleksfront) [reply src/renderer/components/+extensions/install.tsx]: It was created in `+catalog` by mistake. Moved to `./components` just now.

**Review by jakolehm — APPROVED** [review]

**Review by ixrock — APPROVED** [review]
