### PR TITLE
Show event last-seen column in addition to age

### LINKED ISSUE #2819: Events: Last Seen column displays First Seen value
**Describe the bug**
The "Last Seen" column in the Events view on Lens currently displays the first seen value.

**To Reproduce**
1. Go to 'Events'
2. Show the "Last Seen" column
3. See incorrect value in Last Seen column

**Expected behavior**
The column should be the value of Last Seen.

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 4.2.4
- OS: OSX
- Installation method (e.g. snap or AppImage in Linux): Website

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
N/A
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
N/A
```

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by Nokel81**
Signed-off-by: Sebastian Malton <sebastian@malton.name>

fixes #2819

### CODE REVIEW

**Review by aleksfront — DISMISSED** [review]

File: src/renderer/components/+events/events.tsx [hunk 1]
```diff
@@ -163,7 +163,7 @@ export class Events extends React.Component<Props> {
           { title: "Involved Object", className: "object", sortBy: columnId.object, id: columnId.object },
           { title: "Source", className: "source", id: columnId.source },
           { title: "Count", className: "count", sortBy: columnId.count, id: columnId.count },
-          { title: "Last Seen", className: "age", sortBy: columnId.age, id: columnId.age },
+          { title: "Age", className: "age", sortBy: columnId.age, id: columnId.age },
```
Comment (jakolehm) [inline src/renderer/components/+events/events.tsx:169]: I think we should fix "Last Seen" instead of this.

**Review by jakolehm — CHANGES_REQUESTED** [review]

File: src/renderer/components/+events/events.tsx (hunk 1 above)
Comment (Nokel81) [reply src/renderer/components/+events/events.tsx:169]: How about both?

Comment (jim-docker) [reply src/renderer/components/+events/events.tsx:169]: what is meant by "Last Seen"? It can mean "when an event was last seen", which would be the age of the event. Or it can mean "show me the last event seen", so the default order would be from most recent to oldest(?) Or does it mean when a specific event was last seen, which would be an actual time value. I think "Age" makes it unambiguous.

Comment (Nokel81) [reply src/renderer/components/+events/events.tsx:169]: @jim-docker See discussion on https://github.com/lensapp/lens/issues/2819. Some controllers increment the count and last seen time instead of creating a new one.

**Review by nevalla — DISMISSED** [review]

File: src/renderer/api/endpoints/events.api.ts [hunk 2]
```diff
@@ -75,6 +75,10 @@ export class KubeEvent extends KubeObject {
 
     return formatDuration(diff, true);
   }
+
+  getLastSeenTimeDiffFromNow(): number {
```
Comment (jakolehm) [inline src/renderer/api/endpoints/events.api.ts]: Just a note that these kind of helper methods should not be in the api itself.. but we already have similar method so maybe it's fine to add "one more".

**Review by jakolehm — DISMISSED** [review]

File: src/renderer/api/endpoints/events.api.ts (hunk 2 above)
Comment (Nokel81) [reply src/renderer/api/endpoints/events.api.ts]: Okay makes sense, we probably want to remove both in the future. Shall I not make it worse in this PR?

**Review by jakolehm — APPROVED** [review]

**Review by jim-docker — APPROVED** [review]
