### PR TITLE
Fix auto-update exiting too fast

### LINKED ISSUE #2715: beta update notification quits and does nothing
after I click "Yes"
image

lens just quits and then when I re-open the beta it prompts this again.

### PR DESCRIPTION
**Pull request by jakolehm**
Fixes #2715

### CODE REVIEW

**Review by msa0311 — APPROVED** [review]

File: src/main/app-updater.ts [hunk 1]
```diff
@@ -17,7 +17,6 @@ function handleAutoUpdateBackChannel(event: Electron.IpcMainEvent, ...[arg]: Upd
     if (arg.now) {
       logger.info(`${AutoUpdateLogPrefix}: User chose to update now`);
       autoUpdater.quitAndInstall(true, true);
-      app.exit(); // this is needed for the installer not to fail on windows.
```
Comment (nevalla) [inline src/main/app-updater.ts:20]: Is the whole app exiting without this. I mean that the tray service also is closed?

**Review by nevalla — APPROVED** [review]
Tested on Mac and Windows and update process worked as expected.
