### PR TITLE
Fix opening of release details

### LINKED ISSUE #5767: Namespace error when upgrading a helm chart
**Describe the bug**
I am trying to upgrade a helm chart "cert-manager" that I had added to the namespace "cert-manager" from the UI

I get the following error message

> the namespace from the provided object "kube-system" does not match the namespace "cert-manager". You must pass '--namespace=kube-system' to perform this operation.

**To Reproduce**
1. Go to Lens > Helm > Releases
2. Click on a release, the upgrade
3. Select a higher version

**Expected behavior**
The helm chart should be upgraded in its namespace

**Screenshots**
Screenshot 2022-07-01 at 12 01 15

**Environment (please complete the following information):**
- Lens Version: Lens: 5.5.4-latest.20220609.2
- OS: macOs 12.3.1 (21E258)
- Installation method (e.g. snap or AppImage in Linux): manual download

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
N/A
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
cyrilduchon-doris@Cyril-DD-MacbookPro staging % cat ~/.kube/config
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: XXX==
    server: https://XXX.yl4.eu-central-1.eks.amazonaws.com
  name: arn:aws:eks:eu-central-1:XXX:cluster/mjg-dev
- cluster:
    certificate-authority-data: XXX==
    server: https://XXX.gr7.eu-central-1.eks.amazonaws.com
  name: arn:aws:eks:eu-central-1:XXX:cluster/mjg-production
contexts:
- context:
    cluster: arn:aws:eks:eu-central-1:XXX:cluster/mjg-dev
    user: arn:aws:eks:eu-central-1:XXX:cluster/mjg-dev
  name: arn:aws:eks:eu-central-1:XXX:cluster/mjg-dev
- context:
    cluster: arn:aws:eks:eu-central-1:113227347315:cluster/mjg-production
    user: arn:aws:eks:eu-central-1:113227347315:cluster/mjg-production
  name: arn:aws:eks:eu-central-1:113227347315:cluster/mjg-production
current-context: arn:aws:eks:eu-central-1:113227347315:cluster/mjg-dev
kind: Config
preferences: {}
users:
- name: arn:aws:eks:eu-central-1:xxx:cluster/mjg-dev
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - eu-central-1
      - eks
      - get-token
      - --cluster-name
      - mjg-dev
      command: aws
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
- name: arn:aws:eks:eu-central-1:xxx:cluster/mjg-production
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - eu-central-1
      - eks
      - get-token
      - --cluster-name
      - mjg-production
      command: aws
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
```

**Additional context**

### LINKED ISSUE #5849: Unrelated resources shown in release details
**Describe the bug**
When I open details for a Helm Release, there is list of resources which contain clearly unrelated resources.

**To Reproduce**
1. Install two helm charts
2. Open details for helm release
3. Scroll down to see list of resources
5. See that it lists unrelated resources 

**Expected behavior**
Only resources created by release should be listed

**Screenshots**

https://user-images.githubusercontent.com/3083083/179717318-1e4505b7-7214-4577-84aa-c9b0a5fc7dcb.mov

**Environment (please complete the following information):**
- Lens Version: 5.6.0-alpha.6.2
- OS: OSX

### PR DESCRIPTION
**Pull request by jansav**
Fixes #5767
Fixes #5849

### CODE REVIEW

**Comment by jansav** [comment]
Working on adding behaviour to cover this

File: src/main/helm/helm-release-manager.ts [hunk 1]
```diff
@@ -191,7 +191,6 @@ async function getResources(name: string, namespace: string, kubeconfigPath: str
   ];
   const kubectlArgs = [
     "get",
-    "--namespace", namespace,
```
Comment (Nokel81) [inline src/main/helm/helm-release-manager.ts:194]: Why would removing the namespace mean that the "correct" resources are retrieved?

Comment (jansav) [reply src/main/helm/helm-release-manager.ts:194]: This part fixes the crash.  https://github.com/lensapp/lens/issues/5767

Comment (jansav) [reply src/main/helm/helm-release-manager.ts:194]: Other changes fixes https://github.com/lensapp/lens/issues/5849.

But more changes are coming when I get the behaviours in because I can already see two blindspots which lead to crash in correct circumstance.

File: src/renderer/components/+helm-releases/release-details/release-details.tsx [hunk 2]
```diff
@@ -70,7 +71,11 @@ class NonInjectedReleaseDetails extends Component<ReleaseDetailsProps & Dependen
   }
 
   @computed get details() {
-    return this.props.releaseDetails.value.get();
+    const details = this.props.releaseDetails.value.get();
+
+    assert(details);
+
+    return details;
   }
```
Comment (Nokel81) [inline src/renderer/components/+helm-releases/release-details/release-details.tsx]: Given that this is only used in the `renderNotes` function below and that is only used once in `renderContent`, I think we probably could just drop this computed and just pipe the value through.

Comment (jansav) [reply src/renderer/components/+helm-releases/release-details/release-details.tsx]: Resolving this because I implemented details to remove many bugs and blindspots.

**Comment by jansav** [comment]
@Nokel81 @jim-docker This is now ready for review. It's fully behavioural tested, so please review that behaviour is correct.

File: src/main/getDiForUnitTesting.ts [hunk 3]
```diff
@@ -124,6 +124,16 @@ export function getDiForUnitTesting(opts: { doGeneralOverrides?: boolean } = {})
...
+    const globalOverrideFilePaths = getGlobalOverridePaths();
+
+    const globalOverrides = globalOverrideFilePaths.map(
+      (filePath) => require(filePath).default,
+    );
+
+    globalOverrides.forEach(globalOverride => {
+      di.override(globalOverride.injectable, globalOverride.overridingInstantiate);
+    });
+
```
Comment (jansav) [inline src/main/getDiForUnitTesting.ts:136]: Note: This is here so that we can stop bloating this file. We can now just add file with postfix `.global-override-for-injectable.ts` which is used for override automatically.

File: src/renderer/components/+helm-releases/call-for-helm-releases/call-for-helm-releases.global-override-for-injectable.ts [hunk 4]
```diff
@@ -0,0 +1,15 @@
...
+import { getGlobalOverride } from "../../../../common/test-utils/get-global-override";
+
+export default getGlobalOverride(
+  callForHelmReleasesInjectable,
+  () => () => {
+    throw new Error(
+      "Tried to call for helm releases without explicit override.",
+    );
+  },
+);
```
Comment (jansav) [inline src/renderer/components/+helm-releases/call-for-helm-releases/call-for-helm-releases.global-override-for-injectable.ts:15]: Note: First example of global override.

File: src/main/getDiForUnitTesting.ts (hunk 3 above)
Comment (jansav) [reply src/main/getDiForUnitTesting.ts:136]: In future PR, we can consolidate all overrides here to new way.

File: src/renderer/components/+helm-releases/release-details/release-details-content.tsx [hunk 5]
```diff
@@ -0,0 +1,210 @@
...
+      testIdForClose="close-helm-release-detail"
+      toolbar={
+        !isLoading && (
+          <HelmReleaseMenu
+            release={model.release}
+            toolbar
+            hideDetails={model.close}
+          />
+        )
+      }
```
Comment (jansav) [inline src/renderer/components/+helm-releases/release-details/release-details-content.tsx:56]: Notice: Here the pain is that we have to set `title` and `toolbar` even though we don't have the data yet. Drawer needs to be refactored to place where we can set `title` and `toolbar` later.

It would look something like this:

```jsx
return (
  <Drawer open={true}>
    <DrawerHeader>
      <span>{model.release.getName()}</span>
     
      <HelmReleaseMenu toolbar release={model.release} />
    </DrawerHeader>

    <DrawerContent>
      Some content
    </DrawerContent>
  </Drawer>
)
```

In that case we could:

```jsx
return (
  <Drawer open={true}>
    <ReleaseDetailsContent />
  </Drawer>
);
```

And now `ReleaseDetailsContent` could have `async` dependency and `getPlaceholder` which returns spinner that looks good for drawer.

---

**Key thing is to start combining different components and stop expanding the scope of a single component by adding more props. That gives us flexibility, when latter only limits our ability to change our mind later.**

File: src/renderer/components/+helm-releases/release-details/release-details-model/release-details-model.injectable.tsx [hunk 6]
```diff
@@ -0,0 +1,312 @@
...
+  callForHelmReleaseConfiguration: CallForHelmReleaseConfiguration;
+  getResourceDetailsUrl: GetResourceDetailsUrl;
+  updateRelease: CallForHelmReleaseUpdate;
+  showCheckedErrorNotification: ShowCheckedErrorNotification;
+  showSuccessNotification: ShowNotification;
+  createUpgradeChartTab: (release: HelmRelease) => string;
+  navigateToHelmReleases: NavigateToHelmReleases;
+}
+
+export class ReleaseDetailsModel {
```
Comment (jansav) [inline src/renderer/components/+helm-releases/release-details/release-details-model/release-details-model.injectable.tsx:105]: Note: I'd call this view model since it is the only dependency that `ReleaseDetails` has and it combines all of the functionality and business logic details needs. It doesn't expose anything else than is required and it's allowed to be injected only by `ReleaseDetails`. Therefore it serves only one purpose.

File: src/renderer/components/dock/upgrade-chart/view.tsx [hunk 7]
```diff
@@ -96,7 +98,7 @@ export class NonInjectedUpgradeChart extends React.Component<UpgradeChartProps &
     const versions = await helmChartStore.getVersions(release.getChart());
 
     this.versions.replace(versions);
-    this.version = this.versions[0];
+    this.version = first(this.versions);
```
Comment (jansav) [inline src/renderer/components/dock/upgrade-chart/view.tsx:101]: Note: had to do this since opening tab for the purpose of upgrading chart shows warning without the data. There is still open issue for the crashes in upgrade #5852.

File: src/main/getDiForUnitTesting.ts (hunk 3 above)
Comment (Nokel81) [reply src/main/getDiForUnitTesting.ts:136]: Is this worth it though since the end game would be to have as few of these global overrides as possible?

File: src/renderer/components/+helm-releases/release-details/release-details-model/release-details-model.injectable.tsx [hunk 8]
```diff
@@ -0,0 +1,312 @@
...
+    // TODO: Reorganize Drawer to allow setting of header-bar in children to make "getPlaceholder" from injectable usable.
+    load();
+
+    return model;
+  },
+
+  lifecycle: lifecycleEnum.keyedSingleton({
+    getInstanceKey: (di, release: TargetHelmRelease) =>
+      `${release?.namespace}/${release?.name}`,
+  }),
```
Comment (Nokel81) [inline src/renderer/components/+helm-releases/release-details/release-details-model/release-details-model.injectable.tsx]: This seems weird, why is it `release?.namespace` and not `release.namespace`? If the reason is that `release` could be `undefined | null` then why is the function not declaring that?

File: src/renderer/components/+helm-releases/release-details/release-details-model/release-details-model.injectable.tsx [hunk 9]
```diff
@@ -0,0 +1,312 @@
...
+    this.dependencies.createUpgradeChartTab(this.release);
+
+    this.close();
+  };
+
+  @computed get id() {
+    const { name, namespace } = this.dependencies.targetRelease;
+
+    return `${namespace}/${name}`;
+  }
```
Comment (Nokel81) [inline src/renderer/components/+helm-releases/release-details/release-details-model/release-details-model.injectable.tsx]: nit: this seems strange, why is not just assigned once at construction time?

File: src/renderer/components/dock/upgrade-chart/view.tsx (hunk 7 above)
Comment (Nokel81) [reply src/renderer/components/dock/upgrade-chart/view.tsx:101]: What is the difference then? Or do you mean a mobx warning in the console?

File: src/behaviours/helm-releases/showing-details-for-helm-release.test.ts [hunk 10]
```diff
@@ -0,0 +1,604 @@
...
+
+      rendererDi.override(
+        callForHelmReleasesInjectable,
+        () => callForHelmReleasesMock,
+      );
+
+      rendererDi.override(
+        callForHelmReleaseInjectable,
+        () => callForHelmReleaseMock,
+      );
```
Comment (Nokel81) [inline src/behaviours/helm-releases/showing-details-for-helm-release.test.ts:80]: why the duplicate calls to override?

**Review by Nokel81 — COMMENTED** [review]
The behaviours look good

File: src/renderer/components/+helm-releases/release-details/release-details-model/release-details-model.injectable.tsx (hunk 8 above)
Comment (jansav) [reply src/renderer/components/+helm-releases/release-details/release-details-model/release-details-model.injectable.tsx]: Good catch. Removed the optional chaining.

File: src/renderer/components/+helm-releases/release-details/release-details-model/release-details-model.injectable.tsx (hunk 9 above)
Comment (jansav) [reply src/renderer/components/+helm-releases/release-details/release-details-model/release-details-model.injectable.tsx]: Sure, changed.

File: src/behaviours/helm-releases/showing-details-for-helm-release.test.ts (hunk 10 above)
Comment (jansav) [reply src/behaviours/helm-releases/showing-details-for-helm-release.test.ts:80]: `releases` vs `release` :)

**Comment by jansav** [comment]
> What is the difference then? Or do you mean a mobx warning in the console?

No difference in behaviour, but gets rid of MobX warning.

**Comment by jansav** [comment]
> Is this worth it though since the end game would be to have as few of these global overrides as possible?

It is, because I don't see how we could get rid of global overrides before this file gets out of control. In the end, it's very easy to remove if we don't need it. Even though we wouldn't refactor existing ones, adding new is a lot easier because now global override can live right next to the actual implementation.

**Review by Nokel81 — APPROVED** [review]

File: src/renderer/components/+helm-releases/release-details/release-details-content.tsx (hunk 5 above)
Comment (aleksfront) [reply src/renderer/components/+helm-releases/release-details/release-details-content.tsx:56]: Totally agree, let's do this.

**Review by aleksfront — APPROVED** [review]
