### PR TITLE
display last-applied-configuration annotation in detail-view

### LINKED ISSUE #719: Only single line annotations are shown in detailed view
**Describe the bug**
When getting details about an object, for instance deployments, daemon sets or services, the detail view will display only single line annotations and will ignore those that are multiline

**To Reproduce**

In the attached window capture you can see how a service that has two annotations is shown as having only one annotation, having the multi-line annotation (kubectl.kubernetes.io/last-applied-configuration) ignored.

Screen Shot 2020-08-20 at 11 50 43

**Expected behavior**
I expect either:
* To display the full annotation in a foldable way, a multi-line annotation can take a lot of space and we don't want that
* To get an indication that the annotation is there, maybe just the name equals three dots as I can always go to edit to see it

What I find misleading is that the annotation just "disappears". That can make me miss something important.

**Screenshots**
See above in explanation

**Environment (please complete the following information):**
- Lens Version: 3.5.3
- OS: OSX
- Installation method: brew
 
**Logs:**
Not applicable

**Kubeconfig:**
Not applicable

**Additional context**
Not applicable

### PR DESCRIPTION
**Pull request by junior-5058**
fix #719 display last-applied-configuration annotation in detail-view , but still filter it in search fields

Signed-off-by: Yangjun Wang <yangjun.wang@wartsila.com>

### CODE REVIEW

File: src/renderer/api/kube-object.ts [hunk 1]
```diff
@@ -115,12 +115,12 @@ export class KubeObject implements ItemObject {
     return KubeObject.stringifyLabels(this.metadata.labels);
   }
 
-  getAnnotations(): string[] {
+  getAnnotations(filter = false): string[] {
```
Comment (ixrock) [inline src/renderer/api/kube-object.ts:118]: Maybe it's better to make first argument `filter` as a callback: `filter: (label: string) => boolean` for more flexible filtering.

So instead of `...getAnnotations(true)` would be like:
```ts
...getAnnotations(label => resourceApplierApi.annotations.some(skipLabel => !label.startsWith(skipLabel)))
```

**Review by ixrock — APPROVED** [review]
LGTM

File: src/renderer/api/kube-object.ts (hunk 1 above)
Comment (junior-5058) [reply src/renderer/api/kube-object.ts:118]: It doesn't look good when multi places have logic like `...getAnnotations(label => resourceApplierApi.annotations.some(skipLabel => !label.startsWith(skipLabel)))`

**Comment by ixrock** [comment]
@nevalla integration tests on Windows again failed, can't spot why.. any clue?
image

File: src/renderer/api/kube-object.ts (hunk 1 above)
Comment (ixrock) [reply src/renderer/api/kube-object.ts:118]: it's okay, they just should not repeating same inline filter and extracted to function in order to reuse.
Currently it's always bound to some dependent label list, but maybe it's fine for now.

**Comment by Nokel81** [comment]
@ixrock not any more, shall we merge this?
