### PR TITLE
fix: Don't crash when hovering hotbar menu index

### LINKED ISSUE #7703: Crash when hovering or changing hot bars
**Describe the bug**
The UI displays an error when hovering the hotbar input or clicking the arrows to change hotbars.

**To Reproduce**
1. Go to 'Catalog'
2. Hover on hotbar input
3. See error

**Expected behavior**
A tooltip with the hotbar is displayed

**Screenshots**

https://github.com/lensapp/lens/assets/774344/fa9f0ef6-0633-4c53-9715-30ae26ef0f29

**Environment (please complete the following information):**
- Lens Version: 
LensDev: 9000.0.1
Extension API: 6.5.0
Electron: 22.3.5
Chrome: 108.0.5359.215
Node: 16.17.1
© 2023 Mirantis, Inc.
- OS: [e.g. OSX] macos

Additional investigation reveals the error might be related to `tooltip.tsx` because that's the component that the error is referencing.

### PR DESCRIPTION
**Pull request by Nokel81**
- Remove all uses of React.ReactNode as it is unsafe, replace them with usages of SafeReactNode which doesn't contain the '{}' type

closes #7703

### CODE REVIEW

**Comment by jansav** [comment]
I don't understand. Why is `ReactNode` not safe?

File: packages/core/src/renderer/components/custom-resources/crd-resources.tsx [hunk 1]
```diff
@@ -106,7 +106,11 @@ class NonInjectedCustomResources extends React.Component<Dependencies> {
             isNamespaced && (
               <NamespaceSelectBadge namespace={customResource.getNs() as string} />
             ),
-            ...extraColumns.map((column) => safeJSONPathValue(customResource, column.jsonPath)),
+            ...(
+              extraColumns
+                .map((column) => safeJSONPathValue(customResource, column.jsonPath))
+                .map(formatJSONValue)
+            ),
```
Comment (jansav) [inline packages/core/src/renderer/components/custom-resources/crd-resources.tsx]: Is this the real fix? In this type of PRs it would be easier if there was a separate commit for consolidating types and the real fix.

File: packages/core/src/renderer/components/dropdown/dropdown.tsx [hunk 2]
```diff
@@ -31,7 +34,7 @@ export function Dropdown(props: DropdownProps) {
         close={toggle}
         open={toggle}
       >
-        {React.Children.toArray(children)}
+        {toSafeReactChildrenArray(children)}
```
Comment (jansav) [inline packages/core/src/renderer/components/dropdown/dropdown.tsx]: How is this different than`{children}` since we are not manipulating children at all? Notice that overall manipulating children is considered bad practice.

Comment (jansav) [reply packages/core/src/renderer/components/dropdown/dropdown.tsx]:
```tsx
<Dropdown>{[<SomeComponent key={1} />, <SomeComponent key={2} />]}</Dropdown>
```

Works fine with `{children}`

File: packages/core/src/renderer/components/hotbar/hotbar-cell.tsx [hunk 3]
```diff
@@ -4,13 +4,12 @@
...
-import type { HTMLAttributes, ReactNode } from "react";
 import React, { useState } from "react";
-
+import type { SafeReactNode, SingleOrMany } from "@k8slens/utilities";
 import { cssNames } from "@k8slens/utilities";
 
-export interface HotbarCellProps extends HTMLAttributes<HTMLDivElement> {
-  children?: ReactNode;
+export interface HotbarCellProps extends React.HTMLAttributes<HTMLDivElement> {
+  children?: SingleOrMany<SafeReactNode>;
```
Comment (jansav) [inline packages/core/src/renderer/components/hotbar/hotbar-cell.tsx]: `ReactNode` accepts array by default so `SingleOrMany` is not needed.

File: packages/core/src/renderer/components/layout/main-layout.tsx [hunk 4]
```diff
@@ -16,10 +17,10 @@ import sidebarStorageInjectable, { defaultSidebarWidth } from "./sidebar-storage
 import type { StorageLayer } from "../../utils/storage-helper";
 
 export interface MainLayoutProps {
-  sidebar: React.ReactNode;
+  sidebar: SafeReactNode;
   className?: string;
-  footer?: React.ReactNode;
-  children?: React.ReactNode | React.ReactNode[];
+  footer?: SafeReactNode;
+  children?: SingleOrMany<SafeReactNode>;
```
Comment (jansav) [inline packages/core/src/renderer/components/layout/main-layout.tsx]: `React.ReactNode` is enough

**Review by jansav — CHANGES_REQUESTED** [review]
1. We shouldn't introduce new type for `ReactNode` which is somehow magically safer than the original. If the motivation is to prevent developer from forgetting to add `.get()` to observable, then we have bigger issues... This would mean that developer has **never** tried the change because there's no way that it would ever work properly. Also unit tests would catch it.
2. `SingleOrMany` is unnecessary because `ReactNode` accepts array of react nodes by default. 
3. Usage of `React.Children.toArray` is unnecessary because `{children}` would be enough.
4. ~There's only one change in implementation and that doesn't have anything to do with hotbar, so how could it solve something for hotbar?~
5. Unit tests for the fix?

File: packages/core/src/renderer/components/hotbar/hotbar-selector.tsx [hunk 5]
```diff
@@ -88,7 +88,7 @@ const NonInjectedHotbarSelector = observer(({
           targetId="hotbarIndex"
           preferredPositions={[TooltipPosition.TOP, TooltipPosition.TOP_LEFT]}
         >
-          {hotbar?.name}
+          {hotbar?.name.get()}
```
Comment (jansav) [inline packages/core/src/renderer/components/hotbar/hotbar-selector.tsx:94]: Ok, so this is the real fix. Everything else is something unrelated.

**Comment by Iku-turso** [comment]
It would seem to me that here the medicine of introducing custom types for a very specific purpose is worse than the sickness of forgetting to use an `observable` in any proper way. This human error should be abundantly apparent through unit- and even manual-testing... And if it is not that yet, addin unit tests to prove proper use would be far better time investment.

I propose adding said unit tests, doing the following actual fix, and calling it done.
```
-         {hotbar?.name}
+         {hotbar?.name.get()}
```

**Comment by Nokel81** [comment]
I propose also adding unit tests, but keeping the safer types as additional safety.

File: packages/core/src/renderer/components/dropdown/dropdown.tsx (hunk 2 above)
Comment (Nokel81) [reply packages/core/src/renderer/components/dropdown/dropdown.tsx]: Sounds good

File: packages/core/src/renderer/components/layout/main-layout.tsx (hunk 4 above)
Comment (Nokel81) [reply packages/core/src/renderer/components/layout/main-layout.tsx]: No it is not, but `SafeReactNode` (or `StrictReactNode`)

File: packages/core/src/renderer/components/custom-resources/crd-resources.tsx (hunk 1 above)
Comment (Nokel81) [reply packages/core/src/renderer/components/custom-resources/crd-resources.tsx]: Will also add some tests for this

File: packages/utility-features/utilities/src/isReactNode.ts [hunk 6]
```diff
@@ -3,12 +3,31 @@
...
+export type StrictReactFragment =
+  | {
+      key?: string | number | null;
+      ref?: null;
+      props?: {
+        children?: StrictReactNode;
+      };
+    };
+
+export type StrictReactNode =
```
Comment (Iku-turso) [inline packages/utility-features/utilities/src/isReactNode.ts:20]: It would make sense for react itself to expose this typing. Weird stuff.

File: packages/utility-features/utilities/src/isReactNode.ts [hunk 7]
```diff
@@ -3,12 +3,31 @@
...
+  | React.ReactElement
+  | React.ReactText
+  | StrictReactFragment
+  | React.ReactPortal
+  | Iterable<StrictReactNode>
+  | boolean
+  | null
+  | undefined;
```
Comment (Iku-turso) [inline packages/utility-features/utilities/src/isReactNode.ts:28]: Even if react 18 now permits rendering `undefined`, should we internally advocate that? WDYT?

**Review by Iku-turso — APPROVED** [review]
Check comments and merge on will.

**Review by Iku-turso — DISMISSED** [review]
Ok with unit tests.

**Review by jansav — DISMISSED** [review]

File: packages/utility-features/utilities/src/isReactNode.ts (hunk 7 above)
Comment (Nokel81) [reply packages/utility-features/utilities/src/isReactNode.ts:28]: Probably a good idea to remove, will try it.

File: packages/utility-features/utilities/src/isReactNode.ts (hunk 6 above)
Comment (Nokel81) [reply packages/utility-features/utilities/src/isReactNode.ts:20]: Yeah..., might not be needed in react 18 but since we are in react 17 still that might be the problem.

**Review by gabriel-mirantis — APPROVED** [review]
