### PR TITLE
Prefer ref over findDOMNode to make unit tests not flaky

### LINKED ISSUE #4354: Dialog uses non-React event handling causing problems in e.g. unit testing
A way that dialog is closed when clicking outside of the dialog is causing flaky issues when e.g. unit testing components containing dialog. There is a reason why there is eslint rule for it. 

## Culprit
```javascript
get elem() {
  // eslint-disable-next-line react/no-find-dom-node
  return findDOMNode(this) as HTMLElement;
}
```

## Error:

```
Unable to find node on an unmounted component.

      73 |   get elem() {
      74 |     // eslint-disable-next-line react/no-find-dom-node
    > 75 |     return findDOMNode(this) as HTMLElement;
         |                       ^
      76 |   }
      77 |
      78 |   get isOpen() {

      at findCurrentFiberUsingSlowPath (node_modules/react-dom/cjs/react-dom.development.js:4452:13)
      at findCurrentHostFiber (node_modules/react-dom/cjs/react-dom.development.js:4465:23)
      at findHostInstanceWithWarning (node_modules/react-dom/cjs/react-dom.development.js:25389:21)
      at findDOMNode (node_modules/react-dom/cjs/react-dom.development.js:26067:12)
      at Dialog.get elem [as elem] (src/renderer/components/dialog/dialog.tsx:75:23)
      at value (src/renderer/components/dialog/dialog.tsx:119:16)
      at runAnimationFrameCallbacks (node_modules/jsdom/lib/jsdom/browser/Window.js:599:13)
      at Timeout._onTimeout (node_modules/jsdom/lib/jsdom/browser/Window.js:577:11)
```

This blocks merging of #4282.

### PR DESCRIPTION
**Pull request by jansav**
Co-authored-by: Mikko Aspiala <mikko.aspiala@gmail.com>
Signed-off-by: Janne Savolainen <janne.savolainen@live.fi>

Fixes #4354

### CODE REVIEW

File: src/renderer/components/dialog/dialog.tsx [hunk 1]
```diff
@@ -70,8 +71,7 @@ export class Dialog extends React.PureComponent<DialogProps, DialogState> {
   };
 
   get elem() {
-    // eslint-disable-next-line react/no-find-dom-node
-    return findDOMNode(this) as HTMLElement;
+    return this.ref.current as HTMLElement;
```
Comment (Nokel81) [inline src/renderer/components/dialog/dialog.tsx]: Why do you need the cast?

Comment (jansav) [reply src/renderer/components/dialog/dialog.tsx]: Removed.

**Review by Nokel81 — APPROVED** [review]
