### PR TITLE
Fix: closing workspace menu after clicking on iframe

### LINKED ISSUE #2317: WorkspaceMenu does not close after mouse click on iframe
The WorkspaceMenu does not close when the mouse is clicked outside it (specifically when clicking anywhere on dashboard). This looks particularly bad when the cluster settings page is opened from the top right cog, or preferences or extension pages are opened.

Screen Shot 2021-03-11 at 10 42 34 AM

### PR DESCRIPTION
**Pull request by aleksfront**
`iframe` doesn't have `onClick` event handler, but it's possible to work with `window.onBlur` and `document.activeElement` to detect such "clicks".

closing workspace menu

Fixes #2317 

Signed-off-by: Alex Andreev <alex.andreev.email@gmail.com>

### CODE REVIEW

**Comment by aleksfront** [comment]
Switched `z-index` for menu and generic pages fixing visible menu when Preferences is open.
menu behind page

File: src/renderer/components/menu/menu.tsx [hunk 1]
```diff
@@ -232,6 +233,12 @@ export class Menu extends React.Component<MenuProps, State> {
     }
   }
 
+  onBlur() {
+    if (document.activeElement?.tagName == "IFRAME") {
```
Comment (Nokel81) [inline src/renderer/components/menu/menu.tsx:237]: Is this guaranteed to be upper case. Would checking the lower case be safer?

**Review by Nokel81 — APPROVED** [review]

File: src/renderer/components/menu/menu.tsx (hunk 1 above)
Comment (aleksfront) [reply src/renderer/components/menu/menu.tsx:237]: First iteration was with `toLowerCase` checking. But it's safe while we're using `html` not `xhtml` for our markup.

Comment (Nokel81) [reply src/renderer/components/menu/menu.tsx:237]: okay

**Review by jim-docker — APPROVED** [review]
The workspace menu should probably also hide when an app menu is clicked on, but this is less serious(?)

**Comment by Nokel81** [comment]
@jim-docker I agree but that is currently the case for all of Lens's `<Menu />`'s
