### PR TITLE
Handle suspend/resume error from watch stream read

### LINKED ISSUE #2133: Kubernetes watch does not always retry after resume from sleep
**Describe the bug**

Watch that already has received data does not retry if computer goes to sleep for a moment and resumes so fast that network does not go offline during the sleep. 

Note: retry works if watch didn't get any data before computer goes to sleep.

### PR DESCRIPTION
**Pull request by jakolehm**
Had to copy `ReadableWebToNodeStream` to here because we cannot catch read errors with the upstream version. We should probably contribute a fix to upstream.

Fixes #2133

### CODE REVIEW

**Review by nevalla — APPROVED** [review]
LGTM

File: src/renderer/api/kube-api.ts [hunk 1]
```diff
@@ -387,14 +393,17 @@ export class KubeApi<T extends KubeObject = any> {
...
-        if (errorReceived) return; // kubernetes errors should be handled in a callback
+      ["end", "close", "error"].forEach((eventName) => {
+        nodeStream.on(eventName, () => {
+          if (errorReceived) return; // kubernetes errors should be handled in a callback
 
-        setTimeout(() => { // we did not get any kubernetes errors so let's retry
-          if (abortController.signal.aborted) return;
+          clearTimeout(timedRetry);
+          timedRetry = setTimeout(() => { // we did not get any kubernetes errors so let's retry
+            if (abortController.signal.aborted) return;
```
Comment (Nokel81) [inline src/renderer/api/kube-api.ts:402]: Why do we need this give lines 379-381 above, if the signal has already aborted, shouldn't the watch just stop anyway?

File: src/renderer/utils/readableStream.ts [hunk 2]
```diff
@@ -0,0 +1,87 @@
...
+
+      if (data.done || this.released) {
+        this.push(null); // Signal EOF
+      } else {
+        this.bytesRead += data.value.length;
+        this.push(data.value); // Push new data to the queue
+      }
+    } catch(error) {
+      this.push(null); // Signal EOF
+    }
```
Comment (Nokel81) [inline src/renderer/utils/readableStream.ts:62]: This is the change? Why do we want to signal `EOF` on an error? Shouldn't we log these errors anyway?

File: src/renderer/utils/readableStream.ts [hunk 3]
```diff
@@ -0,0 +1,87 @@
+import { Readable } from "readable-stream";
```
Comment (ixrock) [inline src/renderer/utils/readableStream.ts:1]:
```suggestion
import { Readable } from "stream";
```

> This package is a mirror of the streams implementations in Node.js.
>
> If you want to guarantee a stable streams base, regardless of what version of Node you, or the users of your libraries are using, use readable-stream only and avoid the "stream" module in Node-core, for background see this blogpost.

Since we bundle app with Node.js `v12.x` maybe we could use native `stream` module?
https://nodejs.org/dist/latest-v12.x/docs/api/stream.html#stream_readable_streams

**Review by ixrock — APPROVED** [review]

File: src/renderer/api/kube-api.ts [hunk 4]
```diff
@@ -387,14 +393,17 @@ export class KubeApi<T extends KubeObject = any> {
       }
       const nodeStream = new ReadableWebToNodeStream(response.body);
 
-      nodeStream.on("end", () => {
-        if (errorReceived) return; // kubernetes errors should be handled in a callback
+      ["end", "close", "error"].forEach((eventName) => {
+        nodeStream.on(eventName, () => {
+          if (errorReceived) return; // kubernetes errors should be handled in a callback
```
Comment (Nokel81) [inline src/renderer/api/kube-api.ts:398]: I think this comment is wrong. Shouldn't it read something like:

```
// kubernetes error status events should prevent auto retrying of the watch.
```

File: src/renderer/api/kube-api.ts (hunk 1 above)
Comment (jakolehm) [reply src/renderer/api/kube-api.ts:402]: You are right, we don't need this.

File: src/renderer/utils/readableStream.ts (hunk 2 above)
Comment (jakolehm) [reply src/renderer/utils/readableStream.ts:62]: We cannot even catch errors that are thrown from here. If we could I would not have copied this library to our codebase.

All other error cases end up with EOF so it makes sense to push this error to the similar path. I really would like to get this fix into upstream and that means this class itself won't be logging anything.

**Comment by jakolehm** [comment]
@ixrock @Nokel81 I'll open a separate PR based on suggestions.

File: src/renderer/utils/readableStream.ts (hunk 3 above)
Comment (jakolehm) [reply src/renderer/utils/readableStream.ts:1]: Makes sense, I'll do that in a separate PR.
