### PR TITLE
fix: Retrieve projectVersion from main for 'extensions-persistent-storage'

### LINKED ISSUE #7803: Remove temporary hard-coding for lens-extensions store version
**Describe the bug**
A temporary fix (#7801 ) was done for #7784. The proper solution should involve determining the migration version from main (when on renderer)

### PR DESCRIPTION
**Pull request by Nokel81**
- Prevent the version being changed by the renderer

### CODE REVIEW

File: packages/core/src/features/extensions/enabled/main/storage-version.injectable.ts [hunk 1]
```diff
@@ -0,0 +1,17 @@
+/**
+ * Copyright (c) OpenLens Authors. All rights reserved.
+ * Licensed under MIT License. See LICENSE in root directory for more information.
+ */
+import storageMigrationVersionInjectable from "../../../../common/persistent-storage/storage-migration-version.injectable";
+import { enabledExtensionsMigrationDeclarationInjectionToken } from "../common/migrations";
```
Comment (jim-docker) [inline packages/core/src/features/extensions/enabled/main/storage-version.injectable.ts]: Do these need to be in `common` still? Could be `main`?

**Review by jim-docker — COMMENTED** [review]
testing...

File: packages/core/src/features/extensions/enabled/main/storage-version.injectable.ts (hunk 1 above)
Comment (Nokel81) [reply packages/core/src/features/extensions/enabled/main/storage-version.injectable.ts]: What do you mean by "in common", this file is under `src/features/**/main/` which means it only gets included in `main`

Comment (jim-docker) [reply packages/core/src/features/extensions/enabled/main/storage-version.injectable.ts]: I'm referring to `storageMigrationVersionInjectable` and `enabledExtensionsMigrationDeclarationInjectionToken`. Do they still need to be in `common`? Is there a need for them in renderer?

Comment (Nokel81) [reply packages/core/src/features/extensions/enabled/main/storage-version.injectable.ts]: Ah I see and yes I think those should probably be moved

File: packages/core/src/features/extensions/enabled/common/storage.injectable.ts [hunk 2]
```diff
@@ -24,13 +31,25 @@ const enabledExtensionsPersistentStorageInjectable = getInjectable({
...
+          })
+          .filter(isDefined);
+
         state.replace(extensions);
       }),
       toJSON: () => ({
         extensions: [...toJS(state)],
       }),
-      projectVersion: di.inject(storageMigrationVersionInjectable, enabledExtensionsMigrationDeclarationInjectionToken),
+      projectVersion: di.inject(enabledExtensionsPersistentStorageVersionInitializable.stateToken),
```
Comment (jim-docker) [inline packages/core/src/features/extensions/enabled/common/storage.injectable.ts:52]: Why is the field called `projectVersion`? It might be clearer if it were `storeVersion` or similar. Without digging deeper in the code one might think this could be the package version.

Comment (Nokel81) [reply packages/core/src/features/extensions/enabled/common/storage.injectable.ts:52]: That is because the underlying library means for it to be the actual version of the project (which is the default value too).

We could change it internally, but I don't know if it is worth it.

**Review by jim-docker — APPROVED** [review]
works!
