### PR TITLE
Fix catalog entity context menu duplicate entries

### LINKED ISSUE #3005: Duplicate 'Unpin from Hotbar' menu items
unping from hotbar

### PR DESCRIPTION
**Pull request by jakolehm**
Fixes #3005

### CODE REVIEW

File: src/renderer/components/+catalog/catalog.tsx [hunk 1]
```diff
@@ -169,8 +169,14 @@ export class Catalog extends React.Component<Props> {
   }
 
   renderItemMenu = (item: CatalogEntityItem) => {
+    const onOpen = () => {
+      this.contextMenu.menuItems = [];
```
Comment (Nokel81) [inline src/renderer/components/+catalog/catalog.tsx:173]: Shouldn't this be `this.contextMenu.clear()` and we should probably do a `runInAction` so that we don't get errors.

**Review by Nokel81 — APPROVED** [review]
Though having tested this. It works great.
