### PR TITLE
Fix: preventing <App/> to render on cluster refresh

### LINKED ISSUE #2208: Drawer or Modal popup gets recreated when it is connected to Mobx
**Description**
Drawer or Modal popup gets recreated when it is connected to Mobx or redux and this behavious is seen greater version of 4.0.8.

**To Reproduce**

Call a AddDialog box from addorremove property using KubeObjectList.

Mount the AddDialog inside the same file. Trigger the open from KubeListTableControls i.e add icon with mobx. It opens and stays for sometime and gets closed after few seconds. This is happening after >4.0.8 versions.

The behaviour is same Drawer component as well

**Expected behavior**
The drawer which is opened or modal popup should not be closed and the values inside should be retained.

### PR DESCRIPTION
**Pull request by aleksfront**
Removing all references to observable cluster object from `<App/>` render method. This prevents app to rerender (and loose state in extension pages) on cluster refresh. Changed route files because of same references inside `isAllowedResource` method.

Also, adding `observer` wrapper to `<MainLayoutHeader/>` to properly catch cluster renaming from Settings.

Fixes #2208

Signed-off-by: Alex Andreev <alex.andreev.email@gmail.com>

### CODE REVIEW

**Review by Nokel81 — DISMISSED** [review]
Except for the lint catch. Looks good. Nice and simple

**Review by Nokel81 — DISMISSED** [review]

**Review by jakolehm — COMMENTED** [review]
How can extension route changes work without an observer?

**Comment by hansiemithun** [comment]
Thanks for considering @aleksfront, really appreciate it. Hoping to verify this soon. When we can expect this to be released?

**Comment by hansiemithun** [comment]
@aleksfront  - small lint issue exist for this to close 🙂

**Comment by aleksfront** [comment]
> @aleksfront - small lint issue exist for this to close 🙂

Current fix doesn't solve all of the issues. But the good news is update is on the way. We expecting that it will be fixed soon.

**Comment by hansiemithun** [comment]
> > @aleksfront - small lint issue exist for this to close 🙂
> 
> Current fix doesn't solve all of the issues. But the good news is update is on the way. We expecting that it will be fixed soon.

@aleksfront  - So, can we at-least believe this fixes drawer recreation?

File: src/renderer/components/app.tsx [hunk 1]
```diff
@@ -152,38 +148,6 @@ export class App extends React.Component {
     });
   }
 
-  @observable extensionRoutes: Map<ClusterPageMenuRegistration, React.ReactNode> = new Map();
-
-  generateExtensionTabLayoutRoutes(rootItems: ClusterPageMenuRegistration[]) {
```
Comment (Nokel81) [inline src/renderer/components/app.tsx:157]: What was this used for previously? It isn't being used anywhere.

**Review by Nokel81 — DISMISSED** [review]
From a code review pov this looks good.

File: src/renderer/components/command-palette/command-container.tsx [hunk 2]
```diff
@@ -29,8 +28,9 @@ export class CommandOverlay {
 }
 
 @observer
-export class CommandContainer extends React.Component<{cluster?: Cluster}> {
+export class CommandContainer extends React.Component {
   @observable.ref commandComponent: React.ReactElement;
+  @observable cluster = getHostedCluster();
```
Comment (jakolehm) [inline src/renderer/components/command-palette/command-container.tsx]: Why `getHostedCluster` vs passing it as a prop? This is an anti-pattern.

File: src/renderer/components/+config/config.route.ts [hunk 3]
```diff
@@ -1,12 +1,21 @@
...
-    return Config.tabRoutes.map(({ routePath }) => routePath).flat();
-  }
+  path: [
+    configMapsRoute,
+    secretsRoute,
+    resourceQuotaRoute,
+    limitRangesRoute,
+    hpaRoute,
+    pdbRoute
+  ].map(route => route.path.toString())
```
Comment (ixrock) [inline src/renderer/components/+config/config.route.ts:18]:
```suggestion
  path: [
    configMapsRoute.path,
    secretsRoute.path,
    resourceQuotaRoute.path,
    limitRangesRoute.path,
    hpaRoute.path,
    pdbRoute.path,
  ].map(String)
```

File: src/renderer/components/app.tsx (hunk 1 above)
Comment (jakolehm) [reply src/renderer/components/app.tsx:157]: Wasn't it called on line 95?

File: src/renderer/components/app.tsx [hunk 4]
```diff
@@ -92,24 +92,20 @@ export class App extends React.Component {
         broadcastMessage(`cluster-warning-event-count:${getHostedCluster().id}`, count);
       }),
 
-      reaction(() => clusterPageMenuRegistry.getRootItems(), (rootItems) => {
-        this.generateExtensionTabLayoutRoutes(rootItems);
-      }, {
-        fireImmediately: true
+      reaction(getHostedCluster, () => {
```
Comment (ixrock) [inline src/renderer/components/app.tsx]: This looks weird. What it the intention here? 
I suppose we can setup `startUrl` without any reactions since it should be available when app is renders first time.

File: src/renderer/components/+workloads/workloads.route.ts [hunk 5]
```diff
@@ -35,6 +28,19 @@ export const cronJobsRoute: RouteProps = {
   path: "/cronjobs"
 };
 
+export const workloadsRoute: RouteProps = {
```
Comment (jakolehm) [inline src/renderer/components/+workloads/workloads.route.ts:31]: Are these refactorings necessary for the fix?

File: src/renderer/components/app.tsx (hunk 1 above)
Comment (Nokel81) [reply src/renderer/components/app.tsx:157]: It was called yes but the field `extensionRoutes` was never read from outside of that function

File: src/renderer/components/+workloads/workloads.route.ts (hunk 5 above)
Comment (aleksfront) [reply src/renderer/components/+workloads/workloads.route.ts:31]: Yes, they're tightly coupled. Previous `workloadsRoute` (and similar) used following sentence:
```
return Workloads.tabRoutes.map(({ routePath }) => routePath).flat();
```
`Workloads.tabRoutes` checks if some resource is allowed then pushed it to `routes` array
```
if (isAllowedResource("pods")) {
      routes.push({
        title: "Pods",
        component: Pods,
        url: podsURL({ query }),
        routePath: podsRoute.path.toString()
      });
    }
```
The key here that `isAllowedResouse` is using observable `getHostedCluster` inside. This causes an `<App/>` to rerender. So, by removing references to observable field we eliminate excessive rerenderings.

File: src/renderer/components/app.tsx (hunk 1 above)
Comment (aleksfront) [reply src/renderer/components/app.tsx:157]: True. `extensionRoutes` was used for some time, but after [this changes](https://github.com/lensapp/lens/pull/1990/files#diff-bf0690965bbc846224b78fb77bb20125b2c02c3e48553d6c35f825d7b20bd01e) no longer in use

File: src/renderer/components/+config/config.route.ts (hunk 3 above)
Comment (aleksfront) [reply src/renderer/components/+config/config.route.ts:18]: Not sure what option is better. Are we okay with lots of `.path` repeats?

File: src/renderer/components/app.tsx (hunk 4 above)
Comment (aleksfront) [reply src/renderer/components/app.tsx]: Fixed

File: src/renderer/components/command-palette/command-container.tsx (hunk 2 above)
Comment (aleksfront) [reply src/renderer/components/command-palette/command-container.tsx]: Fixed, passing cluster id as a prop.

**Review by jakolehm — APPROVED** [review]

**Review by nevalla — APPROVED** [review]
LGTM
