### PR TITLE
Always refresh stores when object list is mounted

### LINKED ISSUE #270: Node list doesn't refresh
**Describe the bug**
List of nodes doesn't refresh. Even if my node was terminated i can still see it in the list of nodes as "ready". Need to close and open Lens to refresh the list

Lens 3.2.0 installed on Fedora 30 via snap. K8s 1.11

### PR DESCRIPTION
**Pull request by jakolehm**
Probably fixes many (most?) issues where list does not refresh properly.

Fixes #270

### CODE REVIEW

File: dashboard/client/components/item-object-list/item-list-layout.tsx [hunk 1]
```diff
@@ -114,9 +114,7 @@ export class ItemListLayout extends React.Component<ItemListLayoutProps> {
     const { store, dependentStores, isClusterScoped } = this.props;
     const stores = [store, ...dependentStores];
     if (!isClusterScoped) stores.push(namespaceStore);
-    const loadingStores = stores.filter(store => !store.isLoaded);
-    loadingStores.forEach(store => store.loadAll());
-    await when(() => loadingStores.every(store => !store.isLoading));
+    await Promise.all(stores.map(store => store.loadAll()));
```
Comment (ixrock) [inline dashboard/client/components/item-object-list/item-list-layout.tsx:117]: Do you want to load resources every time on visiting some page? Clusters might be huge as you know...

**Review by nevalla — APPROVED** [review]
LGTM

File: dashboard/client/components/item-object-list/item-list-layout.tsx (hunk 1 above)
Comment (jakolehm) [reply dashboard/client/components/item-object-list/item-list-layout.tsx:117]: Not sure we have other options. If we don't load them every time list is loaded we are actually using stale store where we replay all events since last visit to the same list. This might cause list to "jitter" while events are replayed. Worst case is that kube apiserver does not have all events and then replay is only partial -> list goes out-of-sync.
