### PR TITLE
Fix triple click breaking inputs

### LINKED ISSUE #5076: filter text box - backspace does not work when text is selected
**Describe the bug**
 using backspace key on the selected text in the filter box does not delete the text. you must click on the x button in the filter box or unselect the text and use the backspace key to delete character by character

**To Reproduce**
1. Go to any screen that has a text box to filter . eg. pods secrets anything.
2. write down any text
3. select the text
4. press back space key

**Expected behavior**
backspace on selected text will delete that text

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 5.4.3
- OS: [e.g. OSX]  osx 12.3
- Installation method (e.g. snap or AppImage in Linux): brew

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

### LINKED ISSUE #5580: Triple click on search bar makes it unusable
**Describe the bug**
Triple clicking on the search bar next to the namespaces dropdown in order to select all makes it unusable, you can't type or delete

**To Reproduce**
1. Go to any dashboard (Workloads->Pods).
2. Type more than 2 words.
2. Triple click on search bar to select all.
3. Try to type anything or delete the selected text.

**Expected behavior**
Selected text gets replaced by what you type or deleted.

**Environment (please complete the following information):**
- Lens 5.5.3-latest.20220602.2:
- OS: MacOS 12.3.1
- Installation method: dmg

### PR DESCRIPTION
**Pull request by Nokel81**
Signed-off-by: Sebastian Malton <sebastian@malton.name>

fixes https://github.com/lensapp/lens/issues/5580

### CODE REVIEW

File: src/renderer/components/drawer/drawer.tsx [hunk 1]
```diff
@@ -108,7 +108,7 @@ class NonInjectedDrawer extends React.Component<DrawerProps & Dependencies & typ
     if (ev.detail === 3) {
       const selection = window.getSelection();
 
-      if (selection?.anchorNode?.parentNode) {
+      if (selection?.anchorNode?.parentNode && !(selection.anchorNode instanceof HTMLLabelElement)) {
```
Comment (jansav) [inline src/renderer/components/drawer/drawer.tsx]: Not really related but do we really have global click handler which counts for clicks? 
Do you know what is the reasoning behind it? Sounds horrible. 

About the fix itself: sure. Code could explain the reasoning better, e.g. by introducing variable with good name

**Review by jansav — APPROVED** [review]

**Review by ixrock — APPROVED** [review]
