### PR TITLE
Fix issue where releases are not reloaded when new release is added e…

### LINKED ISSUE #5269: Helm Releases sometimes do not refresh
**What would you like to be added**:
~Helm repos are not auto updated and have to close lens from icon tray and then repoen.~

Helm releases are not auto updated and have to disconnect from cluster and come back to see them.

The latter is more important IMO.

Please either auto update or add a refresh button.

**Why is this needed**:
Slows down workflow.

**Environment you are Lens application on:**

- Kubernetes distribution: [ AKS,.]
- Desktop OS: <win10 with kubeconfig in ubuntu 20.04 WSL2 on >

### PR DESCRIPTION
**Pull request by jansav**
…xternally (e.g. from terminal)

Notice:

There should be behaviour for this, but adding it would lead to cascade of refactorings so I chose not do it for now. 

How to test:

1. Open Releases
2. Open Terminal
3. `$ helm install --generate-name bitnami/consul`
4. Make sure that releases are reloaded (this is the part that wasn't working before)
5. `$ helm list` and `$ helm uninstall X`
6. Make sure that releases are reloaded (Notice how the release which is uninstalled will stay in the list with status "Uninstalling". If this is not intended behaviour, then it's separate bug somewhere in `SecretStore`)

Signed-off-by: Janne Savolainen <janne.savolainen@live.fi>

### CODE REVIEW

**Comment by Nokel81** [comment]
fixes https://github.com/lensapp/lens/issues/5269

File: src/renderer/components/+helm-releases/release-secrets.injectable.ts [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+
+    const releaseSecrets = computed(() =>
+      secretStore.contextItems.filter((secret) =>
+        secret.type.startsWith("helm.sh/release"),
+      ),
+    );
+
+    let unsubscribe: () => void;
+
+    onBecomeObserved(releaseSecrets, () => {
```
Comment (Nokel81) [inline src/renderer/components/+helm-releases/release-secrets.injectable.ts:25]: This is neat

File: src/renderer/components/+helm-releases/releases.injectable.ts [hunk 2]
```diff
@@ -7,17 +7,21 @@ import { asyncComputed } from "@ogre-tools/injectable-react";
...
 
   instantiate: (di) => {
     const clusterContext = di.inject(clusterFrameContextInjectable);
     const namespaceStore = di.inject(namespaceStoreInjectable);
+    const releaseSecrets = di.inject(releaseSecretsInjectable);
 
     return asyncComputed(async () => {
       const contextNamespaces = namespaceStore.contextNamespaces || [];
 
+      void releaseSecrets.get();
```
Comment (Nokel81) [inline src/renderer/components/+helm-releases/releases.injectable.ts:23]: Why is this enough?

**Review by Nokel81 — APPROVED** [review]

File: src/renderer/components/+helm-releases/release-secrets.injectable.ts (hunk 1 above)
Comment (jansav) [reply src/renderer/components/+helm-releases/release-secrets.injectable.ts:25]: Need to remember that this is very dangerous tool. It's easy to create stuff which goes to endless observe-unobserve loop. :)

File: src/renderer/components/+helm-releases/releases.injectable.ts (hunk 2 above)
Comment (jansav) [reply src/renderer/components/+helm-releases/releases.injectable.ts:23]: `asyncComputed` works as `computed` does. So if you observe some observable, and the value changes, it will re-compute. Here `releaseSecrets` changes when something is installed, so that causes `asyncComputed` to recompute.

**Review by Iku-turso — APPROVED** [review]
