### PR TITLE
Fix set of cluster entity icon src

### LINKED ISSUE #3131: Mobx ClusterManager error
```
[0] [mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Reaction@333]' TypeError: Cannot set property 'src' of undefined
[0]     at ClusterManager.updateEntityFromCluster (webpack-internal:///./src/main/cluster-manager.ts:159:30)
[0]     at ClusterManager.updateCatalog (webpack-internal:///./src/main/cluster-manager.ts:136:18)
[0]     at executeAction (/Users/jari/Code/lens/node_modules/mobx/dist/mobx.cjs.development.js:1130:15)
[0]     at ClusterManager.updateCatalog (/Users/jari/Code/lens/node_modules/mobx/dist/mobx.cjs.development.js:1114:12)
[0]     at Object.fireImmediately (webpack-internal:///./src/main/cluster-manager.ts:77:136)
[0]     at executeAction (/Users/jari/Code/lens/node_modules/mobx/dist/mobx.cjs.development.js:1130:15)
[0]     at Reaction@333 (/Users/jari/Code/lens/node_modules/mobx/dist/mobx.cjs.development.js:1114:12)
[0]     at reactionRunner (/Users/jari/Code/lens/node_modules/mobx/dist/mobx.cjs.development.js:2670:109)
[0]     at Reaction.onInvalidate_ (/Users/jari/Code/lens/node_modules/mobx/dist/mobx.cjs.development.js:2651:7)
[0]     at Reaction.runReaction_ (/Users/jari/Code/lens/node_modules/mobx/dist/mobx.cjs.development.js:2286:16)
```

### PR DESCRIPTION
**Pull request by jakolehm**
Fixes #3131

### CODE REVIEW

**Review by aleksfront — DISMISSED** [review]

File: src/main/cluster-manager.ts [hunk 1]
```diff
@@ -119,7 +119,10 @@ export class ClusterManager extends Singleton {
       entity.spec.metrics.prometheus = prometheus;
     }
 
-    entity.spec.icon.src = cluster.preferences.icon;
+    cluster.preferences.icon ? entity.spec.icon = {
+      ...entity.spec.icon,
```
Comment (Nokel81) [inline src/main/cluster-manager.ts]: This will break if someone forgets to specify `icon` as part of `spec`.

**Review by msa0311 — DISMISSED** [review]

File: src/main/cluster-manager.ts [hunk 2]
```diff
@@ -119,7 +119,10 @@ export class ClusterManager extends Singleton {
       entity.spec.metrics.prometheus = prometheus;
     }
 
-    entity.spec.icon.src = cluster.preferences.icon;
+    cluster.preferences.icon ? entity.spec.icon = {
```
Comment (Nokel81) [inline src/main/cluster-manager.ts]: I cannot find any typings for `icon` under spec at all. We need to add them.

**Review by Nokel81 — CHANGES_REQUESTED** [review]
