### PR TITLE
Fix ensure hashed directory for extension

### LINKED ISSUE #7052: Allow extension to specify storeName
If extension's package.json specifies `storeName` property which is set to a truthy value, use it for persisting data (e.g. extension stores and extension data) instead of the extension `name`.

This allows extension to be renamed without losing data.

### PR DESCRIPTION
**Pull request by jweak**
Earlier open lens versions stored `extension_data` directory based on path of extension's package.json. This causes problems because extensions have moved to new location. This ensures backward compatibility that extension will get the same directory than before the change and migrates the key to a new implementation that does not depend on the installed directory.

Fixes #7052

### CODE REVIEW

File: packages/core/src/common/utils/find-key-contains.injectable.ts [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+      for (const [key, value] of entries) {
+        if (key.includes(text)) {
+          return value;
+        }
+      }
+
+      return undefined;
+    };
+  },
+});
```
Comment (Nokel81) [inline packages/core/src/common/utils/find-key-contains.injectable.ts]: nit: This doesn't need to be an injectable because it has no side effects and has no dependencies.

File: packages/core/src/extensions/extension-loader/file-system-provisioner-store/ensure-hashed-directory-for-extension.injectable.ts [hunk 2]
```diff
@@ -24,8 +25,15 @@ const ensureHashedDirectoryForExtensionInjectable = getInjectable({
     const directoryForExtensionData = di.inject(directoryForExtensionDataInjectable);
     const ensureDirectory = di.inject(ensureDirInjectable);
     const getHash = di.inject(getHashInjectable);
+    const findKeyContains = di.inject(findKeyContainsInjectable)<string>;
 
     return async (extensionName, registeredExtensions) => {
```
Comment (Nokel81) [inline packages/core/src/extensions/extension-loader/file-system-provisioner-store/ensure-hashed-directory-for-extension.injectable.ts]: Shouldn't this `extensionName` be the value from the `package.json`?

**Review by Nokel81 — COMMENTED** [review]
I don't understand why this is needed.

File: packages/core/src/extensions/extension-loader/file-system-provisioner-store/ensure-hashed-directory-for-extension.injectable.ts [hunk 3]
```diff
@@ -24,8 +25,15 @@ const ensureHashedDirectoryForExtensionInjectable = getInjectable({
...
+      const legacyDirPath = findKeyContains(registeredExtensions, extensionName);
+
+      if (legacyDirPath) {
+        return legacyDirPath;
```
Comment (jweak) [inline packages/core/src/extensions/extension-loader/file-system-provisioner-store/ensure-hashed-directory-for-extension.injectable.ts]: instead of returning early here, we should still make sure that `ensureDir` is run after this

File: packages/core/src/common/utils/find-key-contains.injectable.ts [hunk 4]
```diff
@@ -0,0 +1,27 @@
...
+
+const findKeyContainsInjectable = getInjectable({
+  id: "find-key-contains",
+
+  instantiate: (): FindKeyContains => {
+    return <T>(map: Map<string, T>, text: string) => {
+      const entries = map.entries();
+
+      for (const [key, value] of entries) {
+        if (key.includes(text)) {
```
Comment (jweak) [inline packages/core/src/common/utils/find-key-contains.injectable.ts]: instead of using `includes` we should try to reconstruct the whole legacy key path.

something like this:
`path.join(directoryForUserData, "extension_data", name, "package.json") `

Comment (jweak) [reply packages/core/src/common/utils/find-key-contains.injectable.ts]: done

File: packages/core/src/extensions/extension-loader/file-system-provisioner-store/ensure-hashed-directory-for-extension.injectable.ts (hunk 3 above)
Comment (jweak) [reply packages/core/src/extensions/extension-loader/file-system-provisioner-store/ensure-hashed-directory-for-extension.injectable.ts]: done

File: packages/core/src/extensions/extension-loader/file-system-provisioner-store/ensure-hashed-directory-for-extension.injectable.ts (hunk 2 above)
Comment (jweak) [reply packages/core/src/extensions/extension-loader/file-system-provisioner-store/ensure-hashed-directory-for-extension.injectable.ts]: yeah this has been changed to reconstruct the legacy key

File: packages/core/src/common/utils/find-key-contains.injectable.ts (hunk 1 above)
Comment (jweak) [reply packages/core/src/common/utils/find-key-contains.injectable.ts]: the file has been removed

File: packages/core/src/extensions/extension-loader/file-system-provisioner-store/ensure-hashed-directory-for-extension.test.ts [hunk 5]
```diff
@@ -0,0 +1,82 @@
...
+    runInAction(() => {
+      registeredExtensions.set("/some-directory-for-user-data/node_modules/some-extension-name/package.json", "some-directory");
+    });
+
+    await ensureHashedDirectoryForExtension(
+      "some-extension-name",
+      registeredExtensions,
+    );
+
+    expect(ensureDirMock).toHaveBeenCalledWith("some-directory");
```
Comment (Iku-turso) [inline packages/core/src/extensions/extension-loader/file-system-provisioner-store/ensure-hashed-directory-for-extension.test.ts]: A "negation-test" with `expect(ensureDirMock).not.toHaveBeenCalled()` is missing :)

File: packages/core/src/extensions/extension-loader/file-system-provisioner-store/get-path-to-legacy-package-json.injectable.ts [hunk 6]
```diff
@@ -0,0 +1,24 @@
...
+ * Copyright (c) OpenLens Authors. All rights reserved.
+ * Licensed under MIT License. See LICENSE in root directory for more information.
+ */
+import { getInjectable } from "@ogre-tools/injectable";
+import directoryForUserDataInjectable from "../../../common/app-paths/directory-for-user-data/directory-for-user-data.injectable";
+import joinPathsInjectable from "../../../common/path/join-paths.injectable";
+
+export type GetPathToLegacyPackageJson = (extensionName: string) => string;
+
+const getPathToLegacyPackageJson = getInjectable({
```
Comment (Iku-turso) [inline packages/core/src/extensions/extension-loader/file-system-provisioner-store/get-path-to-legacy-package-json.injectable.ts:11]: This could be unit tested as part of `ensure-hashed-directory-for-extension.test.ts`, instead of coupling tests too tightly with implementation details.

File: packages/core/src/extensions/extension-loader/file-system-provisioner-store/ensure-hashed-directory-for-extension.test.ts [hunk 7]
```diff
@@ -0,0 +1,82 @@
...
+  });
+
+  it("given registered extension exists, returns existing directory", async () => {
+    runInAction(() => {
+      registeredExtensions.set("some-extension-name", "some-directory");
+    });
+
+    const actual = await ensureHashedDirectoryForExtension(
+      "some-extension-name",
+      registeredExtensions,
```
Comment (Iku-turso) [inline packages/core/src/extensions/extension-loader/file-system-provisioner-store/ensure-hashed-directory-for-extension.test.ts]: Hmm. I wonder if `registeredExtensions` could be promoted to be a **dependency** instead of **function parameter** for a bit less complexity. There's only one set of those, right?

File: packages/core/src/extensions/extension-loader/file-system-provisioner-store/ensure-hashed-directory-for-extension.test.ts [hunk 8]
```diff
@@ -0,0 +1,82 @@
...
+  let ensureHashedDirectoryForExtension: EnsureHashedDirectoryForExtension;
+  let ensureDirMock: jest.Mock;
+  let registeredExtensions: ObservableMap<string, string>;
+
+  beforeEach(() => {
+    const di = getDiForUnitTesting({  doGeneralOverrides: true });
+
+    ensureDirMock = jest.fn();
+
+    di.override(ensureDirInjectable, () => ensureDirMock);
```
Comment (Iku-turso) [inline packages/core/src/extensions/extension-loader/file-system-provisioner-store/ensure-hashed-directory-for-extension.test.ts:25]: Note: Another way to test `ensureDir` and its effects would be to test it using those **file system fakes**. Generally it leads to bit more credible, but also sometimes easier to write tests.

File: packages/core/src/extensions/extension-loader/file-system-provisioner-store/ensure-hashed-directory-for-extension.test.ts [hunk 9]
```diff
@@ -0,0 +1,82 @@
...
+    });
+    const actual = await ensureHashedDirectoryForExtension(
+      "some-extension-name",
+      registeredExtensions,
+    );
+
+    expect(actual).toBe("some-directory");
+  });
+
+  it("given extension directory was saved based on extension's package.json path, ensure dir is called with right parameter", async () => {
```
Comment (Iku-turso) [inline packages/core/src/extensions/extension-loader/file-system-provisioner-store/ensure-hashed-directory-for-extension.test.ts]: Instead of "right parameter", one could document what makes the parameter right :)

File: packages/core/src/extensions/extension-loader/file-system-provisioner-store/get-path-to-legacy-package-json.test.ts [hunk 10]
```diff
@@ -0,0 +1,34 @@
...
+
+  beforeEach(() => {
+    const di = getDiForUnitTesting({ doGeneralOverrides: true });
+    const directoryForExtensionDataMock = jest.fn().mockReturnValue("/path/to/user/data");
+
+    di.override(directoryForUserDataInjectable, directoryForExtensionDataMock);
+    getPathToLegacyPackageJson = di.inject(getPathToLegacyPackageJsonInjectable);
+  });
+
+  describe("given extension name", () => {
```
Comment (Iku-turso) [inline packages/core/src/extensions/extension-loader/file-system-provisioner-store/get-path-to-legacy-package-json.test.ts]: Describe is not required :)

File: packages/core/src/extensions/extension-loader/file-system-provisioner-store/get-path-to-legacy-package-json.injectable.ts [hunk 11]
```diff
@@ -0,0 +1,24 @@
...
+  id: "get-path-to-legacy-package-json",
+
+  instantiate: (di): GetPathToLegacyPackageJson => {
+    const directoryForUserData = di.inject(directoryForUserDataInjectable);
+    const joinPaths = di.inject(joinPathsInjectable);
+
+    return (extensionName: string) => {
+      return joinPaths(directoryForUserData, "node_modules", extensionName, "package.json");
```
Comment (Iku-turso) [inline packages/core/src/extensions/extension-loader/file-system-provisioner-store/get-path-to-legacy-package-json.injectable.ts]: Nit: `return` can be removed.

File: packages/core/src/extensions/extension-loader/file-system-provisioner-store/ensure-hashed-directory-for-extension.test.ts [hunk 12]
```diff
@@ -0,0 +1,82 @@
...
+    expect(actual).toBe("some-directory");
+  });
+
+  it("given registered extension does not exist, returns random directory", async () => {
+    const actual = await ensureHashedDirectoryForExtension(
+      "some-extension-name",
+      registeredExtensions,
+    );
+
+    expect(actual).not.toBe("some-directory");
```
Comment (Iku-turso) [inline packages/core/src/extensions/extension-loader/file-system-provisioner-store/ensure-hashed-directory-for-extension.test.ts]: To test eg. `expect(actual).toBe("some-random-directory");` would be more credible.

File: packages/core/src/extensions/extension-loader/file-system-provisioner-store/ensure-hashed-directory-for-extension.test.ts [hunk 13]
```diff
@@ -0,0 +1,82 @@
...
+import type { ObservableMap } from "mobx";
+import { observable, runInAction } from "mobx";
+import { getDiForUnitTesting } from "../../../main/getDiForUnitTesting";
+import type { EnsureHashedDirectoryForExtension } from "./ensure-hashed-directory-for-extension.injectable";
+import ensureHashedDirectoryForExtensionInjectable from "./ensure-hashed-directory-for-extension.injectable";
+import ensureDirInjectable from "../../../common/fs/ensure-dir.injectable";
+import directoryForExtensionDataInjectable from "./directory-for-extension-data.injectable";
+import directoryForUserDataInjectable from "../../../common/app-paths/directory-for-user-data/directory-for-user-data.injectable";
+
+describe("ensure-hashed-directory-for-extension", () => {
```
Comment (Iku-turso) [inline packages/core/src/extensions/extension-loader/file-system-provisioner-store/ensure-hashed-directory-for-extension.test.ts:15]: I'm thinking if case of NPM-packages with a namespaced name (eg. `"name": "@some-namespace/some-package-name"`) will require their own tests and maybe implementations. WDYT?

File: packages/core/src/extensions/extension-loader/file-system-provisioner-store/ensure-hashed-directory-for-extension.injectable.ts [hunk 14]
```diff
@@ -24,14 +26,24 @@ const ensureHashedDirectoryForExtensionInjectable = getInjectable({
...
+      let dirPath: string;
+
+      const legacyDirPath = getPathToLegacyPackageJson(extensionName);
+      const hashedDirectoryForLegacyDirPath = registeredExtensions.get(legacyDirPath);
+
+      if (hashedDirectoryForLegacyDirPath) {
+        dirPath = hashedDirectoryForLegacyDirPath;
+      } else {
+        dirPath = await getOrInsertWithAsync(registeredExtensions, extensionName, async () => {
+          const salt = (await randomBytes(32)).toString("hex");
```
Comment (Iku-turso) [inline packages/core/src/extensions/extension-loader/file-system-provisioner-store/ensure-hashed-directory-for-extension.injectable.ts]: I don't think `randomBytes` should be `async` :)

File: packages/core/src/extensions/extension-loader/file-system-provisioner-store/get-path-to-legacy-package-json.test.ts [hunk 15]
```diff
@@ -0,0 +1,34 @@
...
+    it("given some extension returns path for package.json in user data directory", () => {
+      const pathToExtensionPackageJson = getPathToLegacyPackageJson("some-extension");
+
+      expect(pathToExtensionPackageJson).toEqual("/path/to/user/data/node_modules/some-extension/package.json");
+    });
+
+    it("given some other extension returns path for package.json in user data directory", () => {
```
Comment (Iku-turso) [inline packages/core/src/extensions/extension-loader/file-system-provisioner-store/get-path-to-legacy-package-json.test.ts]: Separating Given/When/Then with colons would make names of tests a bit more skimmable :)

File: packages/core/src/extensions/extension-loader/file-system-provisioner-store/ensure-hashed-directory-for-extension.injectable.ts (hunk 14 above)
Comment (jweak) [reply packages/core/src/extensions/extension-loader/file-system-provisioner-store/ensure-hashed-directory-for-extension.injectable.ts]: I think this is some kind of optimisation. 

> The crypto.randomBytes() method will not complete until there is sufficient entropy available. This should normally never take longer than a few milliseconds. The only time when generating the random bytes may conceivably block for a longer period of time is right after boot, when the whole system is still low on entropy.
> 
> This API uses libuv's threadpool, which can have surprising and negative performance implications for some applications; see the [UV_THREADPOOL_SIZE](https://nodejs.org/api/cli.html#uv_threadpool_sizesize) documentation for more information.
> 
> The asynchronous version of crypto.randomBytes() is carried out in a single threadpool request. To minimize threadpool task length variation, partition large randomBytes requests when doing so as part of fulfilling a client request.
> 

https://nodejs.org/api/crypto.html#cryptorandombytessize-callback

File: packages/core/src/extensions/extension-loader/file-system-provisioner-store/ensure-hashed-directory-for-extension.test.ts (hunk 7 above)
Comment (jweak) [reply packages/core/src/extensions/extension-loader/file-system-provisioner-store/ensure-hashed-directory-for-extension.test.ts]: Is there only one? I'm not sure. That is a part of `Store`, does it have some kind main / renderer thing going on with syncing stuff. Can we move `registeredExtensions` from the Store to a dependency?

File: packages/core/src/extensions/extension-loader/file-system-provisioner-store/get-path-to-legacy-package-json.injectable.ts (hunk 6 above)
Comment (jweak) [reply packages/core/src/extensions/extension-loader/file-system-provisioner-store/get-path-to-legacy-package-json.injectable.ts:11]: sure we can just get rid off the specific tests for this dependency

File: packages/core/src/extensions/extension-loader/file-system-provisioner-store/get-path-to-legacy-package-json.test.ts (hunk 15 above)
Comment (jweak) [reply packages/core/src/extensions/extension-loader/file-system-provisioner-store/get-path-to-legacy-package-json.test.ts]: this is test removed

File: packages/core/src/extensions/extension-loader/file-system-provisioner-store/ensure-hashed-directory-for-extension.injectable.ts (hunk 14 above)
Comment (jweak) [reply packages/core/src/extensions/extension-loader/file-system-provisioner-store/ensure-hashed-directory-for-extension.injectable.ts]: anyway moved to the sync version of the random bytes

File: packages/core/src/extensions/extension-loader/file-system-provisioner-store/ensure-hashed-directory-for-extension.test.ts (hunk 12 above)
Comment (jweak) [reply packages/core/src/extensions/extension-loader/file-system-provisioner-store/ensure-hashed-directory-for-extension.test.ts]: good catch, fixed

File: packages/core/src/extensions/extension-loader/file-system-provisioner-store/get-path-to-legacy-package-json.injectable.ts (hunk 11 above)
Comment (jweak) [reply packages/core/src/extensions/extension-loader/file-system-provisioner-store/get-path-to-legacy-package-json.injectable.ts]: done

File: packages/core/src/extensions/extension-loader/file-system-provisioner-store/ensure-hashed-directory-for-extension.test.ts (hunk 9 above)
Comment (jweak) [reply packages/core/src/extensions/extension-loader/file-system-provisioner-store/ensure-hashed-directory-for-extension.test.ts]: good call. done

File: packages/core/src/extensions/extension-loader/file-system-provisioner-store/ensure-hashed-directory-for-extension.test.ts (hunk 5 above)
Comment (jweak) [reply packages/core/src/extensions/extension-loader/file-system-provisioner-store/ensure-hashed-directory-for-extension.test.ts]: I'm not sure I follow. `ensureDirMock` is called always with something or am I missing something?

File: packages/core/src/extensions/extension-loader/file-system-provisioner-store/get-path-to-legacy-package-json.test.ts (hunk 10 above)
Comment (jweak) [reply packages/core/src/extensions/extension-loader/file-system-provisioner-store/get-path-to-legacy-package-json.test.ts]: got rid off this one

File: packages/core/src/extensions/extension-loader/file-system-provisioner-store/ensure-hashed-directory-for-extension.test.ts (hunk 5 above)
Comment (Iku-turso) [reply packages/core/src/extensions/extension-loader/file-system-provisioner-store/ensure-hashed-directory-for-extension.test.ts]: Ah! My mistake :)

File: packages/core/src/extensions/extension-loader/file-system-provisioner-store/ensure-hashed-directory-for-extension.test.ts (hunk 7 above)
Comment (Iku-turso) [reply packages/core/src/extensions/extension-loader/file-system-provisioner-store/ensure-hashed-directory-for-extension.test.ts]: There indeed is only one, because `fileSystemProvisionerStoreInjectable` is a `singleton` (that being the default lifecycle of an `injectable`). 

This means we could extract eg. `registeredExtensionsInjectable`, and make it a dependency for both `fileSystemProvisionerStoreInjectable` and `ensureHashedDirectoryForExtensionInjectable`.

Being diligent about separating dependencies and eg. function arguments will lead to a cleaner kitchen, as it creates more easily reusable functions, and hides irrelevant details out of sight.

File: packages/core/src/extensions/extension-loader/file-system-provisioner-store/ensure-hashed-directory-for-extension.test.ts [hunk 16]
```diff
@@ -0,0 +1,101 @@
...
+    it("returns existing directory", async () => {
+      const actual = await ensureHashedDirectoryForExtension(
+        "some-extension-name",
+        registeredExtensions,
+      );
+
+      expect(actual).toBe("some-directory");
+    });
+
+    it("ensure dir is called with some directory", async () => {
```
Comment (Iku-turso) [inline packages/core/src/extensions/extension-loader/file-system-provisioner-store/ensure-hashed-directory-for-extension.test.ts:72]: "ensure dir" is a technical phenomenon, and in general, unit tests benefit more from describing motivations of the real world. That would mean eg.: `it("ensures that the said extension directory exists", ...)`.

**Review by Iku-turso — DISMISSED** [review]

**Review by Iku-turso — APPROVED** [review]
