### PR TITLE
Fix mobx error after closing Edit Resource tab

### LINKED ISSUE #5096: Mobx error when closing Edit Resource tab
```
mobx.esm.js:2579 [mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Autorun@1000]' TypeError: Cannot read properties of undefined (reading 'isLoaded')
    at view.tsx:49
    at reactionRunner (mobx.esm.js:2875)
    at trackDerivedFunction (mobx.esm.js:1953)
    at Reaction.track (mobx.esm.js:2541)
    at Reaction.onInvalidate_ (mobx.esm.js:2854)
    at Reaction.runReaction_ (mobx.esm.js:2501)
    at runReactionsHelper (mobx.esm.js:2680)
    at reactionScheduler (mobx.esm.js:2652)
    at mobx.esm.js:2693
    at batchedUpdates$1 (react-dom.development.js:22380)
```

https://user-images.githubusercontent.com/9607060/159908762-2afb4c92-e177-4c9d-a60f-6267a8d023ee.mov

### PR DESCRIPTION
**Pull request by aleksfront**
Fixes #5096 

Signed-off-by: Alex Andreev <alex.andreev.email@gmail.com>

### CODE REVIEW

**Review by DmitriyNoa — APPROVED** [review]

File: src/renderer/components/dock/edit-resource/view.tsx [hunk 1]
```diff
@@ -46,7 +46,7 @@ class NonInjectedEditResource extends React.Component<EditResourceProps & Depend
         const obj = this.resource;
 
         if (!obj) {
-          if (store.isLoaded) {
+          if (store?.isLoaded) {
```
Comment (ixrock) [inline src/renderer/components/dock/edit-resource/view.tsx:49]: _nit:_ i'd better to just quit above in case of `if(obj || !store) return;`

**Review by ixrock — APPROVED** [review]
