### PR TITLE
Fix: cluster commands disappeared from Command Palette

### LINKED ISSUE #2760: Cluster commands disappeared from Command Palette
There's no cluster commands available in list like
* `Cluster: View Secrets` 
* `Cluster: View Pods` 
* etc.

no cluster commands
no pods

### PR DESCRIPTION
**Pull request by ixrock**
**Global view:**
Screenshot 2021-05-27 at 14 55 47

**Cluster view:**
Screenshot 2021-05-27 at 14 56 04

fix #2760

### CODE REVIEW

File: src/renderer/components/cluster-manager/cluster-view.tsx [hunk 1]
```diff
@@ -65,6 +67,7 @@ export class ClusterView extends React.Component {
         initView(clusterId); // init cluster-view (iframe), requires parent container #lens-views to be in DOM
         requestMain(clusterActivateHandler, clusterId, false); // activate and fetch cluster's state from main
         catalogEntityRegistry.activeEntity = catalogEntityRegistry.getById(clusterId);
+        this.store.setActive(clusterId);
```
Comment (ixrock) [inline src/renderer/components/cluster-manager/cluster-view.tsx]: Setting active cluster was missing somehow at all (only in `ClusterStore.fromStore`)

File: src/extensions/registries/command-registry.ts [hunk 2]
```diff
@@ -39,14 +38,6 @@ export interface CommandRegistration {
 }
 
 export class CommandRegistry extends BaseRegistry<CommandRegistration> {
-  @observable.ref activeEntity: CatalogEntity;
```
Comment (ixrock) [inline src/extensions/registries/command-registry.ts:42]: Removed in favour `catalogEntityRegistry.activeEntity`

File: src/renderer/components/cluster-manager/cluster-view.tsx (hunk 1 above)
Comment (ixrock) [reply src/renderer/components/cluster-manager/cluster-view.tsx]: If we keep only this line and remove all other changes from the PR then cluster commands are shown, but navigation to corresponding pages is broken for some reasons..

Comment (Nokel81) [reply src/renderer/components/cluster-manager/cluster-view.tsx]: Why do we need this, shouldn't it be possible to derive the active cluster from the active catalog entity?

Comment (jakolehm) [reply src/renderer/components/cluster-manager/cluster-view.tsx]: I'm also wondering do we really need this?

Comment (ixrock) [reply src/renderer/components/cluster-manager/cluster-view.tsx]: Question is why do we need `ClusterStore.setActive(id: string)`? 
It sets `ClusterStore.activeCluster` and used in:

```ts
  @computed get active(): Cluster | null {
    return this.getById(this.activeCluster);
  }
```

Current usages of `ClusterStore.active`:

image

Comment (ixrock) [reply src/renderer/components/cluster-manager/cluster-view.tsx]: Should we use something like this instead?

```ts
  @computed get active(): Cluster | null {
    return this.getById(catalogEntityRegistry.activeEntity?.getId());
  }
```

Comment (Nokel81) [reply src/renderer/components/cluster-manager/cluster-view.tsx]: I would get rid of `active()` from `ClusterStore` entirely. Since it has no use on `main` and from `renderer` it would be better to just use `ClusterStore.getInstance().getById(catalogEntityRegistry.activeEntity?.getId())` directly.

**Comment by ixrock** [comment]
Refactored. @jakolehm @Nokel81 PTAL

File: src/common/cluster-store.ts [hunk 3]
```diff
@@ -217,43 +214,14 @@ export class ClusterStore extends BaseStore<ClusterStoreModel> {
...
-
   @computed get connectedClustersList(): Cluster[] {
     return this.clustersList.filter((c) => !c.disconnected);
   }
 
-  isActive(id: ClusterId) {
-    return this.activeCluster === id;
-  }
-
-  isMetricHidden(resource: ResourceType) {
```
Comment (ixrock) [inline src/common/cluster-store.ts:240]: Moved to `cluster.ts`

File: src/renderer/api/catalog-entity-registry.ts [hunk 4]
```diff
@@ -39,14 +41,6 @@ export class CatalogEntityRegistry {
     });
   }
 
-  set activeEntity(entity: CatalogEntity) {
```
Comment (ixrock) [inline src/renderer/api/catalog-entity-registry.ts:42]: This is removed cause doesn't add any extra logic on `set`. 
We can revert when we need more actions on assign.

**Review by jakolehm — APPROVED** [review]
LGTM

**Review by Nokel81 — APPROVED** [review]
