### PR TITLE
Optimise cluster activate and refresh

### LINKED ISSUE #933: Kubectl binary download blocks when opening a cluster dashboard
**Describe the bug**
When opening a cluster dashboard first time, Lens will download kubectl binary matching to the cluster version. However, afaik the dashboard itself does not require kubectl binary. When opening the terminal, installing features or applying resources kubectl binary is needed and Lens will already download it on demand. So it seems that downloading kubectl binary is not necessary when opening the cluster dashboard.

### PR DESCRIPTION
**Pull request by nevalla**
This PR will optimise cluster dashboard opening. `cluster.activate()` will fetch only those data that is required for the dashboard. Also kubectl downloading is not blocking operation anymore (fixes #933). Full cluster information refresh is done periodically and when opening cluster settings.

Signed-off-by: Lauri Nevala <lauri.nevala@gmail.com>

### CODE REVIEW

File: src/main/cluster.ts [hunk 1]
```diff
@@ -133,7 +133,13 @@ export class Cluster implements ClusterModel {
     if (this.disconnected || (!init && !this.accessible)) {
       await this.reconnect();
     }
-    await this.refresh();
+    await this.refreshConnectionStatus()
+    if (this.accessible) {
+      await this.refreshAllowedResources()
+      this.ready = true
+      this.kubeCtl = new Kubectl(this.version)
+      this.kubeCtl.ensureKubectl() // download kubectl in background, so it's not blocking dashboard
```
Comment (ixrock) [inline src/main/cluster.ts:141]: But still, will it block sending the state via `pushState` below? If so that means dashboard won't receive "ready-state" until downloading finished?

**Review by ixrock — APPROVED** [review]
LGTM

File: src/main/cluster.ts (hunk 1 above)
Comment (nevalla) [reply src/main/cluster.ts:141]: I tested by removing kubectl binaries from app resources and did not see the same empty screen as with `master`  anymore when opened the dashboard.

Comment (ixrock) [reply src/main/cluster.ts:141]: Oh, right, there is no `await` for `kubeCtl.ensureKubectl()`
