### PR TITLE
Make node shell image configurable

### LINKED ISSUE #2007: node-shell : Failed to pull image "docker.io/alpine:3.12"
**Describe the bug**

node-shell-888ce968-f3b4-4b86-9bd6-ba4487a37604

Failed to pull image "docker.io/alpine:3.12": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:46565->[::1]:53: read: connection refused

**To Reproduce**
when k8s cluster network cann't connect to internat, k8s only can connect to local harbor registry，can not pull the internet image docker.io/alpine:3.12

**Code In**
in this code file:  lens/src/main/node-shell-session.ts  line 78, have this line  image: "docker.io/alpine:3.12", 

**Solve Suggestion**
Is this can make a config  to solve the problem;

or use K8S DaemonSet YAML, I can change the DaemonSet YAML in runtime to solve the problem;

### PR DESCRIPTION
**Pull request by vshakirova**
deploy node shell pod using an image from a private repo
Screenshot from 2021-07-08 17-01-43

settings
Screen Shot 2021-07-12 at 4 45 20 PM

fixes: https://github.com/lensapp/lens/issues/2007

### CODE REVIEW

File: src/main/cluster.ts [hunk 1]
```diff
@@ -736,4 +737,12 @@ export class Cluster implements ClusterModel, ClusterState {
...
     return Boolean(this.preferences.hiddenMetrics?.includes(resource));
   }
+
+  getNodeShellImage(): string {
+    return this.preferences.nodeShellImage || initialNodeShellImage;
+  }
+
+  getImagePullSecret(): string {
+    return this.preferences.imagePullSecret || "";
+  }
```
Comment (Nokel81) [inline src/main/cluster.ts]: These two should be getters probably.

File: src/main/cluster-manager.ts [hunk 2]
```diff
@@ -149,7 +149,8 @@ export class ClusterManager extends Singleton {
         this.store.addCluster({
           id: entity.metadata.uid,
           preferences: {
-            clusterName: entity.metadata.name
+            clusterName: entity.metadata.name,
+            nodeShellImage: initialNodeShellImage,
```
Comment (Nokel81) [inline src/main/cluster-manager.ts]: No need to set this here if the getter defaults to this.

File: src/renderer/components/cluster-settings/components/cluster-node-shell-setting.tsx [hunk 3]
```diff
@@ -0,0 +1,140 @@
...
+          <FormSwitch
+            control={
+              <Switcher
+                checked={this.usePrivateRegistry}
+                onClick={this.onSwitchChange}
+                name="private-registry"
+              />
+            }
+            label="Use private registry"
+          />
```
Comment (Nokel81) [inline src/renderer/components/cluster-settings/components/cluster-node-shell-setting.tsx]: I think this will be confusing for users because it is essentially a "clear imagePullSecret" button. I think it would be better to not have it and just add something like "Optional" to the hint for the `imagePullSecret`

File: src/renderer/components/cluster-settings/components/cluster-node-shell-setting.tsx [hunk 4]
```diff
@@ -0,0 +1,140 @@
...
+          <SubTitle title="Image pull secret" id="image-pull-secret"/>
+          <Input
+            theme="round-black"
+            value={this.imagePullSecret}
+            onChange={this.onSecretChange}
+            onBlur={this.saveSecret}
+            iconRight={clearSecretIcon}
+          />
+          <small className="hint">
+            Image pull secret. Used for pulling image from a private registry.
```
Comment (Nokel81) [inline src/renderer/components/cluster-settings/components/cluster-node-shell-setting.tsx]: This should specify that it is the name of a pre-existing secret object.

File: src/main/cluster.ts (hunk 1 above)
Comment (vshakirova) [reply src/main/cluster.ts]: fixed, thank you.

File: src/renderer/components/cluster-settings/components/cluster-node-shell-setting.tsx (hunk 4 above)
Comment (vshakirova) [reply src/renderer/components/cluster-settings/components/cluster-node-shell-setting.tsx]: Is it better? 
Screen Shot 2021-07-12 at 4 45 16 PM

Comment (Nokel81) [reply src/renderer/components/cluster-settings/components/cluster-node-shell-setting.tsx]: Yes thanks.

File: src/renderer/components/cluster-settings/components/cluster-node-shell-setting.tsx [hunk 5]
```diff
@@ -0,0 +1,114 @@
...
+    this.nodeShellImage = initialNodeShellImage; //revert to default
+  };
+
+  clearSecret = () => {
+    this.imagePullSecret = "";
+  };
+
+  render() {
+    const resetImageIcon = <Icon small material="close" onClick={this.resetImage} tooltip={"Reset"}/>;
+    const clearSecretIcon = <Icon small material="close" onClick={this.clearSecret} tooltip={"Clear"}/>;
```
Comment (Nokel81) [inline src/renderer/components/cluster-settings/components/cluster-node-shell-setting.tsx]: Nit: the tooltip props can just be `tooltip="Reset"` (etc...)

Nit: these are only each used once, so I think it would be better to just declare them inline.

**Review by Nokel81 — COMMENTED** [review]
One final thing and then LGTM!

**Review by Nokel81 — APPROVED** [review]

**Comment by Nokel81** [comment]
closes https://github.com/lensapp/lens/pull/3214

**Comment by meganeinu7** [comment]
@vshakirova I am wondering how I can access this feature. I downloaded the latest version - Lens: 5.4.5-latest.20220405.1
, but I can't find the UI that I see here in this PR.
I am not sure this is the right place to ask this question...

**Comment by meganeinu7** [comment]
@vshakirova I could not find where to ask this question... 
I downloaded the latest version of Lens, but I was not able to access this feature.
Could you let me know where I can find any documentation on this feature?
