### PR TITLE
Fix bundled kubectl path on dev env

### LINKED ISSUE #980: Dev: production bundled kubectl gets overwritten
**Describe the bug**

Production (bundled) kubectl gets overwritten if Lens is started on development environment.

### PR DESCRIPTION
**Pull request by jakolehm**
Bundled kubectl on dev environment was pointing to "production" path. Debugging this revealed multiple issues caused by global state (which was modified during import).

Fixes #980

### CODE REVIEW

**Comment by nevalla** [comment]
`kubectl_spec.ts` is still importing `bundledKubectl` and tests are failing.

**Comment by jakolehm** [comment]
> `kubectl_spec.ts` is still importing `bundledKubectl` and tests are failing.

Fixed.

**Review by nevalla — APPROVED** [review]
LGTM

File: src/main/kubectl.ts [hunk 1]
```diff
@@ -58,7 +64,6 @@ export class Kubectl {
     return path.join((app || remote.app).getPath("userData"), "binaries", "kubectl")
   }
 
-  public static readonly bundledKubectlPath = bundledPath
   public static readonly bundledKubectlVersion: string = bundledVersion
   public static invalidBundle = false
   private static bundledInstance: Kubectl;
```
Comment (Nokel81) [inline src/main/kubectl.ts:69]: I cannot review line 72 but should it be `public stattic get bundled() { ... }`?

Comment (jakolehm) [reply src/main/kubectl.ts:69]: Not sure what you mean 🤔

Comment (Nokel81) [reply src/main/kubectl.ts:69]: I think I meant that I thought it would be better if the way to get the bundled kube instance was through a static getter instead of a static function
