### PR TITLE
Delay removing iframe to fix renderer crash

### LINKED ISSUE #6934: Blank window when cluster disconnected
We see blank view instead of Catalog when disconnected from active cluster.

Tested with minikube with M1 machine.

https://user-images.githubusercontent.com/9607060/212269227-54a7afce-1d50-468a-857c-05fe5b4500b1.mov

v8 fatal error

### PR DESCRIPTION
**Pull request by Nokel81**
Signed-off-by: Sebastian Malton <sebastian@malton.name>

fixes https://github.com/lensapp/lens/issues/6934

### CODE REVIEW

File: src/renderer/components/cluster-manager/cluster-frame-handler.ts [hunk 1]
```diff
@@ -88,7 +88,15 @@ export class ClusterFrameHandler {
           () => {
             this.dependencies.logger.info(`[LENS-VIEW]: remove dashboard, clusterId=${clusterId}`);
             this.views.delete(clusterId);
-            parentElem.removeChild(iframe);
+
+            // Must only remove iframe from DOM after it unloads old code. Else it crashes
+            iframe.addEventListener("load", () => parentElem.removeChild(iframe), {
```
Comment (jim-docker) [inline src/renderer/components/cluster-manager/cluster-frame-handler.ts:93]: `"load"`? How does this work?

Comment (Nokel81) [reply src/renderer/components/cluster-manager/cluster-frame-handler.ts:93]: That event even fires when the load fails.

Comment (jim-docker) [reply src/renderer/components/cluster-manager/cluster-frame-handler.ts:93]: I guess I don't see where the `"load"` event gets called in this situation. By `iframe.setAttribute("src", "");`?

Comment (Nokel81) [reply src/renderer/components/cluster-manager/cluster-frame-handler.ts:93]: https://developer.mozilla.org/en-US/docs/Web/API/Window/load_event

This means that the DOM and all script resources have been loaded.

An empty src means "no src" or empty since that is the default.

**Comment by jim-docker** [comment]
There's still an issue with connection races but the renderer process is not getting killed anymore.

https://user-images.githubusercontent.com/40840436/212776927-4bc55eab-c270-414b-8467-7b902b341a6e.mov

Plus the context menu doesn't always come up right away, or respond right away.

**Review by jim-docker — APPROVED** [review]
Approving as it fixes the crash. I discovered that this bug is manifested by https://github.com/lensapp/lens/pull/6851 (bug exists at that PR commit, but not if you check out the commit just before)

**Comment by aleksfront** [comment]
What kind of renderer crash it fixes? This one https://github.com/lensapp/lens/issues/6934?

**Comment by Nokel81** [comment]
@aleksfront Yes
