### PR TITLE
Fix kubeconfig-sync sometimes producing multiple identical entities

### LINKED ISSUE #3872: No longer seeing a blue 'LED' on connected clusters in the Hotbar
**Describe the bug**
Since 5.2.2 I am no longer seeing a blue 'LED' in the Hotbar on clusters that I have connected to.

**To Reproduce**
1. Open Lens
2. Click a pinned cluster to connect
3. Observe that the black dot in the top left of the cluster icon remains black

**Expected behavior**
Previously the black dot would turn blue when a cluster was connected.

**Screenshots**
image

**Environment (please complete the following information):**
- Lens Version: 5.2.3 (observed since 5.2.2)
- OS: Windows 10 21H1

### PR DESCRIPTION
**Pull request by Nokel81**
- This happens when there is an overlapping sync of a folder and a file
  within that folder both producing the same entities

- This also fixes the LED not showing up on some KubernetesCluster
  instances because of this duplication the connected status was being
  set on the first instance, but renderer would use the second (because
  JS's Map constructor deduplicates its constructor initializer by
  taking the last)

- Added some tests to cover this case

Signed-off-by: Sebastian Malton <sebastian@malton.name>

### CODE REVIEW

**Comment by jim-docker** [comment]
This is a big refactor for the 5.6.0 milestone...

**Comment by Nokel81** [comment]
We can push this to the next milestone

**Review by aleksfront — COMMENTED** [review]
I can't reproduce the issue mentioned in the description:

> This happens when there is an overlapping sync of a folder and a file
within that folder both producing the same entities

Tested with 2 different file/folder structures:
```
configfolder -> config
             -> deepfolder -> config
``` 
and
```
configfolder -> config
             -> config 2
```

all of the config files contained same minikube cluster (copy pasted kubeconfig from one file to another)

In my opinion Lens seems work as expected treating these clusters as separate ones. Both of clusters switched okay with proper LED lights without any sync problem. Example:


https://user-images.githubusercontent.com/9607060/187372472-2bb205e1-306b-4060-be97-4bfcf21d7e92.mov

File: src/common/logger/child-logger.injectable.ts [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+import { getInjectable, lifecycleEnum } from "@ogre-tools/injectable";
+import type { Logger } from "../logger";
+import loggerInjectable from "../logger.injectable";
+
+const childLoggerInjectable = getInjectable({
+  id: "child-logger",
+  instantiate: (di, prefix): Logger => {
+    const logger = di.inject(loggerInjectable);
+
+    return {
```
Comment (Iku-turso) [inline src/common/logger/child-logger.injectable.ts]: Note: it's a questionable practise here and elsewhere to bundle all these responsibilities together.

File: src/common/logger/child-logger.injectable.ts [hunk 2]
```diff
@@ -0,0 +1,37 @@
+/**
+ * Copyright (c) OpenLens Authors. All rights reserved.
+ * Licensed under MIT License. See LICENSE in root directory for more information.
+ */
+import { getInjectable, lifecycleEnum } from "@ogre-tools/injectable";
+import type { Logger } from "../logger";
+import loggerInjectable from "../logger.injectable";
+
+const childLoggerInjectable = getInjectable({
+  id: "child-logger",
```
Comment (Iku-turso) [inline src/common/logger/child-logger.injectable.ts]: Proposed name: "prefixed-logger" :)

File: src/main/catalog-sources/__test__/kubeconfig-sync.test.ts [hunk 3]
```diff
@@ -151,7 +164,7 @@ describe("kubeconfig-sync.source tests", () => {
 
       fs.writeFileSync(filePath, contents);
```
Comment (Iku-turso) [inline src/main/catalog-sources/__test__/kubeconfig-sync.test.ts]: Opportunity to get rid of another `mock-fs` ;) Fix if feeling boy-scoutish :)

While we are at it, maybe these technical unit tests could be more awesome as part of behavioural tests instead. WDYT? :)

File: src/common/fs/watch.injectable.ts [hunk 4]
```diff
@@ -0,0 +1,14 @@
+/**
+ * Copyright (c) OpenLens Authors. All rights reserved.
+ * Licensed under MIT License. See LICENSE in root directory for more information.
+ */
+import { getInjectable } from "@ogre-tools/injectable";
+import { watch } from "chokidar";
+
+const watchInjectable = getInjectable({
```
Comment (Iku-turso) [inline src/common/fs/watch.injectable.ts]: Nit: this foreign 3rd party abstraction is accessed directly from our domestic code, hard-coupling us to chokidar exactly. We could just as well invent our own abstraction that would be simple, stable and controlled in single place.

This may not seem super meaningful here, but as a policy, not letting foreign abstractions bleed in domestic code can sure be a life-saver, and a good investment on top of that.

File: src/main/start-main-application/runnables/kube-config-sync/add-source.injectable.ts [hunk 5]
```diff
@@ -0,0 +1,25 @@
+/**
```
Comment (Iku-turso) [inline src/main/start-main-application/runnables/kube-config-sync/add-source.injectable.ts:1]: As modern code like this emerges, it would be great if it did so accompanied by those darn behavioural tests ;) WDYT?

**Review by Iku-turso — CHANGES_REQUESTED** [review]
Discuss: Add or migrate to behavioural tests? Are you too starting to have the feeling that PR's that don't pull their weight in contributions to unit testing don't kinda feel up-to-par anymore? No? :)

**Review by Iku-turso — DISMISSED** [review]

File: src/common/logger/child-logger.injectable.ts (hunk 1 above)
Comment (Iku-turso) [reply src/common/logger/child-logger.injectable.ts]: Discussion handled IRL.

File: src/main/catalog-sources/__test__/kubeconfig-sync.test.ts (hunk 3 above)
Comment (Iku-turso) [reply src/main/catalog-sources/__test__/kubeconfig-sync.test.ts]: Discussion handled IRL.

File: src/common/fs/watch.injectable.ts (hunk 4 above)
Comment (Iku-turso) [reply src/common/fs/watch.injectable.ts]: Discussion handled IRL.

File: src/main/start-main-application/runnables/kube-config-sync/add-source.injectable.ts (hunk 5 above)
Comment (Iku-turso) [reply src/main/start-main-application/runnables/kube-config-sync/add-source.injectable.ts:1]: Discussion handled IRL.

**Review by Iku-turso — DISMISSED** [review]
