### PR TITLE
Fix prometheus operator metrics to work out of the box

### LINKED ISSUE #4435: No metrics with 5.3.0-latest.2021125.2
**Describe the bug**
After installing the 5.3.0-latest.2021125.2 version (both on Windows 10 and Rocky Linux 8.5) the metrics for GKE based cluster are not available.

**To Reproduce**
1. Install 5.2.7 - the metrics are available
2. Install 5.3.0 - the metrics are not available
3. Uninstall 5.3.0 and install 5.2.7 again - metrics are available again

**Expected behavior**
The metric should be availabe

**Screenshots**
image

image

**Environment (please complete the following information):**
- Lens Version: 5.3.0-latest.2021125.2
- OS: Windows 10 and Rocky Linux 8.5 (RHEL 8.5)
- Installation method (e.g. snap or AppImage in Linux): Windows - exe; Rocky - rpm
- GKE base cluster
- Lens metrics configuration: tried Auto detect (works on 5.2.7) and Prometheus Operator (works on 5.2.7)

**Kubeconfig:**
5.2.7 works with the exact same Kubeconfig, so the latter is not an issue

**Additional context**

### PR DESCRIPTION
**Pull request by nevalla**
This PR brings back `group_left` joins removed by https://github.com/lensapp/lens/pull/3653. The reason why joins are not working is that `prometheus-community/kube-prometheus-stack` helm chart has invalid `kube-state-metrics` serviceMonitor custom resource and `kube_pod_info` metrics is not available (https://github.com/prometheus-community/helm-charts/issues/1631).

Metrics on Lens IDE should work without making any additional relabelings and that's why bringing these group left joins back.

Fixes: #4435

### CODE REVIEW

**Review by jweak — APPROVED** [review]

**Review by aleksfront — APPROVED** [review]

File: src/main/prometheus/operator.ts [hunk 1]
```diff
@@ -50,7 +50,7 @@ export class PrometheusOperator extends PrometheusProvider {
           case "memoryAllocatableCapacity":
             return `sum(kube_node_status_allocatable{node=~"${opts.nodes}", resource="memory"})`;
           case "cpuUsage":
-            return `sum(rate(node_cpu_seconds_total{node=~"${opts.nodes}", mode=~"user|system"}[${this.rateAccuracy}]))`;
+            return `sum(rate(node_cpu_seconds_total{mode=~"user|system"}[${this.rateAccuracy}])* on (pod,namespace) group_left(node) kube_pod_info{node=~"${opts.nodes}"})`;
```
Comment (marcbachmann) [inline src/main/prometheus/operator.ts:53]: The queries are now wrong again 😉 
It should be reversed, join on `node`, take the specific labels
```
on (node) group_left(pod, namespace)
```

Or does the query work for you?

Comment (Nokel81) [reply src/main/prometheus/operator.ts:53]: It does not work for us. Many reports about the queries you provided as failing that is why we reverted them.

Comment (marcbachmann) [reply src/main/prometheus/operator.ts:53]: I agree that they need to be reintroduced to fix the compatibilty, but they need to get applied correctly to get it to work.

Comment (marcbachmann) [reply src/main/prometheus/operator.ts:53]: ahhh, so `node_cpu_seconds_total` should contain `pod` and `namespace`. Maybe a comment about that would be useful. The node exporter in my setup doesn't have those labels. That also belongs into the documentation.

Comment (Nokel81) [reply src/main/prometheus/operator.ts:53]: Ah thanks for the info, would you mind making an issue to add that to the documentation?

Comment (nevalla) [reply src/main/prometheus/operator.ts:53]: @marcbachmann how did you install prometheus operator?

Comment (marcbachmann) [reply src/main/prometheus/operator.ts:53]: I have an external node exporter running natively on the hosts.
Therefore it only has the `node` label. I'm doing this because I have still some other services like databases outside kubernetes.

Might be an edge case and I could migrate that into the cluster.
