### PR TITLE
Stop using sharp at runtime

### LINKED ISSUE #5336: 5.5.beta crashes on startup
**Describe the bug**
Updated the app to Version 5.5.0-beta.0.20220505.1 (5.5.0-beta.0.20220505.1.20220505.1) and it crashes on startup.

**To Reproduce**
1. Update app
2. Open the app
3. See error 

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
Screenshot 2022-05-05 at 17 39 21

- Lens Version: 5.5.0-beta.0.20220505.1
- OS: macOS 11.5.2 M1 arm

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Uncaught Exception:
Error: 
Something went wrong installing the "sharp" module

dlopen(/Applications/Lens.app/Contents/Resources/app.asar.unpacked/node_modules/sharp/build/Release/sharp-darwin-arm64v8.node, 1): Library not loaded: @rpath/libvips-cpp.42.dylib
Referenced from: /Applications/Lens.app/Contents/Resources/app.asar.unpacked/node_modules/sharp/build/Release/sharp-darwin-arm64v8.node
Reason: image not found

Possible solutions:
- Install with the --verbose flag and look for errors: "npm install --ignore-scripts=false --verbose sharp"
- Install for the current darwin-arm64v8 runtime: "npm install --platform=darwin --arch=arm64v8 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
at Object.<anonymous> (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/sharp/lib/sharp.js:31:9)
at Module._compile (internal/modules/cjs/loader.js:1083:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1113:10)
at Module.load (internal/modules/cjs/loader.js:940:32)
at Module._load (internal/modules/cjs/loader.js:781:14)
at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
at Module.require (internal/modules/cjs/loader.js:964:19)
at require (internal/modules/cjs/helpers.js:88:18)
at Object.<anonymous> (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/sharp/lib/constructor.js:8:1)
at Module._compile (internal/modules/cjs/loader.js:1083:30)
```

### LINKED ISSUE #5344: Tray icon became white on dark theme in macOS Monterey
Tray icon always should be dark on macOS no matter what native theme is used.

The problem:
lens white icon

This probably a regression from https://github.com/lensapp/lens/pull/5157

### PR DESCRIPTION
**Pull request by Nokel81**
- Generate icons at build time, don't commit them as they are binary
  files

Signed-off-by: Sebastian Malton <sebastian@malton.name>

fixes https://github.com/lensapp/lens/issues/5336

### CODE REVIEW

File: src/main/tray/tray.ts [hunk 1]
```diff
@@ -4,92 +4,45 @@
...
-      prevShouldUseDarkColors = nativeTheme.shouldUseDarkColors;
-      createCurrentTrayIcon()
-        .then(img => tray.setImage(img));
-    }
-  };
-
-  nativeTheme.on("updated", onUpdated);
-
-  return () => nativeTheme.off("updated", onUpdated);
+function getTrayIcon() {
```
Comment (ixrock) [inline src/main/tray/tray.ts]: _nit:_
 ```suggestion
function getTrayIconPath(): string {
```

**Review by ixrock — DISMISSED** [review]

File: build/generate-tray-icons.ts [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+svgRoot.innerHTML += `<style>* {fill: black !important;}</style>`;
+
+const darkTemplate = svgRoot.outerHTML;
+
+console.log("Generating tray icon pngs");
+
+ensureDirSync(outputFolder);
+
+Promise.allSettled([
+  sharp(Buffer.from(darkTemplate))
```
Comment (jim-docker) [inline build/generate-tray-icons.ts:32]: I guess this runs ok during a build on apple silicon?

**Review by jim-docker — APPROVED** [review]

File: build/generate-tray-icons.ts (hunk 2 above)
Comment (Nokel81) [reply build/generate-tray-icons.ts:32]: Yes because the version installed locally will be whatever platform is being built on. The problem with the m1 was that it is being built on a non-m1 system so we were cross compiling the C++.

File: build/generate-tray-icons.ts [hunk 3]
```diff
@@ -0,0 +1,50 @@
...
+  sharp(Buffer.from(lightTemplate))
+    .resize({ width: size, height: size })
+    .png()
+    .toFile(path.join(outputFolder, "trayIconTemplate.png")),
+  sharp(Buffer.from(lightTemplate))
+    .resize({ width: size*2, height: size*2 })
+    .png()
+    .toFile(path.join(outputFolder, "trayIconTemplate@2x.png")),
+])
+  .then(console.log)
```
Comment (chenhunghan) [inline build/generate-tray-icons.ts:49]: Do we need this? but probably no harm.

**Review by chenhunghan — APPROVED** [review]

File: build/generate-tray-icons.ts (hunk 3 above)
Comment (Nokel81) [reply build/generate-tray-icons.ts:49]: We can probably improve this in the future. It is nice to have some confirmation that it completed successfully.

**Comment by jansav** [comment]
1. This PR introduced temporal dependency for running development environment. If you are trying to start application (using `yarn dev-run`) before ever building you will face an error.

```
(node:30868) UnhandledPromiseRejectionWarning: Error: Failed to load image from path '/xxx/lens/build/tray/trayIconTemplate.png'
```

2. `make dev` fails immediately (M1) with

```
error Command failed with signal "SIGKILL".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make: *** [build/tray/trayIconTemplate.png] Error 1
```

3. `build:tray-icons` script in `package.json` is now out-of-date.

**Comment by Nokel81** [comment]
That is a good catch. Will fix again.

**Comment by Nokel81** [comment]
> 1. This PR introduced temporal dependency for running development environment.

I think that `make dev` is the normal way of running dev mode, is that not the case for you?

**Comment by jansav** [comment]
> I think that make dev is the normal way of running dev mode, is that not the case for you?

`make dev` is super slow in comparison to three separate terminals for:

- `yarn dev-run`
- `yarn dev:main`
- `yarn dev:renderer`

There are some downsides but good stuff overwhelms the bad stuff.
