### PR TITLE
Showing colors in logs

### LINKED ISSUE #1357: 4.0.0-beta.1 - Colours are no longer rendered in logs
**Describe the bug**
Log has colour escape codes. These are no longer rendered.

Seems to be a regression of : https://github.com/lensapp/lens/issues/149

**To Reproduce**
1. Output log with colour escape codes

**Expected behavior**
Logs with escape characters render correct colours (or have an option to enable colour support).

**Screenshots**

image

**Environment (please complete the following information):**
- Lens Version: 4.0.0-beta.1
- OS: OSX
- Installation method (e.g. snap or AppImage in Linux): DMG

### PR DESCRIPTION
**Pull request by aleksfront**
Converting ANSI color characters to `span` elements with styles.

debian
airflow logs

Fixes https://github.com/lensapp/lens/issues/1357

### CODE REVIEW

**Review by Nokel81 — APPROVED** [review]

File: src/renderer/components/dock/pod-logs.tsx [hunk 1]
```diff
@@ -185,6 +188,7 @@ export class PodLogs extends React.Component<Props> {
     const { searchQuery, isActiveOverlay } = searchStore;
     const item = this.logs[rowIndex];
     const contents: React.ReactElement[] = [];
+    const ansiToHtml = (ansi: string) => DOMPurify.sanitize(this.colorConverter.ansi_to_html(ansi));
```
Comment (Nokel81) [inline src/renderer/components/dock/pod-logs.tsx:191]: Why is this a local variable and not a new method?

Comment (aleksfront) [reply src/renderer/components/dock/pod-logs.tsx:191]: This function only used inside wrapper method it's defined. No external places using it.

Comment (Nokel81) [reply src/renderer/components/dock/pod-logs.tsx:191]: Ah okay
