### PR TITLE
Initialize HelmRepoManager on demand

### LINKED ISSUE #2594: Loading of screens seems to take more than 5s
**Describe the bug**
When clicking on a cluster from the catalog screen the green notification box says the cluster is connected but the screen is empty for approx 5s before the cluster view is displayed.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 5.0.0-alpha.2
- OS: [e.g. OSX] OSX
- Installation method (e.g. snap or AppImage in Linux):

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

### PR DESCRIPTION
**Pull request by Nokel81**
- Make most functions static as they don't actually reference the parsed
  helm ENV

- Fix HelmRepoManager not being made on main

Signed-off-by: Sebastian Malton <sebastian@malton.name>

Fixes #2594

### CODE REVIEW

**Review by jakolehm — APPROVED** [review]

File: src/main/helm/helm-repo-manager.ts [hunk 1]
```diff
@@ -102,13 +106,7 @@ export class HelmRepoManager extends Singleton {
     }
   }
 
-  public async repository(name: string) {
-    const repositories = await this.repositories();
-
-    return repositories.find(repo => repo.name == name);
-  }
```
Comment (jim-docker) [inline src/main/helm/helm-repo-manager.ts:109]: Why eliminate this method in favour of duplicating code (calling `repositories()` and the `find()` call everywhere we used to just call `repository()`)?

**Review by jim-docker — APPROVED** [review]

File: src/main/helm/helm-repo-manager.ts (hunk 1 above)
Comment (Nokel81) [reply src/main/helm/helm-repo-manager.ts:109]: Mostly to call out that have to get all `repositories` and that there isn't a way to get a single repo.
