### PR TITLE
Fix syncing shell env on TCSH and CSH

### LINKED ISSUE #6446: Incorrect PATH env variable with tcsh
**Describe the bug**
PATH is incorrect in Lens when default shell is tcsh on Mac.

The PATH is correct if Lens is started from terminal.

**To Reproduce**
1. Change default shell to tcsh with `chsh -s /bin/tcsh`
2. Close Lens (also from icon) and terminal windows (just to be sure)
3. Verify that `os.userInfo().shell` returns `/bin/tcsh` in Node repl
4. Verify that PATH contains `/usr/local/bin` in terminal with tcsh
5. Start Lens from e.g. Finder, not terminal.
6. Execute `process.env.PATH` in Developer Tools

**Expected behavior**
It should return `/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin` (or whatever is PATH).

**Actual behavior**
It returns `/usr/bin:/bin:/usr/sbin:/sbin``

This can break various extensions and features in Lens.

**Environment (please complete the following information):**
- Lens Version: 2022.10.181357-latest
- OS: Intel Mac

### PR DESCRIPTION
**Pull request by Nokel81**
Signed-off-by: Sebastian Malton <sebastian@malton.name>

fixes #6446

### CODE REVIEW

File: src/main/utils/shell-env/compute-unix-shell-environment.injectable.ts [hunk 1]
```diff
@@ -8,84 +8,92 @@ import { basename } from "path";
...
+      const noAttach = process.env["ELECTRON_NO_ATTACH_CONSOLE"];
+      const env = {
+        ...process.env,
+        ELECTRON_RUN_AS_NODE: "1",
+        ELECTRON_NO_ATTACH_CONSOLE: "1",
+      };
+      const mark = randomUUID().replace(/-/g, "");
+      const regex = new RegExp(`${mark}(\\{.*\\})${mark}`);
+      const shellName = basename(shell);
+      const { command, shellArgs } = (() => {
```
Comment (panuhorsmalahti) [inline src/main/utils/shell-env/compute-unix-shell-environment.injectable.ts]: I'd refactor this IIFE into a separate function for readability and simplicity.

**Review by panuhorsmalahti — APPROVED** [review]
