### PR TITLE
Fix kubernetes api requests to work with non-"namespaces" pathnames

### LINKED ISSUE #394: Custom Resources List is Never Loading if version does not match regex "v.*?"
**To Reproduce**
1. Go to 'Custom Resources → Group → Your CRD'
2. Click on selected CRD
3. Wait until list of CRs will load
4. It will never load

**Expected behavior**
Expected to see list of CRs for CRD

**Screenshots**
Lens 2020-05-29 19-45-06

**Environment (please complete the following information):**
- Lens Version: 3.4.0
- OS: OSX
- Installation method: OSX Official Image
 
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
/Applications/Lens.app/Contents/MacOS/Lens
info: Checking for update
info: Update for version 3.4.0 is not available (latest version: 3.4.0, downgrade is disallowed).
warn: PrometheusLens: failed to list services: [object Object]
warn: PrometheusLens: failed to list services: [object Object]
info: using operator as prometheus provider
info: using operator as prometheus provider
```

Thank you,

### PR DESCRIPTION
**Pull request by Nokel81**
This PR fixes `parseAPI` not accepting versions that don't start with 'v'.

The brunt of this work was getting the `parseAPI` function to work with pathnames that don't have `/namespaces/` in them and with versions that don't start with `v`.

With this branch some localization is still broken so I will look into that before merging.

fixes #394

### CODE REVIEW

**Comment by nevalla** [comment]
Looking good. Also, nice to have unit tests covering this :+1:. 

One thing about `@babel/preset-env` upgrade. Is it really required to upgrade it? If it's not required for this PR, I would love to see it  done in separate PR, if we feel it's good to upgrade.

**Comment by nevalla** [comment]
@Nokel81 please could you revert `yarn.lock` too?

**Comment by Nokel81** [comment]
Oops, I thought I did because there were changes to it when I revert that package version.

**Comment by Nokel81** [comment]
@nevalla done

**Review by nevalla — APPROVED** [review]
LGTM

File: dashboard/client/api/kube-api.ts [hunk 1]
```diff
@@ -32,20 +33,45 @@ export interface IKubeApiLinkRef {
...
-    const [, apiPrefix, apiGroup = "", apiVersion, namespace, resource, name] = apiPath.match(KubeApi.matcher) || [];
+    const [, prefix, ...parts] = apiPath.split("/");
+    const apiPrefix = `/${prefix}`;
+
+    const [left, right, found] = split(parts, "namespaces");
+    let apiGroup, apiVersion, namespace, resource, name;
+
+    if (found) {
+      if (left.length == 0) {
+        throw new Error(`invalid apiPath: ${apiPath}`)
```
Comment (jakolehm) [inline dashboard/client/api/kube-api.ts:53]: Throwing errors here is a breaking change (and it breaks the whole app in some cases).

Comment (Nokel81) [reply dashboard/client/api/kube-api.ts:53]: Well if this is throwing an error then that api would be a very good candidate for a new unit test and extending this function.
