### PR TITLE
Keep disabled Hotbar entries visible

### LINKED ISSUE #2650: Adding a cluster to the hotbar should override "empty" entries
**Describe the bug**
Now that the hotbar has "empty" entries by default (see #2638) (though I don't know why they actually exist instead of just being placeholders). If you add a cluster they should override them.

This is what happens if you add a cluster currently:
Screen Shot 2021-04-27 at 3 52 43 PM

@aleksfront ?

### PR DESCRIPTION
**Pull request by aleksfront**
When items get deleted from catalog (technically checking their existence inside in `catalogEntityRegistry.items`) - associated hotbar items became `disabled`.

Disabled state means it can't be clicked, has dimmed styles and has one menu option `Remove from Hotbar`.

https://user-images.githubusercontent.com/9607060/117285386-a273cb80-ae70-11eb-9449-25f2c9b910e4.mp4

Now, instead of "reserver" empty cells user will see disabled ones.

Fixes #2650 

In addition, added some more tooltip styling.

### CODE REVIEW

File: src/common/hotbar-store.ts [hunk 1]
```diff
@@ -8,6 +8,8 @@ import isNull from "lodash/isNull";
 export interface HotbarItem {
   entity: {
     uid: string;
+    name: string;
+    source: string;
```
Comment (aleksfront) [inline src/common/hotbar-store.ts]: Those extra data needed for disabled HotbarIcon, since entity might be disappeared, but we still need to show name and background color for `disabled` item.

File: src/renderer/components/+catalog/material-tooltip/material-tooltip.tsx [hunk 2]
```diff
@@ -0,0 +1,28 @@
+import React from "react";
+import { makeStyles, Tooltip, TooltipProps } from "@material-ui/core";
+
+const useStyles = makeStyles(() => ({
+  arrow: {
+    color: "#18191c",
```
Comment (aleksfront) [inline src/renderer/components/+catalog/material-tooltip/material-tooltip.tsx]: Light theme coloring would come with another PR

File: src/renderer/components/hotbar/hotbar-entity-icon.tsx [hunk 3]
```diff
@@ -0,0 +1,115 @@
...
+
+interface Props extends DOMAttributes<HTMLElement> {
+  entity: CatalogEntity;
+  className?: IClassName;
+  errorClass?: IClassName;
+  remove: (uid: string) => void;
+}
+
+@observer
+export class HotbarEntityIcon extends React.Component<Props> {
```
Comment (aleksfront) [inline src/renderer/components/hotbar/hotbar-entity-icon.tsx:25]: I've separated `HotbarEntityIcon` out of `HotbarIcon` to create another layer of abstraction and make `HotbarIcon` more generic regardless of entity availability.

File: src/renderer/components/+catalog/material-tooltip/material-tooltip.tsx (hunk 2 above)
Comment (Nokel81) [reply src/renderer/components/+catalog/material-tooltip/material-tooltip.tsx]: Wouldn't it make sense to have it in this PR though?

File: src/common/hotbar-store.ts (hunk 1 above)
Comment (Nokel81) [reply src/common/hotbar-store.ts]: Have you tested the flow of changing an entity's name? Does the hotbar icon update accordingly?

**Review by Nokel81 — DISMISSED** [review]

**Comment by aleksfront** [comment]
> Have you tested the flow of changing an entity's name? Does the hotbar icon update accordingly?

Yes, if cluster name is changes via settings, the icon changes accordingly.

super-minikube

File: src/migrations/hotbar-store/5.0.0-alpha.0.ts [hunk 4]
```diff
@@ -22,7 +22,11 @@ export default migration({
       }
 
       hotbar.items.push({
-        entity: { uid: cluster.id },
+        entity: {
```
Comment (jakolehm) [inline src/migrations/hotbar-store/5.0.0-alpha.0.ts]: We need to create a new migration because this will not be applied to existing beta users.

Comment (aleksfront) [reply src/migrations/hotbar-store/5.0.0-alpha.0.ts]: Created new migration in `src/migrations/hotbar-store/5.0.0-beta.4.ts`

File: src/renderer/components/+catalog/material-tooltip/material-tooltip.tsx (hunk 2 above)
Comment (aleksfront) [reply src/renderer/components/+catalog/material-tooltip/material-tooltip.tsx]: Yes, this changes took a while for some cache issue which I can't solve right now quickly. So don't want to freeze current PR because of that.

File: src/common/hotbar-store.ts [hunk 5]
```diff
@@ -123,9 +125,14 @@ export class HotbarStore extends BaseStore<HotbarStoreModel> {
     }
   }
 
+  @action
   addToHotbar(item: CatalogEntityItem, cellIndex = -1) {
     const hotbar = this.getActive();
-    const newItem = { entity: { uid: item.id }};
+    const newItem = { entity: {
+      uid: item.id,
+      name: item.name,
```
Comment (Nachasic) [inline src/common/hotbar-store.ts:133]: This change seems to have broken a migration in `src/migrations/hotbar-store/5.0.0-alpha.0.ts(25,9)`:
```
TS2739: Type '{ uid: any; }' is missing the following properties from type '{ uid: string; name: string; source: string; }': name, source
```

**Review by Nachasic — CHANGES_REQUESTED** [review]

**Comment by aleksfront** [comment]
@jakolehm @Nachasic Please take another look. I've added new migration along with related tests.

File: src/migrations/hotbar-store/5.0.0-beta.4.ts [hunk 6]
```diff
@@ -0,0 +1,30 @@
+import { Hotbar } from "../../common/hotbar-store";
```
Comment (Nokel81) [inline src/migrations/hotbar-store/5.0.0-beta.4.ts]: This prevents a circular dependency.

```suggestion
import type { Hotbar } from "../../common/hotbar-store";
```

File: src/migrations/hotbar-store/index.ts [hunk 7]
```diff
@@ -2,8 +2,10 @@
 
 import version500alpha0 from "./5.0.0-alpha.0";
 import version500alpha2 from "./5.0.0-alpha.2";
+import version500beta4 from "./5.0.0-beta.4";
 
 export default {
   ...version500alpha0,
-  ...version500alpha2
+  ...version500alpha2,
+  ...version500beta4
```
Comment (Nokel81) [inline src/migrations/hotbar-store/index.ts]: Please add a comma here so that future diffs are smaller. (I am thinking of adding a lint for this)

File: src/renderer/components/+catalog/material-tooltip/material-tooltip.tsx (hunk 2 above)
Comment (Nokel81) [reply src/renderer/components/+catalog/material-tooltip/material-tooltip.tsx]: Cache issue? What is wrong with just putting these into the default MuiProvider which is called in `bootstrap.tsx`? That way we don't even need this special component.

File: src/renderer/components/hotbar/hotbar-cell.tsx [hunk 8]
```diff
@@ -0,0 +1,36 @@
...
+
+export function HotbarCell({ innerRef, children, className, ...rest }: Props) {
+  const [animating, setAnimating] = useState(false);
+  const onAnimationEnd = () => { setAnimating(false); };
+  const onClick = () => {
+    if (className.includes("isDraggingOver")) {
+      return;
+    }
+
+    setAnimating(true);
```
Comment (Nokel81) [inline src/renderer/components/hotbar/hotbar-cell.tsx]: I think the following would have the same effect.

```suggestion
    setAnimating(!className.includes("isDraggingOver"));
```

File: src/renderer/components/+catalog/material-tooltip/material-tooltip.tsx (hunk 2 above)
Comment (aleksfront) [reply src/renderer/components/+catalog/material-tooltip/material-tooltip.tsx]: Recently we removed global styles pointing MuiProvider to allow redesign tooltips from different places. Meanwhile, the cache bug is fixed with `make dev`, so css variables are set here. So this issue is fixed and no longer relevant.

**Review by Nachasic — DISMISSED** [review]
LGTM

File: src/migrations/hotbar-store/5.0.0-beta.4.ts [hunk 9]
```diff
@@ -0,0 +1,30 @@
+import type { Hotbar } from "../../common/hotbar-store";
+import { migration } from "../migration-wrapper";
+import { catalogEntityRegistry } from "../../renderer/api/catalog-entity-registry";
+
+export default migration({
+  version: "5.0.0-beta.4",
```
Comment (jakolehm) [inline src/migrations/hotbar-store/5.0.0-beta.4.ts]: I think this needs to be bumped to `beta.5` because `beta.4` has already been released.

File: src/renderer/components/hotbar/hotbar-selector.tsx [hunk 10]
```diff
@@ -2,43 +2,31 @@ import "./hotbar-selector.scss";
...
   const store = HotbarStore.getInstance();
   const activeIndexDisplay = store.activeHotbarIndex + 1;
-  const classes = useStyles();
 
   return (
     <div className="HotbarSelector flex align-center">
       <Icon material="play_arrow" className="previous box" onClick={() => store.switchToPrevious()} />
       <div className="box grow flex align-center">
-        <Tooltip arrow title={hotbar.name} classes={classes}>
+        <MaterialTooltip arrow title={hotbar.name}>
```
Comment (Nokel81) [inline src/renderer/components/hotbar/hotbar-selector.tsx:22]: Nit: is there a reason why we don't just override the default CSS. That way we don't need to write out own component (if all we are doing is changing the styles).

Or is that not a good direction to take this is?

Comment (aleksfront) [reply src/renderer/components/hotbar/hotbar-selector.tsx:22]: Yes, `MaterialTooltip` used as a styled wrapper for Tooltip component. It encapsulates styles inside and allows to use default (or any other) styling for material tooltip from other places.

Comment (jakolehm) [reply src/renderer/components/hotbar/hotbar-selector.tsx:22]: Is `MaterialTooltip` specific to just Catalog? If yes: why catalog tooltips are different?

**Review by Nachasic — APPROVED** [review]

File: src/renderer/components/hotbar/hotbar-selector.tsx (hunk 10 above)
Comment (aleksfront) [reply src/renderer/components/hotbar/hotbar-selector.tsx:22]: It's replacement for our native `Tooltip`. Used in couple of places so far.

Comment (Nokel81) [reply src/renderer/components/hotbar/hotbar-selector.tsx:22]: I still don't understand why we don't just set default values for the `Tooltip` styling and then not need a new component.

Comment (jakolehm) [reply src/renderer/components/hotbar/hotbar-selector.tsx:22]: > It's replacement for our native `Tooltip`. Used in couple of places so far.

I think the location of that component is not right if it's a reusable component. Is there some reason not to replace all uses of the old `Tooltip`?

**Review by jakolehm — APPROVED** [review]
LGTM. We should move `MaterialTooltip` under `components` in follow-up PR (or merge with `Tooltip`).

**Comment by Nokel81** [comment]
I agree with @jakolehm I think that all our uses of `<Tooltip>` should be replaced with the one from Material UI.

Futhermore, I think that this should be done by setting defaults and importing `Tooltip` from `@material-ui/core` directly.
