### PR TITLE
Make opening of release details work properly when release has resources without namespace

### LINKED ISSUE #6031: lens spins infinitely viewing certain helm releases
**Describe the bug**
Clicking on the details of a helm release causes lens to show the pane and a "loading" spinner infinitely.

Issue is present in 6.0.0 & 6.0.1, but not 5.x.x.

This doesn't occur for all helm releases: it seems specific to helm releases from our internal charts. eg, opening the helm release from a community datadog chart works fine.

The error log below reports that it can't load certain resources, but I can load them just fine with lens if I track down the resource manually (confirmed by opening up `guru-web-app-staging-reverse-proxy-configmap` and viewing its contents). Suspect a namespace issue of some kind ..

The RBAC role in use has no restrictions around secrets, resources, etc.

**To Reproduce**

1. Click on "Helm -> Releases"
2. Click on a release
3. Wait

**Expected behavior**

Helm release information is shown

**Screenshots**

image

**Environment (please complete the following information):**
- Lens Version: OpenLens (6.0.1-latest.1660302598735)
- OS: OSX 12.3.1 ARM
- Installation method: .dmg download from https://github.com/MuhammedKalkan/OpenLens/releases/tag/v6.0.1

Note that I observed this behaviour as well with the 6.0.0 binary downloaded via k8slens.dev.

**Logs:**
```
BrowserConsole.js:41 [KUBE-API] watch (secret-1) started /api/v1/secrets?watch=1&resourceVersion=140771938
BrowserConsole.js:47 Orphan promise rejection encountered JsonApiErrorParsederror: "Error from server (NotFound): serviceaccounts \"guru-web-app\" not found\nError from server (NotFound): configmaps \"guru-web-app-staging-reverse-proxy-configmap\" not found\nError from server (NotFound): services \"guru-web-app\" not found\nError from server (NotFound): deployments.apps \"guru-web-app\" not found\nError from server (NotFound): horizontalpodautoscalers.autoscaling \"guru-web-app\" not found\nError from server (NotFound): ingresses.networking.k8s.io \"guru-web-app-internal\" not found\nError from server (NotFound): ingresses.networking.k8s.io \"guru-web-app-external\" not found\n"isUsedForNotification: falsemessages: Array(1)0: "Error from server (NotFound): serviceaccounts \"guru-web-app\" not found\nError from server (NotFound): configmaps \"guru-web-app-staging-reverse-proxy-configmap\" not found\nError from server (NotFound): services \"guru-web-app\" not found\nError from server (NotFound): deployments.apps \"guru-web-app\" not found\nError from server (NotFound): horizontalpodautoscalers.autoscaling \"guru-web-app\" not found\nError from server (NotFound): ingresses.networking.k8s.io \"guru-web-app-internal\" not found\nError from server (NotFound): ingresses.networking.k8s.io \"guru-web-app-external\" not found\n"length: 1[[Prototype]]: Array(0)at: ƒ at()concat: ƒ concat()constructor: ƒ Array()copyWithin: ƒ copyWithin()entries: ƒ entries()every: ƒ every()fill: ƒ fill()filter: ƒ filter()find: ƒ find()findIndex: ƒ findIndex()flat: ƒ flat()flatMap: ƒ flatMap()forEach: ƒ forEach()includes: ƒ includes()indexOf: ƒ indexOf()join: ƒ join()keys: ƒ keys()lastIndexOf: ƒ lastIndexOf()length: 0map: ƒ map()pop: ƒ pop()push: ƒ push()reduce: ƒ reduce()reduceRight: ƒ reduceRight()reverse: ƒ reverse()shift: ƒ shift()slice: ƒ slice()some: ƒ some()sort: ƒ sort()splice: ƒ splice()toLocaleString: ƒ toLocaleString()toString: ƒ toString()unshift: ƒ unshift()values: ƒ values()Symbol(Symbol.iterator): ƒ values()Symbol(Symbol.unscopables): {copyWithin: true, entries: true, fill: true, find: true, findIndex: true, …}[[Prototype]]: ObjectisAborted: (...)[[Prototype]]: Object
__webpack_modules__.1246.BrowserConsole.log @ BrowserConsole.js:47

```

### PR DESCRIPTION
**Pull request by jansav**
Fixes #6031

Review commit by commit. Please verify with multiple charts and installing them to separate namespaces etc.

Problem:

The issue comes from place where we get resources of a Helm release.

Before this PR, the process of getting resources of a Helm release works like this:
1.  Get manifest of a Helm release e.g. `$ helm get manifest chatwoot-1660899467 --namespace some-namespace --kubeconfig /var/folders/_3/some-kubeconfig`
2. With response of first command, we call `kubectl` to get kube resources. e.g. `$ kubectl get --kubeconfig /var/folders/_3/some-kubeconfig --output json -f -` (notice output of first command as input)

However, latter command doesn't work properly:

1. In case Helm Release has resources in single namespace, it doesn't matter if we specify `--namespace`
2. In case Helm Release has resources in single namespace and resources without namespace, we have to specify `--namespace` to get all resources (it will crash without it, because it cannot find the resource without namespace)
3. In case Helm Release has resources in multiple namespaces, we shouldn't specify `--namespace` (it will crash if namespace doesn't match)

This means that to get all of these combinations to work properly, we have to:
1. Helm manifest of Helm release
2. Split resources from manifest to groups with namespace and default to whatever namespace was set in the 1. command.
3. Get resources from `kubectl` for each group individually and specify the `--namespace`.

---

Also fixed the CSS for the resources tables so that everything lines up even without namespaces and that the names of the resources get the most space:

Screen Shot 2022-09-08 at 8 24 14 AM

### CODE REVIEW

File: src/renderer/components/+helm-releases/release-details/release-details-content.tsx [hunk 1]
```diff
@@ -36,96 +35,85 @@ interface Dependencies {
 
 const NonInjectedReleaseDetailsContent = observer(({ model }: Dependencies & ReleaseDetailsContentProps) => {
   const isLoading = model.isLoading.get();
+  const failedToLoad = model.failedToLoad.get();
+
+  if (failedToLoad) {
+    return <div data-testid="helm-release-detail-error">Failed to load release</div>;
+  }
```
Comment (Nokel81) [inline src/renderer/components/+helm-releases/release-details/release-details-content.tsx]: Shouldn't we display the load error?

File: src/renderer/components/+helm-releases/release-details/release-details-content.tsx [hunk 2]
```diff
@@ -36,96 +35,85 @@ interface Dependencies {
...
-          <DrawerItem
-            name="Status"
-            className="status"
-            labelsOnly>
-            <Badge
-              label={model.release.getStatus()}
-              className={kebabCase(model.release.getStatus())}
+    (isLoading ? (
+      <Spinner center data-testid="helm-release-detail-content-spinner" />
+    ) : (
```
Comment (Nokel81) [inline src/renderer/components/+helm-releases/release-details/release-details-content.tsx]: Isn't the point of `getPlaceholder` so that we don't have to have these sorts of things?

File: src/renderer/components/+helm-releases/release-details/release-details-model/release-details-model.injectable.tsx [hunk 3]
```diff
@@ -92,14 +82,13 @@ export interface ConfigurationInput {
...
   targetRelease: TargetHelmRelease;
-  themeStore: ThemeStore;
   callForHelmReleaseConfiguration: CallForHelmReleaseConfiguration;
   getResourceDetailsUrl: GetResourceDetailsUrl;
   updateRelease: CallForHelmReleaseUpdate;
   showCheckedErrorNotification: ShowCheckedErrorNotification;
   showSuccessNotification: ShowNotification;
   createUpgradeChartTab: (release: HelmRelease) => string;
-  navigateToHelmReleases: NavigateToHelmReleases;
+  closeDrawer: () => void;
```
Comment (Nokel81) [inline src/renderer/components/+helm-releases/release-details/release-details-model/release-details-model.injectable.tsx]: Shouldn't the dependency name be "correct" and then the exposed name be "closeDrawer"?

File: src/main/helm/helm-service/get-helm-release-resources/call-for-helm-manifest/call-for-helm-manifest.injectable.ts [hunk 4]
```diff
@@ -0,0 +1,52 @@
...
+import execHelmInjectable from "../../../exec-helm/exec-helm.injectable";
+import yaml from "js-yaml";
+
+export interface HelmResourceManifest {
+  metadata: {
+    namespace: string;
+  };
+}
+
+const callForHelmManifestInjectable = getInjectable({
```
Comment (Nokel81) [inline src/main/helm/helm-service/get-helm-release-resources/call-for-helm-manifest/call-for-helm-manifest.injectable.ts:11]: nit: most of the rest of these sorts of injectables are prefixed with `request` now, given that you *have* to call a function to use it anyway, using the name "callFor" seems rather redundant.

File: src/main/helm/helm-service/get-helm-release-resources/call-for-kube-resources-by-manifest/call-for-kube-resources-by-manifest.injectable.ts [hunk 5]
```diff
@@ -0,0 +1,73 @@
...
+      kubectlPath,
+      resourceManifests,
+    ) => {
+      const input = pipeline(
+        resourceManifests,
+        map((manifest) => yaml.dump(manifest)),
+        wideJoin("---\n"),
+      );
+
+      const result = await execFileWithInput({
```
Comment (Nokel81) [inline src/main/helm/helm-service/get-helm-release-resources/call-for-kube-resources-by-manifest/call-for-kube-resources-by-manifest.injectable.ts:40]: I guess this is what would be simplified if we just used the kube api directly, since we could do (only on renderer within iframe at the moment)...

File: src/main/helm/helm-service/get-helm-release-resources/get-helm-release-resources.injectable.ts [hunk 6]
```diff
@@ -0,0 +1,52 @@
...
+      const result = await callForHelmManifest(name, namespace, kubeconfigPath);
+
+      if (!result.callWasSuccessful) {
+        throw new Error(result.error);
+      }
+
+      const results = await pipeline(
+        result.response,
+
+        groupBy((item) => item.metadata.namespace || namespace),
```
Comment (Nokel81) [inline src/main/helm/helm-service/get-helm-release-resources/get-helm-release-resources.injectable.ts:36]: Do we need to group cluster scoped resources with a namespace?

File: src/renderer/components/+helm-releases/release-details/release-details-content.tsx (hunk 2 above)
Comment (jansav) [reply src/renderer/components/+helm-releases/release-details/release-details-content.tsx]: Good catch. This was actually just leftover code that was supposed to be removed. Fixed.

File: src/main/helm/helm-service/get-helm-release-resources/call-for-kube-resources-by-manifest/call-for-kube-resources-by-manifest.injectable.ts (hunk 5 above)
Comment (Nokel81) [reply src/main/helm/helm-service/get-helm-release-resources/call-for-kube-resources-by-manifest/call-for-kube-resources-by-manifest.injectable.ts:40]: Let us leave this as is and we can switch in the future if we want to.

File: src/main/helm/helm-service/get-helm-release-resources/get-helm-release-resources.injectable.ts (hunk 6 above)
Comment (Nokel81) [reply src/main/helm/helm-service/get-helm-release-resources/get-helm-release-resources.injectable.ts:36]: Probably not but it is easier if we do not.

**Review by Nokel81 — DISMISSED** [review]

**Comment by jim-docker** [comment]
I'm seeing this, which doesn't happen on 6.0.1-latest.

https://user-images.githubusercontent.com/40840436/188932440-f7c4bbaf-161c-4a63-824c-83dd362703fe.mov

happens for `kube-prometheus-stack` release but not others I tried

**Comment by Nokel81** [comment]
Thanks I will investigate.

**Comment by jim-docker** [comment]
Installed Rook Ceph, version 1.8.3, and got:

https://user-images.githubusercontent.com/40840436/188957872-10fbed1d-2880-4d9a-a3a6-13a6c360b175.mov

same error after upgrade to Ceph 1.10.0, so version may be irrelevant

**Comment by Nokel81** [comment]
@jim-docker Can you try again now?

File: src/main/helm/exec-helm/exec-helm.injectable.ts [hunk 7]
```diff
@@ -8,7 +8,7 @@ import helmBinaryPathInjectable from "../helm-binary-path.injectable";
 import type { AsyncResult } from "../../../common/utils/async-result";
 import { getErrorMessage } from "../../../common/utils/get-error-message";
 
-export type ExecHelm = (...args: string[]) => Promise<AsyncResult<string>>;
+export type ExecHelm = (args: string[]) => Promise<AsyncResult<string>>;
```
Comment (jim-docker) [inline src/main/helm/exec-helm/exec-helm.injectable.ts:11]: this seems like a ride-along change

**Review by jim-docker — COMMENTED** [review]
I still see `Error: Exited without exit code` for `ceph`, and now for `kube-prometheus-stack`. Maybe this only happens with some pre-existing Helm releases?

File: src/main/helm/helm-service/get-helm-release-resources/call-for-kube-resources-by-manifest/exec-file-with-input/exec-file-with-input.injectable.ts [hunk 8]
```diff
@@ -26,7 +26,9 @@ const execFileWithInputInjectable = getInjectable({
         let execution: ChildProcess;
 
         try {
-          execution = execFile(filePath, commandArguments);
+          execution = execFile(filePath, commandArguments, {
+            maxBuffer: 8 * 1024 * 1024 * 1024, // 8 MiB
```
Comment (jim-docker) [inline src/main/helm/helm-service/get-helm-release-resources/call-for-kube-resources-by-manifest/exec-file-with-input/exec-file-with-input.injectable.ts:30]: how do we know this is enough?

**Review by jim-docker — APPROVED** [review]

**Review by jim-docker — APPROVED** [review]
I think this should be for 6.1 unless we think it is really critical.

File: src/main/helm/helm-service/get-helm-release-resources/call-for-kube-resources-by-manifest/exec-file-with-input/exec-file-with-input.injectable.ts (hunk 8 above)
Comment (Nokel81) [reply src/main/helm/helm-service/get-helm-release-resources/call-for-kube-resources-by-manifest/exec-file-with-input/exec-file-with-input.injectable.ts:30]: I guess we don't. The default is 200KiB so this is about 20x the size.

**Review by Nokel81 — APPROVED** [review]
