### PR TITLE
quick fix for logs not showing in tabs after first tab

### LINKED ISSUE #4958: 5.4.0-latest.20220301.1 There is a long delay in getting pod logs
**Describe the bug**
There is a long delay in getting pod logs，sometimes very long
**To Reproduce**
1. Go to 'workload->pods'
2. Click on 'logs'

**Expected behavior**

**Screenshots**
image

**Environment (please complete the following information):**
- Lens Version: 5.4.0-latest.20220301.1
- OS: Win10
- Installation method (e.g. snap or AppImage in Linux): download exe then install

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

### PR DESCRIPTION
**Pull request by jim-docker**
Fixes #4958 

When opening the first pods log tab a pod watch is started and the logs are successfully loaded:
```
[KUBE-API] watch (pod-7) started /api/v1/namespaces/lens-platform/pods?watch=1&resourceVersion=617360
```
But opening subsequent pods log tabs reports an error on (re)starting the watch:
```
[KUBE-API] watch (pod-7) aborted /api/v1/namespaces/lens-platform/pods?watch=1&resourceVersion=617360
[KUBE-API] watch (pod-7) throwed /api/v1/namespaces/lens-platform/pods?watch=1&resourceVersion=617360 The user aborted a request. 
AbortError {type: 'aborted', message: 'The user aborted a request.', stack: 'AbortError: The user aborted a request.\n    at abo…ld/OpenLensDev.js?dfc84d02244888fa6d21:518651:11)'}
KUBE-API] watch (pod-8) started /api/v1/namespaces/default/pods?watch=1&resourceVersion=617433
```
I don't know if this watch error is a factor but the result of this is that on subsequent log tab openings the logs are not loaded. The logs are meant to be loaded in `LogsDockTab` via a call to `model.reloadLogs()` in a react effect:
```
  useEffect(() => {
    model.reloadLogs();

    return model.stopLoadingLogs;
  }, []);
```
This is not being called for subsequent log tabs and is the root of the problem.
It looks like the pod watch is restarted also in an effect here, maybe this is related?
```
  useEffect(() => subscribeStores([
    podsStore,
  ], {
    namespaces: data ? [data.namespace] : [],
  }), [data?.namespace]);
```

~~In any case, I opted for a small kludge to ensure `model.reloadLogs()` gets called when the tab is first opened. I'm sure there's a better way...~~
@Nokel81 pointed to what I think is the proper fix.

### CODE REVIEW

File: src/renderer/components/dock/logs/view.tsx [hunk 1]
```diff
@@ -34,6 +34,12 @@ interface Dependencies {
 const NonInjectedLogsDockTab = observer(({ className, tab, model, subscribeStores }: Dependencies & LogsDockTabProps) => {
   const logListElement = createRef<LogList>();
   const data = model.logTabData.get();
+  const [tabIds, setTabIds] = useState([]);
+
+  if (!tabIds.find(id => tab.id === id)) {
+    setTabIds([...tabIds, tab.id]);
+    model.reloadLogs();
```
Comment (jim-docker) [inline src/renderer/components/dock/logs/view.tsx]: Is it ok to call this here?

Comment (Nokel81) [reply src/renderer/components/dock/logs/view.tsx]: I wonder if having the reloadLogs effect have a dependency on `tabId` would be enough.

Or barring that also having the `subscribeStores` effect change its dependency to `tabId`

Comment (jim-docker) [reply src/renderer/components/dock/logs/view.tsx]: adding tabId as a dependency just limits when the effect is applied? As it is it should always be applied, right?

**Review by Nokel81 — APPROVED** [review]

**Review by jakolehm — APPROVED** [review]
