### PR TITLE
Show active item in hotbar & allow to pin/unpin

### LINKED ISSUE #2791: Hotbar icon active border & status led are not visible
Broken in master branch.

image

### PR DESCRIPTION
**Pull request by jakolehm**
Shows active catalog item in hotbar even if it's not pinned there. This mimics similar behaviour of MacOS dock / Windows taskbar. Current way of not-showing active item (unless pinned) seems to be very confusing for most users.

https://user-images.githubusercontent.com/1446224/118625431-af7aae00-b7d2-11eb-8fee-8e6135257825.mov

Also fixes #2791

### CODE REVIEW

File: src/common/hotbar-store.ts [hunk 1]
```diff
@@ -23,8 +23,8 @@ import { action, comparer, observable, toJS } from "mobx";
 import { BaseStore } from "./base-store";
 import migrations from "../migrations/hotbar-store";
 import * as uuid from "uuid";
-import { CatalogEntityItem } from "../renderer/components/+catalog/catalog-entity.store";
```
Comment (jakolehm) [inline src/common/hotbar-store.ts:26]: Why changed: it's not good practice to import from renderer to common. This change also simplifies things (see tests).

**Review by nevalla — APPROVED** [review]

File: src/renderer/components/hotbar/hotbar-menu.tsx [hunk 2]
```diff
@@ -151,7 +181,7 @@ export class HotbarMenu extends React.Component<Props> {
     return (
       <div className={cssNames("HotbarMenu flex column", className)}>
         <div className="HotbarItems flex column gaps">
-          <DragDropContext onDragEnd={this.onDragEnd}>
+          <DragDropContext onDragEnd={this.onDragEnd.bind(this)}>
```
Comment (ixrock) [inline src/renderer/components/hotbar/hotbar-menu.tsx:184]: nit: I'd better to use arrow-function for all event-handlers by default (or `@boundMethod`, but it would be available only after merging `mobx6` migration branch)

**Review by ixrock — APPROVED** [review]
