### PR TITLE
Fix iframe ipc flakyness after cluster is removed

### LINKED ISSUE #946: Empty dashboard after removing and re-adding the same cluster
**Describe the bug**
I will see occasionally empty dashboard after removing cluster and re-adding it back 

**To Reproduce**
1. Remove cluster
2. Add the same cluster
3. Repeat steps 1 & 2
4. See empty dashboard

**Expected behavior**
Dashboard should be opened correctly

### PR DESCRIPTION
**Pull request by jakolehm**
Fixes #946

Alternative for #931

### CODE REVIEW

File: src/common/cluster-store.ts [hunk 1]
```diff
@@ -73,20 +73,27 @@ export class ClusterStore extends BaseStore<ClusterStoreModel> {
...
 
   @observable activeClusterId: ClusterId;
   @observable removedClusters = observable.map<ClusterId, Cluster>();
   @observable clusters = observable.map<ClusterId, Cluster>();
 
+  registerIpcListener() {
+    logger.info(`[CLUSTER-STORE] start to listen (${webFrame.routingId})`)
+    ipcRenderer.on("cluster:state", (event, model: ClusterState) => {
+      this.applyWithoutSync(() => {
+        logger.info(`[CLUSTER-STORE]: received push-state at ${location.host} (${webFrame.routingId})`, model);
```
Comment (nevalla) [inline src/common/cluster-store.ts]: can we put these back to `silly` level?

File: src/common/base-store.ts [hunk 2]
```diff
@@ -93,6 +93,10 @@ export class BaseStore<T = any> extends Singleton {
     }
   }
 
+  unregisterIpcListener() {
```
Comment (jakolehm) [inline src/common/base-store.ts:96]: Added this so that we can gracefully teardown store listeners.

File: src/common/cluster-ipc.ts [hunk 3]
```diff
@@ -9,7 +9,7 @@ export const clusterIpc = {
       const cluster = clusterStore.getById(clusterId);
       if (cluster) {
         if (frameId) cluster.frameId = frameId; // save cluster's webFrame.routingId to be able to send push-updates
-        return cluster.activate(true);
+        return cluster.activate();
```
Comment (jakolehm) [inline src/common/cluster-ipc.ts:12]: While debugging IPC I noticed that activate really don't need a parameter. Idk why it was there 🤔

File: src/common/cluster-store.ts [hunk 4]
```diff
@@ -73,20 +73,27 @@ export class ClusterStore extends BaseStore<ClusterStoreModel> {
...
-        })
-      })
-    }
   }
 
   @observable activeClusterId: ClusterId;
   @observable removedClusters = observable.map<ClusterId, Cluster>();
   @observable clusters = observable.map<ClusterId, Cluster>();
 
+  registerIpcListener() {
```
Comment (jakolehm) [inline src/common/cluster-store.ts:82]: Moved to a separate function so that we can call this later in bootstrap (registering IPC during "import" might cause problems later).

File: src/common/cluster-store.ts (hunk 1 above)
Comment (jakolehm) [reply src/common/cluster-store.ts]: Oops, yes.. fixed.

File: src/renderer/bootstrap.tsx [hunk 5]
```diff
@@ -27,10 +27,22 @@ export async function bootstrap(App: AppComponent) {
...
   if (App.init) {
     await App.init();
   }
+  window.addEventListener("message", (ev: MessageEvent) => {
+    if (ev.data === "teardown") {
+      userStore.unregisterIpcListener()
+      workspaceStore.unregisterIpcListener()
+      clusterStore.unregisterIpcListener()
+      unmountComponentAtNode(rootElem)
+      window.location.href = "about:blank"
```
Comment (ixrock) [inline src/renderer/bootstrap.tsx:43]: Unmounting root component also somehow related to fix? Or what's it for?

File: src/renderer/bootstrap.tsx [hunk 6]
```diff
@@ -27,10 +27,22 @@ export async function bootstrap(App: AppComponent) {
...
 
+  // Register additional store listeners
+  clusterStore.registerIpcListener();
+
   // init app's dependencies if any
   if (App.init) {
     await App.init();
   }
+  window.addEventListener("message", (ev: MessageEvent) => {
+    if (ev.data === "teardown") {
```
Comment (ixrock) [inline src/renderer/bootstrap.tsx:38]: This event currently is bound to both apps (ClusterManager & Dashboard), but should be listening only in iframes.
Probably make sense move to `app.tsx` or add extra check `process.isMainFrame` before binding.

Also maybe we should check for `evt.origin` that it comes from parent host (`localhost:port`)
Read more: https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage

File: src/renderer/components/cluster-manager/lens-views.ts [hunk 7]
```diff
@@ -20,10 +20,9 @@ export async function initView(clusterId: ClusterId) {
     return;
   }
   logger.info(`[LENS-VIEW]: init dashboard, clusterId=${clusterId}`)
-  const cluster = clusterStore.getById(clusterId);
   const parentElem = document.getElementById("lens-views");
   const iframe = document.createElement("iframe");
-  iframe.name = cluster.contextName;
+  iframe.name = clusterId;
```
Comment (ixrock) [inline src/renderer/components/cluster-manager/lens-views.ts]: This is don't needed anymore I guess. Name was used previously only for dev-purposes.
But `clusterId` also visible in frame's URL.

File: src/renderer/components/cluster-manager/lens-views.ts [hunk 8]
```diff
@@ -42,9 +41,9 @@ export async function autoCleanOnRemove(clusterId: ClusterId, iframe: HTMLIFrame
   // Keep frame in DOM to avoid possible bugs when same cluster re-created after being removed.
   // In that case for some reasons `webFrame.routingId` returns some previous frameId (usage in app.tsx)
   // Issue: https://github.com/lensapp/lens/issues/811
-  iframe.dataset.meta = `${iframe.name} was removed at ${new Date().toLocaleString()}`;
-  iframe.removeAttribute("src")
+  iframe.dataset.meta = `${iframe.name} was removed at ${new Date().toLocaleString()}`
   iframe.removeAttribute("name")
+  iframe.contentWindow.postMessage("teardown", "*")
```
Comment (ixrock) [inline src/renderer/components/cluster-manager/lens-views.ts:50]:
```suggestion
  iframe.contentWindow.postMessage("teardown", getClusterFrameUrl(clusterId))
```
but in `getClusterFrameUrl` should be added `location.protocol` before `//` explicitly (required by postMessage)

File: src/renderer/components/cluster-manager/lens-views.ts (hunk 7 above)
Comment (nevalla) [inline src/renderer/components/cluster-manager/lens-views.ts]: this line is causing integration tests to fail:
```
const waitForMinikubeDashboard = async (app: Application) => {
    ...
    await app.client.waitForExist(`iframe[name="minikube"]`)
    ...
}
```

**Review by ixrock — APPROVED** [review]
Seems to work fine now 👍
But, if this is totally related to unbinding ALL IPC-events before destroying `iframe` we still have one missing `ipcRenderer.on` inside `src/renderer/navigation.ts` and it's not affecting to this issue?

File: src/renderer/components/cluster-manager/lens-views.ts (hunk 7 above)
Comment (jakolehm) [reply src/renderer/components/cluster-manager/lens-views.ts]: It seems that integration tests needs a proper name here.

Comment (jakolehm) [reply src/renderer/components/cluster-manager/lens-views.ts]: Right, will fix.

File: src/renderer/components/cluster-manager/lens-views.ts (hunk 8 above)
Comment (jakolehm) [reply src/renderer/components/cluster-manager/lens-views.ts:50]: Why do we need this? Context is already an iframe so it cannot go anywhere else.

File: src/renderer/bootstrap.tsx (hunk 5 above)
Comment (jakolehm) [reply src/renderer/bootstrap.tsx:43]: I tried to implement symmetric teardown (compared to bootstrap). It's just a bit more smooth compared to direct location change without unmount.

File: src/common/cluster-store.ts (hunk 4 above)
Comment (ixrock) [reply src/common/cluster-store.ts:82]: Because initial `disconnected` previously was `falsy`

File: src/common/cluster-ipc.ts (hunk 3 above)
Comment (ixrock) [reply src/common/cluster-ipc.ts:12]: Yes, indeed it's redundant if we put initial `disconnected` state to `true`

File: src/renderer/components/cluster-manager/lens-views.ts (hunk 8 above)
Comment (ixrock) [reply src/renderer/components/cluster-manager/lens-views.ts:50]: This is saying from docs:

>  Always provide a specific targetOrigin, not *, if you know where the other window's document should be located. Failing to provide a specific target discloses the data you send to any interested malicious site.

Maybe it's more safe.. otherwise i don't know why specifiing `targetOrigin` needed to `postMessage` at all.

**Review by nevalla — APPROVED** [review]
LGTM
