### PR TITLE
Open application only if new update is available when using tray to check for updates

### LINKED ISSUE #5941: 'Check for updates' opens Lens unnecessarily
**To Reproduce**
1. Close Lens but have it running in the tray
2. Open tray menu and choose 'Check for updates'

**Expected behavior**
Lens should not open (especially if there is no update available).

**Actual behavior**
Lens open (but there is no update available).

**Environment (please complete the following information):**
- Lens Version:6.0.0-latest.20220728.2
- OS: OSX

### PR DESCRIPTION
**Pull request by jansav**
Closes #5941

### CODE REVIEW

File: src/renderer/utils/sync-box/provide-initial-values-for-sync-boxes.injectable.ts [hunk 1]
```diff
@@ -7,21 +7,35 @@ import { beforeFrameStartsInjectionToken } from "../../before-frame-starts/befor
...
-        initialValues.forEach(({ id, value }) => {
-          setSyncBoxState(id, value);
+        runInAction(() => {
+          initialValues.forEach(({ id, value }) => {
+            const syncBox = syncBoxes.find((box) => box.id === id);
+
+            assert(syncBox);
+
+            setSyncBoxState(syncBox, value);
+          });
```
Comment (jansav) [inline src/renderer/utils/sync-box/provide-initial-values-for-sync-boxes.injectable.ts:38]: Note: This change here would be covered by that skipped unit test having TODO. Importance of that rises because this is something that we would have seen.

**Review by panuhorsmalahti — APPROVED** [review]

File: src/behaviours/application-update/installing-update-using-topbar-button.test.tsx [hunk 2]
```diff
@@ -107,6 +105,11 @@ describe("encourage user to update when sufficient time passed since update was
           expect(button).toHaveAttribute("data-warning-level", "light");
         });
 
+        // TODO: Implement after starting main and renderer is separated in ApplicationBuilder
+        xit("given closing the application window, when starting the application window again, still shows the button", () => {
+          expect(button).toBeInTheDocument();
+        });
```
Comment (aleksfront) [inline src/behaviours/application-update/installing-update-using-topbar-button.test.tsx:111]: Nit: maybe better to use `it.todo` for such cases? https://jestjs.io/docs/api#testtodoname

File: src/main/application-update/check-for-updates-tray-item.injectable.ts [hunk 3]
```diff
@@ -59,9 +59,11 @@ const checkForUpdatesTrayItemInjectable = getInjectable({
 
       click: pipeline(
         async () => {
-          await processCheckingForUpdates("tray");
+          const { updateIsReadyToBeInstalled } = await processCheckingForUpdates("tray");
 
-          await showApplicationWindow();
+          if (updateIsReadyToBeInstalled) {
+            await showApplicationWindow();
```
Comment (aleksfront) [inline src/main/application-update/check-for-updates-tray-item.injectable.ts:65]: There is no point to show just the application window after user intentionally checked for updates. We should show message at least or dedicated page says `New update is available` with some update info and an action button ("Update now"). Could be done as a separate PR though.

Comment (jansav) [reply src/main/application-update/check-for-updates-tray-item.injectable.ts:65]: Hmm. I'd say it's not that bad, since first thing you see when the application opens in this case is the "Update" button in the top bar. :)

**Review by aleksfront — APPROVED** [review]
