### PR TITLE
Fix CPU/Memory usage metrics when using prometheus operator.

### LINKED ISSUE #607: cpu pod usage wrong
When looking at the pod CPU usage, the numbers are different than in kubernetes-dashboard and `kubectl -n kube-infrastructure top pod`.

1. Go to the pod
2. Click on it
3. See the CPU usage
4. compare it with `kubectl top pod` or kubernetes dashboard
5. notice that the cpu usage is different

**Expected behavior**
The cpu usage is the same

**Environment (please complete the following information):**
- Lens Version: 3.5.1
- OS: linux
- Installation method AppImage

### PR DESCRIPTION
**Pull request by Delorien84**
According to those graphs https://github.com/coreos/kube-prometheus/tree/master/manifests POD cpu and memory should be calculated differently.

Fix #607

### CODE REVIEW

**Comment by Delorien84** [comment]
I added additional fix to cluster graphs.

**Comment by jakolehm** [comment]
@nevalla PTAL

File: src/main/prometheus/operator.ts [hunk 1]
```diff
@@ -62,10 +62,10 @@ export class PrometheusOperator implements PrometheusProvider {
       }
     case 'pods':
       return {
-        cpuUsage: `sum(rate(container_cpu_usage_seconds_total{container!="POD",container!="",pod=~"${opts.pods}",namespace="${opts.namespace}"}[${this.rateAccuracy}])) by (${opts.selector})`,
+        cpuUsage: `sum(rate(container_cpu_usage_seconds_total{container!="POD",container!="",image!="",pod=~"${opts.pods}",namespace="${opts.namespace}"}[${this.rateAccuracy}])) by (${opts.selector})`,
```
Comment (aleksfront) [inline src/main/prometheus/operator.ts:65]: Testing pod metrics on minikube and find no difference with changed commands.

**Review by aleksfront — APPROVED** [review]
