### PR TITLE
Fix TypeError: Cannot read property 'stopServer' of undefined

### LINKED ISSUE #1012: Lens fails to quit
**Describe the bug**
Quitting Lens does not actually terminate the application.  The application continues to run and requires a force-quit.

**To Reproduce**
1. Command-Q, right click dock and Quit, or menu File->Quit

**Expected behavior**
The application will shut down gracefully.

**Environment (please complete the following information):**
- Lens Version: 3.6.5
- OS: MacOS Catalina 10.15.7
- Installation method : dmg

Running the application via `/Applications/Lens.app/Contents/MacOS/Lens` gives the following output when I attempt to quit:

```
info: Closing proxy server
info: [CLUSTER]: disconnect {"id":"c9b4cff4-dafa-424f-8652-778550e005d9","name":"REDACTED","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: unbind events {"id":"c9b4cff4-dafa-424f-8652-778550e005d9","name":"REDACTED","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: disconnect {"id":"d78b19d6-290e-4af2-a227-4c90c7cc3a28","name":"REDACTED","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: unbind events {"id":"d78b19d6-290e-4af2-a227-4c90c7cc3a28","name":"REDACTED","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: disconnect {"id":"b034558b-b41f-45c6-a820-6f163dd68968","name":"REDACTED","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: unbind events {"id":"b034558b-b41f-45c6-a820-6f163dd68968","name":"REDACTED","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: disconnect {"id":"efebe8ee-c388-450d-b286-aa9bea04c45a","name":"REDACTED","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: unbind events {"id":"efebe8ee-c388-450d-b286-aa9bea04c45a","name":"REDACTED","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: disconnect {"id":"91125f5e-3bf0-47ac-9a14-27622f214889","name":"REDACTED","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: unbind events {"id":"91125f5e-3bf0-47ac-9a14-27622f214889","name":"REDACTED","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: disconnect {"id":"530ef343-55f6-43d5-b362-07c286abb146","name":"REDACTED","initialized":true,"ready":true,"online":true,"accessible":true,"disconnected":false}
info: [CLUSTER]: unbind events {"id":"530ef343-55f6-43d5-b362-07c286abb146","name":"REDACTED","initialized":true,"ready":true,"online":true,"accessible":true,"disconnected":false}
info: [CLUSTER]: disconnect {"id":"ccae321f-c41d-4fa8-af96-375a96cc2a19","name":"REDACTED","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: unbind events {"id":"ccae321f-c41d-4fa8-af96-375a96cc2a19","name":"REDACTED","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: disconnect {"id":"4203ac8d-0496-4366-83f3-b82618cac866","name":"REDACTED","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: unbind events {"id":"4203ac8d-0496-4366-83f3-b82618cac866","name":"REDACTED","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: disconnect {"id":"c79e0db6-4723-4113-b1a4-662a4590926d","name":"REDACTED","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: unbind events {"id":"c79e0db6-4723-4113-b1a4-662a4590926d","name":"REDACTED","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: disconnect {"id":"013d1cf1-0705-4d3b-a935-5409c4088ed7","name":"REDACTED","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: unbind events {"id":"013d1cf1-0705-4d3b-a935-5409c4088ed7","name":"REDACTED","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: disconnect {"id":"45155a18-e6bb-4539-a67b-9088b2c2398c","name":"REDACTED","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: unbind events {"id":"45155a18-e6bb-4539-a67b-9088b2c2398c","name":"REDACTED","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: disconnect {"id":"25f412f5-45dc-408d-9dd4-7c2e60c90c4b","name":"REDACTED","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: unbind events {"id":"25f412f5-45dc-408d-9dd4-7c2e60c90c4b","name":"REDACTED","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
(node:29568) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'stopServer' of undefined
    at V.disconnect (/Applications/Lens.app/Contents/Resources/app.asar/static/build/main.js:1:19461)
    at executeAction (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/mobx/lib/mobx.js:927:19)
    at V.disconnect (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/mobx/lib/mobx.js:914:16)
    at /Applications/Lens.app/Contents/Resources/app.asar/static/build/main.js:1:112770
    at ObservableMap.forEach (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/mobx/lib/mobx.js:3651:26)
    at Le.stop (/Applications/Lens.app/Contents/Resources/app.asar/static/build/main.js:1:112756)
    at App.<anonymous> (/Applications/Lens.app/Contents/Resources/app.asar/static/build/main.js:1:117850)
    at App.emit (events.js:223:5)
(node:29568) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:29568) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Please advise if a kubeconfig is required, per the template.  I would need to redact quite a bit of information from it.

### PR DESCRIPTION
**Pull request by jakolehm**
Fixes #1012

### CODE REVIEW

**Review by nevalla — APPROVED** [review]

**Review by nevalla — APPROVED** [review]
LGTM

File: src/main/cluster.ts [hunk 1]
```diff
@@ -170,26 +170,30 @@ export class Cluster implements ClusterModel, ClusterState {
       await this.refreshAllowedResources()
       this.isAdmin = await this.isClusterAdmin()
       this.ready = true
-      this.kubeCtl = new Kubectl(this.version)
-      this.kubeCtl.ensureKubectl() // download kubectl in background, so it's not blocking dashboard
+      this.ensureKubectl()
```
Comment (Nokel81) [inline src/main/cluster.ts:173]: This is dangerous, because if the kubectl promise throws then we will get a "UnhandledPromiseRejectionError" which in the future will cause Lens to crash.
