### PR TITLE
fix inputs not blurring when pressing enter

### LINKED ISSUE #4669: Allow saving cluster name by tapping esc key while on cluster name text box
In the current lens app when adding a cluster and trying to change its name, you must click outside the cluster name text box in order for the change to take place.
Tapping esc goes back to the previous screen without making any changes.

Everytime I add a cluster I must click outside the text box in order to save my change which means it takes a longer time to rename it and it's not quite intuitive.

OS: Ubuntu 20.04.3

- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...]
- Desktop OS: <the OS Lens app runs on in your case>

Thanks.

### PR DESCRIPTION
**Pull request by ndrscodes**
Fixes #4669.

This fix/feature causes inputs to blur (causing the onChange event to be triggered) once the Enter key is pressed. As of now, the user has to manually click outside of the active input in order to save the value.

### CODE REVIEW

File: src/renderer/components/input/input.tsx [hunk 1]
```diff
@@ -283,6 +283,9 @@ export class Input extends React.Component<InputProps, State> {
       } else {
         this.setDirty();
       }
+
+      //pressing enter indicates that the edit is complete, we can unfocus now
+      this.blur();
```
Comment (Nokel81) [inline src/renderer/components/input/input.tsx]: Shouldn't this happen a few lines up, after the `this.setState()` call?

Comment (ndrscodes) [reply src/renderer/components/input/input.tsx]: It depends. doing it like this, the user can unfocus the input even if it's not valid. If we blurred the input right after calling setState, the user would lose the ability to do so (even if trying to submit invalid data doesn't make much sense).. Idk which solution is better.

Comment (Nokel81) [reply src/renderer/components/input/input.tsx]: How does this work with components like `EditableList`? Have you tried that?

makes sense

Comment (ndrscodes) [reply src/renderer/components/input/input.tsx]: i've tested EditableLists using the accessible namespaces. The namespace is added and after that, the input blurs. Should we keep the input focussed in those cases?

Comment (Nokel81) [reply src/renderer/components/input/input.tsx]: I think we should

Comment (ndrscodes) [reply src/renderer/components/input/input.tsx]: What's the cleanest way of doing this in this scenario? Checking the type of Input in the onKeyDown method seems pretty unclean, but that would mean each class would have to decide if the input needs to be blurred itself, or needs to  focus the input again. All of these solutions are not optimal imho

Comment (Nokel81) [reply src/renderer/components/input/input.tsx]: Since I think `EditableList` is the only place where this matters I would make a prop called something like `blurOnEnter` with default value `true` and then `EditableList` can set it to `false`.

File: editable-list.tsx [hunk 2]
```diff
@@ -0,0 +1,95 @@
+/**
```
Comment (Nokel81) [inline editable-list.tsx]: Did you mean to add files at the root of the repo?

Comment (ndrscodes) [reply editable-list.tsx]: errare humanum est. I amended the commit and moved the files to their correct places. sorry!

**Review by Nokel81 — DISMISSED** [review]

**Comment by ndrscodes** [comment]
sorry for causing trouble again. I removed an unnecessary call to stopPropagation(). @Nokel81

**Review by Nokel81 — DISMISSED** [review]

**Review by jim-docker — DISMISSED** [review]

**Comment by Nokel81** [comment]
@ndrscodes Can you please investigate the namespace selector test that is failing?

**Comment by ndrscodes** [comment]
> @ndrscodes Can you please investigate the namespace selector test that is failing?

I've checked it, but i do not know what is causing this issue. It seems like the event is not being propagated to the Wizard/WizardStep. As soon as i implement this.blur() (even this.input.blur()), the WizardStep stops executing the next() function. Do you know what could be causing this? @Nokel81

**Comment by ndrscodes** [comment]
> > @ndrscodes Can you please investigate the namespace selector test that is failing?
> 
> I've checked it, but i do not know what is causing this issue. It seems like the event is not being propagated to the Wizard/WizardStep. As soon as i implement this.blur() (even this.input.blur()), the WizardStep stops executing the next() function. Do you know what could be causing this? @Nokel81 

What we could do is giving an onKeyDown handler to the `WizardStep` in order to execute `submit` when pressing enter. That would also likely lead to cleaner implementation than trusting in onSubmit to fire if Enter is pressed.

**Comment by Nokel81** [comment]
> What we could do is giving an onKeyDown handler to the WizardStep in order to execute submit when pressing enter. That would also likely lead to cleaner implementation than trusting in onSubmit to fire if Enter is pressed.

That is a good idea

**Review by Nokel81 — APPROVED** [review]
Looks great. Thanks!

**Review by ixrock — APPROVED** [review]
