### PR TITLE
Handle status values that contains an object

### LINKED ISSUE #692: Crash when viewing custom resource with a status containing an object
**Describe the bug**

The AppsCode Voyager ingress controller uses a custom resource that its status contains an object. The status has an value that looks like this

```yaml
  status:
    loadBalancer:
      ingress:
      - ip: 13.70.555.555
```

**To Reproduce**

1. Install Voyager operator.
2. Create an ingress
3. Attempt to view ingress.

**Expected behavior**

The information should show rather than the UI crash.

**Screenshots**

image

```
Component stack:
    in span
    in div
    in DrawerItem
    in div
    in CrdResourceDetails
    in div
    in div
    in div
    in Animate
    in Drawer
    in KubeObjectDetails
    in ErrorBoundary
    in Router
    in Unknown
    in App
```

Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bip%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

**Environment (please complete the following information):**
- Lens Version: 3.5.2
- OS: Windows
- Installation method (e.g. snap or AppImage in Linux): Downloaded installer
 
**Additional context**

I have a PR that I will submit that fixes this. Note this points you to the direction of a proper fix, however am open for coding style improvements or whether you already have components that can render it better.

### PR DESCRIPTION
**Pull request by ocdi**
This fixes #692 

I did the bare minimum to fix the bug, and am generally unfamiliar with the codebase. If there are any components that can display the status nicer than me JSON stringifying it, pointers would be helpful.

### CODE REVIEW

**Comment by aleksfront** [comment]
@ocdi Thanks for your contribution! I've prepared some comments and suggestions related to your PR.
1. Your changes not related explicitly to `status` column, but for all `additionalPrinterColumns`, so I would change name of your component to `CrdColumnValue` instead of `RenderCrdStatus`. Also, we shouldn't pass `status` prop here, let's stick with `value`.
2. Need to check with specs. Since `Voyager` creates CRD with additional `status` column it shouldn't contain any objects (https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#additional-printer-columns) - see _Type_ section here.
3. For object column type we can use textarea field as we do it other places.

File: dashboard/client/components/+custom-resources/crd-resource-details.tsx [hunk 1]
```diff
@@ -18,6 +18,15 @@ import { KubeObjectMeta } from "../kube-object/kube-object-meta";
...
 
+function RenderCrdStatus({ status }: { status: any[] | {} | string }) {
+  if (Array.isArray(status)) {
+    return <>{status.map((a, i) => <RenderCrdStatus key={i} status={a} />)}</>
+  }
+  if (typeof(status) === 'object') return <>{JSON.stringify(status)}</>;
+
+  return <>{status}</>
+}
+
```
Comment (aleksfront) [inline dashboard/client/components/+custom-resources/crd-resource-details.tsx]:
```suggestion
function CrdColumnValue({ value }: { value: any[] | {} | string }) {
  if (Array.isArray(value)) {
    return <>{value.map((item, index) => <CrdColumnValue key={index} value={item} />)}</>
  }
  if (typeof(value) === 'object') return (
    <Input
      readOnly
      multiLine
      theme="round-black"
      className="box grow"
      value={JSON.stringify(value, null, 2)}
    />
  );
  return <span>{value}</span>;
}
```

File: dashboard/client/components/+custom-resources/crd-resource-details.tsx [hunk 2]
```diff
@@ -43,9 +52,10 @@ export class CrdResourceDetails extends React.Component<Props> {
         <KubeObjectMeta object={object}/>
         {extraColumns.map(column => {
           const { name } = column;
+          const value = jsonPath.query(object, column.JSONPath.slice(1));
           return (
             <DrawerItem key={name} name={name}>
-              {jsonPath.query(object, column.JSONPath.slice(1))}
+              <RenderCrdStatus status={value} />
```
Comment (aleksfront) [inline dashboard/client/components/+custom-resources/crd-resource-details.tsx]:
```suggestion
              <CrdColumnValue value={value} />
```

**Comment by aleksfront** [comment]
In addition to my code suggestions: we can add this lines into `dashboard/client/components/+custom-resources/crd-resource-details.scss` 
```
.extra-column {
    .value {
      span {
        margin-right: $margin;
      }
    }
  }
```
to make some gaps between spans (if column contains an array).

**Review by aleksfront — CHANGES_REQUESTED** [review]

**Comment by aleksfront** [comment]
@ocdi Can you please also look int DCO bot failure - https://github.com/lensapp/lens/pull/693/checks?check_run_id=1002593627
There is need to sign-off all of your commits.

File: dashboard/client/components/+custom-resources/crd-resource-details.tsx [hunk 3]
```diff
@@ -18,6 +18,21 @@ import { KubeObjectMeta } from "../kube-object/kube-object-meta";
 interface Props extends KubeObjectDetailsProps<KubeObject & { status: any }> {
 }
 
+function CrdColumnValue({ value }: { value: any[] | {} | string }) {
+  if (Array.isArray(value)) {
+    return <>{value.map((item, index) => <CrdColumnValue key={index} value={item} />)}</>
```
Comment (ixrock) [inline dashboard/client/components/+custom-resources/crd-resource-details.tsx]:
```suggestion
    return value.map((item, index) => <CrdColumnValue key={index} value={item} />)
```

**Comment by ocdi** [comment]
I'll fix the commit on my desktop, and squash, I used the github ui which clearly didn't sign off as expected.

File: dashboard/client/components/+custom-resources/crd-resource-details.tsx (hunk 3 above)
Comment (ocdi) [reply dashboard/client/components/+custom-resources/crd-resource-details.tsx]: The reason for using the fragment is because the component is recursively calling itself and the typings don't like it without. I am sure it could be made to work but this is the simplest solution.

**Comment by ocdi** [comment]
@aleksfront thank you for your suggestions - I fixed up the commit issues and added the missing import - this is the end result
image

**Review by aleksfront — APPROVED** [review]
Looking good!

**Comment by nevalla** [comment]
Btw we might want to change target branch to `master` and aim this to `3.6.0`

**Comment by ocdi** [comment]
Rebased and retargeted against master. I tried to test the changes there but the dev build on Windows has changed such that it didn't work for me. I managed to get electron to load but had this error.

```
Uncaught Error: Something went wrong during the migration! Changes applied to the store until this failed migration will be restored. TypeError: Cannot read property 'getPath' of undefined
    at ElectronStore._migrate (app_vue.js:182490)
    at new Conf (app_vue.js:182403)
    at new ElectronStore (app_vue.js:189036)
    at new ClusterStore (app_vue.js:406322)
    at Function.getInstance (app_vue.js:406405)
    at Module../src/common/cluster-store.ts (app_vue.js:406413)
    at __webpack_require__ (app_vue.js:20)
    at Module../node_modules/ts-loader/index.js?!./node_modules/vue-loader/lib/index.js?!./src/renderer/_vue/components/MainMenu/MainMenu.vue?vue&type=script&lang=js& (app_vue.js:362430)
    at __webpack_require__ (app_vue.js:20)
    at Module../src/renderer/_vue/components/MainMenu/MainMenu.vue?vue&type=script&lang=js& (app_vue.js:411227)
```

Given this is a dev build I am unsure if me manually running electron was the cause or something else.

**Comment by aleksfront** [comment]
@ocdi Feel free to squash and merge. There will be big changes in `master` branch very soon when [Vue migration branch](https://github.com/lensapp/lens/pull/585) will be merged. We'll double check the issue then.

**Comment by ocdi** [comment]
I did the squash and rebase, I can't merge because I don't have write access. I managed to get master to run but had to make a change I don't think should be necessary in the import.

```diff
diff --git a/src/migrations/cluster-store/3.6.0-beta.1.ts b/src/migrations/cluster-store/3.6.0-beta.1.ts
index d4c867ffbd8c0a9ead5e300c4ea2b4045b9586de..00ed6f255ddc81df904bb3313f85137748fe8b48 100644
--- a/src/migrations/cluster-store/3.6.0-beta.1.ts
+++ b/src/migrations/cluster-store/3.6.0-beta.1.ts
@@ -1,5 +1,6 @@
 // move embedded kubeconfig into separate file and add reference to it to cluster settings
-import { app } from "electron"
+import { app } from "electron";
+import elec from "electron";
 import  { ensureDirSync } from "fs-extra"
 import * as path from "path"
 import { KubeConfig } from "@kubernetes/client-node";
@@ -8,8 +9,8 @@ import { writeEmbeddedKubeConfig } from "../../common/utils/kubeconfig"
 export function migration(store: any) {
   console.log("CLUSTER STORE, MIGRATION: 3.6.0-beta.1");
   const clusters: any[] = []
-
-  const kubeConfigBase = path.join(app.getPath("userData"), "kubeconfigs")
+  const a = app ?? elec.remote.app;
+  const kubeConfigBase = path.join(a.getPath("userData"), "kubeconfigs")
   ensureDirSync(kubeConfigBase)
   const storedClusters = store.get("clusters") as any[]
   if (!storedClusters) return
```

**Comment by jakolehm** [comment]
@aleksfront only maintainers have squash&merge superpowers 🙂 I'll hit that button now.

@ocdi thanks for contributing this!
