### PR TITLE
Fix broken shell when workdir not exists

### LINKED ISSUE #125: Shell not working if working directory not exists.
**Describe the bug**
"Pod shell" and "Node shell" console hangs if terminal working directory not exists.

**To Reproduce**
1. Create "xxx" local directory
2. Go to cluster settings
3. Set "Terminal Working Directory" as "xxx"
4. Delete directory "xxx"
5. Go to nodes or pods. Select any and press "Exec" button
6. Console just hangs on "Connecting..."

**Expected behavior**
Probably it should use some default working directory.
Or show user friendly error to set proper working directory.

**Environment (please complete the following information):**
- Lens Version: 3.01
- OS: Windows
- Installation method (e.g. snap or AppImage in Linux): Setup.exe

### PR DESCRIPTION
**Pull request by devodev**
- validate shell session cwd exists, otherwise use default: `env.HOME`.

Resolves: https://github.com/lensapp/lens/issues/125

### CODE REVIEW

File: src/main/utils/shell-env.ts [hunk 1]
```diff
@@ -64,3 +64,13 @@ export async function shellEnv(shell?: string, forceRetry = false) : Promise<Env
 
   return envVars;
 }
+
+export function resolveEnv(value: string, env: Record<string, any>): string {
+  // resolves both $VAR and ${VAR} syntax, and makes sure to
+  // ignore malformed syntax, such as begins with digit or lower case characters.
+  return value.replace(/\$\{?([A-Z_][A-Z0-9_]*)(?:(?<=\$\{\1)\})?/g, function (match) {
```
Comment (Nokel81) [inline src/main/utils/shell-env.ts]: It is incorrect that lowercase values are invalid in the environment.

Furthermore shouldn't this regex has a `^` at the end? Lastly this regex is incorrect as it matches `${A`. Furthermore there is no need for it to be a global regex.

To continue bracket matching is not a regular language and requires at least a context free grammer to properly match.

File: src/main/shell-session/shell-session.ts [hunk 2]
```diff
@@ -50,23 +52,33 @@ export abstract class ShellSession {
...
+    if (value) {
+      const resolvedEnvValue = resolveEnv(value, env);
+
+      if (fs.existsSync(resolvedEnvValue)) {
+        cwd = resolvedEnvValue;
+      }
+    }
+
+    return cwd;
+  }
```
Comment (Nokel81) [inline src/main/shell-session/shell-session.ts]: This could be a free function instead.

File: src/main/utils/shell-env.ts (hunk 1 above)
Comment (Nokel81) [reply src/main/utils/shell-env.ts]: I think that we should just support `$...` and not `${..}` and this information should be added to the hint of the "Working Directory" setting.

Comment (devodev) [reply src/main/utils/shell-env.ts]: Agreed, will update, thanks.

File: src/main/shell-session/shell-session.ts (hunk 2 above)
Comment (devodev) [reply src/main/shell-session/shell-session.ts]: Will update.

File: src/main/utils/shell-env.ts (hunk 1 above)
Comment (devodev) [reply src/main/utils/shell-env.ts]: I pushed some changes to now only match on simple syntax (`$HOME`, `$var`), and I added some tests to validate the logic.

Also the reason for a global regex and no line start anchor (`^`) is I thought it would be a good idea while at it to support more than one var, although I have no problem restricting it.

Finally, I updated the hint of "Working Directory" setting to mention environment variable expansion.

Comment (Nokel81) [reply src/main/utils/shell-env.ts]: Will rereview. If we wanted to do some sort of hierarchy then I think we would switch to an array. No need to do weird string parsing.

Comment (devodev) [reply src/main/utils/shell-env.ts]: Yeah the more I think of it, the less I think its useful. The idea was just to allow arbitrary vars expansion, like: `$HOME/myfolder/$ENV` to resolve to `/home/alice/myfolder/development`.

Let me know if you just want me to update this to only validate that cwd exists instead. Thanks.

Comment (Nokel81) [reply src/main/utils/shell-env.ts]: After discussing it with some other team members we think that the expansion of vars is a very good idea but probably should be its own PR because it is is a feature enhancement whereas the rest of this PR is a bug fix.

File: src/main/shell-session/shell-session.ts [hunk 3]
```diff
@@ -50,23 +51,19 @@ export abstract class ShellSession {
   protected kubectlBinDirP: Promise<string>;
   protected kubeconfigPathP: Promise<string>;
 
-  protected get cwd(): string | undefined {
```
Comment (Nokel81) [inline src/main/shell-session/shell-session.ts:53]: Probably making this an `abstract get cwd()` would be a good, then we don't need to change the arguments of `open()`

File: src/main/utils/shell-env.ts (hunk 1 above)
Comment (devodev) [reply src/main/utils/shell-env.ts]: Awesome I will do the split and keep only the bug fix here.

I'll open another PR to add var expansion, and we can discuss there the best way to implement, thanks :)

File: src/main/shell-session/shell-session.ts (hunk 3 above)
Comment (devodev) [reply src/main/shell-session/shell-session.ts:53]: Makes much more sense, will update.

**Comment by devodev** [comment]
I applied the changes requested, and opened a new PR for the env var expansion feature here: https://github.com/lensapp/lens/pull/3386

File: src/main/shell-session/shell-session.ts [hunk 4]
```diff
@@ -61,9 +60,15 @@ export abstract class ShellSession {
   }
 
   open(shell: string, args: string[], env: Record<string, any>): void {
+    let cwd = env.HOME;
+
+    if (this.cwd && fs.existsSync(this.cwd)) {
+      cwd = this.cwd;
+    }
```
Comment (Nokel81) [inline src/main/shell-session/shell-session.ts]: Nit, this could be 
```suggestion
    const cwd = (this.cwd && await fse.pathExists(this.cwd)) 
    	? this.cwd 
    	: env.HOME;
```

Also, given that both child classes have an `async open` function. I think it would be fine to change this function to async too. Don't want to use blocking FS calls within an async context.

Comment (devodev) [reply src/main/shell-session/shell-session.ts]: Agreed, this is an oversight on my part about the async logic.

And I also prefer the ternary. Will update.

**Review by Nokel81 — APPROVED** [review]
