### PR TITLE
Terminal: set NO_PROXY env for localhost communication

### LINKED ISSUE #975: Can't exec on pods
**Describe the bug**
Lens no longer connects to a shell on pods on my setup. Maybe related to the proxy.

We have to connect to our clusters via a jumpbox so I open a socks proxy with ssh then use tinyproxy to act as a http -> socks proxy middle man. This works fine for the normal kubectl on my system with the HTTP_PROXY var set for the tinypoxy port but doesn't seem to work in Lens. If unset `KUBECONFIG` in Lens it work again. I'm on 3.6.4. I see there was a note in prior releases about the proxy not working in some cases but it wasn't in this one so I'm guessing it was resolved.

**To Reproduce**
1. Use a ssh jumpbox to reach k8s via a socks proxy `ssh -D 12345 <jumpbox>`
2. Set up a proxy server to act as HTTP to socks proxy (relevant tinyproxy config below)
```
Port 8118
Listen 127.0.0.1
upstream socks5 127.0.0.1:12345
```
3. Set up shell rc file to use proxy `export HTTP_PROXY=http://localhost:8118`
4. Open Lens and navigate to cluster with HTTP Proxy set in config `http://localhost:8118`
5. Look at pods, see them as expected.
6. Navigate to pod and click icon for `Pod shell`
7. Wait for timeout `error: unable to upgrade connection: error dialing backend: dial tcp <ip>: i/o timeout`
8. Copy and paste command into personal shell and see it work.

**Expected behavior**
Connect to pod shell

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 3.6.4
- OS: OSX
- brew cask installed but updated from within app
- In case it helps, tinyproxy also comes from brew `tinyproxy: stable 1.10.0 (bottled)`
 
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
❯ exec kubectl exec -i -t -n <namespace> <pod> -c <container name> "--" sh -c "clear; (bash || ash || sh)"
error: unable to upgrade connection: error dialing backend: dial tcp <IP>: i/o timeout
Terminal will auto-close in 15 seconds ...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
kind: Config
preferences: {}
current-context: <redacted>
clusters:
  - name: <redacted>
    cluster:
      server: 'http://127.0.0.1:52181/<UUID>'
contexts:
  - name: <redacted>
    context:
      cluster: <redacted>
      user: proxy
users:
  - name: proxy
    user: {}
```

**Additional context**

### PR DESCRIPTION
**Pull request by jakolehm**
Fixes #975

### CODE REVIEW

**Review by kke — APPROVED** [review]
LGTM

**Comment by nevalla** [comment]
what about PowerShell and fish terminals? Should we add this also to `ShellSession.getShellEnv()`?

**Comment by nevalla** [comment]
Pushed change to include `NO_PROXY` in shell env and ensure that localhost is included after sourcing init scripts.

**Comment by jakolehm** [comment]
> Pushed change to include `NO_PROXY` in shell env and ensure that localhost is included after sourcing init scripts.

Thanks!

**Review by nevalla — APPROVED** [review]
Tested and `NO_PROXY` seem to work well. Pushed change that localhost is included in `NO_PROXY` env in regular shell env, so if someone else can take a look that part.

File: src/main/shell-session.ts [hunk 1]
```diff
@@ -125,6 +125,8 @@ export class ShellSession extends EventEmitter {
     if (this.preferences.httpsProxy) {
       env["HTTPS_PROXY"] = this.preferences.httpsProxy
     }
+    const no_proxy = ["localhost", "127.0.0.1", env["NO_PROXY"]]
+    env["NO_PROXY"] = no_proxy.filter(address => !!address).join()
```
Comment (jim-docker) [inline src/main/shell-session.ts:129]: this leaves a trailing comma if `NO_PROXY` was not already defined:
```
jimehrismann@JE-MBP13-2017:~$ env | grep NO_PROXY
NO_PROXY=localhost,127.0.0.1,
jimehrismann@JE-MBP13-2017:~$
```
presumably that's not an issue?

Comment (nevalla) [reply src/main/shell-session.ts:129]: Why is it leaving that? 🤔 I thought that filter would have rejected empty values

Comment (Nokel81) [reply src/main/shell-session.ts:129]: maybe `env["NO_PROXY"]` is filled with whitespace

Comment (jim-docker) [reply src/main/shell-session.ts:129]: this might impact the changes in kubectl.ts as well?

Comment (jim-docker) [reply src/main/shell-session.ts:129]: never mind, sorry. I checked out `fix/skip-https-proxy-for-localhost` but forgot to pull after. So I got Jari's commit but not yours Lauri. After pulling I do not see the trailing comma.
@nevalla 

But it could still be there in the kubectl.ts changes(?)

File: src/main/kubectl.ts [hunk 2]
```diff
@@ -283,7 +283,9 @@ export class Kubectl {
     bashScript += "fi\n"
     bashScript += `export PATH="${helmPath}:${kubectlPath}:$PATH"\n`
     bashScript += "export KUBECONFIG=\"$tempkubeconfig\"\n"
-    bashScript += "export NO_PROXY=localhost,127.0.0.1,$NO_PROXY\n"
+    bashScript += "if [ \"$NO_PROXY\" != \"localhost,127.0.0.1\" ]; then\n"
+    bashScript += "  export NO_PROXY=\"localhost,127.0.0.1,$NO_PROXY\"\n"
```
Comment (jim-docker) [inline src/main/kubectl.ts]: if `$NO_PROXY` is empty this could leave a trailing comma?

Comment (nevalla) [reply src/main/kubectl.ts]: We are setting it as non-empty, but that's true if user's init script sets that empty

Comment (nevalla) [reply src/main/kubectl.ts]: @jim-docker added check that tests `$NO_PROXY` is empty. PTAL again.

Comment (kke) [reply src/main/kubectl.ts]: Something like this could do the trick:

```bash
NO_PROXY=",${NO_PROXY:-localhost},"  # add leading and trailing , change empty val to localhost
NO_PROXY="${NO_PROXY//,localhost,/,}"  # replace ,localhost, with ,
NO_PROXY="${NO_PROXY//,127.0.0.1,/,}"  # replace ,127.0.0.1, with ,
NO_PROXY="localhost,127.0.0.1${NO_PROXY%,}"  # prepend string, remove trailing ,
```

Comment (kke) [reply src/main/kubectl.ts]: same should work for zsh

Comment (kke) [reply src/main/kubectl.ts]: (edited + optimized slightly after first commenting)

Comment (nevalla) [reply src/main/kubectl.ts]: > Something like this could do the trick:
> 
> ```shell
> NO_PROXY=",${NO_PROXY:-localhost},"  # add leading and trailing , change empty val to localhost
> NO_PROXY="${NO_PROXY//,localhost,/,}"  # replace ,localhost, with ,
> NO_PROXY="${NO_PROXY//,127.0.0.1,/,}"  # replace ,127.0.0.1, with ,
> NO_PROXY="localhost,127.0.0.1${NO_PROXY%,}"  # prepend string, remove trailing ,
> ```

Actually it does not. When exporting the env var the value becomes `localhost,127.0.0.1unset` so reverted back.

**Review by kke — APPROVED** [review]
