### PR TITLE
Add migration to fix kubeconfig paths that point to snap config dir

### LINKED ISSUE #951: Kubeconfig path in lens-cluster-store.json is broken after upgrade with Snap
**Describe the bug**
When storing a pasted (or migrated) kubeconfig file, Lens will store it under app config files. However, when snap version is upgraded, snap will create new config directory for the app and kubeconfig file paths referenced in `lens-cluster-store.json` points to old config dir, which might not exist anymore.

### PR DESCRIPTION
**Pull request by nevalla**
This PR adds cluster store migration that is executed every time the snap version of the app is upgraded. The migration will replace `/snap/kontena-lens/[0-9]*/` in kubeconfig path with `/snap/kontena-lens/current/`.

Fixes #951 

Signed-off-by: Lauri Nevala <lauri.nevala@gmail.com>

### CODE REVIEW

File: src/migrations/cluster-store/snap.ts [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+    const storedClusters: ClusterModel[] = store.get("clusters") || [];
+    if (!storedClusters.length) return;
+
+    printLog("Number of clusters to migrate: ", storedClusters.length)
+    const migratedClusters = storedClusters
+      .map(cluster => {
+        /**
+         * replace snap version with 'current' in kubeconfig path
+         */
+        const kubeconfigPath = cluster.kubeConfigPath.replace(/\/snap\/kontena-lens\/[0-9]*\//, "/snap/kontena-lens/current/")
```
Comment (jakolehm) [inline src/migrations/cluster-store/snap.ts]: Should we only do this if file does not exist?

Comment (nevalla) [reply src/migrations/cluster-store/snap.ts]: Added check for that

**Review by jakolehm — APPROVED** [review]
LGTM
