### PR TITLE
Always override PATH when syncing from shell

### LINKED ISSUE #3898: aws credential_process with gsts doesn't work
**Describe the bug**
I'm using `gsts` to auth into my AWS account via Google IDP.
It works for all my tools like kubectl, aws, etc, but Lens is complaining with:
image

My `~/aws/config` looks like:
```
[profile sts]
region = eu-west-1
credential_process =  gsts --json --idp-id xxxx --sp-id xxxx --username xxxx@xxxx.xx --aws-shared-credentials-file /home/xxxx/.aws/gsts_credentials
```

**To Reproduce**
1. Configure your aws/config just like I configured mine;
2. Launch Lens.

**Expected behavior**
I should be able to connect to my Kuberbetes/EKS cluster.

**Environment (please complete the following information):**
image
$ whereis gsts
gsts: /home/xxxx/.nvm/versions/node/v10.15.3/bin/gsts

### PR DESCRIPTION
**Pull request by Nokel81**
Signed-off-by: Sebastian Malton <sebastian@malton.name>

I cannot think of a reason not do so this merge... fixes #3898

### CODE REVIEW

File: src/main/shell-sync.ts [hunk 1]
```diff
@@ -47,14 +40,13 @@ export async function shellSync() {
     env.LANG += ".UTF-8";
   }
 
-  // Overwrite PATH on darwin
-  if (process.env.NODE_ENV === "production" && process.platform === "darwin") {
-    process.env["PATH"] = env.PATH;
-  }
+  process.env.PATH += `${isWindows ? ";" : ":"}${env.PATH}`;
```
Comment (jakolehm) [inline src/main/shell-sync.ts]: Why do we append PATH now? Isn't this a bit different what we have done before on `darwin`?

Comment (Nokel81) [reply src/main/shell-sync.ts]: yes it could result in some duplicate PATH entries, but this way we don't remove any from either. Maybe we could do some filtering instead and therefore a union of the two sets. WDYT?

Comment (jakolehm) [reply src/main/shell-sync.ts]: Yeah, does not remove any but it also might change the priority of paths because we always keep original PATH at the beginning. Are we really sure that we need append instead of replace?

Comment (jakolehm) [reply src/main/shell-sync.ts]: Also not sure if we can do this on every environment, like `snap`: https://snapcraft.io/docs/environment-variables

Comment (Nokel81) [reply src/main/shell-sync.ts]: Maybe replace is good enough. I'll change it

Comment (jakolehm) [reply src/main/shell-sync.ts]: @Nokel81 did you notice my comment about snap?

Comment (Nokel81) [reply src/main/shell-sync.ts]: I did, but I figured that if the environment is the same everywhere then this assignment won't do anything.

Should I check for snap-ness and just skip this assignment?

Comment (Nokel81) [reply src/main/shell-sync.ts]: I'll skip the assignment when in snap and on windows

**Comment by Nokel81** [comment]
@jakolehm PTALA

File: src/main/shell-sync.ts [hunk 2]
```diff
@@ -22,23 +22,16 @@
...
  * useful on macos where this always needs to be done.
  */
 export async function shellSync() {
-  const { shell } = os.userInfo();
-  let envVars = {};
-
-  envVars = await shellEnv(shell);
-
-  const env: Env = JSON.parse(JSON.stringify(envVars));
+  const env = await shellEnv(os.userInfo().shell);
```
Comment (jakolehm) [inline src/main/shell-sync.ts:34]: Just wondering why we are passing always users default shell and not the current one (if current is set). Probably story for another issue/PR.

**Review by jakolehm — APPROVED** [review]

File: src/main/shell-sync.ts (hunk 2 above)
Comment (Nokel81) [reply src/main/shell-sync.ts:34]: Yeah probably for a different PR. Don't think this is wrong though, where else would they define it?
