### PR TITLE
Fix cluster server path being duplicated by proxy

### LINKED ISSUE #5455: Lens 5.5.0 can't login with kubeconfig render by Rancher
**Describe the bug**

Login kubeconfig render by Rancher display error **`Invalid Credentail`** , and log  404 

**Environment (please complete the following information):**
- Lens Version: 5.5.0
- OS: Linux
- Installation method:  AppImage in Linux

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
StatusCodeError: 404 - {"paths":["/apis","/apis/","/apis/apiextensions.k8s.io","/apis/apiextensions.k8s.io/v1","/apis/apiextensions.k8s.io/v1beta1","/healthz","/healthz/etcd","/healthz/log","/healthz/ping","/healthz/poststarthook/crd-informer-synced","/healthz/poststarthook/generic-apiserver-start-informers","/healthz/poststarthook/priority-and-fairness-config-consumer","/healthz/poststarthook/priority-and-fairness-filter","/healthz/poststarthook/start-apiextensions-controllers","/healthz/poststarthook/start-apiextensions-informers","/livez","/livez/etcd","/livez/log","/livez/ping","/livez/poststarthook/crd-informer-synced","/livez/poststarthook/generic-apiserver-start-informers","/livez/poststarthook/priority-and-fairness-config-consumer","/livez/poststarthook/priority-and-fairness-filter","/livez/poststarthook/start-apiextensions-controllers","/livez/poststarthook/start-apiextensions-informers","/metrics","/openapi/v2","/readyz","/readyz/etcd","/readyz/informer-sync","/readyz/log","/readyz/ping","/readyz/poststarthook/crd-informer-synced","/readyz/poststarthook/generic-apiserver-start-informers","/readyz/poststarthook/priority-and-fairness-config-consumer","/readyz/poststarthook/priority-and-fairness-filter","/readyz/poststarthook/start-apiextensions-controllers","/readyz/poststarthook/start-apiextensions-informers","/readyz/shutdown","/version"]}
```

**Kubeconfig:**
Example config render by Rancher
```
apiVersion: v1
kind: Config
clusters:
- name: "global"
  cluster:
    server: "https://xxx.xxxx/k8s/clusters/c-jdxrh"

users:
- name: "global"
  user:
    token: "kubeconfig-user-zzzzz:t6vbvmdq9drzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"


contexts:
- name: "global"
  context:
    user: "global"
    cluster: "global"

current-context: "global"

```

### LINKED ISSUE #5473: Cannot authenticate successfully and connect the clusters.
**Describe the bug**

E0527 16:26:25.414166 51680 proxy_server.go:147] Error while proxying request: Service Unavailable

Service Unavailable

**To Reproduce**
1. Launch the lens desktop for Mac
 (lastest version: Lens: 5.5.1-latest.20220526.1
Electron: 14.2.9
Chrome: 93.0.4577.82
Node: 14.17.0
2. Click on AKS cluster name (authenticated via Kubeconfig)

**Expected behavior**
Allow to connect to cluster

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: Lens: 5.5.1-latest.20220526.1
- OS: OSX
- Installation method (Mac DMG Mac OS):

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
E0527 16:26:25.414166 51680 proxy_server.go:147] Error while proxying request: Service Unavailable

Service Unavailable

**Kubeconfig:**

your kubeconfig here

Will share via private channel.

### PR DESCRIPTION
**Pull request by Nokel81**
- This resolves an issue with non-Rancher clusters that have been added to Rancher, for some reason this causes the server path to be duplicated in that case. Other connection types don't seem to be affected either way.

Signed-off-by: Sebastian Malton <sebastian@malton.name>

### CODE REVIEW

File: src/main/context-handler/context-handler.ts [hunk 1]
```diff
@@ -152,9 +152,6 @@ export class ContextHandler implements ClusterContextHandler {
 
   protected async newApiTarget(timeout: number): Promise<httpProxy.ServerOptions> {
     const kubeAuthProxy = await this.ensureServerHelper();
-    const ca = this.resolveAuthProxyCa();
-    const clusterPath = this.clusterUrl.path !== "/" ? this.clusterUrl.path : "";
```
Comment (jim-docker) [inline src/main/context-handler/context-handler.ts:156]: Needing this seems a bit of a kludge anyway? The same check exists on line 134. Should it be removed too?

Comment (Nokel81) [reply src/main/context-handler/context-handler.ts:156]: I don't think so... it didn't seem necessary to fix the rancher issue so I don't want to unless there is a test case for that. 

Not that this change has a test case. I don't know how I would write one...

**Comment by jim-docker** [comment]
Does this code run for every connected cluster? The fix seems a bit scary to me.

**Comment by Nokel81** [comment]
> Does this code run for every connected cluster? The fix seems a bit scary to me.

Yes it does. But from all the testing I have done it doesn't break anything.

I have tried connecting to the following:

1. Lens spaces cluster
2. Minikube
3. minkube shared via rancher (this used to fail)
4. redhat occ cluster

**Comment by tsaxon13** [comment]
FWIW I have successfully connected to an AWS EKS cluster directly as well and Rancher managed clusters with this branch.

**Review by jakolehm — APPROVED** [review]
lens-k8s-proxy is already appending the path so we don't need the workaround here anymore.

**Comment by jim-docker** [comment]
> lens-k8s-proxy is already appending the path so we don't need the workaround here anymore.

Should that go for line 134 as well?

**Review by jim-docker — APPROVED** [review]
