### PR TITLE
Fix download percentages not updating in tray

### LINKED ISSUE #5682: Tray menu download percentage stuck at 0%
**Describe the bug**
The download percentage that is displayed within the tray menu while the update is being downloaded stays at 0% until the download is complete. Even if you close and reopen the menu.

**To Reproduce**
1. Download and install manually https://lens-binaries.s3.eu-west-1.amazonaws.com/ide/Lens-5.6.0-alpha.2.20220615.1.dmg
2. Launch lens
3. Once the update is detected the tray menu icon changes
4. Open menu, see that it is at 0%
5. Close menu
6. Reopen menu, still at 0%

**Expected behavior**
The percentage should tick up.

**Screenshots**
Screen Shot 2022-06-20 at 2 53 43 PM

### PR DESCRIPTION
**Pull request by jansav**
Problem was stale state from `label` and `enabled` of tray item not being observed.

Fixes #5682

### CODE REVIEW

**Review by jakolehm — APPROVED** [review]

**Review by Iku-turso — APPROVED** [review]

File: src/main/tray/reactive-tray-menu-items/reactive-tray-menu-items.injectable.ts [hunk 1]
```diff
@@ -5,26 +5,40 @@
...
+
+const toNonReactiveItem = (item: TrayMenuItem): MinimalTrayMenuItem => ({
+  id: item.id,
+  parentId: item.parentId,
+  click: item.click,
+  tooltip: item.tooltip,
+  separator: item.separator,
+  enabled: item.enabled.get(),
+  label: item.label?.get(),
+});
```
Comment (aleksfront) [inline src/main/tray/reactive-tray-menu-items/reactive-tray-menu-items.injectable.ts:44]: It *feels* that there should be some utility for such cases. Will be https://mobx.js.org/api.html#tojs useful?

Comment (jansav) [reply src/main/tray/reactive-tray-menu-items/reactive-tray-menu-items.injectable.ts:44]: It's not the same. Here we are removing the properties that are not used inside of `ElectronTray`. Stuff like `orderNumber` and `visibility`.
