### PR TITLE
Fix involuntary rerenders in item list layout

### LINKED ISSUE #4703: Namespace Selector is closed when trying to multiselect
**Describe the bug**
Any page using KubeObjectListLayout is rendered too often causing e.g. `NamespaceSelector` to close when not supposed to.

**To Reproduce**
1. Go to e.g. Pods
2. Click on namespace selector
3. Ctrl/Cmd + Click value to multiselect
4. See that selector is closed

**Expected behavior**
Selector shouldn't close

**Additional context**
Regression of #4653

### PR DESCRIPTION
**Pull request by jansav**
Main attraction here is that `ItemListLayout` has now been split to multiple components to make re-rendering happen more locally instead of full-renders. It's also nice to have a smaller components. 

**The changes here highlight that ItemListLayout is wrong abstraction and should be re-designed.**

Closes #4703. 

Opening separate issue for proper love for `ItemListLayout`.

Note: This PR is built on top of #4710 which should be merged first.

### CODE REVIEW

File: src/renderer/components/item-object-list/item-list-layout-content/item-list-layout-content.tsx [hunk 1]
```diff
@@ -0,0 +1,271 @@
...
+            if (!headCell || this.showColumn(headCell)) {
+              return <TableCell key={index} {...cellProps} />;
+            }
+
+            return null;
+          })
+        }
+        {renderItemMenu && (
+          <TableCell className="menu">
+            <div onClick={stopPropagation}>
```
Comment (ixrock) [inline src/renderer/components/item-object-list/item-list-layout-content/item-list-layout-content.tsx]: What does `stopPropagation` here and why do we need it?

File: src/renderer/components/item-object-list/item-list-layout-content/item-list-layout-content.tsx [hunk 2]
```diff
@@ -0,0 +1,271 @@
...
+  removeItemsDialog() {
+    const { customizeRemoveDialog, store } = this.props;
+    const { selectedItems, removeSelectedItems } = store;
+    const visibleMaxNamesCount = 5;
+    const selectedNames = selectedItems.map(ns => ns.getName()).slice(0, visibleMaxNamesCount).join(", ");
+    const dialogCustomProps = customizeRemoveDialog ? customizeRemoveDialog(selectedItems) : {};
+    const selectedCount = selectedItems.length;
+    const tailCount = selectedCount > visibleMaxNamesCount ? selectedCount - visibleMaxNamesCount : 0;
+    const tail = tailCount > 0 ? <>, and <b>{tailCount}</b> more</> : null;
+    const message = selectedCount <= 1 ? <p>Remove item <b>{selectedNames}</b>?</p> : <p>Remove <b>{selectedCount}</b> items <b>{selectedNames}</b>{tail}?</p>;
```
Comment (ixrock) [inline src/renderer/components/item-object-list/item-list-layout-content/item-list-layout-content.tsx]: _nit:_




```suggestion
    const message = selectedCount === 1 
      ? <p>Remove item <b>{selectedNames}</b>?</p> 
      : <p>Remove <b>{selectedCount}</b> items <b>{selectedNames}</b>{tail}?</p>;
```

File: src/renderer/components/item-object-list/item-list-layout-content/item-list-layout-content.tsx [hunk 3]
```diff
@@ -0,0 +1,271 @@
...
+    if (!this.props.getIsReady()) {
+      return <Spinner center />;
+    }
+
+    if (this.props.getFilters().length > 0) {
+      return (
+        <NoItems>
+          No items found.
+          <p>
+            <a onClick={() => pageFilters.reset()} className="contrast">
```
Comment (ixrock) [inline src/renderer/components/item-object-list/item-list-layout-content/item-list-layout-content.tsx]: Probably we should stop/ban using global css class names like `contrast` (except all from `tailwindcss` for the time being) since currenlt plan to have (s)css-modules only in whole codebase (e.g. `item-list-layout.module.scss`)

File: src/renderer/components/item-object-list/item-list-layout-header/item-list-layout-header-info/item-list-layout-header-info.tsx [hunk 4]
```diff
@@ -0,0 +1,55 @@
...
+  <I extends ItemObject>({
+    headerPlaceholders,
+    getItems,
+    getFilters,
+    store,
+    toggleFilters,
+  }: ItemListLayoutHeaderInfoProps<I>) => {
+    const renderInfo = () => {
+      const allItemsCount = store.getTotalCount();
+      const itemsCount = getItems().length;
```
Comment (ixrock) [inline src/renderer/components/item-object-list/item-list-layout-header/item-list-layout-header-info/item-list-layout-header-info.tsx]: _nit:_ I'd better to move destructing input params inside constructor (more readable):

```suggestion
export const ItemListLayoutHeaderInfo = observer(
  <I extends ItemObject>(props: ItemListLayoutHeaderInfoProps<I>) => {
    const { headerPlaceholders, getItems, getFilters, store, toggleFilters, } = props;
```

File: src/renderer/components/item-object-list/item-list-layout-header/item-list-layout-header-title/item-list-layout-header-title.tsx [hunk 5]
```diff
@@ -0,0 +1,25 @@
+/**
+ * Copyright (c) OpenLens Authors. All rights reserved.
+ * Licensed under MIT License. See LICENSE in root directory for more information.
+ */
+import { observer } from "mobx-react";
+import React from "react";
+import type { HeaderPlaceholders } from "../../item-list-layout";
+
+interface ItemListLayoutHeaderTitleProps {
+  renderHeaderTitle: React.ReactNode | (() => React.ReactNode); // MIKKO: "this" parameter
```
Comment (ixrock) [inline src/renderer/components/item-object-list/item-list-layout-header/item-list-layout-header-title/item-list-layout-header-title.tsx]: What means comment `// MIKKO: "this" parameter`?

File: src/renderer/components/item-object-list/item-list-layout-content/item-list-layout-content.tsx [hunk 6]
```diff
@@ -0,0 +1,271 @@
...
+            <div onClick={stopPropagation}>
+              {renderItemMenu(item, store)}
+            </div>
+          </TableCell>
+        )}
+      </TableRow>
+    );
+  }
+
+  @boundMethod
```
Comment (ixrock) [inline src/renderer/components/item-object-list/item-list-layout-content/item-list-layout-content.tsx]: I'd like to remove `@boundMethod` in nearest future since we currently have 2 libraries for that:


```ts
// lens/src/common/utils/autobind.ts
import { boundMethod, boundClass } from "autobind-decorator";
import autoBindClass, { Options } from "auto-bind";...
```

For most cases to bind all class methods we use this:
```ts
constructor(private dependencies: Dependencies)
    makeObservable(this);
    autoBind(this); // note: this is important to call after `makeObservable`
```

For binding single methods I'm suggesting stick to arrow-functions or to use re-assign class fields with `.bind(this)` inside constructor.

**Review by ixrock — DISMISSED** [review]
LGTM

File: src/renderer/components/item-object-list/item-list-layout-content/item-list-layout-content.tsx (hunk 1 above)
Comment (jansav) [reply src/renderer/components/item-object-list/item-list-layout-content/item-list-layout-content.tsx]: Old code, no idea.

File: src/renderer/components/item-object-list/item-list-layout-content/item-list-layout-content.tsx (hunk 2 above)
Comment (jansav) [reply src/renderer/components/item-object-list/item-list-layout-content/item-list-layout-content.tsx]: Yep, old code. This PR just splits these to separate components and make them observer where needed.

File: src/renderer/components/item-object-list/item-list-layout-header/item-list-layout-header-title/item-list-layout-header-title.tsx (hunk 5 above)
Comment (jansav) [reply src/renderer/components/item-object-list/item-list-layout-header/item-list-layout-header-title/item-list-layout-header-title.tsx]: Wow, good catch. Shouldn't be there. Just a reminder to have discussion with Mikko.

File: src/renderer/components/item-object-list/item-list-layout-content/item-list-layout-content.tsx (hunk 6 above)
Comment (jansav) [reply src/renderer/components/item-object-list/item-list-layout-content/item-list-layout-content.tsx]: I'd like to remove all these binds. But, this is old code and not touching this on this PR

**Comment by ixrock** [comment]
One other thing what I don't really like is too much nesting in codebase (besides too much bloated amount of files): `src/renderer/components/item-object-list/item-list-layout-content/item-list-layout-content.tsx`

Could we keep more flat in `src/renderer/components/item-object-list/item-*.tsx`?
Also would be nice to have whole bundle of inner components available at `src/renderer/components/item-object-list/index.ts`

File: src/renderer/components/item-object-list/item-list-layout-header/item-list-layout-header-info/item-list-layout-header-info.tsx (hunk 4 above)
Comment (jansav) [reply src/renderer/components/item-object-list/item-list-layout-header/item-list-layout-header-info/item-list-layout-header-info.tsx]: Updated

File: src/renderer/components/item-object-list/item-list-layout-header/item-list-layout-header-title/item-list-layout-header-title.tsx (hunk 5 above)
Comment (jansav) [reply src/renderer/components/item-object-list/item-list-layout-header/item-list-layout-header-title/item-list-layout-header-title.tsx]: Updated

File: src/renderer/components/item-object-list/item-list-layout-content/item-list-layout-content.tsx (hunk 3 above)
Comment (jansav) [reply src/renderer/components/item-object-list/item-list-layout-content/item-list-layout-content.tsx]: Again, old code. Not on this PR. But I agree with your comment.

**Review by Iku-turso — DISMISSED** [review]

**Comment by jim-docker** [comment]
Just noticed this, not sure if this PR is the source of this bug:

https://user-images.githubusercontent.com/40840436/150566869-175f9a3f-5672-416f-a6b0-c1d6fd97a837.mov

It should select all/select none. Other uses of item-list-layout are ok.

**** confirmed this is happening on master too. Made issue #4740 and PR #4742  ****

**Comment by jim-docker** [comment]
item/filtered count is missing (between Pods title and namespace selector):
Screen Shot 2022-01-21 at 12 07 10 PM

**Comment by jim-docker** [comment]
The list scrolls to top as it rerenders due to changes in the list items (I'm trying to keep it near the bottom, which works on 5.3.x):

https://user-images.githubusercontent.com/40840436/150576354-aac7a94c-eda0-47d6-a8b5-81b165fd1805.mov


**** happens on master too, suspect it is due to #4653. This similar issue is still occurring as well: https://github.com/lensapp/lens/pull/4653#issuecomment-1012457220

**Review by Nokel81 — DISMISSED** [review]

**Review by jim-docker — DISMISSED** [review]
will fix https://github.com/lensapp/lens/pull/4720#issuecomment-1018698807 in separate PR

File: src/renderer/components/item-object-list/header-info.tsx [hunk 7]
```diff
@@ -0,0 +1,54 @@
...
+        </>
+      );
+    }
+
+    return allItemsCount === 1
+      ? `${allItemsCount} item`
+      : `${allItemsCount} items`;
+  };
+
+  const info = headerPlaceholders.info ?? renderInfo();
```
Comment (jim-docker) [inline src/renderer/components/item-object-list/header-info.tsx]: This looks like the wrong check. It uses `headerPlaceholders.info` but it is simply an empty `</>`

**Review by Nokel81 — APPROVED** [review]
