### PR TITLE
Fix pasting unicode into terminal sometimes not working

### LINKED ISSUE #351: Terminal does not like Unicode strings with kube_ps1
**Describe the bug**
I use kube_ps1 with zsh. By default it adds the Helm symbol to the prompt.

```
KUBE_PS1_SYMBOL_DEFAULT=${KUBE_PS1_SYMBOL_DEFAULT:-$'\u2388 '}
```

Lens terminal doesn't like this.

Screenshot 2020-05-07 at 19 00 01

I can fix this by overriding the symbol:

```
KUBE_PS1_SYMBOL_DEFAULT="k"
```

Interestingly I can use the character successfully:

```
KUBE_PS1_SYMBOL_DEFAULT="⎈"
```

Screenshot 2020-05-07 at 19 14 53

Even more interestingly, I cannot replicate the issue if I run Lens app from the command line, the Terminal does not throw an error and shows the symbol as expected.

```
$ /Applications/Lens.app/Contents/MacOS/Lens
```

**To Reproduce**

Use zsh with kube_ps1

**Expected behavior**
When launching the Lens app from Applications, when using zsh + kube_ps1, it should not throw an error.

- Lens Version: 3.4.0-rc.1
- OSX

### PR DESCRIPTION
**Pull request by Nokel81**
- add LANG env with UTF-8 specified
- When Lens is run (especially on macos) the LANG env var was not being picked up (even by `shell-env`) which for some reason broke pasting utf-8 unicode into the terminal emulator.

Fixes #351 

Signed-off-by: Sebastian Malton <smalton@mirantis.com>

### CODE REVIEW

**Comment by Nokel81** [comment]
I think that this could also be classified as a bug in `shell-env`, so should I register a bug over there?

**Comment by jakolehm** [comment]
> I think that this could also be classified as a bug in `shell-env`, so should I register a bug over there?

Yes, makes sense.

File: src/main/shell-sync.ts [hunk 1]
```diff
@@ -1,18 +1,34 @@
...
+  }
 
   // Overwrite PATH on darwin
   if (process.env.NODE_ENV === "production" && process.platform === "darwin") {
     process.env["PATH"] = env.PATH
   }
 
-  let key = null
-  for(key in env) {
-    if(!env.hasOwnProperty(key) || process.env[key]) continue // skip existing and prototype keys
```
Comment (nevalla) [inline src/main/shell-sync.ts:14]: @kke do you remember why did we have this check?

Comment (kke) [reply src/main/shell-sync.ts:14]: Yes. The loop will go through all of the JS prototype object's functions and what ever without that. This check will limit the loop to only go  through the actual user defined attributes.

And the `|| process.env[key]` is to avoid overwriting.

Comment (nevalla) [reply src/main/shell-sync.ts:14]: I think we want to explicitly overwrite `LANG` here. Maybe it could be done similar way as `PATH`?

Comment (kke) [reply src/main/shell-sync.ts:14]: Maybe. But it could also have been done stupidly orginally :)

Comment (Nokel81) [reply src/main/shell-sync.ts:14]: Given this fiddle: https://jsfiddle.net/2v3pdbqL/

I think that I should have put `...env` first because JS overwrites the first's fields when joining.

**Review by nevalla — APPROVED** [review]
LGTM
