### PR TITLE
display close button on deleted kube details page

### LINKED ISSUE #2345: SideWindow does not close - SideWindow does not close with Pod/deployemnt info if it was open when resource was deleted via terminal
**Describe the bug**
SideWindow does not close with Pod/deployemnt info if it was open when resource was deleted via terminal

**To Reproduce**
1. Create a Pod
2. Open the information side window
3. Kill the pod/deployment from the terminal
4. Side window goes blank(expected) but then the X on the top right does not close the side window. need to disconnect from the cluster and reconnect

**Expected behavior**
Side window should close either automatically on resource deletion or close button should work

**Environment (please complete the following information):**
- Mac OS  Big Sur 11.1 (20C69)
- Lens: 4.1.4
Electron: 9.4.0
Chrome: 83.0.4103.122
Node: 12.14.1
Copyright 2020 Mirantis, Inc.

### PR DESCRIPTION
**Pull request by Nokel81**
Signed-off-by: Sebastian Malton <sebastian@malton.name>

fixes #2345

### CODE REVIEW

File: src/renderer/components/kube-object/kube-object-menu.tsx [hunk 1]
```diff
@@ -7,13 +7,13 @@ import { hideDetails } from "./kube-object-details";
 import { apiManager } from "../../api/api-manager";
 import { kubeObjectMenuRegistry } from "../../../extensions/registries/kube-object-menu-registry";
 
-export interface KubeObjectMenuProps<T extends KubeObject = any> extends MenuActionsProps {
-  object: T;
+export interface KubeObjectMenuProps<T> extends MenuActionsProps {
+  object: T | null | undefined;
```
Comment (ixrock) [inline src/renderer/components/kube-object/kube-object-menu.tsx:11]: Why both `null` and `undefined`?  
Can you provide an example when it could be helpful? since `null == undefined` // true

File: src/renderer/components/kube-object/kube-object-list-layout.tsx [hunk 2]
```diff
@@ -53,9 +53,7 @@ export class KubeObjectListLayout extends React.Component<KubeObjectListLayoutPr
         preloadStores={false} // loading handled in kubeWatchApi.subscribeStores()
         detailsItem={this.selectedItem}
         onDetails={this.onDetails}
-        renderItemMenu={(item) => {
-          return <KubeObjectMenu object={item}/>;
-        }}
+        renderItemMenu={(item) => <KubeObjectMenu object={item as KubeObject} />} // safe because we are dealing with KubeObjects here
```
Comment (ixrock) [inline src/renderer/components/kube-object/kube-object-list-layout.tsx]:
```suggestion
        renderItemMenu={(item: KubeObject) => {
          return <KubeObjectMenu object={item}/>;
        }}
```

**Review by ixrock — DISMISSED** [review]

File: src/renderer/components/kube-object/kube-object-menu.tsx (hunk 1 above)
Comment (Nokel81) [reply src/renderer/components/kube-object/kube-object-menu.tsx:11]: I guess I can remove one of them, I did this to be "most correct" since we sometimes return `null` and sometimes return `undefined`. When we move to `strict` mode this will become more relevant.

File: src/renderer/components/kube-object/kube-object-list-layout.tsx [hunk 3]
```diff
@@ -17,6 +17,10 @@ export interface KubeObjectListLayoutProps extends ItemListLayoutProps {
 
 @observer
 export class KubeObjectListLayout extends React.Component<KubeObjectListLayoutProps> {
+  static defaultProps: Partial<KubeObjectListLayoutProps> = {
```
Comment (ixrock) [inline src/renderer/components/kube-object/kube-object-list-layout.tsx]: You cannot use it like this (not sure exactly why though), but it leads to that all props becomes `optional`.
For example comment out required `store={...}` in some place of use and you'll see no complains from TS.

Workaround would be as done in other places:

```ts
const defaultProps: Partial<Props> = {
  // define optionals
};

export class ComponentName extends React.Component<Props> {
  static defaultProps = defaultProps as object;
```

File: src/renderer/components/kube-object/kube-object-menu.tsx (hunk 1 above)
Comment (ixrock) [reply src/renderer/components/kube-object/kube-object-menu.tsx:11]: Are we going to move forward `strict`? What's for if so?

Comment (Nokel81) [reply src/renderer/components/kube-object/kube-object-menu.tsx:11]: It help catches more problems, the rules that it turns on is:

- noImplicitAny
- noImplicitThis
- strictNullChecks
- strictPropertyInitialization
- strictBindCallApply
- strictFunctionTypes

File: src/renderer/components/kube-object/kube-object-list-layout.tsx (hunk 3 above)
Comment (Nokel81) [reply src/renderer/components/kube-object/kube-object-list-layout.tsx]: Ah fair thanks for the catch. I think we still do this in some places but that should be a different PR.

**Review by ixrock — DISMISSED** [review]

**Review by ixrock — APPROVED** [review]

**Review by jim-docker — APPROVED** [review]
Amid the cleanup and refactoring I'm not sure what actually fixes the bug. Although I couldn't reproduce the bug before this fix anyway :)

File: src/renderer/components/kube-object/kube-object-menu.tsx [hunk 4]
```diff
@@ -52,34 +52,45 @@ export class KubeObjectMenu extends React.Component<KubeObjectMenuProps> {
...
+          toolbar={toolbar}
+        />
+      ));
+  }
+
   render() {
     const { remove, update, renderRemoveMessage, isEditable, isRemovable } = this;
-    const { className, object, editable, removable, toolbar, ...menuProps } = this.props;
-
-    if (!object) return null;
```
Comment (Nokel81) [inline src/renderer/components/kube-object/kube-object-menu.tsx:67]: The moving of this check to the above is the substance of the fix
