### PR TITLE
Fix KubeApi watch retry on timeout

### LINKED ISSUE #6635: K8s api watch does not retry
```
[KUBE-API] watch (event-7) started /api/v1/namespaces/xxx/events?watch=1&resourceVersion=162063
[KUBE-API] watch (pod-6) started /api/v1/namespaces/xxx/pods?watch=1&resourceVersion=162063
[KUBE-API] watch (event-7) aborted /api/v1/namespaces/xxx/events?watch=1&resourceVersion=162063
[KUBE-API] watch (pod-6) aborted /api/v1/namespaces/xxx/pods?watch=1&resourceVersion=162063
... stops here ...
```

### PR DESCRIPTION
**Pull request by jakolehm**
Fixes #6635

### CODE REVIEW

File: src/common/k8s-api/kube-api.ts [hunk 1]
```diff
@@ -695,8 +693,10 @@ export class KubeApi<
           }, timeout * 1000 * 1.1);
         }
 
-        if (!response.body) {
-          this.dependencies.logger.error(`[KUBE-API]: watch (${watchId}) did not return a body`);
+        if (!response.body || !response.body.readable) {
```
Comment (jakolehm) [inline src/common/k8s-api/kube-api.ts:696]: After a timeout body can be unreadable if no data has come through.

**Review by Nokel81 — DISMISSED** [review]

**Review by Nokel81 — APPROVED** [review]
