### PR TITLE
Catch Cluster create error in cluster-manager

### LINKED ISSUE #3400: [mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in:...
Sentry Issue: [K8SLENS-E5](https://sentry.io/organizations/k8slens/issues/2514579657/?referrer=github_integration)

```
[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Reaction@77]' Error: ENOENT: no such file or directory, open '/Users/danielmorris/.kube/config~'
```

### PR DESCRIPTION
**Pull request by Nokel81**
- Only warn if the file is missing. The file must have disapeared
  betweeen kubeconfig-sync detecting it and cluster-manager performing
  the addCluster call

- For all other errors log an error

Signed-off-by: Sebastian Malton <sebastian@malton.name>

fixes https://github.com/lensapp/lens/issues/3400

### CODE REVIEW

File: src/main/cluster-manager.ts [hunk 1]
```diff
@@ -161,14 +161,22 @@ export class ClusterManager extends Singleton {
...
+            id: entity.metadata.uid,
+            preferences: {
+              clusterName: entity.metadata.name
+            },
+            kubeConfigPath: entity.spec.kubeconfigPath,
+            contextName: entity.spec.kubeconfigContext
+          });
+        } catch (error) {
+          if (error.code === "ENOENT" && error.path === entity.spec.kubeconfigPath) {
+            console.warn("[CLUSTER-MANGER]: kubeconfig file disappeared", { path: entity.spec.kubeconfigPath });
```
Comment (jim-docker) [inline src/main/cluster-manager.ts]:
```suggestion
            console.warn("[CLUSTER-MANAGER]: kubeconfig file disappeared", { path: entity.spec.kubeconfigPath });
```

**Review by jim-docker — DISMISSED** [review]
LGTM but I didn't test

**Comment by Nokel81** [comment]
@jim-docker 😄 testing this is def hard, as are all race conditions.

File: src/main/cluster-manager.ts [hunk 2]
```diff
@@ -161,14 +163,22 @@ export class ClusterManager extends Singleton {
...
+            id: entity.metadata.uid,
+            preferences: {
+              clusterName: entity.metadata.name
+            },
+            kubeConfigPath: entity.spec.kubeconfigPath,
+            contextName: entity.spec.kubeconfigContext
+          });
+        } catch (error) {
+          if (error.code === "ENOENT" && error.path === entity.spec.kubeconfigPath) {
+            console.warn(`${logPrefix} kubeconfig file disappeared`, { path: entity.spec.kubeconfigPath });
```
Comment (jakolehm) [inline src/main/cluster-manager.ts]: Probably should use `logger`?

Comment (Nokel81) [reply src/main/cluster-manager.ts]: Yes

File: src/main/cluster-manager.ts [hunk 3]
```diff
@@ -161,14 +163,22 @@ export class ClusterManager extends Singleton {
...
+        try {
+          this.store.addCluster({
+            id: entity.metadata.uid,
+            preferences: {
+              clusterName: entity.metadata.name
+            },
+            kubeConfigPath: entity.spec.kubeconfigPath,
+            contextName: entity.spec.kubeconfigContext
+          });
+        } catch (error) {
```
Comment (jim-docker) [inline src/main/cluster-manager.ts:175]: Does this `entity` need to be removed from `entities`, or somehow signal that it should be removed?

Comment (Nokel81) [reply src/main/cluster-manager.ts:175]: If the file is no longer present then kubesync will detect that it is no longer there are remove it from the catalog. If kubesync tries to read a file and gets an EACCESS then it clears all entities that it had previously detected.

**Review by jakolehm — APPROVED** [review]
