### PR TITLE
Fix splash window having window control buttons

### LINKED ISSUE #5417: Splash window has window buttons on macos
**Describe the bug**
On the latest master, the splash window has window control buttons.

Screen Shot 2022-05-18 at 3 35 47 PM

Regression from #5324

### PR DESCRIPTION
**Pull request by Nokel81**
Signed-off-by: Sebastian Malton <sebastian@malton.name>

fixes #5417

### CODE REVIEW

File: src/main/start-main-application/lens-window/application-window/application-window.injectable.ts [hunk 1]
```diff
@@ -22,35 +22,27 @@ const applicationWindowInjectable = getInjectable({
...
     return createLensWindow({
       id: "only-application-window",
       title: applicationName,
       defaultHeight: 900,
       defaultWidth: 1440,
-      getContentUrl,
+      getContentUrl: () => `http://localhost:${lensProxyPort.get()}`,
       resizable: true,
       windowFrameUtilitiesAreShown: isMac,
+      titleBarStyle: isMac ? "hiddenInset" : "hidden",
```
Comment (jim-docker) [inline src/main/start-main-application/lens-window/application-window/application-window.injectable.ts:35]: Where is the fix exactly? Here?

**Review by jim-docker — APPROVED** [review]

File: src/main/start-main-application/lens-window/application-window/application-window.injectable.ts (hunk 1 above)
Comment (Nokel81) [reply src/main/start-main-application/lens-window/application-window/application-window.injectable.ts:35]: Yes, the bug was that all windows on mac were having this field forced. Which was not the case before the reference PR

**Review by jansav — APPROVED** [review]
