### PR TITLE
Catch ipc errors on proxy exit

### LINKED ISSUE #212: Error on exit of lens when running via snapd
**Describe the bug**
When exiting lens 3.1.0, I always get the following error:

```
Unhandled rejection TypeError: Cannot read property 'send' of undefined
    at send (/var/lib/snapd/snap/kontena-lens/90/resources/app.asar/node_modules/electron-promise-ipc/src/base.js:39:14)
    at Promise._execute (/var/lib/snapd/snap/kontena-lens/90/resources/app.asar/node_modules/electron-promise-ipc/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/var/lib/snapd/snap/kontena-lens/90/resources/app.asar/node_modules/electron-promise-ipc/node_modules/bluebird/js/release/promise.js:488:18)
    at new Promise (/var/lib/snapd/snap/kontena-lens/90/resources/app.asar/node_modules/electron-promise-ipc/node_modules/bluebird/js/release/promise.js:79:10)
    at PromiseIpcMain.send (/var/lib/snapd/snap/kontena-lens/90/resources/app.asar/node_modules/electron-promise-ipc/src/base.js:19:12)
    at PromiseIpcMain.send (/var/lib/snapd/snap/kontena-lens/90/resources/app.asar/node_modules/electron-promise-ipc/src/mainProcess.js:11:5)
    at errorMsg [as sendIpcLogMessage] (/var/lib/snapd/snap/kontena-lens/90/resources/app.asar/webpack:/src/main/kube-auth-proxy.ts:95:12)
    at ChildProcess.error (/var/lib/snapd/snap/kontena-lens/90/resources/app.asar/webpack:/src/main/kube-auth-proxy.ts:61:14)
    at ChildProcess.emit (events.js:200:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

I run lens via snapd. I don't know if this problem is specific to that environment or not.

**To Reproduce**
1. Run lens via snapd (`snap run kontena-lens`)
2. Close lens
3. See error on the console

**Environment (please complete the following information):**
- Lens Version: 3.1.0
- OS: Linux
- Installation method (e.g. snap or AppImage in Linux):  Snap
 
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
info: SNAP env is defined, updater is disabled
error: proxy devkube2 exited with code null
error: watch error: Error: Internal Server Error
error: proxy devkube2 exited with code null
error: proxy devkube2 exited with code null
Unhandled rejection TypeError: Cannot read property 'send' of undefined
    at send (/var/lib/snapd/snap/kontena-lens/90/resources/app.asar/node_modules/electron-promise-ipc/src/base.js:39:14)
    at Promise._execute (/var/lib/snapd/snap/kontena-lens/90/resources/app.asar/node_modules/electron-promise-ipc/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/var/lib/snapd/snap/kontena-lens/90/resources/app.asar/node_modules/electron-promise-ipc/node_modules/bluebird/js/release/promise.js:488:18)
    at new Promise (/var/lib/snapd/snap/kontena-lens/90/resources/app.asar/node_modules/electron-promise-ipc/node_modules/bluebird/js/release/promise.js:79:10)
    at PromiseIpcMain.send (/var/lib/snapd/snap/kontena-lens/90/resources/app.asar/node_modules/electron-promise-ipc/src/base.js:19:12)
    at PromiseIpcMain.send (/var/lib/snapd/snap/kontena-lens/90/resources/app.asar/node_modules/electron-promise-ipc/src/mainProcess.js:11:5)
    at errorMsg [as sendIpcLogMessage] (/var/lib/snapd/snap/kontena-lens/90/resources/app.asar/webpack:/src/main/kube-auth-proxy.ts:95:12)
    at ChildProcess.error (/var/lib/snapd/snap/kontena-lens/90/resources/app.asar/webpack:/src/main/kube-auth-proxy.ts:61:14)
    at ChildProcess.emit (events.js:200:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

### PR DESCRIPTION
**Pull request by nevalla**
When closing Lens app and main process is terminated, kube-auth-proxy child processes are calling `sendIpcLogMessage` on exit hook and those are erroring out. This PR will fix this just catching errors silently.

Fixes #212

### CODE REVIEW

File: src/main/kube-auth-proxy.ts [hunk 1]
```diff
@@ -95,15 +95,14 @@ export class KubeAuthProxy {
...
-    this.promiseIpc.send(`kube-auth:${this.cluster.id}`, findMainWebContents(), { data: data, stream: stream })
+  protected async sendIpcLogMessage(data: string, stream: string) {
+      await this.promiseIpc.send(`kube-auth:${this.cluster.id}`, findMainWebContents(), { data: data, stream: stream })
   }
 
   public exit() {
     if (this.proxyProcess) {
       logger.debug(`Stopping local proxy: ${this.cluster.contextName}`)
       this.proxyProcess.kill()
-      this.proxyProcess = null
```
Comment (nevalla) [inline src/main/kube-auth-proxy.ts:106]: Not sure if this is redundant, since this is set to null also on "exit" hook.

**Review by jakolehm — APPROVED** [review]
LGTM
