### PR TITLE
TabLayout should not be part of LensRuntimeRendererEnv

### LINKED ISSUE #1028: TabLayout should not be part of LensRuntimeRendererEnv
**Describe the bug**

`TabLayout` is now part of the `LensRuntimeRendererEnv` and extension developer needs to use it to wrap a page contents. 

**Expected behavior**

Lens should wrap dynamic pages automatically to `TabLayout`. No need to expose it via runtime.

### PR DESCRIPTION
**Pull request by ixrock**
fix #1028

Signed-off-by: Roman <ixrock@gmail.com>

### CODE REVIEW

File: src/extensions/register-page.tsx [hunk 1]
```diff
@@ -43,4 +49,15 @@ export class PagesStore {
   }
 }
 
+export class DynamicPage extends React.Component<{ page: PageRegistration }> {
+  render() {
+    const { className, components: { Page }, subPages = [] } = this.props.page;
+    return (
+      <TabLayout className={cssNames("ExtensionPage", className)} tabs={subPages}>
```
Comment (jim-docker) [inline src/extensions/register-page.tsx:56]: Is `ExtensionPage` used anywhere? Is it a "reserved" className? Could cause problems if an extensions developer also used this className for their own extension?

**Review by jim-docker — APPROVED** [review]

File: src/extensions/register-page.tsx (hunk 1 above)
Comment (ixrock) [reply src/extensions/register-page.tsx:56]: Well, it could be considered as one of "system" component classNames. Otherwise we have a tons of top-level `ComponentName` class-names which might conflict with extension class-names (depending how they gonna be bundled/loaded with the extension).

File: src/renderer/components/layout/tab-layout.tsx [hunk 2]
```diff
@@ -23,17 +21,13 @@ interface Props {
 
 export const TabLayout = observer(({ className, contentClass, tabs, children }: Props) => {
   const routePath = navigation.location.pathname;
-  const cluster = getHostedCluster();
-  if (!cluster) {
-    return null; // fix: skip render when removing active (visible) cluster
```
Comment (jakolehm) [inline src/renderer/components/layout/tab-layout.tsx:28]: Why this is removed? It was part of #928 which fixed something 🙂

Comment (ixrock) [reply src/renderer/components/layout/tab-layout.tsx:28]: I have tried to reproduce what is said in the comment, works fine.
It's removed primarily to make the component "pure" and as a result it can be exposed via `@lens/extension` as common component.
Regarding to #928 it doesn't affect scrollbar at all.

Comment (ixrock) [reply src/renderer/components/layout/tab-layout.tsx:28]: Well, it's not fully pure at the moment since it use `const routePath = navigation.location.pathname` from external `import`.. :) but it can be fixed easily with react `context`  or moving it up to `props`.

**Review by jakolehm — APPROVED** [review]
